#TODO missing script for building, see https://openfoam.org/download/11-source/
[source]
tar = "http://dl.openfoam.org/source/11"
[build]
template = "custom"
dependencies = [
    "paraview",
    "scotch",
]
