#TODO missing script for GNU Autotools, see https://github.com/openwall/john/blob/bleeding-jumbo/doc/INSTALL
[source]
tar = "https://www.openwall.com/john/k/john-1.9.0-jumbo-1.tar.xz"
[build]
template = "custom"
dependencies = [
    "openssl1",
    "nss",
    "kerberos5",
    "libgmp",
]
