#TODO openssl error
[source]
git = "https://github.com/Siriusmart/youtube-tui"
rev = "f321f7c1e9b41644b976ea8672807c3062908c5c"
[build]
template = "custom"
dependencies = [
    "openssl1",
]
script = """
cookbook_cargo --no-default-features
"""
