#TODO missing script for QMake, see https://github.com/AnimeEffectsDevs/AnimeEffects#clone--building
[source]
git = "https://github.com/AnimeEffectsDevs/AnimeEffects"
rev = "6080497684809aa5c73bf015fec36e88443f6d11"
[build]
template = "custom"
dependencies = [
    "ffmpeg6",
    "mesa",
    "qt5-base",
    "glib",
]
