sys_includes = ["stdint.h"]
include_guard = "_RELIBC_TERMIOS_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[defines]
"target_os=linux" = "__linux__"
"target_os=redox" = "__redox__"

[enum]
prefix_with_name = true

[export.rename]
"winsize" = "struct winsize"
