#TODO missing script for CMake, see https://github.com/TheWaveWarden/odin2#all-platforms
[source]
git = "https://github.com/TheWaveWarden/odin2"
[build]
template = "custom"
dependencies = [
    "mesa",
    "curl",
    "libx11",
    "webkitgtk3",
]
