#TODO OpenSSL error
[source]
git = "https://github.com/lasantosr/intelli-shell"
rev = "f1a3f24c8dbc9a9a10bfc702f6feb205f433fed0"
[build]
template = "custom"
dependencies = [
    "openssl1",
]
script = """
export OPENSSL_DIR="${COOKBOOK_SYSROOT}"
export OPENSSL_STATIC="true"
cookbook_cargo
"""
