#TODO missing script for SCons, see https://github.com/mongodb/mongo/blob/master/docs/building.md
[source]
git = "https://github.com/mongodb/mongo"
branch = "v6.0"
[build]
template = "custom"
dependencies = [
    "curl",
    "xz",
]
