#TODO missing script for building, see https://github.com/defold/defold/blob/dev/README_BUILD.md
#TODO build the editor, see https://github.com/defold/defold/blob/dev/editor/README_BUILD.md
# probably the SDKs can't run on Redox, avoid them
[source]
git = "https://github.com/defold/defold"
rev = "4e156b7cf37a380122aada30dacbf2b590ead76b"
[build]
template = "custom"
dependencies = [
    "libxi",
    "libxext",
    "mesa-glu",
    "mesa",
    "curl",
    "freeglut",
    "libuuid",
    "openal",
    "ncurses",
]
script = """
export CPPFLAGS="-I${COOKBOOK_SYSROOT}/include/ncurses"
"""
