#TODO make dependencies work
[source]
git = "https://github.com/orhun/gpg-tui"
rev = "0f6e598f9beb19c0263d6fbc0bbbcb222fc704c4"
[build]
template = "cargo"
dependencies = [
    "gnupg",
    "gpgme",
    "libgpg-error",
]
