#TODO gmp-mpfr-sys crate error (after cargo update)
[source]
git = "https://github.com/PaddiM8/kalker"
[build]
template = "custom"
dependencies = [
    "libgmp",
    "libmpfr",
    "mpc",
]
script = """
cookbook_cargo_packages kalker
"""
