#TODO make capnproto work
#TODO probably wrong template, see https://github.com/rr-debugger/rr/wiki/Building-And-Installing
[source]
git = "https://github.com/rr-debugger/rr"
rev = "7cf5a12dba5aaeea9efc5ad97176b07b5614e350"
[build]
template = "configure"
dependencies = [
    "zlib",
    "capnproto",
]
