[package]
name = "audiod"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
edition = "2018"

[dependencies]
redox-daemon = "0.1.2"
redox_syscall = "0.4.1"
libc = "0.2"
libredox = "0.0.3"
redox-scheme = { git = "https://gitlab.redox-os.org/redox-os/redox-scheme.git" }
