[package]
name = "sb16d"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2"
common = { path = "../../common" }
libredox = "0.1.3"
log = "0.4"
redox-daemon = "0.1"
redox-log = "0.1.2"
redox_event = "0.4.1"
redox_syscall = "0.5"
spin = "0.9"
