#!/bin/bash

# install some packages (might have dupes) that are important
sudo apt install build-essential psmisc \
      xdg-utils \
      xorg \
      xorg-dev \
      x11-xserver-utils \
      x11-utils \
      libgtk-3-0 \
      libgtk-3-dev \
      libwnck-dev \
      libwnck-3-0 \
      libwnck-common \
      libwnck-3-dev \
      libwnck-3-common \
#      wmctrl \
      intltool dbus dbus-system-bus-common \
      libglib2.0-dev libgtk2.0-dev  \
      at-spi2-core libxi-dev  \
      libxi6 libxi-dev libxinerama1 libxinerama-dev libgtk-3-bin \
      libxv1 \
      mesa-utils \
      mesa-utils-extra -y

BUILD_ORDER=("xfce4-dev-tools-4.18.0" "libxfce4util-4.18.0" "xfconf-4.18.0" "libxfce4ui-4.18.0" "garcon-4.18.0" "exo-4.18.0" "xfce4-panel-4.18.0" "thunar-4.18.0" "xfce4-settings-4.18.0" "xfce4-session-4.18.0" "xfwm4-4.18.0" "xfdesktop-4.18.0" "xfce4-appfinder-4.18.0" "tumbler-4.18.0")

sudo mkdir -p /usr/xfce-source

install_pack() {
    PACK=$1
    sudo cp "/home/ubuntu/Documents/myxfce/xfce-source/$PACK" "/usr/xfce-source/$PACK" -r
    cd "/usr/xfce-source/$PACK" && sudo ./configure --prefix=/usr/local && sudo make && sudo make install
}

sudo apt install libc6 libglib2.0-0 autoconf automake
install_pack xfce4-dev-tools-4.18.0

install_pack libxfce4util-4.18.0

sudo apt install dbus-user-session dbus-x11
install_pack xfconf-4.18.0

sudo apt install libgtk-3-0 libatk1.0-0 libgdk-pixbuf-2.0-0 libice6 libsm6 libstartup-notification0 libx11-6
install_pack libxfce4ui-4.18.0

sudo apt install # todo...
