#!/bin/bash

# install some packages (might have dupes) that are important
sudo apt install build-essential psmisc \
      xdg-utils \
      xorg \
      xorg-dev \
      x11-xserver-utils \
      x11-utils \
      libgtk-3-0 \
      libgtk-3-dev \
      libwnck-dev \
      libwnck-3-0 \
      libwnck-common \
      libwnck-3-dev \
      libwnck-3-common \
#      wmctrl \
      intltool dbus dbus-system-bus-common \
      libglib2.0-dev libgtk2.0-dev  \
      at-spi2-core libxi-dev  \
      libxi6 libxi-dev libxinerama1 libxinerama-dev libgtk-3-bin \
      libxv1 \
      mesa-utils \
      mesa-utils-extra -y

BUILD_ORDER=("xfce4-dev-tools-4.18.0" "libxfce4util-4.18.0" "xfconf-4.18.0" "libxfce4ui-4.18.0" "garcon-4.18.0" "exo-4.18.0" "xfce4-panel-4.18.0" "thunar-4.18.0" "xfce4-settings-4.18.0" "xfce4-session-4.18.0" "xfwm4-4.18.0" "xfdesktop-4.18.0" "xfce4-appfinder-4.18.0" "tumbler-4.18.0")

sudo mkdir -p /usr/xfce-source

install_pack() {
    PACK=$1
    sudo cp "/home/ubuntu/Documents/myxfce/xfce-source/$PACK" "/usr/xfce-source/$PACK" -r
    cd "/usr/xfce-source/$PACK" && sudo ./configure --prefix=/usr/local && sudo make && sudo make install
}

sudo apt install libc6 libglib2.0-0 autoconf automake
install_pack xfce4-dev-tools-4.18.0

install_pack libxfce4util-4.18.0

sudo apt install dbus-user-session dbus-x11
install_pack xfconf-4.18.0

sudo apt install libgtk-3-0 libatk1.0-0 libgdk-pixbuf-2.0-0 \
    libice6 libsm6 libstartup-notification0 libx11-6
install_pack libxfce4ui-4.18.0

install_pack garcon-4.18.0

sudo apt install libcairo2 liburi-perl sensible-utils
install_pack exo-4.18.0

sudo apt install libdbusmenu-gtk3-4 libpangocairo-1.0-0 \
    libpango-1.0-0 libwnck-3-0 libxext6
install_pack xfce4-panel-4.18.0

sudo apt install exo-utils desktop-file-utils libgudev-1.0-0 \
    libthunarx-3-0 shared-mime-info
install_pack thunar-4.18.0

sudo apt install libcairo-gobject2 libcolord2 libfontconfig1 \
    libnotify4 libupower-glib3 \
    libxcursor1 libxi6 libxklavier16 libxranr2 xfce4-helpers colord
install_pack xfce4-settings-4.18.0

sudo apt install libpolkit-gobject-1-0 x11-server-utils light-locker upower
install_pack xfce4-session-4.18.0

sudo apt install libepoxy0 libgtk-3-0 libxcomposite1 libxdamage1 \
    libxfixes3 libxinerama1 libxpresent1 libxrender1 libxres1 \
    librsvg2-common
install_pack xfwm4-4.18.0

sudo apt install xfdesktop4-data xdg-user-dirs
install_pack xfdesktop-4.18.0


install_pack xfce4-appfinder-4.18.0

sudo apt install libfreetype6 libgstreamer-plugins-base1.0-0 \
    libgstreamer1.0-0 libjpeg62-turbo libpng16-16 libpoppler-glib8 \
    tumbler-plugins-extra
install_pack tumbler-4.18.0


echo "...well, anything could've happened."
