sudo apt install colord \
  dbus-user-session \
  dbus-x11 \
  desktop-file-utils \
  libc6 \
  libcairo2 \
  libcairo-gobject2 \
  libcolord2 \
  libdbusmenu-gtk3-4 \
  libepoxy0 \
  libfontconfig1 \
  libgdk-pixbuf-2.0-0 \
  libglib2.0-0 \
  libgtk-3-0 \
  libgudev-1.0-0 \
  libice6 \
  libnotify4 \
  libpango-1.0-0 \
  libpolkit-gobject-1-0 \
  libsm6 \
  libstartup-notification0 \
  libupower-glib3 \
  libwnck-3-0 \
  libx11-6 \
  libx11-xcb1 \
  libxcomposite1 \
  libxdamage1 \
  libxext6 \
  libxfixes3 \
  libxi6 \
  libxinerama1 \
  libxklavier16 \
  libxpresent1 \
  libxrandr2 \
  libxrender1 \
  libxres1 \
  libxcursor1 \
  libxdamage1 \
  libxfixes3 \
  libxinerama1 \
  libxpresent1 \
  libxrender1 \
  libxres1 \
  librsvg2-common \
  shared-mime-info \
  thunar-data \
  xfce4-helpers \
  xfce4-pulseaudio-plugin \
  xfce4-screensaver \
  xfdesktop4-data \
  x11-xserver-utils \
  xiccd
