/* automatically generated from xfdesktop-settings-ui.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfdesktop_settings_ui)
#endif
#ifdef __GNUC__
static const char xfdesktop_settings_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfdesktop_settings_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!-- Generated with glade 3"
  ".22.1 -->\n<interface>\n  <requires lib=\"gtk+\" version=\"3.20\"/>\n  "
  "<requires lib=\"libxfce4ui-2\" version=\"4.12\"/>\n  <object class=\"Gt"
  "kAdjustment\" id=\"adjustment3\">\n    <property name=\"lower\">16</pro"
  "perty>\n    <property name=\"upper\">192</property>\n    <property name"
  "=\"value\">48</property>\n    <property name=\"step_increment\">2</prop"
  "erty>\n    <property name=\"page_increment\">10</property>\n  </object>"
  "\n  <object class=\"GtkAdjustment\" id=\"adjustment4\">\n    <property "
  "name=\"upper\">144</property>\n    <property name=\"value\">12</propert"
  "y>\n    <property name=\"step_increment\">1</property>\n    <property n"
  "ame=\"page_increment\">10</property>\n  </object>\n  <object class=\"Gt"
  "kAdjustment\" id=\"adjustment_tooltip\">\n    <property name=\"upper\">"
  "256</property>\n    <property name=\"value\">64</property>\n    <proper"
  "ty name=\"step_increment\">4</property>\n    <property name=\"page_incr"
  "ement\">8</property>\n  </object>\n  <object class=\"GtkImage\" id=\"im"
  "age1\">\n    <property name=\"visible\">True</property>\n    <property "
  "name=\"can_focus\">False</property>\n    <property name=\"icon_name\">w"
  "indow-close-symbolic</property>\n  </object>\n  <object class=\"GtkImag"
  "e\" id=\"image2\">\n    <property name=\"visible\">True</property>\n   "
  " <property name=\"can_focus\">False</property>\n    <property name=\"ic"
  "on_name\">help-browser</property>\n  </object>\n  <object class=\"GtkLi"
  "stStore\" id=\"model3\">\n    <columns>\n      <!-- column-name gcharar"
  "ray -->\n      <column type=\"gchararray\"/>\n    </columns>\n    <data"
  ">\n      <row>\n        <col id=\"0\" translatable=\"yes\">Left</col>\n"
  "      </row>\n      <row>\n        <col id=\"0\" translatable=\"yes\">M"
  "iddle</col>\n      </row>\n      <row>\n        <col id=\"0\" translata"
  "ble=\"yes\">Right</col>\n      </row>\n    </data>\n  </object>\n  <obj"
  "ect class=\"GtkListStore\" id=\"model4\">\n    <columns>\n      <!-- co"
  "lumn-name gchararray -->\n      <column type=\"gchararray\"/>\n    </co"
  "lumns>\n    <data>\n      <row>\n        <col id=\"0\" translatable=\"y"
  "es\">None</col>\n      </row>\n      <row>\n        <col id=\"0\" trans"
  "latable=\"yes\">Shift</col>\n      </row>\n      <row>\n        <col id"
  "=\"0\" translatable=\"yes\">Alt</col>\n      </row>\n      <row>\n     "
  "   <col id=\"0\" translatable=\"yes\">Control</col>\n      </row>\n    "
  "</data>\n  </object>\n  <object class=\"GtkListStore\" id=\"model5\">\n"
  "    <columns>\n      <!-- column-name gchararray -->\n      <column typ"
  "e=\"gchararray\"/>\n    </columns>\n    <data>\n      <row>\n        <c"
  "ol id=\"0\" translatable=\"yes\">Left</col>\n      </row>\n      <row>\n"
  "        <col id=\"0\" translatable=\"yes\">Middle</col>\n      </row>\n"
  "      <row>\n        <col id=\"0\" translatable=\"yes\">Right</col>\n  "
  "    </row>\n    </data>\n  </object>\n  <object class=\"GtkListStore\" "
  "id=\"model6\">\n    <columns>\n      <!-- column-name gchararray -->\n "
  "     <column type=\"gchararray\"/>\n    </columns>\n    <data>\n      <"
  "row>\n        <col id=\"0\" translatable=\"yes\">None</col>\n      </ro"
  "w>\n      <row>\n        <col id=\"0\" translatable=\"yes\">Shift</col>"
  "\n      </row>\n      <row>\n        <col id=\"0\" translatable=\"yes\""
  ">Alt</col>\n      </row>\n      <row>\n        <col id=\"0\" translatab"
  "le=\"yes\">Control</col>\n      </row>\n    </data>\n  </object>\n  <ob"
  "ject class=\"GtkListStore\" id=\"model7\">\n    <columns>\n      <!-- c"
  "olumn-name gchararray -->\n      <column type=\"gchararray\"/>\n    </c"
  "olumns>\n    <data>\n      <row>\n        <col id=\"0\" translatable=\""
  "yes\">None</col>\n      </row>\n      <row>\n        <col id=\"0\" tran"
  "slatable=\"yes\">Minimized application icons</col>\n      </row>\n     "
  " <row>\n        <col id=\"0\" translatable=\"yes\">File/launcher icons<"
  "/col>\n      </row>\n    </data>\n  </object>\n  <object class=\"GtkLis"
  "tStore\" id=\"model8\">\n    <columns>\n      <!-- column-name gchararr"
  "ay -->\n      <column type=\"gchararray\"/>\n    </columns>\n    <data>"
  "\n      <row>\n        <col id=\"0\" translatable=\"yes\">Top Left Vert"
  "ical</col>\n      </row>\n      <row>\n        <col id=\"0\" translatab"
  "le=\"yes\">Top Left Horizontal</col>\n      </row>\n      <row>\n      "
  "  <col id=\"0\" translatable=\"yes\">Top Right Vertical</col>\n      </"
  "row>\n      <row>\n        <col id=\"0\" translatable=\"yes\">Top Right"
  " Horizontal</col>\n      </row>\n      <row>\n        <col id=\"0\" tra"
  "nslatable=\"yes\">Bottom Left Vertical</col>\n      </row>\n      <row>"
  "\n        <col id=\"0\" translatable=\"yes\">Bottom Left Horizontal</co"
  "l>\n      </row>\n      <row>\n        <col id=\"0\" translatable=\"yes"
  "\">Bottom Right Vertical</col>\n      </row>\n      <row>\n        <col"
  " id=\"0\" translatable=\"yes\">Bottom Right Horizontal</col>\n      </r"
  "ow>\n    </data>\n  </object>\n  <object class=\"XfceTitledDialog\" id="
  "\"prefs_dialog\">\n    <property name=\"can_focus\">False</property>\n "
  "   <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTI"
  "ON_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</propert"
  "y>\n    <property name=\"title\" translatable=\"yes\">Desktop</property"
  ">\n    <property name=\"window_position\">center-on-parent</property>\n"
  "    <property name=\"default_width\">640</property>\n    <property name"
  "=\"default_height\">480</property>\n    <property name=\"icon_name\">or"
  "g.xfce.xfdesktop</property>\n    <child internal-child=\"vbox\">\n     "
  " <object class=\"GtkBox\" id=\"dialog-vbox1\">\n        <property name="
  "\"visible\">True</property>\n        <property name=\"can_focus\">False"
  "</property>\n        <property name=\"events\">GDK_POINTER_MOTION_MASK "
  "| GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_REL"
  "EASE_MASK</property>\n        <property name=\"orientation\">vertical</"
  "property>\n        <property name=\"spacing\">2</property>\n        <ch"
  "ild internal-child=\"action_area\">\n          <object class=\"GtkButto"
  "nBox\" id=\"dialog-action_area1\">\n            <property name=\"visibl"
  "e\">True</property>\n            <property name=\"can_focus\">False</pr"
  "operty>\n            <property name=\"events\">GDK_POINTER_MOTION_MASK "
  "| GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_REL"
  "EASE_MASK</property>\n            <child>\n              <object class="
  "\"GtkButton\" id=\"button2\">\n                <property name=\"label\""
  " translatable=\"yes\">_Help</property>\n                <property name="
  "\"visible\">True</property>\n                <property name=\"can_focus"
  "\">True</property>\n                <property name=\"receives_default\""
  ">True</property>\n                <property name=\"events\">GDK_POINTER"
  "_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | G"
  "DK_BUTTON_RELEASE_MASK</property>\n                <property name=\"ima"
  "ge\">image2</property>\n                <property name=\"use_underline\""
  ">True</property>\n              </object>\n              <packing>\n   "
  "             <property name=\"expand\">True</property>\n               "
  " <property name=\"fill\">True</property>\n                <property nam"
  "e=\"position\">0</property>\n              </packing>\n            </ch"
  "ild>\n            <child>\n              <object class=\"GtkButton\" id"
  "=\"bnt_exit\">\n                <property name=\"label\" translatable=\""
  "yes\">_Close</property>\n                <property name=\"visible\">Tru"
  "e</property>\n                <property name=\"can_focus\">True</proper"
  "ty>\n                <property name=\"receives_default\">True</property"
  ">\n                <property name=\"events\">GDK_POINTER_MOTION_MASK | "
  "GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEA"
  "SE_MASK</property>\n                <property name=\"image\">image1</pr"
  "operty>\n                <property name=\"use_underline\">True</propert"
  "y>\n              </object>\n              <packing>\n                <"
  "property name=\"expand\">True</property>\n                <property nam"
  "e=\"fill\">True</property>\n                <property name=\"position\""
  ">1</property>\n              </packing>\n            </child>\n        "
  "  </object>\n          <packing>\n            <property name=\"expand\""
  ">False</property>\n            <property name=\"fill\">False</property>"
  "\n            <property name=\"pack_type\">end</property>\n            "
  "<property name=\"position\">0</property>\n          </packing>\n       "
  " </child>\n        <child>\n          <object class=\"GtkAlignment\" id"
  "=\"alignment1\">\n            <property name=\"visible\">True</property"
  ">\n            <property name=\"can_focus\">False</property>\n         "
  "   <property name=\"vexpand\">True</property>\n            <child>\n   "
  "           <object class=\"GtkNotebook\" id=\"notebook_settings\">\n   "
  "             <property name=\"visible\">True</property>\n              "
  "  <property name=\"can_focus\">True</property>\n                <proper"
  "ty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MA"
  "SK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n      "
  "          <property name=\"border_width\">6</property>\n               "
  " <child>\n                  <object class=\"GtkNotebook\" id=\"notebook"
  "_screens\">\n                    <property name=\"visible\">True</prope"
  "rty>\n                    <property name=\"can_focus\">True</property>\n"
  "                    <property name=\"show_border\">False</property>\n  "
  "                </object>\n                </child>\n                <c"
  "hild type=\"tab\">\n                  <object class=\"GtkLabel\" id=\"l"
  "abel1\">\n                    <property name=\"visible\">True</property"
  ">\n                    <property name=\"can_focus\">False</property>\n "
  "                   <property name=\"events\">GDK_POINTER_MOTION_MASK | "
  "GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEA"
  "SE_MASK</property>\n                    <property name=\"label\" transl"
  "atable=\"yes\">_Background</property>\n                    <property na"
  "me=\"use_underline\">True</property>\n                  </object>\n    "
  "              <packing>\n                    <property name=\"tab_fill\""
  ">False</property>\n                  </packing>\n                </chil"
  "d>\n                <child>\n                  <object class=\"GtkBox\""
  " id=\"vbox4\">\n                    <property name=\"visible\">True</pr"
  "operty>\n                    <property name=\"can_focus\">False</proper"
  "ty>\n                    <property name=\"events\">GDK_POINTER_MOTION_M"
  "ASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON"
  "_RELEASE_MASK</property>\n                    <property name=\"border_w"
  "idth\">12</property>\n                    <property name=\"orientation\""
  ">vertical</property>\n                    <property name=\"spacing\">18"
  "</property>\n                    <child>\n                      <object"
  " class=\"GtkFrame\" id=\"frame4\">\n                        <property n"
  "ame=\"visible\">True</property>\n                        <property name"
  "=\"can_focus\">False</property>\n                        <property name"
  "=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GD"
  "K_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n             "
  "           <property name=\"label_xalign\">0</property>\n              "
  "          <property name=\"shadow_type\">none</property>\n             "
  "           <child>\n                          <object class=\"GtkAlignm"
  "ent\" id=\"alignment5\">\n                            <property name=\""
  "visible\">True</property>\n                            <property name=\""
  "can_focus\">False</property>\n                            <property nam"
  "e=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | G"
  "DK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n            "
  "                <property name=\"top_padding\">6</property>\n          "
  "                  <property name=\"left_padding\">12</property>\n      "
  "                      <child>\n                              <object cl"
  "ass=\"GtkBox\" id=\"vbox7\">\n                                <property"
  " name=\"visible\">True</property>\n                                <pro"
  "perty name=\"can_focus\">False</property>\n                            "
  "    <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOT"
  "ION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</proper"
  "ty>\n                                <property name=\"orientation\">ver"
  "tical</property>\n                                <property name=\"spac"
  "ing\">6</property>\n                                <child>\n          "
  "                        <object class=\"GtkCheckButton\" id=\"chk_show_"
  "delete_option\">\n                                    <property name=\""
  "label\" translatable=\"yes\">Enable \"Delete\" option in file context m"
  "enu</property>\n                                    <property name=\"vi"
  "sible\">True</property>\n                                    <property "
  "name=\"can_focus\">True</property>\n                                   "
  " <property name=\"receives_default\">False</property>\n                "
  "                    <property name=\"events\">GDK_POINTER_MOTION_MASK |"
  " GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELE"
  "ASE_MASK</property>\n                                    <property name"
  "=\"use_underline\">True</property>\n                                   "
  " <property name=\"active\">True</property>\n                           "
  "         <property name=\"draw_indicator\">True</property>\n           "
  "                       </object>\n                                  <pa"
  "cking>\n                                    <property name=\"expand\">T"
  "rue</property>\n                                    <property name=\"fi"
  "ll\">True</property>\n                                    <property nam"
  "e=\"position\">0</property>\n                                  </packin"
  "g>\n                                </child>\n                         "
  "       <child>\n                                  <object class=\"GtkCh"
  "eckButton\" id=\"chk_show_desktop_menu\">\n                            "
  "        <property name=\"label\" translatable=\"yes\">Include applicati"
  "ons menu on _desktop right click</property>\n                          "
  "          <property name=\"visible\">True</property>\n                 "
  "                   <property name=\"can_focus\">True</property>\n      "
  "                              <property name=\"receives_default\">False"
  "</property>\n                                    <property name=\"event"
  "s\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON"
  "_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                     "
  "               <property name=\"use_underline\">True</property>\n      "
  "                              <property name=\"active\">True</property>"
  "\n                                    <property name=\"draw_indicator\""
  ">True</property>\n                                  </object>\n        "
  "                          <packing>\n                                  "
  "  <property name=\"expand\">True</property>\n                          "
  "          <property name=\"fill\">True</property>\n                    "
  "                <property name=\"position\">1</property>\n             "
  "                     </packing>\n                                </chil"
  "d>\n                                <child>\n                          "
  "        <object class=\"GtkAlignment\" id=\"box_menu_subopts\">\n      "
  "                              <property name=\"visible\">True</property"
  ">\n                                    <property name=\"can_focus\">Fal"
  "se</property>\n                                    <property name=\"eve"
  "nts\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTT"
  "ON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                   "
  "                 <property name=\"left_padding\">12</property>\n       "
  "                             <child>\n                                 "
  "     <object class=\"GtkBox\" id=\"vbox10\">\n                         "
  "               <property name=\"visible\">True</property>\n            "
  "                            <property name=\"can_focus\">False</propert"
  "y>\n                                        <property name=\"events\">G"
  "DK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRES"
  "S_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                          "
  "              <property name=\"orientation\">vertical</property>\n     "
  "                                   <property name=\"spacing\">6</proper"
  "ty>\n                                        <child>\n                 "
  "                         <object class=\"GtkBox\" id=\"hbox11\">\n     "
  "                                       <property name=\"can_focus\">Fal"
  "se</property>\n                                            <property na"
  "me=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | "
  "GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n           "
  "                                 <property name=\"spacing\">12</propert"
  "y>\n                                            <child>\n              "
  "                                <object class=\"GtkLabel\" id=\"label17"
  "\">\n                                                <property name=\"v"
  "isible\">True</property>\n                                             "
  "   <property name=\"can_focus\">False</property>\n                     "
  "                           <property name=\"events\">GDK_POINTER_MOTION"
  "_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTT"
  "ON_RELEASE_MASK</property>\n                                           "
  "     <property name=\"label\" translatable=\"yes\">_Button:</property>\n"
  "                                                <property name=\"use_un"
  "derline\">True</property>\n                                            "
  "    <property name=\"mnemonic_widget\">combobox1</property>\n          "
  "                                    </object>\n                        "
  "                      <packing>\n                                      "
  "          <property name=\"expand\">False</property>\n                 "
  "                               <property name=\"fill\">True</property>\n"
  "                                                <property name=\"positi"
  "on\">0</property>\n                                              </pack"
  "ing>\n                                            </child>\n           "
  "                                 <child>\n                             "
  "                 <object class=\"GtkComboBox\" id=\"combobox1\">\n     "
  "                                           <property name=\"visible\">T"
  "rue</property>\n                                                <proper"
  "ty name=\"can_focus\">False</property>\n                               "
  "                 <property name=\"events\">GDK_POINTER_MOTION_MASK | GD"
  "K_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE"
  "_MASK</property>\n                                                <prop"
  "erty name=\"model\">model3</property>\n                                "
  "                <child>\n                                              "
  "    <object class=\"GtkCellRendererText\" id=\"renderer3\"/>\n         "
  "                                         <attributes>\n                "
  "                                    <attribute name=\"text\">0</attribu"
  "te>\n                                                  </attributes>\n "
  "                                               </child>\n              "
  "                                </object>\n                            "
  "                  <packing>\n                                          "
  "      <property name=\"expand\">False</property>\n                     "
  "                           <property name=\"fill\">True</property>\n   "
  "                                             <property name=\"position\""
  ">1</property>\n                                              </packing>"
  "\n                                            </child>\n               "
  "                             <child>\n                                 "
  "             <object class=\"GtkLabel\" id=\"label18\">\n              "
  "                                  <property name=\"visible\">True</prop"
  "erty>\n                                                <property name=\""
  "can_focus\">False</property>\n                                         "
  "       <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_"
  "MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</pro"
  "perty>\n                                                <property name="
  "\"label\" translatable=\"yes\">Mo_difier:</property>\n                 "
  "                               <property name=\"use_underline\">True</p"
  "roperty>\n                                                <property nam"
  "e=\"mnemonic_widget\">combobox2</property>\n                           "
  "                   </object>\n                                         "
  "     <packing>\n                                                <proper"
  "ty name=\"expand\">False</property>\n                                  "
  "              <property name=\"fill\">True</property>\n                "
  "                                <property name=\"position\">2</property"
  ">\n                                              </packing>\n          "
  "                                  </child>\n                           "
  "                 <child>\n                                             "
  " <object class=\"GtkComboBox\" id=\"combobox2\">\n                     "
  "                           <property name=\"visible\">True</property>\n"
  "                                                <property name=\"can_fo"
  "cus\">False</property>\n                                               "
  " <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION"
  "_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>"
  "\n                                                <property name=\"mode"
  "l\">model4</property>\n                                                "
  "<child>\n                                                  <object clas"
  "s=\"GtkCellRendererText\" id=\"renderer4\"/>\n                         "
  "                         <attributes>\n                                "
  "                    <attribute name=\"text\">0</attribute>\n           "
  "                                       </attributes>\n                 "
  "                               </child>\n                              "
  "                </object>\n                                            "
  "  <packing>\n                                                <property "
  "name=\"expand\">False</property>\n                                     "
  "           <property name=\"fill\">True</property>\n                   "
  "                             <property name=\"position\">3</property>\n"
  "                                              </packing>\n             "
  "                               </child>\n                              "
  "            </object>\n                                          <packi"
  "ng>\n                                            <property name=\"expan"
  "d\">True</property>\n                                            <prope"
  "rty name=\"fill\">True</property>\n                                    "
  "        <property name=\"position\">0</property>\n                     "
  "                     </packing>\n                                      "
  "  </child>\n                                        <child>\n          "
  "                                <object class=\"GtkCheckButton\" id=\"c"
  "hk_menu_show_app_icons\">\n                                            "
  "<property name=\"label\" translatable=\"yes\">Show _application icons i"
  "n menu</property>\n                                            <propert"
  "y name=\"visible\">True</property>\n                                   "
  "         <property name=\"can_focus\">True</property>\n                "
  "                            <property name=\"receives_default\">False</"
  "property>\n                                            <property name=\""
  "events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_B"
  "UTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                "
  "                            <property name=\"use_underline\">True</prop"
  "erty>\n                                            <property name=\"act"
  "ive\">True</property>\n                                            <pro"
  "perty name=\"draw_indicator\">True</property>\n                        "
  "                  </object>\n                                          "
  "<packing>\n                                            <property name=\""
  "expand\">True</property>\n                                            <"
  "property name=\"fill\">True</property>\n                               "
  "             <property name=\"position\">1</property>\n                "
  "                          </packing>\n                                 "
  "       </child>\n                                        <child>\n     "
  "                                     <object class=\"GtkBox\" id=\"hbox"
  "12\">\n                                            <property name=\"can"
  "_focus\">False</property>\n                                            "
  "<property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_"
  "HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n"
  "                                            <property name=\"spacing\">"
  "12</property>\n                                            <child>\n   "
  "                                           <object class=\"GtkButton\" "
  "id=\"button5\">\n                                                <prope"
  "rty name=\"label\" translatable=\"yes\">_Edit desktop menu</property>\n"
  "                                                <property name=\"visibl"
  "e\">True</property>\n                                                <p"
  "roperty name=\"can_focus\">True</property>\n                           "
  "                     <property name=\"receives_default\">True</property"
  ">\n                                                <property name=\"eve"
  "nts\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTT"
  "ON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                   "
  "                             <property name=\"use_underline\">True</pro"
  "perty>\n                                              </object>\n      "
  "                                        <packing>\n                    "
  "                            <property name=\"expand\">False</property>\n"
  "                                                <property name=\"fill\""
  ">True</property>\n                                                <prop"
  "erty name=\"position\">0</property>\n                                  "
  "            </packing>\n                                            </c"
  "hild>\n                                          </object>\n           "
  "                               <packing>\n                             "
  "               <property name=\"expand\">True</property>\n             "
  "                               <property name=\"fill\">True</property>\n"
  "                                            <property name=\"position\""
  ">2</property>\n                                          </packing>\n  "
  "                                      </child>\n                       "
  "               </object>\n                                    </child>\n"
  "                                  </object>\n                          "
  "        <packing>\n                                    <property name=\""
  "expand\">True</property>\n                                    <property"
  " name=\"fill\">True</property>\n                                    <pr"
  "operty name=\"position\">2</property>\n                                "
  "  </packing>\n                                </child>\n               "
  "               </object>\n                            </child>\n       "
  "                   </object>\n                        </child>\n       "
  "                 <child type=\"label\">\n                          <obj"
  "ect class=\"GtkLabel\" id=\"label10\">\n                            <pr"
  "operty name=\"visible\">True</property>\n                            <p"
  "roperty name=\"can_focus\">False</property>\n                          "
  "  <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTIO"
  "N_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property"
  ">\n                            <property name=\"label\" translatable=\""
  "yes\">&lt;b&gt;Desktop Menu&lt;/b&gt;</property>\n                     "
  "       <property name=\"use_markup\">True</property>\n                 "
  "         </object>\n                        </child>\n                 "
  "     </object>\n                      <packing>\n                      "
  "  <property name=\"expand\">False</property>\n                        <"
  "property name=\"fill\">True</property>\n                        <proper"
  "ty name=\"position\">0</property>\n                      </packing>\n  "
  "                  </child>\n                    <child>\n              "
  "        <object class=\"GtkFrame\" id=\"frame5\">\n                    "
  "    <property name=\"visible\">True</property>\n                       "
  " <property name=\"can_focus\">False</property>\n                       "
  " <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION"
  "_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>"
  "\n                        <property name=\"label_xalign\">0</property>\n"
  "                        <property name=\"shadow_type\">none</property>\n"
  "                        <child>\n                          <object clas"
  "s=\"GtkAlignment\" id=\"alignment6\">\n                            <pro"
  "perty name=\"visible\">True</property>\n                            <pr"
  "operty name=\"can_focus\">False</property>\n                           "
  " <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION"
  "_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>"
  "\n                            <property name=\"top_padding\">6</propert"
  "y>\n                            <property name=\"left_padding\">12</pro"
  "perty>\n                            <child>\n                          "
  "    <object class=\"GtkBox\" id=\"vbox8\">\n                           "
  "     <property name=\"visible\">True</property>\n                      "
  "          <property name=\"can_focus\">False</property>\n              "
  "                  <property name=\"events\">GDK_POINTER_MOTION_MASK | G"
  "DK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEAS"
  "E_MASK</property>\n                                <property name=\"ori"
  "entation\">vertical</property>\n                                <proper"
  "ty name=\"spacing\">6</property>\n                                <chil"
  "d>\n                                  <object class=\"GtkCheckButton\" "
  "id=\"chk_show_winlist_menu\">\n                                    <pro"
  "perty name=\"label\" translatable=\"yes\">Show _window list menu on des"
  "ktop middle click</property>\n                                    <prop"
  "erty name=\"visible\">True</property>\n                                "
  "    <property name=\"can_focus\">True</property>\n                     "
  "               <property name=\"receives_default\">False</property>\n  "
  "                                  <property name=\"events\">GDK_POINTER"
  "_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | G"
  "DK_BUTTON_RELEASE_MASK</property>\n                                    "
  "<property name=\"use_underline\">True</property>\n                     "
  "               <property name=\"active\">True</property>\n             "
  "                       <property name=\"draw_indicator\">True</property"
  ">\n                                  </object>\n                       "
  "           <packing>\n                                    <property nam"
  "e=\"expand\">True</property>\n                                    <prop"
  "erty name=\"fill\">True</property>\n                                   "
  " <property name=\"position\">0</property>\n                            "
  "      </packing>\n                                </child>\n           "
  "                     <child>\n                                  <object"
  " class=\"GtkAlignment\" id=\"box_winlist_subopts\">\n                  "
  "                  <property name=\"visible\">True</property>\n         "
  "                           <property name=\"can_focus\">False</property"
  ">\n                                    <property name=\"events\">GDK_PO"
  "INTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MAS"
  "K | GDK_BUTTON_RELEASE_MASK</property>\n                               "
  "     <property name=\"left_padding\">12</property>\n                   "
  "                 <child>\n                                      <object"
  " class=\"GtkBox\" id=\"vbox11\">\n                                     "
  "   <property name=\"visible\">True</property>\n                        "
  "                <property name=\"can_focus\">False</property>\n        "
  "                                <property name=\"events\">GDK_POINTER_M"
  "OTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK"
  "_BUTTON_RELEASE_MASK</property>\n                                      "
  "  <property name=\"orientation\">vertical</property>\n                 "
  "                       <property name=\"spacing\">6</property>\n       "
  "                                 <child>\n                             "
  "             <object class=\"GtkBox\" id=\"hbox14\">\n                 "
  "                           <property name=\"can_focus\">False</property"
  ">\n                                            <property name=\"events\""
  ">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PR"
  "ESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                        "
  "                    <property name=\"spacing\">12</property>\n         "
  "                                   <child>\n                           "
  "                   <object class=\"GtkLabel\" id=\"label23\">\n        "
  "                                        <property name=\"visible\">True"
  "</property>\n                                                <property "
  "name=\"can_focus\">False</property>\n                                  "
  "              <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_P"
  "OINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MA"
  "SK</property>\n                                                <propert"
  "y name=\"label\" translatable=\"yes\">B_utton:</property>\n            "
  "                                    <property name=\"use_underline\">Tr"
  "ue</property>\n                                                <propert"
  "y name=\"mnemonic_widget\">combobox8</property>\n                      "
  "                        </object>\n                                    "
  "          <packing>\n                                                <p"
  "roperty name=\"expand\">False</property>\n                             "
  "                   <property name=\"fill\">True</property>\n           "
  "                                     <property name=\"position\">0</pro"
  "perty>\n                                              </packing>\n     "
  "                                       </child>\n                      "
  "                      <child>\n                                        "
  "      <object class=\"GtkComboBox\" id=\"combobox8\">\n                "
  "                                <property name=\"visible\">True</proper"
  "ty>\n                                                <property name=\"c"
  "an_focus\">False</property>\n                                          "
  "      <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_M"
  "OTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</prop"
  "erty>\n                                                <property name=\""
  "model\">model5</property>\n                                            "
  "    <child>\n                                                  <object "
  "class=\"GtkCellRendererText\" id=\"renderer5\"/>\n                     "
  "                             <attributes>\n                            "
  "                        <attribute name=\"text\">0</attribute>\n       "
  "                                           </attributes>\n             "
  "                                   </child>\n                          "
  "                    </object>\n                                        "
  "      <packing>\n                                                <prope"
  "rty name=\"expand\">False</property>\n                                 "
  "               <property name=\"fill\">True</property>\n               "
  "                                 <property name=\"position\">1</propert"
  "y>\n                                              </packing>\n         "
  "                                   </child>\n                          "
  "                  <child>\n                                            "
  "  <object class=\"GtkLabel\" id=\"label24\">\n                         "
  "                       <property name=\"visible\">True</property>\n    "
  "                                            <property name=\"can_focus\""
  ">False</property>\n                                                <pro"
  "perty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT"
  "_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n   "
  "                                             <property name=\"label\" t"
  "ranslatable=\"yes\">Modi_fier:</property>\n                            "
  "                    <property name=\"use_underline\">True</property>\n "
  "                                               <property name=\"mnemoni"
  "c_widget\">combobox9</property>\n                                      "
  "        </object>\n                                              <packi"
  "ng>\n                                                <property name=\"e"
  "xpand\">False</property>\n                                             "
  "   <property name=\"fill\">True</property>\n                           "
  "                     <property name=\"position\">2</property>\n        "
  "                                      </packing>\n                     "
  "                       </child>\n                                      "
  "      <child>\n                                              <object cl"
  "ass=\"GtkComboBox\" id=\"combobox9\">\n                                "
  "                <property name=\"visible\">True</property>\n           "
  "                                     <property name=\"can_focus\">False"
  "</property>\n                                                <property "
  "name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK "
  "| GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n         "
  "                                       <property name=\"model\">model6<"
  "/property>\n                                                <child>\n  "
  "                                                <object class=\"GtkCell"
  "RendererText\" id=\"renderer6\"/>\n                                    "
  "              <attributes>\n                                           "
  "         <attribute name=\"text\">0</attribute>\n                      "
  "                            </attributes>\n                            "
  "                    </child>\n                                         "
  "     </object>\n                                              <packing>"
  "\n                                                <property name=\"expa"
  "nd\">False</property>\n                                                "
  "<property name=\"fill\">True</property>\n                              "
  "                  <property name=\"position\">3</property>\n           "
  "                                   </packing>\n                        "
  "                    </child>\n                                         "
  " </object>\n                                          <packing>\n      "
  "                                      <property name=\"expand\">True</p"
  "roperty>\n                                            <property name=\""
  "fill\">True</property>\n                                            <pr"
  "operty name=\"position\">0</property>\n                                "
  "          </packing>\n                                        </child>\n"
  "                                        <child>\n                      "
  "                    <object class=\"GtkCheckButton\" id=\"chk_winlist_s"
  "how_app_icons\">\n                                            <property"
  " name=\"label\" translatable=\"yes\">Sh_ow application icons in menu</p"
  "roperty>\n                                            <property name=\""
  "visible\">True</property>\n                                            "
  "<property name=\"can_focus\">True</property>\n                         "
  "                   <property name=\"receives_default\">False</property>"
  "\n                                            <property name=\"events\""
  ">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PR"
  "ESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                        "
  "                    <property name=\"use_underline\">True</property>\n "
  "                                           <property name=\"active\">Tr"
  "ue</property>\n                                            <property na"
  "me=\"draw_indicator\">True</property>\n                                "
  "          </object>\n                                          <packing"
  ">\n                                            <property name=\"expand\""
  ">True</property>\n                                            <property"
  " name=\"fill\">True</property>\n                                       "
  "     <property name=\"position\">1</property>\n                        "
  "                  </packing>\n                                        <"
  "/child>\n                                        <child>\n             "
  "                             <object class=\"GtkCheckButton\" id=\"chk_"
  "show_winlist_ws_names\">\n                                            <"
  "property name=\"label\" translatable=\"yes\">Show workspace _names in l"
  "ist</property>\n                                            <property n"
  "ame=\"visible\">True</property>\n                                      "
  "      <property name=\"can_focus\">True</property>\n                   "
  "                         <property name=\"receives_default\">False</pro"
  "perty>\n                                            <property name=\"ev"
  "ents\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUT"
  "TON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                  "
  "                          <property name=\"use_underline\">True</proper"
  "ty>\n                                            <property name=\"activ"
  "e\">True</property>\n                                            <prope"
  "rty name=\"draw_indicator\">True</property>\n                          "
  "                </object>\n                                          <p"
  "acking>\n                                            <property name=\"e"
  "xpand\">True</property>\n                                            <p"
  "roperty name=\"fill\">True</property>\n                                "
  "            <property name=\"position\">2</property>\n                 "
  "                         </packing>\n                                  "
  "      </child>\n                                        <child>\n      "
  "                                    <object class=\"GtkAlignment\" id=\""
  "box_winlist_names_subopts\">\n                                         "
  "   <property name=\"visible\">True</property>\n                        "
  "                    <property name=\"can_focus\">False</property>\n    "
  "                                        <property name=\"events\">GDK_P"
  "OINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MA"
  "SK | GDK_BUTTON_RELEASE_MASK</property>\n                              "
  "              <property name=\"left_padding\">12</property>\n          "
  "                                  <child>\n                            "
  "                  <object class=\"GtkCheckButton\" id=\"chk_show_winlis"
  "t_ws_submenus\">\n                                                <prop"
  "erty name=\"label\" translatable=\"yes\">Use _submenus for the windows "
  "in each workspace</property>\n                                         "
  "       <property name=\"visible\">True</property>\n                    "
  "                            <property name=\"can_focus\">True</property"
  ">\n                                                <property name=\"rec"
  "eives_default\">False</property>\n                                     "
  "           <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POIN"
  "TER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK<"
  "/property>\n                                                <property n"
  "ame=\"use_underline\">True</property>\n                                "
  "                <property name=\"draw_indicator\">True</property>\n    "
  "                                          </object>\n                  "
  "                          </child>\n                                   "
  "       </object>\n                                          <packing>\n"
  "                                            <property name=\"expand\">T"
  "rue</property>\n                                            <property n"
  "ame=\"fill\">True</property>\n                                         "
  "   <property name=\"position\">3</property>\n                          "
  "                </packing>\n                                        </c"
  "hild>\n                                        <child>\n               "
  "                           <object class=\"GtkCheckButton\" id=\"chk_sh"
  "ow_winlist_sticky_once\">\n                                            "
  "<property name=\"label\" translatable=\"yes\">Show s_ticky windows only"
  " in active workspace</property>\n                                      "
  "      <property name=\"visible\">True</property>\n                     "
  "                       <property name=\"can_focus\">True</property>\n  "
  "                                          <property name=\"receives_def"
  "ault\">False</property>\n                                            <p"
  "roperty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HI"
  "NT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n "
  "                                           <property name=\"use_underli"
  "ne\">True</property>\n                                            <prop"
  "erty name=\"draw_indicator\">True</property>\n                         "
  "                 </object>\n                                          <"
  "packing>\n                                            <property name=\""
  "expand\">True</property>\n                                            <"
  "property name=\"fill\">True</property>\n                               "
  "             <property name=\"position\">4</property>\n                "
  "                          </packing>\n                                 "
  "       </child>\n                                        <child>\n     "
  "                                     <object class=\"GtkCheckButton\" i"
  "d=\"chk_show_app_remove_workspaces\">\n                                "
  "            <property name=\"label\" translatable=\"yes\">Show a_dd and"
  " remove workspace options in list</property>\n                         "
  "                   <property name=\"visible\">True</property>\n        "
  "                                    <property name=\"can_focus\">True</"
  "property>\n                                            <property name=\""
  "receives_default\">False</property>\n                                  "
  "          <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINT"
  "ER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</"
  "property>\n                                            <property name=\""
  "use_underline\">True</property>\n                                      "
  "      <property name=\"active\">True</property>\n                      "
  "                      <property name=\"draw_indicator\">True</property>"
  "\n                                          </object>\n                "
  "                          <packing>\n                                  "
  "          <property name=\"expand\">True</property>\n                  "
  "                          <property name=\"fill\">True</property>\n    "
  "                                        <property name=\"position\">5</"
  "property>\n                                          </packing>\n      "
  "                                  </child>\n                           "
  "           </object>\n                                    </child>\n   "
  "                               </object>\n                             "
  "     <packing>\n                                    <property name=\"ex"
  "pand\">True</property>\n                                    <property n"
  "ame=\"fill\">True</property>\n                                    <prop"
  "erty name=\"position\">1</property>\n                                  "
  "</packing>\n                                </child>\n                 "
  "             </object>\n                            </child>\n         "
  "                 </object>\n                        </child>\n         "
  "               <child type=\"label\">\n                          <objec"
  "t class=\"GtkLabel\" id=\"label11\">\n                            <prop"
  "erty name=\"visible\">True</property>\n                            <pro"
  "perty name=\"can_focus\">False</property>\n                            "
  "<property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_"
  "HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n"
  "                            <property name=\"label\" translatable=\"yes"
  "\">&lt;b&gt;Window List Menu&lt;/b&gt;</property>\n                    "
  "        <property name=\"use_markup\">True</property>\n                "
  "          </object>\n                        </child>\n                "
  "      </object>\n                      <packing>\n                     "
  "   <property name=\"expand\">False</property>\n                        "
  "<property name=\"fill\">True</property>\n                        <prope"
  "rty name=\"position\">1</property>\n                      </packing>\n "
  "                   </child>\n                  </object>\n             "
  "     <packing>\n                    <property name=\"position\">1</prop"
  "erty>\n                  </packing>\n                </child>\n        "
  "        <child type=\"tab\">\n                  <object class=\"GtkLabe"
  "l\" id=\"label2\">\n                    <property name=\"visible\">True"
  "</property>\n                    <property name=\"can_focus\">False</pr"
  "operty>\n                    <property name=\"events\">GDK_POINTER_MOTI"
  "ON_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BU"
  "TTON_RELEASE_MASK</property>\n                    <property name=\"labe"
  "l\" translatable=\"yes\">_Menus</property>\n                    <proper"
  "ty name=\"use_underline\">True</property>\n                  </object>\n"
  "                  <packing>\n                    <property name=\"posit"
  "ion\">1</property>\n                    <property name=\"tab_fill\">Fal"
  "se</property>\n                  </packing>\n                </child>\n"
  "                <child>\n                  <object class=\"GtkBox\" id="
  "\"vbox9\">\n                    <property name=\"visible\">True</proper"
  "ty>\n                    <property name=\"can_focus\">False</property>\n"
  "                    <property name=\"events\">GDK_POINTER_MOTION_MASK |"
  " GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELE"
  "ASE_MASK</property>\n                    <property name=\"border_width\""
  ">12</property>\n                    <property name=\"orientation\">vert"
  "ical</property>\n                    <property name=\"spacing\">18</pro"
  "perty>\n                    <child>\n                      <object clas"
  "s=\"GtkFrame\" id=\"frame6\">\n                        <property name=\""
  "visible\">True</property>\n                        <property name=\"can"
  "_focus\">False</property>\n                        <property name=\"eve"
  "nts\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTT"
  "ON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                   "
  "     <property name=\"label_xalign\">0</property>\n                    "
  "    <property name=\"shadow_type\">none</property>\n                   "
  "     <child>\n                          <object class=\"GtkAlignment\" "
  "id=\"alignment11\">\n                            <property name=\"visib"
  "le\">True</property>\n                            <property name=\"can_"
  "focus\">False</property>\n                            <property name=\""
  "events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_B"
  "UTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                "
  "            <property name=\"top_padding\">6</property>\n              "
  "              <property name=\"left_padding\">12</property>\n          "
  "                  <child>\n                              <object class="
  "\"GtkGrid\">\n                                <property name=\"visible\""
  ">True</property>\n                                <property name=\"can_"
  "focus\">False</property>\n                                <property nam"
  "e=\"row_spacing\">6</property>\n                                <proper"
  "ty name=\"column_spacing\">12</property>\n                             "
  "   <child>\n                                  <object class=\"GtkLabel\""
  " id=\"label12\">\n                                    <property name=\""
  "visible\">True</property>\n                                    <propert"
  "y name=\"can_focus\">False</property>\n                                "
  "    <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOT"
  "ION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</proper"
  "ty>\n                                    <property name=\"label\" trans"
  "latable=\"yes\">Icon _type:</property>\n                               "
  "     <property name=\"use_underline\">True</property>\n                "
  "                    <property name=\"xalign\">0</property>\n           "
  "                       </object>\n                                  <pa"
  "cking>\n                                    <property name=\"left_attac"
  "h\">0</property>\n                                    <property name=\""
  "top_attach\">0</property>\n                                  </packing>"
  "\n                                </child>\n                           "
  "     <child>\n                                  <object class=\"GtkComb"
  "oBox\" id=\"combo_icons\">\n                                    <proper"
  "ty name=\"visible\">True</property>\n                                  "
  "  <property name=\"can_focus\">False</property>\n                      "
  "              <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_P"
  "OINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MA"
  "SK</property>\n                                    <property name=\"hal"
  "ign\">start</property>\n                                    <property n"
  "ame=\"model\">model7</property>\n                                    <c"
  "hild>\n                                      <object class=\"GtkCellRen"
  "dererText\" id=\"renderer7\"/>\n                                      <"
  "attributes>\n                                        <attribute name=\""
  "text\">0</attribute>\n                                      </attribute"
  "s>\n                                    </child>\n                     "
  "             </object>\n                                  <packing>\n  "
  "                                  <property name=\"left_attach\">1</pro"
  "perty>\n                                    <property name=\"top_attach"
  "\">0</property>\n                                  </packing>\n        "
  "                        </child>\n                                <chil"
  "d>\n                                  <object class=\"GtkLabel\" id=\"l"
  "abel13\">\n                                    <property name=\"visible"
  "\">True</property>\n                                    <property name="
  "\"can_focus\">False</property>\n                                    <pr"
  "operty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HIN"
  "T_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n  "
  "                                  <property name=\"label\" translatable"
  "=\"yes\">Icon _size:</property>\n                                    <p"
  "roperty name=\"use_underline\">True</property>\n                       "
  "             <property name=\"xalign\">0</property>\n                  "
  "                </object>\n                                  <packing>\n"
  "                                    <property name=\"left_attach\">0</p"
  "roperty>\n                                    <property name=\"top_atta"
  "ch\">1</property>\n                                  </packing>\n      "
  "                          </child>\n                                <ch"
  "ild>\n                                  <object class=\"GtkSpinButton\""
  " id=\"spin_icon_size\">\n                                    <property "
  "name=\"visible\">True</property>\n                                    <"
  "property name=\"can_focus\">True</property>\n                          "
  "          <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINT"
  "ER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</"
  "property>\n                                    <property name=\"halign\""
  ">start</property>\n                                    <property name=\""
  "text\" translatable=\"yes\">48</property>\n                            "
  "        <property name=\"adjustment\">adjustment3</property>\n         "
  "                           <property name=\"value\">48</property>\n    "
  "                              </object>\n                              "
  "    <packing>\n                                    <property name=\"lef"
  "t_attach\">1</property>\n                                    <property "
  "name=\"top_attach\">1</property>\n                                  </p"
  "acking>\n                                </child>\n                    "
  "            <child>\n                                  <object class=\""
  "GtkLabel\" id=\"label14\">\n                                    <proper"
  "ty name=\"visible\">True</property>\n                                  "
  "  <property name=\"can_focus\">False</property>\n                      "
  "              <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_P"
  "OINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MA"
  "SK</property>\n                                    <property name=\"lab"
  "el\" translatable=\"yes\">Icons _orientation:</property>\n             "
  "                       <property name=\"use_underline\">True</property>"
  "\n                                    <property name=\"xalign\">0</prop"
  "erty>\n                                  </object>\n                   "
  "               <packing>\n                                    <property"
  " name=\"left_attach\">0</property>\n                                   "
  " <property name=\"top_attach\">2</property>\n                          "
  "        </packing>\n                                </child>\n         "
  "                       <child>\n                                  <obje"
  "ct class=\"GtkComboBox\" id=\"combo_orientation\">\n                   "
  "                 <property name=\"visible\">True</property>\n          "
  "                          <property name=\"can_focus\">False</property>"
  "\n                                    <property name=\"events\">GDK_POI"
  "NTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK"
  " | GDK_BUTTON_RELEASE_MASK</property>\n                                "
  "    <property name=\"halign\">start</property>\n                       "
  "             <property name=\"model\">model8</property>\n              "
  "                      <child>\n                                      <o"
  "bject class=\"GtkCellRendererText\" id=\"renderer8\"/>\n               "
  "                       <attributes>\n                                  "
  "      <attribute name=\"text\">0</attribute>\n                         "
  "             </attributes>\n                                    </child"
  ">\n                                  </object>\n                       "
  "           <packing>\n                                    <property nam"
  "e=\"left_attach\">1</property>\n                                    <pr"
  "operty name=\"top_attach\">2</property>\n                              "
  "    </packing>\n                                </child>\n             "
  "                   <child>\n                                  <object c"
  "lass=\"GtkCheckButton\" id=\"primary\">\n                              "
  "      <property name=\"label\" translatable=\"yes\">Show icons on prima"
  "ry display</property>\n                                    <property na"
  "me=\"visible\">True</property>\n                                    <pr"
  "operty name=\"can_focus\">True</property>\n                            "
  "        <property name=\"receives_default\">False</property>\n         "
  "                           <property name=\"draw_indicator\">True</prop"
  "erty>\n                                  </object>\n                   "
  "               <packing>\n                                    <property"
  " name=\"left_attach\">0</property>\n                                   "
  " <property name=\"top_attach\">3</property>\n                          "
  "        </packing>\n                                </child>\n         "
  "                       <child>\n                                  <obje"
  "ct class=\"GtkCheckButton\" id=\"chk_custom_font_size\">\n             "
  "                       <property name=\"label\" translatable=\"yes\">Us"
  "e custom _font size:</property>\n                                    <p"
  "roperty name=\"visible\">True</property>\n                             "
  "       <property name=\"can_focus\">True</property>\n                  "
  "                  <property name=\"receives_default\">False</property>\n"
  "                                    <property name=\"events\">GDK_POINT"
  "ER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK |"
  " GDK_BUTTON_RELEASE_MASK</property>\n                                  "
  "  <property name=\"use_underline\">True</property>\n                   "
  "                 <property name=\"draw_indicator\">True</property>\n   "
  "                               </object>\n                             "
  "     <packing>\n                                    <property name=\"le"
  "ft_attach\">0</property>\n                                    <property"
  " name=\"top_attach\">4</property>\n                                  </"
  "packing>\n                                </child>\n                   "
  "             <child>\n                                  <object class=\""
  "GtkSpinButton\" id=\"spin_font_size\">\n                               "
  "     <property name=\"visible\">True</property>\n                      "
  "              <property name=\"sensitive\">False</property>\n          "
  "                          <property name=\"can_focus\">True</property>\n"
  "                                    <property name=\"events\">GDK_POINT"
  "ER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK |"
  " GDK_BUTTON_RELEASE_MASK</property>\n                                  "
  "  <property name=\"halign\">start</property>\n                         "
  "           <property name=\"text\" translatable=\"yes\">12</property>\n"
  "                                    <property name=\"adjustment\">adjus"
  "tment4</property>\n                                    <property name=\""
  "value\">12</property>\n                                  </object>\n   "
  "                               <packing>\n                             "
  "       <property name=\"left_attach\">1</property>\n                   "
  "                 <property name=\"top_attach\">4</property>\n          "
  "                        </packing>\n                                </c"
  "hild>\n                                <child>\n                       "
  "           <object class=\"GtkCheckButton\" id=\"chk_show_tooltips\">\n"
  "                                    <property name=\"label\" translatab"
  "le=\"yes\">Show icon tooltips. Size:</property>\n                      "
  "              <property name=\"visible\">True</property>\n             "
  "                       <property name=\"can_focus\">True</property>\n  "
  "                                  <property name=\"receives_default\">F"
  "alse</property>\n                                    <property name=\"e"
  "vents\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BU"
  "TTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                 "
  "                   <property name=\"use_underline\">True</property>\n  "
  "                                  <property name=\"active\">True</prope"
  "rty>\n                                    <property name=\"draw_indicat"
  "or\">True</property>\n                                  </object>\n    "
  "                              <packing>\n                              "
  "      <property name=\"left_attach\">0</property>\n                    "
  "                <property name=\"top_attach\">5</property>\n           "
  "                       </packing>\n                                </ch"
  "ild>\n                                <child>\n                        "
  "          <object class=\"GtkSpinButton\" id=\"spin_tooltip_size\">\n  "
  "                                  <property name=\"visible\">True</prop"
  "erty>\n                                    <property name=\"can_focus\""
  ">True</property>\n                                    <property name=\""
  "events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_B"
  "UTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                "
  "                    <property name=\"tooltip_text\" translatable=\"yes\""
  ">Size of the tooltip preview image.</property>\n                       "
  "             <property name=\"halign\">start</property>\n              "
  "                      <property name=\"text\" translatable=\"yes\">64</"
  "property>\n                                    <property name=\"adjustm"
  "ent\">adjustment_tooltip</property>\n                                  "
  "  <property name=\"value\">64</property>\n                             "
  "     </object>\n                                  <packing>\n          "
  "                          <property name=\"left_attach\">1</property>\n"
  "                                    <property name=\"top_attach\">5</pr"
  "operty>\n                                  </packing>\n                "
  "                </child>\n                                <child>\n    "
  "                              <object class=\"GtkCheckButton\" id=\"chk"
  "_show_thumbnails\">\n                                    <property name"
  "=\"label\" translatable=\"yes\">Show t_humbnails</property>\n          "
  "                          <property name=\"visible\">True</property>\n "
  "                                   <property name=\"can_focus\">True</p"
  "roperty>\n                                    <property name=\"receives"
  "_default\">False</property>\n                                    <prope"
  "rty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_M"
  "ASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n     "
  "                               <property name=\"tooltip_text\" translat"
  "able=\"yes\">Select this option to display preview-able files on the de"
  "sktop as automatically generated thumbnail icons.</property>\n         "
  "                           <property name=\"use_underline\">True</prope"
  "rty>\n                                    <property name=\"draw_indicat"
  "or\">True</property>\n                                  </object>\n    "
  "                              <packing>\n                              "
  "      <property name=\"left_attach\">0</property>\n                    "
  "                <property name=\"top_attach\">6</property>\n           "
  "                       </packing>\n                                </ch"
  "ild>\n                                <child>\n                        "
  "          <object class=\"GtkCheckButton\" id=\"chk_show_hidden_files\""
  ">\n                                    <property name=\"label\" transla"
  "table=\"yes\">Show hidden files on the desktop</property>\n            "
  "                        <property name=\"visible\">True</property>\n   "
  "                                 <property name=\"can_focus\">True</pro"
  "perty>\n                                    <property name=\"receives_d"
  "efault\">False</property>\n                                    <propert"
  "y name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MAS"
  "K | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n       "
  "                             <property name=\"use_underline\">True</pro"
  "perty>\n                                    <property name=\"draw_indic"
  "ator\">True</property>\n                                  </object>\n  "
  "                                <packing>\n                            "
  "        <property name=\"left_attach\">0</property>\n                  "
  "                  <property name=\"top_attach\">7</property>\n         "
  "                         </packing>\n                                </"
  "child>\n                                <child>\n                      "
  "            <object class=\"GtkCheckButton\" id=\"chk_single_click\">\n"
  "                                    <property name=\"label\" translatab"
  "le=\"yes\">Single _click to activate items</property>\n                "
  "                    <property name=\"visible\">True</property>\n       "
  "                             <property name=\"can_focus\">True</propert"
  "y>\n                                    <property name=\"receives_defau"
  "lt\">False</property>\n                                    <property na"
  "me=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | "
  "GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n           "
  "                         <property name=\"use_underline\">True</propert"
  "y>\n                                    <property name=\"draw_indicator"
  "\">True</property>\n                                  </object>\n      "
  "                            <packing>\n                                "
  "    <property name=\"left_attach\">0</property>\n                      "
  "              <property name=\"top_attach\">8</property>\n             "
  "                     </packing>\n                                </chil"
  "d>\n                                <child>\n                          "
  "        <placeholder/>\n                                </child>\n     "
  "                           <child>\n                                  <"
  "placeholder/>\n                                </child>\n              "
  "                  <child>\n                                  <placehold"
  "er/>\n                                </child>\n                       "
  "         <child>\n                                  <placeholder/>\n   "
  "                             </child>\n                              </"
  "object>\n                            </child>\n                        "
  "  </object>\n                        </child>\n                        "
  "<child type=\"label\">\n                          <object class=\"GtkLa"
  "bel\" id=\"label15\">\n                            <property name=\"vis"
  "ible\">True</property>\n                            <property name=\"ca"
  "n_focus\">False</property>\n                            <property name="
  "\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK"
  "_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n              "
  "              <property name=\"label\" translatable=\"yes\">&lt;b&gt;Ap"
  "pearance&lt;/b&gt;</property>\n                            <property na"
  "me=\"use_markup\">True</property>\n                          </object>\n"
  "                        </child>\n                      </object>\n    "
  "                  <packing>\n                        <property name=\"e"
  "xpand\">False</property>\n                        <property name=\"fill"
  "\">True</property>\n                        <property name=\"position\""
  ">0</property>\n                      </packing>\n                    </"
  "child>\n                    <child>\n                      <object clas"
  "s=\"GtkFrame\" id=\"frame7\">\n                        <property name=\""
  "visible\">True</property>\n                        <property name=\"can"
  "_focus\">False</property>\n                        <property name=\"eve"
  "nts\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTT"
  "ON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                   "
  "     <property name=\"label_xalign\">0</property>\n                    "
  "    <property name=\"shadow_type\">none</property>\n                   "
  "     <child>\n                          <object class=\"GtkAlignment\" "
  "id=\"alignment12\">\n                            <property name=\"visib"
  "le\">True</property>\n                            <property name=\"can_"
  "focus\">False</property>\n                            <property name=\""
  "events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_B"
  "UTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                "
  "            <property name=\"top_padding\">6</property>\n              "
  "              <property name=\"left_padding\">12</property>\n          "
  "                  <child>\n                              <object class="
  "\"GtkScrolledWindow\" id=\"scrolledwindow2\">\n                        "
  "        <property name=\"visible\">True</property>\n                   "
  "             <property name=\"can_focus\">True</property>\n            "
  "                    <property name=\"events\">GDK_POINTER_MOTION_MASK |"
  " GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELE"
  "ASE_MASK</property>\n                                <property name=\"s"
  "hadow_type\">etched-in</property>\n                                <chi"
  "ld>\n                                  <object class=\"GtkTreeView\" id"
  "=\"treeview_default_icons\">\n                                    <prop"
  "erty name=\"visible\">True</property>\n                                "
  "    <property name=\"can_focus\">True</property>\n                     "
  "               <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_"
  "POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_M"
  "ASK</property>\n                                    <property name=\"he"
  "aders_visible\">False</property>\n                                    <"
  "child internal-child=\"selection\">\n                                  "
  "    <object class=\"GtkTreeSelection\"/>\n                             "
  "       </child>\n                                  </object>\n         "
  "                       </child>\n                              </object"
  ">\n                            </child>\n                          </ob"
  "ject>\n                        </child>\n                        <child"
  " type=\"label\">\n                          <object class=\"GtkLabel\" "
  "id=\"label16\">\n                            <property name=\"visible\""
  ">True</property>\n                            <property name=\"can_focu"
  "s\">False</property>\n                            <property name=\"even"
  "ts\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTO"
  "N_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                    "
  "        <property name=\"label\" translatable=\"yes\">&lt;b&gt;Default "
  "Icons&lt;/b&gt;</property>\n                            <property name="
  "\"use_markup\">True</property>\n                          </object>\n  "
  "                      </child>\n                      </object>\n      "
  "                <packing>\n                        <property name=\"exp"
  "and\">True</property>\n                        <property name=\"fill\">"
  "True</property>\n                        <property name=\"position\">1<"
  "/property>\n                      </packing>\n                    </chi"
  "ld>\n                  </object>\n                  <packing>\n        "
  "            <property name=\"position\">2</property>\n                 "
  " </packing>\n                </child>\n                <child type=\"ta"
  "b\">\n                  <object class=\"GtkLabel\" id=\"label3\">\n    "
  "                <property name=\"visible\">True</property>\n           "
  "         <property name=\"can_focus\">False</property>\n               "
  "     <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MO"
  "TION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</prope"
  "rty>\n                    <property name=\"label\" translatable=\"yes\""
  ">_Icons</property>\n                    <property name=\"use_underline\""
  ">True</property>\n                  </object>\n                  <packi"
  "ng>\n                    <property name=\"position\">2</property>\n    "
  "                <property name=\"tab_fill\">False</property>\n         "
  "         </packing>\n                </child>\n              </object>\n"
  "            </child>\n          </object>\n          <packing>\n       "
  "     <property name=\"expand\">False</property>\n            <property "
  "name=\"fill\">True</property>\n            <property name=\"position\">"
  "1</property>\n          </packing>\n        </child>\n      </object>\n"
  "    </child>\n    <action-widgets>\n      <action-widget response=\"-11"
  "\">button2</action-widget>\n      <action-widget response=\"-3\">bnt_ex"
  "it</action-widget>\n    </action-widgets>\n  </object>\n</interface>\n"
};

static const unsigned xfdesktop_settings_ui_length = 73534u;

