/* automatically generated from xfdesktop-settings-appearance-frame-ui.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfdesktop_settings_appearance_frame_ui)
#endif
#ifdef __GNUC__
static const char xfdesktop_settings_appearance_frame_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfdesktop_settings_appearance_frame_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!-- Generated with glade 3"
  ".22.1 -->\n<interface>\n  <requires lib=\"gtk+\" version=\"3.20\"/>\n  "
  "<object class=\"GtkAdjustment\" id=\"adjustment3\">\n    <property name"
  "=\"lower\">1</property>\n    <property name=\"upper\">65535</property>\n"
  "    <property name=\"value\">10</property>\n    <property name=\"step_i"
  "ncrement\">1</property>\n    <property name=\"page_increment\">10</prop"
  "erty>\n  </object>\n  <object class=\"GtkListStore\" id=\"model2\">\n  "
  "  <columns>\n      <!-- column-name gchararray -->\n      <column type="
  "\"gchararray\"/>\n    </columns>\n    <data>\n      <row>\n        <col"
  " id=\"0\" translatable=\"yes\">Solid color</col>\n      </row>\n      <"
  "row>\n        <col id=\"0\" translatable=\"yes\">Horizontal gradient</c"
  "ol>\n      </row>\n      <row>\n        <col id=\"0\" translatable=\"ye"
  "s\">Vertical gradient</col>\n      </row>\n      <row>\n        <col id"
  "=\"0\" translatable=\"yes\">Transparent</col>\n      </row>\n    </data"
  ">\n  </object>\n  <object class=\"GtkAlignment\" id=\"alignment_setting"
  "s\">\n    <property name=\"visible\">True</property>\n    <property nam"
  "e=\"can_focus\">False</property>\n    <property name=\"events\">GDK_POI"
  "NTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK"
  " | GDK_BUTTON_RELEASE_MASK</property>\n    <property name=\"border_widt"
  "h\">12</property>\n    <child>\n      <object class=\"GtkBox\" id=\"bac"
  "kground_tab_vbox\">\n        <property name=\"visible\">True</property>"
  "\n        <property name=\"can_focus\">False</property>\n        <prope"
  "rty name=\"orientation\">vertical</property>\n        <property name=\""
  "spacing\">6</property>\n        <child>\n          <object class=\"GtkI"
  "nfoBar\" id=\"infobar_header\">\n            <property name=\"visible\""
  ">True</property>\n            <property name=\"can_focus\">False</prope"
  "rty>\n            <property name=\"events\">GDK_POINTER_MOTION_MASK | G"
  "DK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEAS"
  "E_MASK</property>\n            <child internal-child=\"action_area\">\n"
  "              <object class=\"GtkButtonBox\">\n                <propert"
  "y name=\"can_focus\">False</property>\n              </object>\n       "
  "       <packing>\n                <property name=\"expand\">False</prop"
  "erty>\n                <property name=\"fill\">False</property>\n      "
  "          <property name=\"position\">0</property>\n              </pac"
  "king>\n            </child>\n            <child internal-child=\"conten"
  "t_area\">\n              <object class=\"GtkBox\">\n                <pr"
  "operty name=\"can_focus\">False</property>\n              </object>\n  "
  "            <packing>\n                <property name=\"expand\">False<"
  "/property>\n                <property name=\"fill\">False</property>\n "
  "               <property name=\"position\">0</property>\n              "
  "</packing>\n            </child>\n          </object>\n          <packi"
  "ng>\n            <property name=\"expand\">False</property>\n          "
  "  <property name=\"fill\">True</property>\n            <property name=\""
  "position\">0</property>\n          </packing>\n        </child>\n      "
  "  <child>\n          <object class=\"GtkBox\" id=\"background_tab_hbox\""
  ">\n            <property name=\"visible\">True</property>\n            "
  "<property name=\"can_focus\">False</property>\n            <child>\n   "
  "           <object class=\"GtkLabel\" id=\"label_header\">\n           "
  "     <property name=\"visible\">True</property>\n                <prope"
  "rty name=\"can_focus\">False</property>\n                <property name"
  "=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GD"
  "K_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n             "
  " </object>\n              <packing>\n                <property name=\"e"
  "xpand\">False</property>\n                <property name=\"fill\">True<"
  "/property>\n                <property name=\"position\">1</property>\n "
  "             </packing>\n            </child>\n          </object>\n   "
  "       <packing>\n            <property name=\"expand\">False</property"
  ">\n            <property name=\"fill\">True</property>\n            <pr"
  "operty name=\"position\">1</property>\n          </packing>\n        </"
  "child>\n        <child>\n          <object class=\"GtkScrolledWindow\" "
  "id=\"iconview_imagelist_scrolled_window\">\n            <property name="
  "\"visible\">True</property>\n            <property name=\"can_focus\">T"
  "rue</property>\n            <property name=\"events\">GDK_POINTER_MOTIO"
  "N_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUT"
  "TON_RELEASE_MASK</property>\n            <property name=\"shadow_type\""
  ">etched-in</property>\n            <child>\n              <object class"
  "=\"GtkIconView\" id=\"iconview_imagelist\">\n                <property "
  "name=\"visible\">True</property>\n                <property name=\"can_"
  "focus\">True</property>\n                <property name=\"events\">GDK_"
  "POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_M"
  "ASK | GDK_BUTTON_RELEASE_MASK</property>\n                <property nam"
  "e=\"margin\">0</property>\n              </object>\n            </child"
  ">\n          </object>\n          <packing>\n            <property name"
  "=\"expand\">True</property>\n            <property name=\"fill\">True</"
  "property>\n            <property name=\"position\">2</property>\n      "
  "    </packing>\n        </child>\n        <child>\n          <object cl"
  "ass=\"GtkGrid\" id=\"folder_color_and_image_style_table\">\n           "
  " <property name=\"visible\">True</property>\n            <property name"
  "=\"can_focus\">False</property>\n            <property name=\"row_spaci"
  "ng\">6</property>\n            <property name=\"column_spacing\">12</pr"
  "operty>\n            <child>\n              <object class=\"GtkFileChoo"
  "serButton\" id=\"btn_folder\">\n                <property name=\"visibl"
  "e\">True</property>\n                <property name=\"can_focus\">True<"
  "/property>\n                <property name=\"events\">GDK_POINTER_MOTIO"
  "N_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUT"
  "TON_RELEASE_MASK</property>\n                <property name=\"tooltip_t"
  "ext\" translatable=\"yes\">Choose the folder to select wallpapers from."
  "</property>\n                <property name=\"hexpand\">True</property>"
  "\n                <property name=\"action\">select-folder</property>\n "
  "             </object>\n              <packing>\n                <prope"
  "rty name=\"left_attach\">1</property>\n                <property name=\""
  "top_attach\">0</property>\n              </packing>\n            </chil"
  "d>\n            <child>\n              <object class=\"GtkButton\" id=\""
  "btn_folder_apply\">\n                <property name=\"label\" translata"
  "ble=\"yes\">Apply</property>\n                <property name=\"visible\""
  ">False</property>\n                <property name=\"can-focus\">True</p"
  "roperty>\n                <property name=\"receives-default\">True</pro"
  "perty>\n              </object>\n              <packing>\n             "
  "   <property name=\"left-attach\">2</property>\n                <proper"
  "ty name=\"top-attach\">0</property>\n                <property name=\"w"
  "idth\">2</property>\n              </packing>\n            </child>\n  "
  "          <child>\n              <object class=\"GtkAlignment\" id=\"al"
  "ignment_spacer\">\n                <property name=\"visible\">True</pro"
  "perty>\n                <property name=\"can_focus\">False</property>\n"
  "                <property name=\"hexpand\">True</property>\n           "
  "   </object>\n              <packing>\n                <property name=\""
  "left_attach\">4</property>\n                <property name=\"top_attach"
  "\">0</property>\n              </packing>\n            </child>\n      "
  "      <child>\n              <object class=\"GtkLabel\" id=\"label_styl"
  "e\">\n                <property name=\"visible\">True</property>\n     "
  "           <property name=\"can_focus\">False</property>\n             "
  "   <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTI"
  "ON_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</propert"
  "y>\n                <property name=\"label\" translatable=\"yes\">St_yl"
  "e:</property>\n                <property name=\"use_underline\">True</p"
  "roperty>\n                <property name=\"mnemonic_widget\">combo_styl"
  "e</property>\n                <property name=\"xalign\">0</property>\n "
  "             </object>\n              <packing>\n                <prope"
  "rty name=\"left_attach\">5</property>\n                <property name=\""
  "top_attach\">0</property>\n              </packing>\n            </chil"
  "d>\n            <child>\n              <object class=\"GtkComboBoxText\""
  " id=\"combo_style\">\n                <property name=\"visible\">True</"
  "property>\n                <property name=\"can_focus\">False</property"
  ">\n                <property name=\"events\">GDK_POINTER_MOTION_MASK | "
  "GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEA"
  "SE_MASK</property>\n                <property name=\"tooltip_text\" tra"
  "nslatable=\"yes\">Specify how the image will be resized to fit the scre"
  "en.</property>\n                <items>\n                  <item transl"
  "atable=\"yes\">None</item>\n                  <item translatable=\"yes\""
  ">Centered</item>\n                  <item translatable=\"yes\">Tiled</i"
  "tem>\n                  <item translatable=\"yes\">Stretched</item>\n  "
  "                <item translatable=\"yes\">Scaled</item>\n             "
  "     <item translatable=\"yes\">Zoomed</item>\n                  <item "
  "translatable=\"yes\">Spanning Screens</item>\n                </items>\n"
  "              </object>\n              <packing>\n                <prop"
  "erty name=\"left_attach\">6</property>\n                <property name="
  "\"top_attach\">0</property>\n              </packing>\n            </ch"
  "ild>\n            <child>\n              <object class=\"GtkComboBox\" "
  "id=\"combo_colors\">\n                <property name=\"visible\">True</"
  "property>\n                <property name=\"can_focus\">False</property"
  ">\n                <property name=\"events\">GDK_POINTER_MOTION_MASK | "
  "GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEA"
  "SE_MASK</property>\n                <property name=\"tooltip_text\" tra"
  "nslatable=\"yes\">Specify the style of the color drawn behind the backd"
  "rop image.</property>\n                <property name=\"valign\">center"
  "</property>\n                <property name=\"hexpand\">True</property>"
  "\n                <property name=\"model\">model2</property>\n         "
  "       <child>\n                  <object class=\"GtkCellRendererText\""
  " id=\"renderer2\"/>\n                  <attributes>\n                  "
  "  <attribute name=\"text\">0</attribute>\n                  </attribute"
  "s>\n                </child>\n              </object>\n              <p"
  "acking>\n                <property name=\"left_attach\">1</property>\n "
  "               <property name=\"top_attach\">1</property>\n            "
  "  </packing>\n            </child>\n            <child>\n              "
  "<object class=\"GtkColorButton\" id=\"color1_btn\">\n                <p"
  "roperty name=\"visible\">True</property>\n                <property nam"
  "e=\"can_focus\">True</property>\n                <property name=\"recei"
  "ves_default\">True</property>\n                <property name=\"events\""
  ">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_MO"
  "TION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n"
  "                <property name=\"tooltip_text\" translatable=\"yes\">Sp"
  "ecifies the solid color, or the \"left\" or \"top\" color of the gradie"
  "nt.</property>\n                <property name=\"title\" translatable=\""
  "yes\">Select First Color</property>\n              </object>\n         "
  "     <packing>\n                <property name=\"left_attach\">2</prope"
  "rty>\n                <property name=\"top_attach\">1</property>\n     "
  "         </packing>\n            </child>\n            <child>\n       "
  "       <object class=\"GtkColorButton\" id=\"color2_btn\">\n           "
  "     <property name=\"visible\">True</property>\n                <prope"
  "rty name=\"can_focus\">True</property>\n                <property name="
  "\"receives_default\">True</property>\n                <property name=\""
  "events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_B"
  "UTTON_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</pr"
  "operty>\n                <property name=\"tooltip_text\" translatable=\""
  "yes\">Specifies the \"right\" or \"bottom\" color of the gradient.</pro"
  "perty>\n                <property name=\"title\" translatable=\"yes\">S"
  "elect Second Color</property>\n              </object>\n              <"
  "packing>\n                <property name=\"left_attach\">3</property>\n"
  "                <property name=\"top_attach\">1</property>\n           "
  "   </packing>\n            </child>\n            <child>\n             "
  " <object class=\"GtkCheckButton\" id=\"chk_apply_to_all\">\n           "
  "     <property name=\"label\" translatable=\"yes\">Apply to all _worksp"
  "aces</property>\n                <property name=\"visible\">True</prope"
  "rty>\n                <property name=\"can_focus\">True</property>\n   "
  "             <property name=\"receives_default\">False</property>\n    "
  "            <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POI"
  "NTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK"
  "</property>\n                <property name=\"use_underline\">True</pro"
  "perty>\n                <property name=\"draw_indicator\">True</propert"
  "y>\n              </object>\n              <packing>\n                <"
  "property name=\"left_attach\">6</property>\n                <property n"
  "ame=\"top_attach\">1</property>\n              </packing>\n            "
  "</child>\n            <child>\n              <object class=\"GtkLabel\""
  " id=\"label_folder\">\n                <property name=\"visible\">True<"
  "/property>\n                <property name=\"can_focus\">False</propert"
  "y>\n                <property name=\"events\">GDK_POINTER_MOTION_MASK |"
  " GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELE"
  "ASE_MASK</property>\n                <property name=\"label\" translata"
  "ble=\"yes\">_Folder:</property>\n                <property name=\"use_u"
  "nderline\">True</property>\n                <property name=\"mnemonic_w"
  "idget\">btn_folder</property>\n                <property name=\"xalign\""
  ">0</property>\n              </object>\n              <packing>\n      "
  "          <property name=\"left_attach\">0</property>\n                "
  "<property name=\"top_attach\">0</property>\n              </packing>\n "
  "           </child>\n            <child>\n              <object class=\""
  "GtkLabel\" id=\"label_color\">\n                <property name=\"visibl"
  "e\">True</property>\n                <property name=\"can_focus\">False"
  "</property>\n                <property name=\"events\">GDK_POINTER_MOTI"
  "ON_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BU"
  "TTON_RELEASE_MASK</property>\n                <property name=\"label\" "
  "translatable=\"yes\">C_olor:</property>\n                <property name"
  "=\"use_underline\">True</property>\n                <property name=\"mn"
  "emonic_widget\">combo_colors</property>\n                <property name"
  "=\"xalign\">0</property>\n              </object>\n              <packi"
  "ng>\n                <property name=\"left_attach\">0</property>\n     "
  "           <property name=\"top_attach\">1</property>\n              </"
  "packing>\n            </child>\n            <child>\n              <pla"
  "ceholder/>\n            </child>\n            <child>\n              <p"
  "laceholder/>\n            </child>\n            <child>\n              "
  "<placeholder/>\n            </child>\n            <child>\n            "
  "  <placeholder/>\n            </child>\n          </object>\n          "
  "<packing>\n            <property name=\"expand\">False</property>\n    "
  "        <property name=\"fill\">True</property>\n            <property "
  "name=\"position\">3</property>\n          </packing>\n        </child>\n"
  "        <child>\n          <object class=\"GtkBox\" id=\"cycle_options_"
  "hbox\">\n            <property name=\"visible\">True</property>\n      "
  "      <property name=\"can_focus\">False</property>\n            <prope"
  "rty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_M"
  "ASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n     "
  "       <property name=\"spacing\">12</property>\n            <child>\n "
  "             <object class=\"GtkCheckButton\" id=\"chk_cycle_backdrop\""
  ">\n                <property name=\"label\" translatable=\"yes\">Change"
  " the _background </property>\n                <property name=\"visible\""
  ">True</property>\n                <property name=\"can_focus\">True</pr"
  "operty>\n                <property name=\"receives_default\">False</pro"
  "perty>\n                <property name=\"events\">GDK_POINTER_MOTION_MA"
  "SK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_"
  "RELEASE_MASK</property>\n                <property name=\"tooltip_text\""
  " translatable=\"yes\">Automatically select a different background from "
  "the current directory.</property>\n                <property name=\"use"
  "_underline\">True</property>\n                <property name=\"draw_ind"
  "icator\">True</property>\n              </object>\n              <packi"
  "ng>\n                <property name=\"expand\">False</property>\n      "
  "          <property name=\"fill\">True</property>\n                <pro"
  "perty name=\"position\">0</property>\n              </packing>\n       "
  "     </child>\n            <child>\n              <object class=\"GtkCo"
  "mboBoxText\" id=\"combo_cycle_backdrop_period\">\n                <prop"
  "erty name=\"visible\">True</property>\n                <property name=\""
  "sensitive\">False</property>\n                <property name=\"can_focu"
  "s\">False</property>\n                <property name=\"events\">GDK_POI"
  "NTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK"
  " | GDK_BUTTON_RELEASE_MASK</property>\n                <property name=\""
  "tooltip_text\" translatable=\"yes\">Specify how often the background wi"
  "ll change.</property>\n                <items>\n                  <item"
  " translatable=\"yes\">in seconds:</item>\n                  <item trans"
  "latable=\"yes\">in minutes:</item>\n                  <item translatabl"
  "e=\"yes\">in hours:</item>\n                  <item translatable=\"yes\""
  ">at start up</item>\n                  <item translatable=\"yes\">every"
  " hour</item>\n                  <item translatable=\"yes\">every day</i"
  "tem>\n                  <item translatable=\"yes\">chronologically</ite"
  "m>\n                </items>\n              </object>\n              <p"
  "acking>\n                <property name=\"expand\">False</property>\n  "
  "              <property name=\"fill\">True</property>\n                "
  "<property name=\"position\">1</property>\n              </packing>\n   "
  "         </child>\n            <child>\n              <object class=\"G"
  "tkSpinButton\" id=\"spin_backdrop_time\">\n                <property na"
  "me=\"visible\">True</property>\n                <property name=\"sensit"
  "ive\">False</property>\n                <property name=\"can_focus\">Tr"
  "ue</property>\n                <property name=\"events\">GDK_POINTER_MO"
  "TION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_"
  "BUTTON_RELEASE_MASK</property>\n                <property name=\"toolti"
  "p_text\" translatable=\"yes\">Amount of time before a different backgro"
  "und is selected.</property>\n                <property name=\"adjustmen"
  "t\">adjustment3</property>\n              </object>\n              <pac"
  "king>\n                <property name=\"expand\">False</property>\n    "
  "            <property name=\"fill\">True</property>\n                <p"
  "roperty name=\"position\">2</property>\n              </packing>\n     "
  "       </child>\n            <child>\n              <object class=\"Gtk"
  "CheckButton\" id=\"chk_random_backdrop_order\">\n                <prope"
  "rty name=\"label\" translatable=\"yes\">_Random Order</property>\n     "
  "           <property name=\"visible\">True</property>\n                "
  "<property name=\"sensitive\">False</property>\n                <propert"
  "y name=\"can_focus\">True</property>\n                <property name=\""
  "receives_default\">False</property>\n                <property name=\"e"
  "vents\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BU"
  "TTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                <"
  "property name=\"tooltip_text\" translatable=\"yes\">Randomly selects an"
  "other image from the same directory when the wallpaper is to cycle.</pr"
  "operty>\n                <property name=\"use_underline\">True</propert"
  "y>\n                <property name=\"draw_indicator\">True</property>\n"
  "              </object>\n              <packing>\n                <prop"
  "erty name=\"expand\">False</property>\n                <property name=\""
  "fill\">True</property>\n                <property name=\"position\">3</"
  "property>\n              </packing>\n            </child>\n          </"
  "object>\n          <packing>\n            <property name=\"expand\">Fal"
  "se</property>\n            <property name=\"fill\">True</property>\n   "
  "         <property name=\"position\">5</property>\n          </packing>"
  "\n        </child>\n      </object>\n    </child>\n  </object>\n</inter"
  "face>\n"
};

static const unsigned xfdesktop_settings_appearance_frame_ui_length = 20192u;

