[package]
name = "redoxfs"
description = "The Redox Filesystem"
repository = "https://gitlab.redox-os.org/redox-os/redoxfs"
version = "0.6.3"
license-file = "LICENSE"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
edition = "2021"

[lib]
name = "redoxfs"
path = "src/lib.rs"

[[bin]]
name = "redoxfs"
path = "src/bin/mount.rs"
doc = false
required-features = ["std"]

[[bin]]
name = "redoxfs-ar"
path = "src/bin/ar.rs"
doc = false
required-features = ["std"]

[[bin]]
name = "redoxfs-mkfs"
path = "src/bin/mkfs.rs"
doc = false
required-features = ["std"]

[dependencies]
aes = { version = "=0.7.5", default-features = false }
argon2 = { version = "0.3.4", default-features = false, features = ["alloc"] }
base64ct = { version = "1", default-features = false }
env_logger = { version = "0.9", optional = true }
getrandom = { version = "0.2.5", optional = true }
libc = "0.2"
log = { version = "0.4.14", default-features = false, optional = true}
redox_syscall = "0.5"
range-tree = { version = "0.1", optional = true }
seahash = { version = "4.1.0", default-features = false }
termion = { version = "2", optional = true }
uuid = { version = "1.4", default-features = false }
redox-path = "0.3.0"
libredox = { version = "0.1.3", optional = true }

# https://github.com/rexlunae/simple-endian-rs/pull/5
[dependencies.redox_simple_endian]
version = "0.3.0"
default-features = false
features = [
    "bitwise", "comparisons", "format", "math_ops", "neg_ops", "shift_ops",
    "both_endian", "float_impls", "integer_impls", "byte_impls"
]

[features]
default = ["std", "log"]
force-soft = [
    "aes/force-soft"
]
std = [
    "env_logger",
    "fuser",
    "getrandom",
    "libc",
    "libredox",
    "range-tree",
    "termion",
    "time",
    "uuid/v4"
]

[target.'cfg(not(target_os = "redox"))'.dependencies]
fuser = { version = "0.12.0", optional = true }
libc = { version = "0.2", optional = true }
time = { version = "0.1", optional = true }
