#TODO probably wrong script, see https://github.com/skyjake/lagrange#how-to-compile
#TODO mpg123 dependency broken
[source]
tar = "https://git.skyjake.fi/gemini/lagrange/releases/download/v1.17.4/lagrange-1.17.4.tar.gz"
[build]
template = "custom"
dependencies = [
    "sdl2",
    "openssl1",
    "zlib",
    "harfbuzz",
    "pcre",
    "fribidi",
    "libunistring",
]
script = """
    COOKBOOK_CONFIGURE="cmake"
    COOKBOOK_CONFIGURE_FLAGS=(
	-DCMAKE_BUILD_TYPE=Release
	-DCMAKE_CROSSCOMPILING=True
	-DCMAKE_EXE_LINKER_FLAGS="-static"
	-DCMAKE_INSTALL_PREFIX="/"
    -DCMAKE_PREFIX_PATH="${COOKBOOK_SYSROOT}"
    -DCMAKE_SYSTEM_NAME=Generic
    -DCMAKE_SYSTEM_PROCESSOR="$(echo "${TARGET}" | cut -d - -f1)"
    -DCMAKE_VERBOSE_MAKEFILE=On
    -DENABLE_MPG123=OFF
"${COOKBOOK_SOURCE}"
)
cookbook_configure
"""
