#TODO make dependencies work
[source]
tar = "https://ftp.gnu.org/gnu/guile/guile-3.0.9.tar.xz"
[build]
template = "configure"
dependencies = [
    "libgmp",
    "libiconv",
    "libunistring",
    "libgc",
    "readline",
    "libffi",
    "libintl",
]
