/* automatically generated from xfce4-about-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfce_about_dialog_ui)
#endif
#ifdef __GNUC__
static const char xfce_about_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfce_about_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.0\"/><requires lib=\"libxfce4ui\" version=\"4.5\"/><re"
  "quires lib=\"libxfce4ui-2\" version=\"4.12\"/><object class=\"GtkTextBu"
  "ffer\" id=\"about-buffer\"/><object class=\"GtkTextBuffer\" id=\"bsd-bu"
  "ffer\"><property name=\"text\">Redistribution and use in source and bin"
  "ary forms, with or without modification, are permitted provided that th"
  "e following conditions are met:\n\n1. Redistributions of source code mu"
  "st retain the above copyright notice, this list of conditions and the f"
  "ollowing disclaimer.\n\n2. Redistributions in binary form must reproduc"
  "e the above copyright notice, this list of conditions and the following"
  " disclaimer in the documentation and/or other materials provided with t"
  "he distribution.\n\n3. Neither the name of the organization nor the nam"
  "es of its contributors may be used to endorse or promote products deriv"
  "ed from this software without specific prior written permission.\n\nTHI"
  "S SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS I"
  "S\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED T"
  "O, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICUL"
  "AR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CO"
  "NTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXE"
  "MPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUR"
  "EMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; O"
  "R BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,"
  " WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE O"
  "R OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN I"
  "F ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.</property></object><object"
  " class=\"GtkTextBuffer\" id=\"copyright-buffer\"/><object class=\"GtkTe"
  "xtBuffer\" id=\"credits-buffer\"/><object class=\"GtkTextBuffer\" id=\""
  "gpl-buffer\"><property name=\"text\">GNU GENERAL PUBLIC LICENSE\n\nVers"
  "ion 2, June 1991\n\nCopyright (C) 1989, 1991 Free Software Foundation, "
  "Inc.\n51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA\n\nE"
  "veryone is permitted to copy and distribute verbatim copies of this lic"
  "ense document, but changing it is not allowed.\n\nPreamble\n\nThe licen"
  "ses for most software are designed to take away your freedom to share a"
  "nd change it. By contrast, the GNU General Public License is intended t"
  "o guarantee your freedom to share and change free software--to make sur"
  "e the software is free for all its users. This General Public License a"
  "pplies to most of the Free Software Foundation\'s software and to any o"
  "ther program whose authors commit to using it. (Some other Free Softwar"
  "e Foundation software is covered by the GNU Lesser General Public Licen"
  "se instead.) You can apply it to your programs, too.\n\nWhen we speak o"
  "f free software, we are referring to freedom, not price. Our General Pu"
  "blic Licenses are designed to make sure that you have the freedom to di"
  "stribute copies of free software (and charge for this service if you wi"
  "sh), that you receive source code or can get it if you want it, that yo"
  "u can change the software or use pieces of it in new free programs; and"
  " that you know you can do these things.\n\nTo protect your rights, we n"
  "eed to make restrictions that forbid anyone to deny you these rights or"
  " to ask you to surrender the rights. These restrictions translate to ce"
  "rtain responsibilities for you if you distribute copies of the software"
  ", or if you modify it.\n\nFor example, if you distribute copies of such"
  " a program, whether gratis or for a fee, you must give the recipients a"
  "ll the rights that you have. You must make sure that they, too, receive"
  " or can get the source code. And you must show them these terms so they"
  " know their rights.\n\nWe protect your rights with two steps: (1) copyr"
  "ight the software, and (2) offer you this license which gives you legal"
  " permission to copy, distribute and/or modify the software.\n\nAlso, fo"
  "r each author\'s protection and ours, we want to make certain that ever"
  "yone understands that there is no warranty for this free software. If t"
  "he software is modified by someone else and passed on, we want its reci"
  "pients to know that what they have is not the original, so that any pro"
  "blems introduced by others will not reflect on the original authors\' r"
  "eputations.\n\nFinally, any free program is threatened constantly by so"
  "ftware patents. We wish to avoid the danger that redistributors of a fr"
  "ee program will individually obtain patent licenses, in effect making t"
  "he program proprietary. To prevent this, we have made it clear that any"
  " patent must be licensed for everyone\'s free use or not licensed at al"
  "l.\n\nThe precise terms and conditions for copying, distribution and mo"
  "dification follow.\nTERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND "
  "MODIFICATION\n\n0. This License applies to any program or other work wh"
  "ich contains a notice placed by the copyright holder saying it may be d"
  "istributed under the terms of this General Public License. The \"Progra"
  "m\", below, refers to any such program or work, and a \"work based on t"
  "he Program\" means either the Program or any derivative work under copy"
  "right law: that is to say, a work containing the Program or a portion o"
  "f it, either verbatim or with modifications and/or translated into anot"
  "her language. (Hereinafter, translation is included without limitation "
  "in the term \"modification\".) Each licensee is addressed as \"you\".\n"
  "\nActivities other than copying, distribution and modification are not "
  "covered by this License; they are outside its scope. The act of running"
  " the Program is not restricted, and the output from the Program is cove"
  "red only if its contents constitute a work based on the Program (indepe"
  "ndent of having been made by running the Program). Whether that is true"
  " depends on what the Program does.\n\n1. You may copy and distribute ve"
  "rbatim copies of the Program\'s source code as you receive it, in any m"
  "edium, provided that you conspicuously and appropriately publish on eac"
  "h copy an appropriate copyright notice and disclaimer of warranty; keep"
  " intact all the notices that refer to this License and to the absence o"
  "f any warranty; and give any other recipients of the Program a copy of "
  "this License along with the Program.\n\nYou may charge a fee for the ph"
  "ysical act of transferring a copy, and you may at your option offer war"
  "ranty protection in exchange for a fee.\n\n2. You may modify your copy "
  "or copies of the Program or any portion of it, thus forming a work base"
  "d on the Program, and copy and distribute such modifications or work un"
  "der the terms of Section 1 above, provided that you also meet all of th"
  "ese conditions:\n\n    a) You must cause the modified files to carry pr"
  "ominent notices stating that you changed the files and the date of any "
  "change.\n    b) You must cause any work that you distribute or publish,"
  " that in whole or in part contains or is derived from the Program or an"
  "y part thereof, to be licensed as a whole at no charge to all third par"
  "ties under the terms of this License.\n    c) If the modified program n"
  "ormally reads commands interactively when run, you must cause it, when "
  "started running for such interactive use in the most ordinary way, to p"
  "rint or display an announcement including an appropriate copyright noti"
  "ce and a notice that there is no warranty (or else, saying that you pro"
  "vide a warranty) and that users may redistribute the program under thes"
  "e conditions, and telling the user how to view a copy of this License. "
  "(Exception: if the Program itself is interactive but does not normally "
  "print such an announcement, your work based on the Program is not requi"
  "red to print an announcement.)\n\nThese requirements apply to the modif"
  "ied work as a whole. If identifiable sections of that work are not deri"
  "ved from the Program, and can be reasonably considered independent and "
  "separate works in themselves, then this License, and its terms, do not "
  "apply to those sections when you distribute them as separate works. But"
  " when you distribute the same sections as part of a whole which is a wo"
  "rk based on the Program, the distribution of the whole must be on the t"
  "erms of this License, whose permissions for other licensees extend to t"
  "he entire whole, and thus to each and every part regardless of who wrot"
  "e it.\n\nThus, it is not the intent of this section to claim rights or "
  "contest your rights to work written entirely by you; rather, the intent"
  " is to exercise the right to control the distribution of derivative or "
  "collective works based on the Program.\n\nIn addition, mere aggregation"
  " of another work not based on the Program with the Program (or with a w"
  "ork based on the Program) on a volume of a storage or distribution medi"
  "um does not bring the other work under the scope of this License.\n\n3."
  " You may copy and distribute the Program (or a work based on it, under "
  "Section 2) in object code or executable form under the terms of Section"
  "s 1 and 2 above provided that you also do one of the following:\n\n    "
  "a) Accompany it with the complete corresponding machine-readable source"
  " code, which must be distributed under the terms of Sections 1 and 2 ab"
  "ove on a medium customarily used for software interchange; or,\n    b) "
  "Accompany it with a written offer, valid for at least three years, to g"
  "ive any third party, for a charge no more than your cost of physically "
  "performing source distribution, a complete machine-readable copy of the"
  " corresponding source code, to be distributed under the terms of Sectio"
  "ns 1 and 2 above on a medium customarily used for software interchange;"
  " or,\n    c) Accompany it with the information you received as to the o"
  "ffer to distribute corresponding source code. (This alternative is allo"
  "wed only for noncommercial distribution and only if you received the pr"
  "ogram in object code or executable form with such an offer, in accord w"
  "ith Subsection b above.)\n\nThe source code for a work means the prefer"
  "red form of the work for making modifications to it. For an executable "
  "work, complete source code means all the source code for all modules it"
  " contains, plus any associated interface definition files, plus the scr"
  "ipts used to control compilation and installation of the executable. Ho"
  "wever, as a special exception, the source code distributed need not inc"
  "lude anything that is normally distributed (in either source or binary "
  "form) with the major components (compiler, kernel, and so on) of the op"
  "erating system on which the executable runs, unless that component itse"
  "lf accompanies the executable.\n\nIf distribution of executable or obje"
  "ct code is made by offering access to copy from a designated place, the"
  "n offering equivalent access to copy the source code from the same plac"
  "e counts as distribution of the source code, even though third parties "
  "are not compelled to copy the source along with the object code.\n\n4. "
  "You may not copy, modify, sublicense, or distribute the Program except "
  "as expressly provided under this License. Any attempt otherwise to copy"
  ", modify, sublicense or distribute the Program is void, and will automa"
  "tically terminate your rights under this License. However, parties who "
  "have received copies, or rights, from you under this License will not h"
  "ave their licenses terminated so long as such parties remain in full co"
  "mpliance.\n\n5. You are not required to accept this License, since you "
  "have not signed it. However, nothing else grants you permission to modi"
  "fy or distribute the Program or its derivative works. These actions are"
  " prohibited by law if you do not accept this License. Therefore, by mod"
  "ifying or distributing the Program (or any work based on the Program), "
  "you indicate your acceptance of this License to do so, and all its term"
  "s and conditions for copying, distributing or modifying the Program or "
  "works based on it.\n\n6. Each time you redistribute the Program (or any"
  " work based on the Program), the recipient automatically receives a lic"
  "ense from the original licensor to copy, distribute or modify the Progr"
  "am subject to these terms and conditions. You may not impose any furthe"
  "r restrictions on the recipients\' exercise of the rights granted herei"
  "n. You are not responsible for enforcing compliance by third parties to"
  " this License.\n\n7. If, as a consequence of a court judgment or allega"
  "tion of patent infringement or for any other reason (not limited to pat"
  "ent issues), conditions are imposed on you (whether by court order, agr"
  "eement or otherwise) that contradict the conditions of this License, th"
  "ey do not excuse you from the conditions of this License. If you cannot"
  " distribute so as to satisfy simultaneously your obligations under this"
  " License and any other pertinent obligations, then as a consequence you"
  " may not distribute the Program at all. For example, if a patent licens"
  "e would not permit royalty-free redistribution of the Program by all th"
  "ose who receive copies directly or indirectly through you, then the onl"
  "y way you could satisfy both it and this License would be to refrain en"
  "tirely from distribution of the Program.\n\nIf any portion of this sect"
  "ion is held invalid or unenforceable under any particular circumstance,"
  " the balance of the section is intended to apply and the section as a w"
  "hole is intended to apply in other circumstances.\n\nIt is not the purp"
  "ose of this section to induce you to infringe any patents or other prop"
  "erty right claims or to contest validity of any such claims; this secti"
  "on has the sole purpose of protecting the integrity of the free softwar"
  "e distribution system, which is implemented by public license practices"
  ". Many people have made generous contributions to the wide range of sof"
  "tware distributed through that system in reliance on consistent applica"
  "tion of that system; it is up to the author/donor to decide if he or sh"
  "e is willing to distribute software through any other system and a lice"
  "nsee cannot impose that choice.\n\nThis section is intended to make tho"
  "roughly clear what is believed to be a consequence of the rest of this "
  "License.\n\n8. If the distribution and/or use of the Program is restric"
  "ted in certain countries either by patents or by copyrighted interfaces"
  ", the original copyright holder who places the Program under this Licen"
  "se may add an explicit geographical distribution limitation excluding t"
  "hose countries, so that distribution is permitted only in or among coun"
  "tries not thus excluded. In such case, this License incorporates the li"
  "mitation as if written in the body of this License.\n\n9. The Free Soft"
  "ware Foundation may publish revised and/or new versions of the General "
  "Public License from time to time. Such new versions will be similar in "
  "spirit to the present version, but may differ in detail to address new "
  "problems or concerns.\n\nEach version is given a distinguishing version"
  " number. If the Program specifies a version number of this License whic"
  "h applies to it and \"any later version\", you have the option of follo"
  "wing the terms and conditions either of that version or of any later ve"
  "rsion published by the Free Software Foundation. If the Program does no"
  "t specify a version number of this License, you may choose any version "
  "ever published by the Free Software Foundation.\n\n10. If you wish to i"
  "ncorporate parts of the Program into other free programs whose distribu"
  "tion conditions are different, write to the author to ask for permissio"
  "n. For software which is copyrighted by the Free Software Foundation, w"
  "rite to the Free Software Foundation; we sometimes make exceptions for "
  "this. Our decision will be guided by the two goals of preserving the fr"
  "ee status of all derivatives of our free software and of promoting the "
  "sharing and reuse of software generally.\n\nNO WARRANTY\n\n11. BECAUSE "
  "THE PROGRAM IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY FOR THE PR"
  "OGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN OTHERWISE"
  " STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE T"
  "HE PROGRAM \"AS IS\" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR "
  "IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCH"
  "ANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO "
  "THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROG"
  "RAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, RE"
  "PAIR OR CORRECTION.\n\n12. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LA"
  "W OR AGREED TO IN WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY"
  " WHO MAY MODIFY AND/OR REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE "
  "LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL O"
  "R CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE "
  "PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDER"
  "ED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE "
  "OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER"
  " OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. </"
  "property></object><object class=\"GtkImage\" id=\"image1\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"icon_name\">window-close-symbolic</property></obje"
  "ct><object class=\"GtkDialog\" id=\"license-dialog\"><property name=\"c"
  "an_focus\">False</property><property name=\"border_width\">5</property>"
  "<property name=\"title\" translatable=\"yes\">License</property><proper"
  "ty name=\"modal\">True</property><property name=\"default_width\">500</"
  "property><property name=\"default_height\">300</property><property name"
  "=\"type_hint\">normal</property><child><placeholder/></child><child int"
  "ernal-child=\"vbox\"><object class=\"GtkBox\" id=\"dialog-vbox2\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"orientation\">vertical</property><property "
  "name=\"spacing\">2</property><child internal-child=\"action_area\"><obj"
  "ect class=\"GtkButtonBox\" id=\"dialog-action_area2\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"layout_style\">end</property><child><object class=\"Gtk"
  "Button\" id=\"license-close-button\"><property name=\"label\">_Close</p"
  "roperty><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"receives_default\">True</proper"
  "ty><property name=\"image\">image1</property><property name=\"use_under"
  "line\">True</property></object><packing><property name=\"expand\">False"
  "</property><property name=\"fill\">False</property><property name=\"pos"
  "ition\">0</property></packing></child></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">False</property><pro"
  "perty name=\"pack_type\">end</property><property name=\"position\">0</p"
  "roperty></packing></child><child><object class=\"GtkScrolledWindow\" id"
  "=\"scrolledwindow4\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"border_width\">6</"
  "property><property name=\"shadow_type\">etched-in</property><child><obj"
  "ect class=\"GtkTextView\" id=\"license-textview\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"editable\">False</property><property name=\"wrap_mode\">word"
  "</property><property name=\"justification\">center</property><property "
  "name=\"left_margin\">3</property><property name=\"right_margin\">3</pro"
  "perty><property name=\"cursor_visible\">False</property></object></chil"
  "d></object><packing><property name=\"expand\">True</property><property "
  "name=\"fill\">True</property><property name=\"position\">1</property></"
  "packing></child></object></child><action-widgets><action-widget respons"
  "e=\"0\">license-close-button</action-widget></action-widgets></object><"
  "object class=\"GtkImage\" id=\"image2\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"icon_name\">window-close-symbolic</property></object><object class=\""
  "GtkImage\" id=\"image3\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"icon_name\">h"
  "elp-browser</property></object><object class=\"GtkTextBuffer\" id=\"lgp"
  "l-buffer\"><property name=\"text\">GNU LIBRARY GENERAL PUBLIC LICENSE\n"
  "\nVersion 2, June 1991\n\nCopyright (C) 1991 Free Software Foundation, "
  "Inc.\n51 Franklin St, Fifth Floor, Boston, MA  02110-1301, USA\n\nEvery"
  "one is permitted to copy and distribute verbatim copies of this license"
  " document, but changing it is not allowed.\n\n[This is the first releas"
  "ed version of the library GPL. It is numbered 2 because it goes with ve"
  "rsion 2 of the ordinary GPL.]\n\nPreamble\n\nThe licenses for most soft"
  "ware are designed to take away your freedom to share and change it. By "
  "contrast, the GNU General Public Licenses are intended to guarantee you"
  "r freedom to share and change free software--to make sure the software "
  "is free for all its users.\n\nThis license, the Library General Public "
  "License, applies to some specially designated Free Software Foundation "
  "software, and to any other libraries whose authors decide to use it. Yo"
  "u can use it for your libraries, too.\n\nWhen we speak of free software"
  ", we are referring to freedom, not price. Our General Public Licenses a"
  "re designed to make sure that you have the freedom to distribute copies"
  " of free software (and charge for this service if you wish), that you r"
  "eceive source code or can get it if you want it, that you can change th"
  "e software or use pieces of it in new free programs; and that you know "
  "you can do these things.\n\nTo protect your rights, we need to make res"
  "trictions that forbid anyone to deny you these rights or to ask you to "
  "surrender the rights. These restrictions translate to certain responsib"
  "ilities for you if you distribute copies of the library, or if you modi"
  "fy it.\n\nFor example, if you distribute copies of the library, whether"
  " gratis or for a fee, you must give the recipients all the rights that "
  "we gave you. You must make sure that they, too, receive or can get the "
  "source code. If you link a program with the library, you must provide c"
  "omplete object files to the recipients so that they can relink them wit"
  "h the library, after making changes to the library and recompiling it. "
  "And you must show them these terms so they know their rights.\n\nOur me"
  "thod of protecting your rights has two steps: (1) copyright the library"
  ", and (2) offer you this license which gives you legal permission to co"
  "py, distribute and/or modify the library.\n\nAlso, for each distributor"
  "\'s protection, we want to make certain that everyone understands that "
  "there is no warranty for this free library. If the library is modified "
  "by someone else and passed on, we want its recipients to know that what"
  " they have is not the original version, so that any problems introduced"
  " by others will not reflect on the original authors\' reputations.\n\nF"
  "inally, any free program is threatened constantly by software patents. "
  "We wish to avoid the danger that companies distributing free software w"
  "ill individually obtain patent licenses, thus in effect transforming th"
  "e program into proprietary software. To prevent this, we have made it c"
  "lear that any patent must be licensed for everyone\'s free use or not l"
  "icensed at all.\n\nMost GNU software, including some libraries, is cove"
  "red by the ordinary GNU General Public License, which was designed for "
  "utility programs. This license, the GNU Library General Public License,"
  " applies to certain designated libraries. This license is quite differe"
  "nt from the ordinary one; be sure to read it in full, and don\'t assume"
  " that anything in it is the same as in the ordinary license.\n\nThe rea"
  "son we have a separate public license for some libraries is that they b"
  "lur the distinction we usually make between modifying or adding to a pr"
  "ogram and simply using it. Linking a program with a library, without ch"
  "anging the library, is in some sense simply using the library, and is a"
  "nalogous to running a utility program or application program. However, "
  "in a textual and legal sense, the linked executable is a combined work,"
  " a derivative of the original library, and the ordinary General Public "
  "License treats it as such.\n\nBecause of this blurred distinction, usin"
  "g the ordinary General Public License for libraries did not effectively"
  " promote software sharing, because most developers did not use the libr"
  "aries. We concluded that weaker conditions might promote sharing better"
  ".\n\nHowever, unrestricted linking of non-free programs would deprive t"
  "he users of those programs of all benefit from the free status of the l"
  "ibraries themselves. This Library General Public License is intended to"
  " permit developers of non-free programs to use free libraries, while pr"
  "eserving your freedom as a user of such programs to change the free lib"
  "raries that are incorporated in them. (We have not seen how to achieve "
  "this as regards changes in header files, but we have achieved it as reg"
  "ards changes in the actual functions of the Library.) The hope is that "
  "this will lead to faster development of free libraries.\n\nThe precise "
  "terms and conditions for copying, distribution and modification follow."
  " Pay close attention to the difference between a \"work based on the li"
  "brary\" and a \"work that uses the library\". The former contains code "
  "derived from the library, while the latter only works together with the"
  " library.\n\nNote that it is possible for a library to be covered by th"
  "e ordinary General Public License rather than by this special one.\nTER"
  "MS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION\n\n0. This"
  " License Agreement applies to any software library which contains a not"
  "ice placed by the copyright holder or other authorized party saying it "
  "may be distributed under the terms of this Library General Public Licen"
  "se (also called \"this License\"). Each licensee is addressed as \"you\""
  ".\n\nA \"library\" means a collection of software functions and/or data"
  " prepared so as to be conveniently linked with application programs (wh"
  "ich use some of those functions and data) to form executables.\n\nThe \""
  "Library\", below, refers to any such software library or work which has"
  " been distributed under these terms. A \"work based on the Library\" me"
  "ans either the Library or any derivative work under copyright law: that"
  " is to say, a work containing the Library or a portion of it, either ve"
  "rbatim or with modifications and/or translated straightforwardly into a"
  "nother language. (Hereinafter, translation is included without limitati"
  "on in the term \"modification\".)\n\n\"Source code\" for a work means t"
  "he preferred form of the work for making modifications to it. For a lib"
  "rary, complete source code means all the source code for all modules it"
  " contains, plus any associated interface definition files, plus the scr"
  "ipts used to control compilation and installation of the library.\n\nAc"
  "tivities other than copying, distribution and modification are not cove"
  "red by this License; they are outside its scope. The act of running a p"
  "rogram using the Library is not restricted, and output from such a prog"
  "ram is covered only if its contents constitute a work based on the Libr"
  "ary (independent of the use of the Library in a tool for writing it). W"
  "hether that is true depends on what the Library does and what the progr"
  "am that uses the Library does.\n\n1. You may copy and distribute verbat"
  "im copies of the Library\'s complete source code as you receive it, in "
  "any medium, provided that you conspicuously and appropriately publish o"
  "n each copy an appropriate copyright notice and disclaimer of warranty;"
  " keep intact all the notices that refer to this License and to the abse"
  "nce of any warranty; and distribute a copy of this License along with t"
  "he Library.\n\nYou may charge a fee for the physical act of transferrin"
  "g a copy, and you may at your option offer warranty protection in excha"
  "nge for a fee.\n\n2. You may modify your copy or copies of the Library "
  "or any portion of it, thus forming a work based on the Library, and cop"
  "y and distribute such modifications or work under the terms of Section "
  "1 above, provided that you also meet all of these conditions:\n\n    * "
  "a) The modified work must itself be a software library.\n    * b) You m"
  "ust cause the files modified to carry prominent notices stating that yo"
  "u changed the files and the date of any change.\n    * c) You must caus"
  "e the whole of the work to be licensed at no charge to all third partie"
  "s under the terms of this License.\n    * d) If a facility in the modif"
  "ied Library refers to a function or a table of data to be supplied by a"
  "n application program that uses the facility, other than as an argument"
  " passed when the facility is invoked, then you must make a good faith e"
  "ffort to ensure that, in the event an application does not supply such "
  "function or table, the facility still operates, and performs whatever p"
  "art of its purpose remains meaningful.\n\n      (For example, a functio"
  "n in a library to compute square roots has a purpose that is entirely w"
  "ell-defined independent of the application. Therefore, Subsection 2d re"
  "quires that any application-supplied function or table used by this fun"
  "ction must be optional: if the application does not supply it, the squa"
  "re root function must still compute square roots.)\n\nThese requirement"
  "s apply to the modified work as a whole. If identifiable sections of th"
  "at work are not derived from the Library, and can be reasonably conside"
  "red independent and separate works in themselves, then this License, an"
  "d its terms, do not apply to those sections when you distribute them as"
  " separate works. But when you distribute the same sections as part of a"
  " whole which is a work based on the Library, the distribution of the wh"
  "ole must be on the terms of this License, whose permissions for other l"
  "icensees extend to the entire whole, and thus to each and every part re"
  "gardless of who wrote it.\n\nThus, it is not the intent of this section"
  " to claim rights or contest your rights to work written entirely by you"
  "; rather, the intent is to exercise the right to control the distributi"
  "on of derivative or collective works based on the Library.\n\nIn additi"
  "on, mere aggregation of another work not based on the Library with the "
  "Library (or with a work based on the Library) on a volume of a storage "
  "or distribution medium does not bring the other work under the scope of"
  " this License.\n\n3. You may opt to apply the terms of the ordinary GNU"
  " General Public License instead of this License to a given copy of the "
  "Library. To do this, you must alter all the notices that refer to this "
  "License, so that they refer to the ordinary GNU General Public License,"
  " version 2, instead of to this License. (If a newer version than versio"
  "n 2 of the ordinary GNU General Public License has appeared, then you c"
  "an specify that version instead if you wish.) Do not make any other cha"
  "nge in these notices.\n\nOnce this change is made in a given copy, it i"
  "s irreversible for that copy, so the ordinary GNU General Public Licens"
  "e applies to all subsequent copies and derivative works made from that "
  "copy.\n\nThis option is useful when you wish to copy part of the code o"
  "f the Library into a program that is not a library.\n\n4. You may copy "
  "and distribute the Library (or a portion or derivative of it, under Sec"
  "tion 2) in object code or executable form under the terms of Sections 1"
  " and 2 above provided that you accompany it with the complete correspon"
  "ding machine-readable source code, which must be distributed under the "
  "terms of Sections 1 and 2 above on a medium customarily used for softwa"
  "re interchange.\n\nIf distribution of object code is made by offering a"
  "ccess to copy from a designated place, then offering equivalent access "
  "to copy the source code from the same place satisfies the requirement t"
  "o distribute the source code, even though third parties are not compell"
  "ed to copy the source along with the object code.\n\n5. A program that "
  "contains no derivative of any portion of the Library, but is designed t"
  "o work with the Library by being compiled or linked with it, is called "
  "a \"work that uses the Library\". Such a work, in isolation, is not a d"
  "erivative work of the Library, and therefore falls outside the scope of"
  " this License.\n\nHowever, linking a \"work that uses the Library\" wit"
  "h the Library creates an executable that is a derivative of the Library"
  " (because it contains portions of the Library), rather than a \"work th"
  "at uses the library\". The executable is therefore covered by this Lice"
  "nse. Section 6 states terms for distribution of such executables.\n\nWh"
  "en a \"work that uses the Library\" uses material from a header file th"
  "at is part of the Library, the object code for the work may be a deriva"
  "tive work of the Library even though the source code is not. Whether th"
  "is is true is especially significant if the work can be linked without "
  "the Library, or if the work is itself a library. The threshold for this"
  " to be true is not precisely defined by law.\n\nIf such an object file "
  "uses only numerical parameters, data structure layouts and accessors, a"
  "nd small macros and small inline functions (ten lines or less in length"
  "), then the use of the object file is unrestricted, regardless of wheth"
  "er it is legally a derivative work. (Executables containing this object"
  " code plus portions of the Library will still fall under Section 6.)\n\n"
  "Otherwise, if the work is a derivative of the Library, you may distribu"
  "te the object code for the work under the terms of Section 6. Any execu"
  "tables containing that work also fall under Section 6, whether or not t"
  "hey are linked directly with the Library itself.\n\n6. As an exception "
  "to the Sections above, you may also compile or link a \"work that uses "
  "the Library\" with the Library to produce a work containing portions of"
  " the Library, and distribute that work under terms of your choice, prov"
  "ided that the terms permit modification of the work for the customer\'s"
  " own use and reverse engineering for debugging such modifications.\n\nY"
  "ou must give prominent notice with each copy of the work that the Libra"
  "ry is used in it and that the Library and its use are covered by this L"
  "icense. You must supply a copy of this License. If the work during exec"
  "ution displays copyright notices, you must include the copyright notice"
  " for the Library among them, as well as a reference directing the user "
  "to the copy of this License. Also, you must do one of these things:\n\n"
  "    * a) Accompany the work with the complete corresponding machine-rea"
  "dable source code for the Library including whatever changes were used "
  "in the work (which must be distributed under Sections 1 and 2 above); a"
  "nd, if the work is an executable linked with the Library, with the comp"
  "lete machine-readable \"work that uses the Library\", as object code an"
  "d/or source code, so that the user can modify the Library and then reli"
  "nk to produce a modified executable containing the modified Library. (I"
  "t is understood that the user who changes the contents of definitions f"
  "iles in the Library will not necessarily be able to recompile the appli"
  "cation to use the modified definitions.)\n    * b) Accompany the work w"
  "ith a written offer, valid for at least three years, to give the same u"
  "ser the materials specified in Subsection 6a, above, for a charge no mo"
  "re than the cost of performing this distribution.\n    * c) If distribu"
  "tion of the work is made by offering access to copy from a designated p"
  "lace, offer equivalent access to copy the above specified materials fro"
  "m the same place.\n    * d) Verify that the user has already received a"
  " copy of these materials or that you have already sent this user a copy"
  ".\n\nFor an executable, the required form of the \"work that uses the L"
  "ibrary\" must include any data and utility programs needed for reproduc"
  "ing the executable from it. However, as a special exception, the source"
  " code distributed need not include anything that is normally distribute"
  "d (in either source or binary form) with the major components (compiler"
  ", kernel, and so on) of the operating system on which the executable ru"
  "ns, unless that component itself accompanies the executable.\n\nIt may "
  "happen that this requirement contradicts the license restrictions of ot"
  "her proprietary libraries that do not normally accompany the operating "
  "system. Such a contradiction means you cannot use both them and the Lib"
  "rary together in an executable that you distribute.\n\n7. You may place"
  " library facilities that are a work based on the Library side-by-side i"
  "n a single library together with other library facilities not covered b"
  "y this License, and distribute such a combined library, provided that t"
  "he separate distribution of the work based on the Library and of the ot"
  "her library facilities is otherwise permitted, and provided that you do"
  " these two things:\n\n    * a) Accompany the combined library with a co"
  "py of the same work based on the Library, uncombined with any other lib"
  "rary facilities. This must be distributed under the terms of the Sectio"
  "ns above.\n    * b) Give prominent notice with the combined library of "
  "the fact that part of it is a work based on the Library, and explaining"
  " where to find the accompanying uncombined form of the same work.\n\n8."
  " You may not copy, modify, sublicense, link with, or distribute the Lib"
  "rary except as expressly provided under this License. Any attempt other"
  "wise to copy, modify, sublicense, link with, or distribute the Library "
  "is void, and will automatically terminate your rights under this Licens"
  "e. However, parties who have received copies, or rights, from you under"
  " this License will not have their licenses terminated so long as such p"
  "arties remain in full compliance.\n\n9. You are not required to accept "
  "this License, since you have not signed it. However, nothing else grant"
  "s you permission to modify or distribute the Library or its derivative "
  "works. These actions are prohibited by law if you do not accept this Li"
  "cense. Therefore, by modifying or distributing the Library (or any work"
  " based on the Library), you indicate your acceptance of this License to"
  " do so, and all its terms and conditions for copying, distributing or m"
  "odifying the Library or works based on it.\n\n10. Each time you redistr"
  "ibute the Library (or any work based on the Library), the recipient aut"
  "omatically receives a license from the original licensor to copy, distr"
  "ibute, link with or modify the Library subject to these terms and condi"
  "tions. You may not impose any further restrictions on the recipients\' "
  "exercise of the rights granted herein. You are not responsible for enfo"
  "rcing compliance by third parties to this License.\n\n11. If, as a cons"
  "equence of a court judgment or allegation of patent infringement or for"
  " any other reason (not limited to patent issues), conditions are impose"
  "d on you (whether by court order, agreement or otherwise) that contradi"
  "ct the conditions of this License, they do not excuse you from the cond"
  "itions of this License. If you cannot distribute so as to satisfy simul"
  "taneously your obligations under this License and any other pertinent o"
  "bligations, then as a consequence you may not distribute the Library at"
  " all. For example, if a patent license would not permit royalty-free re"
  "distribution of the Library by all those who receive copies directly or"
  " indirectly through you, then the only way you could satisfy both it an"
  "d this License would be to refrain entirely from distribution of the Li"
  "brary.\n\nIf any portion of this section is held invalid or unenforceab"
  "le under any particular circumstance, the balance of the section is int"
  "ended to apply, and the section as a whole is intended to apply in othe"
  "r circumstances.\n\nIt is not the purpose of this section to induce you"
  " to infringe any patents or other property right claims or to contest v"
  "alidity of any such claims; this section has the sole purpose of protec"
  "ting the integrity of the free software distribution system which is im"
  "plemented by public license practices. Many people have made generous c"
  "ontributions to the wide range of software distributed through that sys"
  "tem in reliance on consistent application of that system; it is up to t"
  "he author/donor to decide if he or she is willing to distribute softwar"
  "e through any other system and a licensee cannot impose that choice.\n\n"
  "This section is intended to make thoroughly clear what is believed to b"
  "e a consequence of the rest of this License.\n\n12. If the distribution"
  " and/or use of the Library is restricted in certain countries either by"
  " patents or by copyrighted interfaces, the original copyright holder wh"
  "o places the Library under this License may add an explicit geographica"
  "l distribution limitation excluding those countries, so that distributi"
  "on is permitted only in or among countries not thus excluded. In such c"
  "ase, this License incorporates the limitation as if written in the body"
  " of this License.\n\n13. The Free Software Foundation may publish revis"
  "ed and/or new versions of the Library General Public License from time "
  "to time. Such new versions will be similar in spirit to the present ver"
  "sion, but may differ in detail to address new problems or concerns.\n\n"
  "Each version is given a distinguishing version number. If the Library s"
  "pecifies a version number of this License which applies to it and \"any"
  " later version\", you have the option of following the terms and condit"
  "ions either of that version or of any later version published by the Fr"
  "ee Software Foundation. If the Library does not specify a license versi"
  "on number, you may choose any version ever published by the Free Softwa"
  "re Foundation.\n\n14. If you wish to incorporate parts of the Library i"
  "nto other free programs whose distribution conditions are incompatible "
  "with these, write to the author to ask for permission. For software whi"
  "ch is copyrighted by the Free Software Foundation, write to the Free So"
  "ftware Foundation; we sometimes make exceptions for this. Our decision "
  "will be guided by the two goals of preserving the free status of all de"
  "rivatives of our free software and of promoting the sharing and reuse o"
  "f software generally.\n\nNO WARRANTY\n\n15. BECAUSE THE LIBRARY IS LICE"
  "NSED FREE OF CHARGE, THERE IS NO WARRANTY FOR THE LIBRARY, TO THE EXTEN"
  "T PERMITTED BY APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING "
  "THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE LIBRARY \"AS IS\""
  " WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, "
  "BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNE"
  "SS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERF"
  "ORMANCE OF THE LIBRARY IS WITH YOU. SHOULD THE LIBRARY PROVE DEFECTIVE,"
  " YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.\n"
  "\n16. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRI"
  "TING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/O"
  "R REDISTRIBUTE THE LIBRARY AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAM"
  "AGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAG"
  "ES ARISING OUT OF THE USE OR INABILITY TO USE THE LIBRARY (INCLUDING BU"
  "T NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSS"
  "ES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE LIBRARY TO OPE"
  "RATE WITH ANY OTHER SOFTWARE), EVEN IF SUCH HOLDER OR OTHER PARTY HAS B"
  "EEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</property></object><obj"
  "ect class=\"GtkTextBuffer\" id=\"vendor-buffer\"/><object class=\"XfceT"
  "itledDialog\" id=\"window\"><property name=\"can_focus\">False</propert"
  "y><property name=\"title\" translatable=\"yes\">About the Xfce Desktop "
  "Environment</property><property name=\"default_width\">550</property><p"
  "roperty name=\"default_height\">600</property><property name=\"icon_nam"
  "e\">org.xfce.about</property><property name=\"type_hint\">normal</prope"
  "rty><child internal-child=\"vbox\"><object class=\"GtkBox\" id=\"dialog"
  "-vbox1\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"orientation\">vertical</prope"
  "rty><property name=\"spacing\">2</property><child internal-child=\"acti"
  "on_area\"><object class=\"GtkButtonBox\" id=\"dialog-action_area1\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"layout_style\">end</property><child><obje"
  "ct class=\"GtkButton\" id=\"help-button\"><property name=\"label\" tran"
  "slatable=\"yes\">_Help</property><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">True</property><property name=\"receiv"
  "es_default\">True</property><property name=\"image\">image3</property><"
  "property name=\"use_underline\">True</property></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">False</prop"
  "erty><property name=\"position\">0</property><property name=\"secondary"
  "\">True</property></packing></child><child><object class=\"GtkButton\" "
  "id=\"close-button\"><property name=\"label\" translatable=\"yes\">_Clos"
  "e</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">True</pr"
  "operty><property name=\"image\">image2</property><property name=\"use_u"
  "nderline\">True</property></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">False</property><property name=\""
  "position\">1</property></packing></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"pack_type\">end</property><property name=\"position\">0"
  "</property></packing></child><child><object class=\"GtkNotebook\" id=\""
  "notebook\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">True</property><property name=\"border_width\">6</property><"
  "child><object class=\"GtkBox\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"valign\""
  ">start</property><property name=\"margin_left\">12</property><property "
  "name=\"margin_right\">12</property><property name=\"margin_top\">18</pr"
  "operty><property name=\"margin_bottom\">12</property><property name=\"s"
  "pacing\">36</property><child><object class=\"GtkImage\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"valign\">start</property><property name=\"pixel_size\""
  ">128</property><property name=\"icon_name\">computer</property><propert"
  "y name=\"icon_size\">6</property></object><packing><property name=\"exp"
  "and\">False</property><property name=\"fill\">True</property><property "
  "name=\"position\">0</property></packing></child><child><object class=\""
  "GtkGrid\" id=\"about-system\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"valign\""
  ">center</property><property name=\"row_spacing\">6</property><property "
  "name=\"column_spacing\">12</property><child><object class=\"GtkLabel\">"
  "<property name=\"visible\">True</property><property name=\"sensitive\">"
  "False</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">Device</property><property name=\"x"
  "align\">1</property></object><packing><property name=\"left_attach\">0<"
  "/property><property name=\"top_attach\">0</property></packing></child><"
  "child><object class=\"GtkLabel\" id=\"device\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"label\" translatable=\"yes\">label</property><property name=\""
  "xalign\">0</property></object><packing><property name=\"left_attach\">1"
  "</property><property name=\"top_attach\">0</property></packing></child>"
  "<child><object class=\"GtkLabel\"><property name=\"visible\">True</prop"
  "erty><property name=\"sensitive\">False</property><property name=\"can_"
  "focus\">False</property><property name=\"label\" translatable=\"yes\">O"
  "S Name</property><property name=\"xalign\">1</property></object><packin"
  "g><property name=\"left_attach\">0</property><property name=\"top_attac"
  "h\">1</property></packing></child><child><object class=\"GtkLabel\" id="
  "\"osname\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"label\" translatable=\"yes\""
  ">label</property><property name=\"xalign\">0</property></object><packin"
  "g><property name=\"left_attach\">1</property><property name=\"top_attac"
  "h\">1</property></packing></child><child><object class=\"GtkLabel\"><pr"
  "operty name=\"visible\">True</property><property name=\"sensitive\">Fal"
  "se</property><property name=\"can_focus\">False</property><property nam"
  "e=\"label\" translatable=\"yes\">OS Type</property><property name=\"xal"
  "ign\">1</property></object><packing><property name=\"left_attach\">0</p"
  "roperty><property name=\"top_attach\">2</property></packing></child><ch"
  "ild><object class=\"GtkLabel\" id=\"ostype\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">label</property><property name=\"xa"
  "lign\">0</property></object><packing><property name=\"left_attach\">1</"
  "property><property name=\"top_attach\">2</property></packing></child><c"
  "hild><object class=\"GtkLabel\" id=\"vendor-info-label\"><property name"
  "=\"visible\">True</property><property name=\"sensitive\">False</propert"
  "y><property name=\"can_focus\">False</property><property name=\"label\""
  " translatable=\"yes\">Distributor</property><property name=\"xalign\">1"
  "</property></object><packing><property name=\"left_attach\">0</property"
  "><property name=\"top_attach\">3</property></packing></child><child><ob"
  "ject class=\"GtkLabel\" id=\"vendor-info\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"label\" translatable=\"yes\">label</property><property name=\"xali"
  "gn\">0</property></object><packing><property name=\"left_attach\">1</pr"
  "operty><property name=\"top_attach\">3</property></packing></child><chi"
  "ld><object class=\"GtkLabel\"><property name=\"visible\">True</property"
  "><property name=\"sensitive\">False</property><property name=\"can_focu"
  "s\">False</property><property name=\"margin_top\">12</property><propert"
  "y name=\"label\" translatable=\"yes\">Xfce Version</property><property "
  "name=\"xalign\">1</property></object><packing><property name=\"left_att"
  "ach\">0</property><property name=\"top_attach\">4</property></packing><"
  "/child><child><object class=\"GtkLabel\" id=\"xfce-version\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"margin_top\">12</property><property name=\"label"
  "\" translatable=\"yes\">label</property><property name=\"xalign\">0</pr"
  "operty></object><packing><property name=\"left_attach\">1</property><pr"
  "operty name=\"top_attach\">4</property></packing></child><child><object"
  " class=\"GtkLabel\"><property name=\"visible\">True</property><property"
  " name=\"sensitive\">False</property><property name=\"can_focus\">False<"
  "/property><property name=\"label\" translatable=\"yes\">GTK Version</pr"
  "operty><property name=\"xalign\">1</property></object><packing><propert"
  "y name=\"left_attach\">0</property><property name=\"top_attach\">5</pro"
  "perty></packing></child><child><object class=\"GtkLabel\" id=\"gtk-vers"
  "ion\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><property name=\"label\" translatable=\"yes\">lab"
  "el</property><property name=\"xalign\">0</property></object><packing><p"
  "roperty name=\"left_attach\">1</property><property name=\"top_attach\">"
  "5</property></packing></child><child><object class=\"GtkLabel\"><proper"
  "ty name=\"visible\">True</property><property name=\"sensitive\">False</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "label\" translatable=\"yes\">Kernel Version</property><property name=\""
  "xalign\">1</property></object><packing><property name=\"left_attach\">0"
  "</property><property name=\"top_attach\">6</property></packing></child>"
  "<child><object class=\"GtkLabel\" id=\"kernel-version\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"label\" translatable=\"yes\">label</property><propert"
  "y name=\"xalign\">0</property></object><packing><property name=\"left_a"
  "ttach\">1</property><property name=\"top_attach\">6</property></packing"
  "></child><child><object class=\"GtkLabel\"><property name=\"visible\">T"
  "rue</property><property name=\"sensitive\">False</property><property na"
  "me=\"can_focus\">False</property><property name=\"margin_top\">12</prop"
  "erty><property name=\"label\" translatable=\"yes\">CPU</property><prope"
  "rty name=\"xalign\">1</property></object><packing><property name=\"left"
  "_attach\">0</property><property name=\"top_attach\">7</property></packi"
  "ng></child><child><object class=\"GtkLabel\" id=\"cpu\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"margin_top\">12</property><property name=\"label\" tr"
  "anslatable=\"yes\">label</property><property name=\"xalign\">0</propert"
  "y></object><packing><property name=\"left_attach\">1</property><propert"
  "y name=\"top_attach\">7</property></packing></child><child><object clas"
  "s=\"GtkLabel\"><property name=\"visible\">True</property><property name"
  "=\"sensitive\">False</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"label\" translatable=\"yes\">Memory</property><pr"
  "operty name=\"xalign\">1</property></object><packing><property name=\"l"
  "eft_attach\">0</property><property name=\"top_attach\">8</property></pa"
  "cking></child><child><object class=\"GtkLabel\" id=\"memory\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"label\" translatable=\"yes\">label</property><p"
  "roperty name=\"xalign\">0</property></object><packing><property name=\""
  "left_attach\">1</property><property name=\"top_attach\">8</property></p"
  "acking></child><child><object class=\"GtkLabel\" id=\"gpu-label\"><prop"
  "erty name=\"visible\">True</property><property name=\"sensitive\">False"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"label\" translatable=\"yes\">GPU</property><property name=\"xalign\">"
  "1</property></object><packing><property name=\"left_attach\">0</propert"
  "y><property name=\"top_attach\">9</property></packing></child><child><o"
  "bject class=\"GtkLabel\" id=\"gpu\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"la"
  "bel\" translatable=\"yes\">label</property><property name=\"xalign\">0<"
  "/property></object><packing><property name=\"left_attach\">1</property>"
  "<property name=\"top_attach\">9</property></packing></child></object><p"
  "acking><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld></object></child><child type=\"tab\"><object class=\"GtkLabel\" id=\""
  "system\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label\" translatable=\"yes\">"
  "System</property></object><packing><property name=\"tab_fill\">False</p"
  "roperty></packing></child><child><object class=\"GtkScrolledWindow\" id"
  "=\"scrolledwindow1\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"hscrollbar_policy\""
  ">never</property><child><object class=\"GtkViewport\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"shadow_type\">none</property><child><object class=\"Gtk"
  "Box\" id=\"about-xfce-box\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"border_wid"
  "th\">18</property><property name=\"orientation\">vertical</property><pr"
  "operty name=\"spacing\">12</property><child><object class=\"GtkImage\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"margin_top\">12</property><property na"
  "me=\"margin_bottom\">12</property><property name=\"pixel_size\">128</pr"
  "operty><property name=\"icon_name\">xfce4-logo</property></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">0</property></packing></child"
  "><child><object class=\"GtkLabel\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"lab"
  "el\" translatable=\"yes\">Xfce is a collection of programs that togethe"
  "r provide a full-featured desktop environment.\nThe following programs "
  "are part of the Xfce core:</property><property name=\"wrap\">True</prop"
  "erty><property name=\"xalign\">0</property></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">True</property>"
  "<property name=\"position\">1</property></packing></child><child><objec"
  "t class=\"GtkBox\" id=\"components-box\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"border_width\">12</property><property name=\"orientation\">vertical<"
  "/property><property name=\"spacing\">12</property><child><placeholder/>"
  "</child><child><placeholder/></child><child><placeholder/></child></obj"
  "ect><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">2</property></packing"
  "></child><child><object class=\"GtkLabel\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"label\" translatable=\"yes\">Xfce is also a development platform p"
  "roviding several libraries that help programmers create applications th"
  "at fit in well with the desktop environment.\n\nXfce components are lic"
  "ensed under free or open source licences; GPL or BSDL for applications "
  "and LGPL or BSDL for libraries. Look at the documentation, the source c"
  "ode or the Xfce website (&lt;a href=\"https://www.xfce.org\"&gt;https:/"
  "/www.xfce.org&lt;/a&gt;) for more information.\n\nThank you for your in"
  "terest in Xfce.\n\n\t- The Xfce Development Team</property><property na"
  "me=\"use_markup\">True</property><property name=\"wrap\">True</property"
  "><property name=\"xalign\">0</property></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">True</property><pro"
  "perty name=\"position\">3</property></packing></child></object></child>"
  "</object></child></object><packing><property name=\"position\">1</prope"
  "rty></packing></child><child type=\"tab\"><object class=\"GtkLabel\" id"
  "=\"label1\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label\" translatable=\"yes"
  "\">About</property></object><packing><property name=\"position\">1</pro"
  "perty><property name=\"tab_fill\">False</property></packing></child><ch"
  "ild><object class=\"GtkScrolledWindow\" id=\"scrolledwindow2\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"shadow_type\">etched-in</property><child><objec"
  "t class=\"GtkTextView\" id=\"credits-textview\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">True</property><propert"
  "y name=\"border_width\">12</property><property name=\"editable\">False<"
  "/property><property name=\"wrap_mode\">word</property><property name=\""
  "left_margin\">3</property><property name=\"right_margin\">3</property><"
  "property name=\"cursor_visible\">False</property><property name=\"buffe"
  "r\">credits-buffer</property></object></child></object><packing><proper"
  "ty name=\"position\">2</property></packing></child><child type=\"tab\">"
  "<object class=\"GtkLabel\" id=\"label2\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"label\" translatable=\"yes\">Credits</property></object><packing><pr"
  "operty name=\"position\">2</property><property name=\"tab_fill\">False<"
  "/property></packing></child><child><object class=\"GtkScrolledWindow\" "
  "id=\"vendor-tab\"><property name=\"can_focus\">True</property><property"
  " name=\"shadow_type\">etched-in</property><child><object class=\"GtkTex"
  "tView\" id=\"vendor-textview\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">True</property><property name=\"border_w"
  "idth\">12</property><property name=\"editable\">False</property><proper"
  "ty name=\"wrap_mode\">word</property><property name=\"left_margin\">3</"
  "property><property name=\"right_margin\">3</property><property name=\"c"
  "ursor_visible\">False</property><property name=\"buffer\">vendor-buffer"
  "</property></object></child></object><packing><property name=\"position"
  "\">3</property></packing></child><child type=\"tab\"><object class=\"Gt"
  "kLabel\" id=\"vendor-label\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"label\">V"
  "endor</property></object><packing><property name=\"position\">3</proper"
  "ty><property name=\"tab_fill\">False</property></packing></child><child"
  "><object class=\"GtkBox\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"orientation\""
  ">vertical</property><child><object class=\"GtkScrolledWindow\" id=\"scr"
  "olledwindow3\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"shadow_type\">etched-in<"
  "/property><child><object class=\"GtkTextView\" id=\"copyright-textview\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"border_width\">6</property><property n"
  "ame=\"editable\">False</property><property name=\"wrap_mode\">word</pro"
  "perty><property name=\"left_margin\">3</property><property name=\"right"
  "_margin\">3</property><property name=\"cursor_visible\">False</property"
  "><property name=\"buffer\">copyright-buffer</property></object></child>"
  "</object><packing><property name=\"expand\">True</property><property na"
  "me=\"fill\">True</property><property name=\"position\">1</property></pa"
  "cking></child><child><object class=\"GtkButtonBox\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"halign\">center</property><property name=\"homogeneous\">"
  "True</property><property name=\"layout_style\">start</property><child><"
  "object class=\"GtkButton\" id=\"gpl-button\"><property name=\"label\" t"
  "ranslatable=\"yes\">GPL</property><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">True</property></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">False</property><property name"
  "=\"position\">0</property></packing></child><child><object class=\"GtkB"
  "utton\" id=\"lgpl-button\"><property name=\"label\" translatable=\"yes\""
  ">LGPL</property><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">True</property><property name=\"receives_default\">True"
  "</property></object><packing><property name=\"expand\">False</property>"
  "<property name=\"fill\">False</property><property name=\"position\">1</"
  "property></packing></child><child><object class=\"GtkButton\" id=\"bsd-"
  "button\"><property name=\"label\" translatable=\"yes\">BSD</property><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Tr"
  "ue</property><property name=\"receives_default\">True</property></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"f"
  "ill\">False</property><property name=\"position\">2</property></packing"
  "></child><style><class name=\"inline-toolbar\"/></style></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">2</property></packing></child>"
  "</object><packing><property name=\"position\">4</property></packing></c"
  "hild><child type=\"tab\"><object class=\"GtkLabel\" id=\"label3\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"label\" translatable=\"yes\">Copyright</pro"
  "perty></object><packing><property name=\"position\">4</property><proper"
  "ty name=\"tab_fill\">False</property></packing></child></object><packin"
  "g><property name=\"expand\">True</property><property name=\"fill\">True"
  "</property><property name=\"position\">1</property></packing></child></"
  "object></child><action-widgets><action-widget response=\"0\">help-butto"
  "n</action-widget><action-widget response=\"0\">close-button</action-wid"
  "get></action-widgets></object></interface>"
};

static const unsigned xfce_about_dialog_ui_length = 62515u;

