[source]
tar = "https://dlcdn.apache.org//apr/apr-1.7.4.tar.bz2"
patches = ["redox.patch"]
[build]
template = "custom"
script = """
COOKBOOK_CONFIGURE_FLAGS+=(
ac_cv_file__dev_zero=yes
ac_cv_working_getaddrinfo=no
apr_cv_process_shared_works=yes
apr_cv_mutex_robust_shared=yes
apr_cv_tcp_nodelay_with_cork=no
)
cookbook_configure
"""
