#TODO probably wrong script, see https://github.com/RastislavKish/clipshare#building
[source]
git = "https://github.com/RastislavKish/clipshare"
rev = "2afa9c5af1a5ebaa6e1e372da6e01a289d31fdb3"
[build]
template = "custom"
dependencies = [
    "xdotool",
]
script = """
cookbook_cargo_packages server
"""
