#TODO: needs libmodule-build-parse-yapp-perl dependency
[source]
git = "https://gitlab.redox-os.org/redox-os/samba.git"
upstream = "https://github.com/samba-team/samba.git"

[build]
template = "custom"
dependencies = [
    "gnutls3",
    "libarchive",
    "libnettle",
    "jansson",
    "zlib",
]
script = """
rsync -av --delete --exclude .git "${COOKBOOK_SOURCE}/" ./
cp -v "${COOKBOOK_RECIPE}/answers.txt" answers.txt

COOKBOOK_CONFIGURE_FLAGS=(
    --builtin-libraries=ALL
    --cross-compile
    --cross-answers=answers.txt
    --disable-python
    --disable-rpath
    --enable-fhs
    --host="${TARGET}"
    --localstatedir=/var
    --prefix=/usr
    --sysconfdir=/etc
    --with-static-modules=ALL,!vfs_snapper
    --without-acl-support
    --without-ad-dc
    --without-ads
    --without-gettext
    --without-ldap
    --without-libunwind
    --without-pam
)
cookbook_configure
"""
