[package]
name = "games-for-redox"
version = "0.1.0"
authors = ["Ticki <Ticki@users.noreply.github.com>", "Marcelo Paez <paezao@users.noreply.github.com>", "Enrico <EGhiorzi@users.noreply.github.com>"]

[dependencies]
libgo = "0.4.0"
#liner = "0.4.4"
rand = "0.3"
rayon = "0.8"
termion = "1.5.1"

[dependencies.redox_liner]
git = "https://gitlab.redox-os.org/redox-os/liner.git"

[dependencies.extra]
git = "https://gitlab.redox-os.org/redox-os/libextra.git"

[dependencies.reversi]
version = "0.5.*"
git = "https://github.com/EGhiorzi/reversi/"

[[bin]]
name = "minesweeper"
path = "src/minesweeper/main.rs"

[[bin]]
name = "ice"
path = "src/ice/main.rs"

[[bin]]
name = "h4xx3r"
path = "src/h4xx3r/main.rs"

[lib]
name = "rusthello_lib"
path = "src/rusthello/lib.rs"

[[bin]]
name = "rusthello"
path = "src/rusthello/main.rs"

[[bin]]
name = "snake"
path = "src/snake/main.rs"

[[bin]]
name = "flappy"
path = "src/flappy/main.rs"

[[bin]]
name = "dem"
path = "src/dem/main.rs"

[[bin]]
name = "reblox"
path = "src/reblox/main.rs"

[[bin]]
name = "baduk"
path = "src/baduk/main.rs"

[[bin]]
name = "redoku"
path = "src/redoku/main.rs"
