#TODO compiled but not tested
[source]
tar = "https://ftp.gnu.org/gnu/gdb/gdb-14.1.tar.xz"
[build]
template = "custom"
dependencies = [
    "libgmp",
    "libmpfr",
]
script = """
COOKBOOK_CONFIGURE_FLAGS+=(
    --disable-binutils
    --disable-ld
    --disable-gold
    --disable-gas
    --disable-sim
    --disable-gprof
    --disable-gprofng
    --disable-intl
)
cookbook_configure
"""
