[source]
git = "https://gitlab.redox-os.org/redox-os/book.git"

[build]
template = "custom"
script = """
dir="${COOKBOOK_STAGE}/share/book"
mkdir -pv "${dir}"
mdbook build --dest-dir "${dir}" "${COOKBOOK_SOURCE}"
"""
