#TODO move to proper category
[source]
git = "https://github.com/sindresorhus/pure"
rev = "87e6f5dd4c793f6d980532205aaefe196780606f"
[build]
template = "custom"
script = """
mkdir -pv "${COOKBOOK_STAGE}"/home/user/.zsh/pure
cp -rv "${COOKBOOK_SOURCE}"/* "${COOKBOOK_STAGE}"/home/user/.zsh/pure
"""
