/* automatically generated from clock-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (clock_dialog_ui)
#endif
#ifdef __GNUC__
static const char clock_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char clock_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><requires lib=\"libxfce4ui-2\" version=\"4.12\"/"
  "><object class=\"GtkListStore\" id=\"binary-mode-model\"><columns><colu"
  "mn type=\"gchararray\"/></columns><data><row><col id=\"0\" translatable"
  "=\"yes\">Decimal</col></row><row><col id=\"0\" translatable=\"yes\">Sex"
  "agesimal</col></row><row><col id=\"0\" translatable=\"yes\">Binary time"
  "</col></row></data></object><object class=\"GtkListStore\" id=\"digital"
  "-format-model\"><columns><column type=\"gchararray\"/></columns><data><"
  "row><col id=\"0\" translatable=\"yes\">Date, then time</col></row><row>"
  "<col id=\"0\" translatable=\"yes\">Time, then date</col></row><row><col"
  " id=\"0\" translatable=\"yes\">Date Only</col></row><row><col id=\"0\" "
  "translatable=\"yes\">Time Only</col></row></data></object><object class"
  "=\"GtkAdjustment\" id=\"fuzziness\"><property name=\"upper\">3</propert"
  "y><property name=\"step_increment\">1</property><property name=\"page_i"
  "ncrement\">1</property><property name=\"page_size\">1</property></objec"
  "t><object class=\"GtkImage\" id=\"image1\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"icon_name\">time-admin</property></object><object class=\"GtkImage"
  "\" id=\"image2\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"icon_name\">window-cl"
  "ose-symbolic</property></object><object class=\"GtkImage\" id=\"image3\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"icon_name\">help-browser</property></"
  "object><object class=\"GtkListStore\" id=\"mode-model\"><columns><colum"
  "n type=\"gchararray\"/></columns><data><row><col id=\"0\" translatable="
  "\"yes\">Analog</col></row><row><col id=\"0\" translatable=\"yes\">Binar"
  "y</col></row><row><col id=\"0\" translatable=\"yes\">Digital</col></row"
  "><row><col id=\"0\" translatable=\"yes\">Fuzzy</col></row><row><col id="
  "\"0\" translatable=\"yes\">LCD</col></row></data></object><object class"
  "=\"XfceTitledDialog\" id=\"dialog\"><property name=\"can_focus\">False<"
  "/property><property name=\"title\" translatable=\"yes\">Clock</property"
  "><property name=\"icon_name\">org.xfce.panel.clock</property><property "
  "name=\"type_hint\">normal</property><child internal-child=\"vbox\"><obj"
  "ect class=\"GtkBox\" id=\"dialog-vbox2\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"orientation\">vertical</property><property name=\"spacing\">2</prope"
  "rty><child internal-child=\"action_area\"><object class=\"GtkButtonBox\""
  " id=\"dialog-action_area2\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"layout_sty"
  "le\">end</property><child><object class=\"GtkButton\" id=\"close-button"
  "\"><property name=\"label\" translatable=\"yes\">_Close</property><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"receives_default\">True</property><property "
  "name=\"image\">image2</property><property name=\"use_underline\">True</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">False</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkButton\" id=\"help-b"
  "utton\"><property name=\"label\" translatable=\"yes\">_Help</property><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"receives_default\">True</property><prope"
  "rty name=\"image\">image3</property><property name=\"use_underline\">Tr"
  "ue</property></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">False</property><property name=\"position\">1"
  "</property><property name=\"secondary\">True</property></packing></chil"
  "d></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">True</property><property name=\"pack_type\">end</propert"
  "y><property name=\"position\">0</property></packing></child><child><obj"
  "ect class=\"GtkBox\" id=\"vbox1\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"bord"
  "er_width\">6</property><property name=\"orientation\">vertical</propert"
  "y><property name=\"spacing\">6</property><child><object class=\"GtkFram"
  "e\" id=\"frame2\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"margin_bottom\">18</"
  "property><property name=\"label_xalign\">0</property><property name=\"s"
  "hadow_type\">none</property><child><object class=\"GtkGrid\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"margin_left\">18</property><property name=\"row_"
  "spacing\">6</property><property name=\"column_spacing\">12</property><c"
  "hild><object class=\"GtkEntry\" id=\"timezone-name\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"hexpand\">True</property><property name=\"invisible_char\""
  ">\342\227\217</property><property name=\"secondary_icon_name\">help-con"
  "tents</property><property name=\"primary_icon_activatable\">False</prop"
  "erty><property name=\"secondary_icon_tooltip_text\" translatable=\"yes\""
  ">Name of a timezone corresponding a file in the zoneinfo database, for "
  "example \"America/New_York\". Leave empty to use the localtime.</proper"
  "ty></object><packing><property name=\"left_attach\">1</property><proper"
  "ty name=\"top_attach\">0</property></packing></child><child><object cla"
  "ss=\"GtkLabel\" id=\"label9\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"label\" "
  "translatable=\"yes\">Time_zone:</property><property name=\"use_underlin"
  "e\">True</property><property name=\"xalign\">0</property></object><pack"
  "ing><property name=\"left_attach\">0</property><property name=\"top_att"
  "ach\">0</property></packing></child><child><object class=\"GtkButton\" "
  "id=\"run-time-config-tool\"><property name=\"label\" translatable=\"yes"
  "\">Time and Date _Settings...</property><property name=\"use_action_app"
  "earance\">False</property><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">True</property><property name=\"receives_defa"
  "ult\">True</property><property name=\"image\">image1</property><propert"
  "y name=\"use_underline\">True</property></object><packing><property nam"
  "e=\"left_attach\">0</property><property name=\"top_attach\">1</property"
  "></packing></child></object></child><child type=\"label\"><object class"
  "=\"GtkLabel\" id=\"label6\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"margin_bot"
  "tom\">6</property><property name=\"label\" translatable=\"yes\">Time Se"
  "ttings</property><attributes><attribute name=\"weight\" value=\"bold\"/"
  "></attributes></object></child></object><packing><property name=\"expan"
  "d\">False</property><property name=\"fill\">True</property><property na"
  "me=\"position\">0</property></packing></child><child><object class=\"Gt"
  "kFrame\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"margin_bottom\">18</property>"
  "<property name=\"label_xalign\">0</property><property name=\"shadow_typ"
  "e\">none</property><child><object class=\"GtkGrid\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"margin_left\">18</property><property name=\"row_spacing\""
  ">6</property><property name=\"column_spacing\">12</property><child><obj"
  "ect class=\"GtkEntry\" id=\"command\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"h"
  "expand\">True</property><property name=\"invisible_char\">\342\227\217<"
  "/property><property name=\"secondary_icon_name\">help-contents</propert"
  "y><property name=\"primary_icon_activatable\">False</property><property"
  " name=\"secondary_icon_tooltip_text\" translatable=\"yes\">If set, this"
  " command is run when the plugin is left-clicked, instead of displaying "
  "the default calendar.</property></object><packing><property name=\"left"
  "_attach\">1</property><property name=\"top_attach\">0</property></packi"
  "ng></child><child><object class=\"GtkLabel\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">Co_mmand:</property><property name="
  "\"use_underline\">True</property><property name=\"xalign\">0</property>"
  "</object><packing><property name=\"left_attach\">0</property><property "
  "name=\"top_attach\">0</property></packing></child></object></child><chi"
  "ld type=\"label\"><object class=\"GtkLabel\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"margin_bottom\">6</property><property name=\"label\" translatabl"
  "e=\"yes\">Calendar</property><attributes><attribute name=\"weight\" val"
  "ue=\"bold\"/></attributes></object></child></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">True</property>"
  "<property name=\"position\">1</property></packing></child><child><objec"
  "t class=\"GtkFrame\" id=\"frame3\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"mar"
  "gin_bottom\">18</property><property name=\"label_xalign\">0</property><"
  "property name=\"shadow_type\">none</property><child><object class=\"Gtk"
  "Grid\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"margin_left\">18</property><pro"
  "perty name=\"row_spacing\">6</property><property name=\"column_spacing\""
  ">12</property><child><object class=\"GtkEntry\" id=\"tooltip-format\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"hexpand\">True</property><property name="
  "\"secondary_icon_name\">help-contents</property><property name=\"primar"
  "y_icon_activatable\">False</property><property name=\"secondary_icon_to"
  "oltip_text\" translatable=\"yes\">The format describes the date and tim"
  "e parts to insert into the panel. For example, %Y will be substituted w"
  "ith the year, %m with the month and %d with the day. Similarly, &lt;b&g"
  "t;&lt;/b&gt; tags will make the text bold. See the \"Help\" page for ad"
  "ditional information.</property></object><packing><property name=\"left"
  "_attach\">0</property><property name=\"top_attach\">2</property><proper"
  "ty name=\"width\">2</property></packing></child><child><object class=\""
  "GtkComboBox\" id=\"tooltip-chooser\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"h"
  "expand\">False</property><child><object class=\"GtkCellRendererText\" i"
  "d=\"cellrenderertext2\"/><attributes><attribute name=\"text\">2</attrib"
  "ute></attributes></child></object><packing><property name=\"left_attach"
  "\">1</property><property name=\"top_attach\">1</property></packing></ch"
  "ild><child><object class=\"GtkLabel\" id=\"label4\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"label\" translatable=\"yes\">_Tooltip format:</property><"
  "property name=\"use_underline\">True</property><property name=\"xalign\""
  ">0</property></object><packing><property name=\"left_attach\">0</proper"
  "ty><property name=\"top_attach\">1</property></packing></child><child><"
  "object class=\"GtkLabel\" id=\"label2\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"label\" translatable=\"yes\">_Layout:</property><property name=\"use_"
  "underline\">True</property><property name=\"xalign\">0</property></obje"
  "ct><packing><property name=\"left_attach\">0</property><property name=\""
  "top_attach\">0</property></packing></child><child><object class=\"GtkCo"
  "mboBox\" id=\"mode\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"hexpand\">True</p"
  "roperty><property name=\"model\">mode-model</property><child><object cl"
  "ass=\"GtkCellRendererText\" id=\"cellrenderertext1\"/><attributes><attr"
  "ibute name=\"text\">0</attribute></attributes></child></object><packing"
  "><property name=\"left_attach\">1</property><property name=\"top_attach"
  "\">0</property></packing></child></object></child><child type=\"label\""
  "><object class=\"GtkLabel\" id=\"label1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"margin_bottom\">6</property><property name=\"label\" translatable=\""
  "yes\">Appearance</property><attributes><attribute name=\"weight\" value"
  "=\"bold\"/></attributes></object></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">True</property><p"
  "roperty name=\"position\">2</property></packing></child><child><object "
  "class=\"GtkFrame\" id=\"frame1\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"label"
  "_xalign\">0</property><property name=\"shadow_type\">none</property><ch"
  "ild><object class=\"GtkGrid\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"margin_l"
  "eft\">18</property><property name=\"hexpand\">True</property><property "
  "name=\"row_spacing\">6</property><property name=\"column_spacing\">12</"
  "property><child><object class=\"GtkCheckButton\" id=\"show-meridiem\"><"
  "property name=\"label\" translatable=\"yes\">Sho_w AM/PM</property><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">True"
  "</property><property name=\"receives_default\">False</property><propert"
  "y name=\"use_underline\">True</property><property name=\"draw_indicator"
  "\">True</property></object><packing><property name=\"left_attach\">0</p"
  "roperty><property name=\"top_attach\">4</property><property name=\"widt"
  "h\">2</property></packing></child><child><object class=\"GtkCheckButton"
  "\" id=\"flash-separators\"><property name=\"label\" translatable=\"yes\""
  ">Fl_ash time separators</property><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">False</property><property name=\"use_underline\">True</pr"
  "operty><property name=\"draw_indicator\">True</property></object><packi"
  "ng><property name=\"left_attach\">0</property><property name=\"top_atta"
  "ch\">3</property><property name=\"width\">2</property></packing></child"
  "><child><object class=\"GtkCheckButton\" id=\"show-military\"><property"
  " name=\"label\" translatable=\"yes\">24-_hour clock</property><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"receives_default\">False</property><property nam"
  "e=\"use_underline\">True</property><property name=\"draw_indicator\">Tr"
  "ue</property></object><packing><property name=\"left_attach\">0</proper"
  "ty><property name=\"top_attach\">2</property><property name=\"width\">2"
  "</property></packing></child><child><object class=\"GtkGrid\" id=\"bina"
  "ry-box\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"hexpand\">True</property><pro"
  "perty name=\"row_spacing\">6</property><property name=\"column_spacing\""
  ">12</property><child><object class=\"GtkComboBox\" id=\"binary-mode\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"hexpand\">True</property><property name"
  "=\"model\">binary-mode-model</property><child><object class=\"GtkCellRe"
  "ndererText\"/><attributes><attribute name=\"text\">0</attribute></attri"
  "butes></child></object><packing><property name=\"left_attach\">1</prope"
  "rty><property name=\"top_attach\">0</property></packing></child><child>"
  "<object class=\"GtkLabel\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"label\" tra"
  "nslatable=\"yes\">Binary mode:</property></object><packing><property na"
  "me=\"left_attach\">0</property><property name=\"top_attach\">0</propert"
  "y></packing></child></object><packing><property name=\"left_attach\">0<"
  "/property><property name=\"top_attach\">0</property><property name=\"wi"
  "dth\">2</property></packing></child><child><object class=\"GtkCheckButt"
  "on\" id=\"show-seconds\"><property name=\"label\" translatable=\"yes\">"
  "Display _seconds</property><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"receives_def"
  "ault\">False</property><property name=\"use_underline\">True</property>"
  "<property name=\"draw_indicator\">True</property></object><packing><pro"
  "perty name=\"left_attach\">0</property><property name=\"top_attach\">1<"
  "/property><property name=\"width\">2</property></packing></child><child"
  "><object class=\"GtkBox\" id=\"fuzziness-box\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><child><"
  "object class=\"GtkLabel\" id=\"label5\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"label\" translatable=\"yes\" comments=\"I18N: the fuzziness the *prec"
  "ision* of the fuzzy clock. Time steps of 5, 15 or parts of the day.\">F"
  "_uzziness:</property><property name=\"use_underline\">True</property><p"
  "roperty name=\"xalign\">0</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">True</property><proper"
  "ty name=\"position\">0</property></packing></child><child><object class"
  "=\"GtkScale\" id=\"hscale1\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">True</property><property name=\"hexpand\">"
  "True</property><property name=\"adjustment\">fuzziness</property><prope"
  "rty name=\"digits\">0</property><property name=\"value_pos\">right</pro"
  "perty></object><packing><property name=\"expand\">True</property><prope"
  "rty name=\"fill\">True</property><property name=\"position\">1</propert"
  "y></packing></child></object><packing><property name=\"left_attach\">0<"
  "/property><property name=\"top_attach\">6</property><property name=\"wi"
  "dth\">2</property></packing></child><child><object class=\"GtkCheckButt"
  "on\" id=\"show-inactive\"><property name=\"label\" translatable=\"yes\""
  ">Show _inactive dots</property><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">True</property><property name=\"receives"
  "_default\">False</property><property name=\"use_underline\">True</prope"
  "rty><property name=\"draw_indicator\">True</property></object><packing>"
  "<property name=\"left_attach\">0</property><property name=\"top_attach\""
  ">7</property><property name=\"width\">2</property></packing></child><ch"
  "ild><object class=\"GtkCheckButton\" id=\"show-grid\"><property name=\""
  "label\" translatable=\"yes\">Show gri_d</property><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"receives_default\">False</property><property name=\"use_unde"
  "rline\">True</property><property name=\"draw_indicator\">True</property"
  "></object><packing><property name=\"left_attach\">0</property><property"
  " name=\"top_attach\">8</property><property name=\"width\">2</property><"
  "/packing></child><child><object class=\"GtkGrid\" id=\"digital-box\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"hexpand\">True</property><property name="
  "\"row_spacing\">6</property><property name=\"column_spacing\">12</prope"
  "rty><child><object class=\"GtkLabel\" id=\"label8\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"label\" translatable=\"yes\">_Layout:</property><property"
  " name=\"use_underline\">True</property><property name=\"xalign\">0</pro"
  "perty></object><packing><property name=\"left_attach\">0</property><pro"
  "perty name=\"top_attach\">0</property></packing></child><child><object "
  "class=\"GtkGrid\" id=\"digital-date\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "row_spacing\">6</property><property name=\"column_spacing\">12</propert"
  "y><child><object class=\"GtkLabel\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"la"
  "bel\" translatable=\"yes\">Font:</property><property name=\"xalign\">0."
  "10000000149011612</property><property name=\"margin_left\">18</property"
  "></object><packing><property name=\"left_attach\">0</property><property"
  " name=\"top_attach\">1</property></packing></child><child><object class"
  "=\"GtkLabel\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"label\" translatable=\"y"
  "es\">Format:</property><property name=\"xalign\">0.10000000149011612</p"
  "roperty><property name=\"margin_left\">18</property></object><packing><"
  "property name=\"left_attach\">0</property><property name=\"top_attach\""
  ">2</property></packing></child><child><object class=\"GtkEntry\" id=\"d"
  "igital-date-format\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"hexpand\">True</pr"
  "operty><property name=\"secondary_icon_name\">help-contents</property><"
  "property name=\"primary_icon_activatable\">False</property><property na"
  "me=\"margin_left\">18</property><property name=\"secondary_icon_tooltip"
  "_text\" translatable=\"yes\">The format describes the date and time par"
  "ts to insert into the panel. For example, %Y will be substituted with t"
  "he year, %m with the month and %d with the day. Similarly, &lt;b&gt;&lt"
  ";/b&gt; tags will make the text bold. See the \"Help\" page for additio"
  "nal information.</property><property name=\"secondary_icon_tooltip_mark"
  "up\" translatable=\"yes\">The format describes the date and time parts "
  "to insert into the panel. For example, %Y will be substituted with the "
  "year, %m with the month and %d with the day. Similarly, &amp;lt;b&amp;g"
  "t;&amp;lt;/b&amp;gt; tags will make the text bold. See the &amp;quot;He"
  "lp&amp;quot; page for additional information.</property></object><packi"
  "ng><property name=\"left_attach\">0</property><property name=\"top_atta"
  "ch\">3</property><property name=\"width\">2</property></packing></child"
  "><child><object class=\"GtkComboBox\" id=\"digital-date-chooser\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"hexpand\">True</property><child><object cla"
  "ss=\"GtkCellRendererText\" id=\"cellrenderertext4\"/><attributes><attri"
  "bute name=\"text\">2</attribute></attributes></child></object><packing>"
  "<property name=\"left_attach\">1</property><property name=\"top_attach\""
  ">2</property></packing></child><child><object class=\"GtkLabel\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"label\" translatable=\"yes\">Date</property>"
  "<property name=\"use_underline\">True</property><property name=\"xalign"
  "\">0</property><attributes><attribute name=\"weight\" value=\"bold\"/><"
  "/attributes></object><packing><property name=\"left_attach\">0</propert"
  "y><property name=\"top_attach\">0</property><property name=\"width\">3<"
  "/property></packing></child><child><object class=\"GtkFontButton\" id=\""
  "digital-date-font\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">True</property><property name=\"receives_default\">"
  "True</property><property name=\"font\">Sans 12</property><property name"
  "=\"language\">en-in</property><property name=\"preview_text\"/></object"
  "><packing><property name=\"left_attach\">1</property><property name=\"t"
  "op_attach\">1</property></packing></child></object><packing><property n"
  "ame=\"left_attach\">0</property><property name=\"top_attach\">1</proper"
  "ty><property name=\"width\">2</property></packing></child><child><objec"
  "t class=\"GtkGrid\" id=\"digital-time\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"row_spacing\">6</property><property name=\"column_spacing\">12</prope"
  "rty><child><object class=\"GtkLabel\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "label\" translatable=\"yes\">Time</property><property name=\"use_underl"
  "ine\">True</property><property name=\"xalign\">0</property><attributes>"
  "<attribute name=\"weight\" value=\"bold\"/></attributes></object><packi"
  "ng><property name=\"left_attach\">0</property><property name=\"top_atta"
  "ch\">0</property><property name=\"width\">3</property></packing></child"
  "><child><object class=\"GtkLabel\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"lab"
  "el\" translatable=\"yes\">Font:</property><property name=\"xalign\">0.1"
  "0000000149011612</property><property name=\"margin_left\">18</property>"
  "</object><packing><property name=\"left_attach\">0</property><property "
  "name=\"top_attach\">1</property></packing></child><child><object class="
  "\"GtkLabel\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label\" translatable=\"yes"
  "\">Format:</property><property name=\"xalign\">0.10000000149011612</pro"
  "perty><property name=\"margin_left\">18</property></object><packing><pr"
  "operty name=\"left_attach\">0</property><property name=\"top_attach\">2"
  "</property></packing></child><child><object class=\"GtkEntry\" id=\"dig"
  "ital-time-format\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"hexpand\">True</prop"
  "erty><property name=\"margin_left\">18</property><property name=\"secon"
  "dary_icon_name\">help-contents</property><property name=\"primary_icon_"
  "activatable\">False</property><property name=\"secondary_icon_tooltip_t"
  "ext\" translatable=\"yes\">The format describes the date and time parts"
  " to insert into the panel. For example, %Y will be substituted with the"
  " year, %m with the month and %d with the day. Similarly, &lt;b&gt;&lt;/"
  "b&gt; tags will make the text bold. See the \"Help\" page for additiona"
  "l information.</property><property name=\"secondary_icon_tooltip_markup"
  "\" translatable=\"yes\">The format describes the date and time parts to"
  " insert into the panel. For example, %Y will be substituted with the ye"
  "ar, %m with the month and %d with the day. Similarly, &amp;lt;b&amp;gt;"
  "&amp;lt;/b&amp;gt; tags will make the text bold. See the &amp;quot;Help"
  "&amp;quot; page for additional information.</property></object><packing"
  "><property name=\"left_attach\">0</property><property name=\"top_attach"
  "\">3</property><property name=\"width\">2</property></packing></child><"
  "child><object class=\"GtkComboBox\" id=\"digital-time-chooser\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"hexpand\">True</property><child><object class"
  "=\"GtkCellRendererText\" id=\"cellrenderertext5\"/><attributes><attribu"
  "te name=\"text\">2</attribute></attributes></child></object><packing><p"
  "roperty name=\"left_attach\">1</property><property name=\"top_attach\">"
  "2</property></packing></child><child><object class=\"GtkFontButton\" id"
  "=\"digital-time-font\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"receives_default"
  "\">True</property><property name=\"font\">Sans 12</property><property n"
  "ame=\"language\">en-in</property><property name=\"preview_text\"/></obj"
  "ect><packing><property name=\"left_attach\">1</property><property name="
  "\"top_attach\">1</property></packing></child></object><packing><propert"
  "y name=\"left_attach\">0</property><property name=\"top_attach\">2</pro"
  "perty><property name=\"width\">2</property></packing></child><child><ob"
  "ject class=\"GtkComboBox\" id=\"digital-layout\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"hexpand\">True</property><property name=\"model\">digital-fo"
  "rmat-model</property><property name=\"active\">0</property><child><obje"
  "ct class=\"GtkCellRendererText\" id=\"cellrenderertext3\"/><attributes>"
  "<attribute name=\"text\">0</attribute></attributes></child></object><pa"
  "cking><property name=\"left_attach\">1</property><property name=\"top_a"
  "ttach\">0</property></packing></child></object><packing><property name="
  "\"left_attach\">0</property><property name=\"top_attach\">5</property><"
  "property name=\"width\">2</property></packing></child></object></child>"
  "<child type=\"label\"><object class=\"GtkLabel\" id=\"label3\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"margin_bottom\">6</property><property name=\"l"
  "abel\" translatable=\"yes\">Clock Options</property><attributes><attrib"
  "ute name=\"weight\" value=\"bold\"/></attributes></object></child></obj"
  "ect><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">3</property></packing"
  "></child></object><packing><property name=\"expand\">True</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">1</prop"
  "erty></packing></child></object></child><action-widgets><action-widget "
  "response=\"0\">close-button</action-widget><action-widget response=\"0\""
  ">help-button</action-widget></action-widgets></object></interface>"
};

static const unsigned clock_dialog_ui_length = 27531u;

