#TODO missing script to properly move the binary
[source]
git = "https://github.com/rust-diplomat/diplomat"
rev = "01bfb4bc53211e1c2a5ea58f64205c3a06727f7d"
[build]
template = "custom"
script = """
cookbook_cargo_packages diplomat
"""
