#TODO fix libgcrypt
#TODO maybe missing dependencies, see https://guix.gnu.org/manual/en/html_node/Requirements.html
[source]
tar = "https://ftpmirror.gnu.org/gnu/guix/guix-1.4.0.tar.gz"
[build]
template = "configure"
dependencies = [
    "libgcrypt",
    "sqlite3",
]
