#TODO missing script for GNU Autotools", see https://specfem2d.readthedocs.io/en/latest/02_getting_started/
[source]
git = "https://github.com/SPECFEM/specfem2d"
rev = "0bbc7858dcd0ac9c1c64a35a41c83fa7f6847205"
[build]
template = "custom"
