/* automatically generated from directorymenu-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (directorymenu_dialog_ui)
#endif
#ifdef __GNUC__
static const char directorymenu_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char directorymenu_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><requires lib=\"libxfce4ui-2\" version=\"4.12\"/"
  "><object class=\"GtkImage\" id=\"image1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"icon_name\">help-browser</property></object><object class=\"GtkImag"
  "e\" id=\"image2\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"icon_name\">window-c"
  "lose-symbolic</property></object><object class=\"XfceTitledDialog\" id="
  "\"dialog\"><property name=\"can_focus\">False</property><property name="
  "\"title\" translatable=\"yes\">Directory Menu</property><property name="
  "\"icon_name\">org.xfce.panel.directorymenu</property><property name=\"t"
  "ype_hint\">normal</property><child internal-child=\"vbox\"><object clas"
  "s=\"GtkBox\" id=\"dialog-vbox2\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"orien"
  "tation\">vertical</property><property name=\"spacing\">2</property><chi"
  "ld internal-child=\"action_area\"><object class=\"GtkButtonBox\" id=\"d"
  "ialog-action_area2\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"layout_style\">en"
  "d</property><child><object class=\"GtkButton\" id=\"close-button\"><pro"
  "perty name=\"label\" translatable=\"yes\">_Close</property><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">True</proper"
  "ty><property name=\"receives_default\">True</property><property name=\""
  "image\">image2</property><property name=\"use_underline\">True</propert"
  "y></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">False</property><property name=\"position\">0</property>"
  "</packing></child><child><object class=\"GtkButton\" id=\"help-button\""
  "><property name=\"label\" translatable=\"yes\">_Help</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"receives_default\">True</property><property nam"
  "e=\"image\">image1</property><property name=\"use_underline\">True</pro"
  "perty></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">False</property><property name=\"position\">1</prope"
  "rty><property name=\"secondary\">True</property></packing></child></obj"
  "ect><packing><property name=\"expand\">False</property><property name=\""
  "fill\">False</property><property name=\"pack_type\">end</property><prop"
  "erty name=\"position\">0</property></packing></child><child><object cla"
  "ss=\"GtkBox\" id=\"vbox1\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"border_widt"
  "h\">6</property><property name=\"orientation\">vertical</property><prop"
  "erty name=\"spacing\">6</property><child><object class=\"GtkFrame\" id="
  "\"frame3\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"label_xalign\">0</property>"
  "<property name=\"shadow_type\">none</property><child><object class=\"Gt"
  "kGrid\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"margin_left\">18</property><pr"
  "operty name=\"row_spacing\">6</property><property name=\"column_spacing"
  "\">12</property><child><object class=\"GtkFileChooserButton\" id=\"base"
  "-directory\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"hexpand\">True</property><"
  "property name=\"action\">select-folder</property><property name=\"local"
  "_only\">False</property><property name=\"title\" translatable=\"yes\">S"
  "elect A Directory</property></object><packing><property name=\"left_att"
  "ach\">1</property><property name=\"top_attach\">0</property></packing><"
  "/child><child><object class=\"GtkButton\" id=\"icon-button\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">True</prop"
  "erty><property name=\"receives_default\">True</property><property name="
  "\"halign\">start</property></object><packing><property name=\"left_atta"
  "ch\">1</property><property name=\"top_attach\">1</property></packing></"
  "child><child><object class=\"GtkLabel\" id=\"label4\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">_Icon:</property><property"
  " name=\"use_underline\">True</property><property name=\"xalign\">0</pro"
  "perty></object><packing><property name=\"left_attach\">0</property><pro"
  "perty name=\"top_attach\">1</property></packing></child><child><object "
  "class=\"GtkLabel\" id=\"label2\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"label"
  "\" translatable=\"yes\">_Base Directory:</property><property name=\"use"
  "_underline\">True</property><property name=\"xalign\">0</property></obj"
  "ect><packing><property name=\"left_attach\">0</property><property name="
  "\"top_attach\">0</property></packing></child></object></child><child ty"
  "pe=\"label\"><object class=\"GtkLabel\" id=\"label1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">Appearance</property><attr"
  "ibutes><attribute name=\"weight\" value=\"bold\"/></attributes></object"
  "></child></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">0</pro"
  "perty></packing></child><child><object class=\"GtkFrame\" id=\"frame2\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label_xalign\">0</property><property "
  "name=\"shadow_type\">none</property><child><object class=\"GtkGrid\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"margin_left\">18</property><property nam"
  "e=\"row_spacing\">6</property><property name=\"column_spacing\">12</pro"
  "perty><child><object class=\"GtkCheckButton\" id=\"new-document\"><prop"
  "erty name=\"label\" translatable=\"yes\">Show \'New Text _Document\'</p"
  "roperty><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"receives_default\">False</prope"
  "rty><property name=\"use_underline\">True</property><property name=\"ac"
  "tive\">True</property><property name=\"draw_indicator\">True</property>"
  "</object><packing><property name=\"left_attach\">0</property><property "
  "name=\"top_attach\">3</property></packing></child><child><object class="
  "\"GtkCheckButton\" id=\"new-folder\"><property name=\"label\" translata"
  "ble=\"yes\">Show \'_New Folder\'</property><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">True</property><property nam"
  "e=\"receives_default\">False</property><property name=\"use_underline\""
  ">True</property><property name=\"active\">True</property><property name"
  "=\"draw_indicator\">True</property></object><packing><property name=\"l"
  "eft_attach\">0</property><property name=\"top_attach\">2</property></pa"
  "cking></child><child><object class=\"GtkCheckButton\" id=\"open-in-term"
  "inal\"><property name=\"label\" translatable=\"yes\">Show \'Open in _Te"
  "rminal\'</property><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"receives_default\">F"
  "alse</property><property name=\"use_underline\">True</property><propert"
  "y name=\"active\">True</property><property name=\"draw_indicator\">True"
  "</property></object><packing><property name=\"left_attach\">0</property"
  "><property name=\"top_attach\">1</property></packing></child><child><ob"
  "ject class=\"GtkCheckButton\" id=\"open-folder\"><property name=\"label"
  "\" translatable=\"yes\">Show \'_Open _Folder\'</property><property name"
  "=\"visible\">True</property><property name=\"can_focus\">True</property"
  "><property name=\"receives_default\">False</property><property name=\"u"
  "se_underline\">True</property><property name=\"active\">True</property>"
  "<property name=\"draw_indicator\">True</property></object><packing><pro"
  "perty name=\"left_attach\">0</property><property name=\"top_attach\">0<"
  "/property></packing></child></object></child><child type=\"label\"><obj"
  "ect class=\"GtkLabel\" id=\"label5\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"l"
  "abel\" translatable=\"yes\">Menu</property><attributes><attribute name="
  "\"weight\" value=\"bold\"/></attributes></object></child></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">1</property></packing></child"
  "><child><object class=\"GtkFrame\" id=\"frame1\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"label_xalign\">0</property><property name=\"shadow_type\">no"
  "ne</property><child><object class=\"GtkGrid\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"margin_left\">18</property><property name=\"row_spacing\">6</pro"
  "perty><property name=\"column_spacing\">12</property><child><object cla"
  "ss=\"GtkCheckButton\" id=\"hidden-files\"><property name=\"label\" tran"
  "slatable=\"yes\">Show _hidden files</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"use_underline"
  "\">True</property><property name=\"draw_indicator\">True</property></ob"
  "ject><packing><property name=\"left_attach\">0</property><property name"
  "=\"top_attach\">1</property><property name=\"width\">2</property></pack"
  "ing></child><child><object class=\"GtkEntry\" id=\"file-pattern\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"tooltip_text\" translatable=\"yes\">Enter a "
  "list of patterns that will be used to determine which files are visible"
  " in a directory. If you specify more than one pattern here, the list it"
  "ems must be separated with semicolons (e.g. *.txt;*.doc).</property><pr"
  "operty name=\"invisible_char\">\342\200\242</property></object><packing"
  "><property name=\"left_attach\">1</property><property name=\"top_attach"
  "\">0</property></packing></child><child><object class=\"GtkLabel\" id=\""
  "label7\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label\" translatable=\"yes\">"
  "_File Pattern:</property><property name=\"use_underline\">True</propert"
  "y><property name=\"xalign\">0</property></object><packing><property nam"
  "e=\"left_attach\">0</property><property name=\"top_attach\">0</property"
  "></packing></child></object></child><child type=\"label\"><object class"
  "=\"GtkLabel\" id=\"label8\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"label\" tr"
  "anslatable=\"yes\">Filtering</property><attributes><attribute name=\"we"
  "ight\" value=\"bold\"/></attributes></object></child></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">True<"
  "/property><property name=\"position\">2</property></packing></child></o"
  "bject><packing><property name=\"expand\">False</property><property name"
  "=\"fill\">True</property><property name=\"position\">1</property></pack"
  "ing></child></object></child><action-widgets><action-widget response=\""
  "0\">close-button</action-widget><action-widget response=\"0\">help-butt"
  "on</action-widget></action-widgets></object><object class=\"GtkSizeGrou"
  "p\" id=\"sizegroup1\"/></interface>"
};

static const unsigned directorymenu_dialog_ui_length = 10845u;

