#TODO missing script for CMake, see https://github.com/ospray/OSPRay#building-and-finding-ospray
[source]
git = "https://github.com/ospray/OSPRay"
rev = "66fa8108485a8a92ff31ad2e06081bbaf391bc26"
[build]
template = "custom"
dependencies = [
    "librkcommon",
    "embree",
    "ispc",
    "onetbb",
    "openvkl",
    "open-image-denoise",
]
