#TODO compilation error
[source]
tar = "https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.0.tar.gz"
[build]
template = "configure"
dependencies = [
    "openssl1",
    "zlib",
    "libyaml",
    "libffi",
]
