/* Generated by make-exo-alias.pl. Do not edit this file. */

#ifdef HAVE_GNUC_VISIBILITY

#include <glib.h>

G_GNUC_BEGIN_IGNORE_DEPRECATIONS

#ifdef __EXO_BINDING_H__
#if 1
extern __typeof (exo_binding_new) IA__exo_binding_new __attribute((visibility("hidden")));
#define exo_binding_new IA__exo_binding_new

extern __typeof (exo_binding_new_full) IA__exo_binding_new_full __attribute((visibility("hidden")));
#define exo_binding_new_full IA__exo_binding_new_full

extern __typeof (exo_binding_new_with_negation) IA__exo_binding_new_with_negation __attribute((visibility("hidden")));
#define exo_binding_new_with_negation IA__exo_binding_new_with_negation

extern __typeof (exo_binding_unbind) IA__exo_binding_unbind __attribute((visibility("hidden")));
#define exo_binding_unbind IA__exo_binding_unbind

extern __typeof (exo_mutual_binding_new) IA__exo_mutual_binding_new __attribute((visibility("hidden")));
#define exo_mutual_binding_new IA__exo_mutual_binding_new

extern __typeof (exo_mutual_binding_new_full) IA__exo_mutual_binding_new_full __attribute((visibility("hidden")));
#define exo_mutual_binding_new_full IA__exo_mutual_binding_new_full

extern __typeof (exo_mutual_binding_new_with_negation) IA__exo_mutual_binding_new_with_negation __attribute((visibility("hidden")));
#define exo_mutual_binding_new_with_negation IA__exo_mutual_binding_new_with_negation

extern __typeof (exo_mutual_binding_unbind) IA__exo_mutual_binding_unbind __attribute((visibility("hidden")));
#define exo_mutual_binding_unbind IA__exo_mutual_binding_unbind

#endif
#endif
#ifdef __EXO_CELL_RENDERER_ICON_H__
#if 1
extern __typeof (exo_cell_renderer_icon_get_type) IA__exo_cell_renderer_icon_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define exo_cell_renderer_icon_get_type IA__exo_cell_renderer_icon_get_type

extern __typeof (exo_cell_renderer_icon_new) IA__exo_cell_renderer_icon_new __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define exo_cell_renderer_icon_new IA__exo_cell_renderer_icon_new

#endif
#endif
#ifdef __EXO_CONFIG_H__
#if 1
extern __typeof (exo_check_version) IA__exo_check_version __attribute((visibility("hidden")));
#define exo_check_version IA__exo_check_version

#endif
#endif
#ifdef __EXO_ENUM_TYPES_H__
#if 1
extern __typeof (exo_icon_view_drop_position_get_type) IA__exo_icon_view_drop_position_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define exo_icon_view_drop_position_get_type IA__exo_icon_view_drop_position_get_type

extern __typeof (exo_icon_view_layout_mode_get_type) IA__exo_icon_view_layout_mode_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define exo_icon_view_layout_mode_get_type IA__exo_icon_view_layout_mode_get_type

#endif
#endif
#ifdef __EXO_EXECUTE_H__
#if 1
extern __typeof (exo_execute_preferred_application) IA__exo_execute_preferred_application __attribute((visibility("hidden")));
#define exo_execute_preferred_application IA__exo_execute_preferred_application

extern __typeof (exo_execute_preferred_application_on_screen) IA__exo_execute_preferred_application_on_screen __attribute((visibility("hidden")));
#define exo_execute_preferred_application_on_screen IA__exo_execute_preferred_application_on_screen

extern __typeof (exo_execute_terminal_shell) IA__exo_execute_terminal_shell __attribute((visibility("hidden")));
#define exo_execute_terminal_shell IA__exo_execute_terminal_shell

extern __typeof (exo_execute_terminal_shell_on_screen) IA__exo_execute_terminal_shell_on_screen __attribute((visibility("hidden")));
#define exo_execute_terminal_shell_on_screen IA__exo_execute_terminal_shell_on_screen

#endif
#endif
#ifdef __EXO_GDK_PIXBUF_EXTENSIONS_H__
#if 1
extern __typeof (exo_gdk_pixbuf_colorize) IA__exo_gdk_pixbuf_colorize __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define exo_gdk_pixbuf_colorize IA__exo_gdk_pixbuf_colorize

extern __typeof (exo_gdk_pixbuf_frame) IA__exo_gdk_pixbuf_frame __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define exo_gdk_pixbuf_frame IA__exo_gdk_pixbuf_frame

extern __typeof (exo_gdk_pixbuf_lucent) IA__exo_gdk_pixbuf_lucent __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define exo_gdk_pixbuf_lucent IA__exo_gdk_pixbuf_lucent

extern __typeof (exo_gdk_pixbuf_spotlight) IA__exo_gdk_pixbuf_spotlight __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define exo_gdk_pixbuf_spotlight IA__exo_gdk_pixbuf_spotlight

extern __typeof (exo_gdk_pixbuf_scale_down) IA__exo_gdk_pixbuf_scale_down __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define exo_gdk_pixbuf_scale_down IA__exo_gdk_pixbuf_scale_down

extern __typeof (exo_gdk_pixbuf_scale_ratio) IA__exo_gdk_pixbuf_scale_ratio __attribute((visibility("hidden"))) G_GNUC_WARN_UNUSED_RESULT;
#define exo_gdk_pixbuf_scale_ratio IA__exo_gdk_pixbuf_scale_ratio

extern __typeof (exo_gdk_pixbuf_new_from_file_at_max_size) IA__exo_gdk_pixbuf_new_from_file_at_max_size __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define exo_gdk_pixbuf_new_from_file_at_max_size IA__exo_gdk_pixbuf_new_from_file_at_max_size

#endif
#endif
#ifdef __EXO_GOBJECT_EXTENSIONS_H__
#if 1
extern __typeof (exo_g_value_transform_negate) IA__exo_g_value_transform_negate __attribute((visibility("hidden")));
#define exo_g_value_transform_negate IA__exo_g_value_transform_negate

#endif
#endif
#ifdef __EXO_GTK_EXTENSIONS_H__
#if 1
extern __typeof (exo_gtk_object_destroy_later) IA__exo_gtk_object_destroy_later __attribute((visibility("hidden")));
#define exo_gtk_object_destroy_later IA__exo_gtk_object_destroy_later

extern __typeof (exo_gtk_file_chooser_add_thumbnail_preview) IA__exo_gtk_file_chooser_add_thumbnail_preview __attribute((visibility("hidden")));
#define exo_gtk_file_chooser_add_thumbnail_preview IA__exo_gtk_file_chooser_add_thumbnail_preview

extern __typeof (exo_gtk_url_about_dialog_hook) IA__exo_gtk_url_about_dialog_hook __attribute((visibility("hidden")));
#define exo_gtk_url_about_dialog_hook IA__exo_gtk_url_about_dialog_hook

extern __typeof (exo_gtk_dialog_get_action_area) IA__exo_gtk_dialog_get_action_area __attribute((visibility("hidden")));
#define exo_gtk_dialog_get_action_area IA__exo_gtk_dialog_get_action_area

extern __typeof (exo_gtk_dialog_add_secondary_button) IA__exo_gtk_dialog_add_secondary_button __attribute((visibility("hidden")));
#define exo_gtk_dialog_add_secondary_button IA__exo_gtk_dialog_add_secondary_button

#endif
#endif
#ifdef __EXO_ICON_CHOOSER_DIALOG_H__
#if 1
extern __typeof (exo_icon_chooser_dialog_get_type) IA__exo_icon_chooser_dialog_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define exo_icon_chooser_dialog_get_type IA__exo_icon_chooser_dialog_get_type

extern __typeof (exo_icon_chooser_dialog_new) IA__exo_icon_chooser_dialog_new __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_NULL_TERMINATED G_GNUC_WARN_UNUSED_RESULT;
#define exo_icon_chooser_dialog_new IA__exo_icon_chooser_dialog_new

extern __typeof (exo_icon_chooser_dialog_get_icon) IA__exo_icon_chooser_dialog_get_icon __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define exo_icon_chooser_dialog_get_icon IA__exo_icon_chooser_dialog_get_icon

extern __typeof (exo_icon_chooser_dialog_set_icon) IA__exo_icon_chooser_dialog_set_icon __attribute((visibility("hidden")));
#define exo_icon_chooser_dialog_set_icon IA__exo_icon_chooser_dialog_set_icon

#endif
#endif
#ifdef __EXO_ICON_VIEW_H__
#if 1
extern __typeof (exo_icon_view_get_type) IA__exo_icon_view_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define exo_icon_view_get_type IA__exo_icon_view_get_type

extern __typeof (exo_icon_view_new) IA__exo_icon_view_new __attribute((visibility("hidden")));
#define exo_icon_view_new IA__exo_icon_view_new

extern __typeof (exo_icon_view_new_with_model) IA__exo_icon_view_new_with_model __attribute((visibility("hidden")));
#define exo_icon_view_new_with_model IA__exo_icon_view_new_with_model

extern __typeof (exo_icon_view_get_model) IA__exo_icon_view_get_model __attribute((visibility("hidden")));
#define exo_icon_view_get_model IA__exo_icon_view_get_model

extern __typeof (exo_icon_view_set_model) IA__exo_icon_view_set_model __attribute((visibility("hidden")));
#define exo_icon_view_set_model IA__exo_icon_view_set_model

extern __typeof (exo_icon_view_get_orientation) IA__exo_icon_view_get_orientation __attribute((visibility("hidden")));
#define exo_icon_view_get_orientation IA__exo_icon_view_get_orientation

extern __typeof (exo_icon_view_set_orientation) IA__exo_icon_view_set_orientation __attribute((visibility("hidden")));
#define exo_icon_view_set_orientation IA__exo_icon_view_set_orientation

extern __typeof (exo_icon_view_get_columns) IA__exo_icon_view_get_columns __attribute((visibility("hidden")));
#define exo_icon_view_get_columns IA__exo_icon_view_get_columns

extern __typeof (exo_icon_view_set_columns) IA__exo_icon_view_set_columns __attribute((visibility("hidden")));
#define exo_icon_view_set_columns IA__exo_icon_view_set_columns

extern __typeof (exo_icon_view_get_item_width) IA__exo_icon_view_get_item_width __attribute((visibility("hidden")));
#define exo_icon_view_get_item_width IA__exo_icon_view_get_item_width

extern __typeof (exo_icon_view_set_item_width) IA__exo_icon_view_set_item_width __attribute((visibility("hidden")));
#define exo_icon_view_set_item_width IA__exo_icon_view_set_item_width

extern __typeof (exo_icon_view_get_spacing) IA__exo_icon_view_get_spacing __attribute((visibility("hidden")));
#define exo_icon_view_get_spacing IA__exo_icon_view_get_spacing

extern __typeof (exo_icon_view_set_spacing) IA__exo_icon_view_set_spacing __attribute((visibility("hidden")));
#define exo_icon_view_set_spacing IA__exo_icon_view_set_spacing

extern __typeof (exo_icon_view_get_row_spacing) IA__exo_icon_view_get_row_spacing __attribute((visibility("hidden")));
#define exo_icon_view_get_row_spacing IA__exo_icon_view_get_row_spacing

extern __typeof (exo_icon_view_set_row_spacing) IA__exo_icon_view_set_row_spacing __attribute((visibility("hidden")));
#define exo_icon_view_set_row_spacing IA__exo_icon_view_set_row_spacing

extern __typeof (exo_icon_view_get_column_spacing) IA__exo_icon_view_get_column_spacing __attribute((visibility("hidden")));
#define exo_icon_view_get_column_spacing IA__exo_icon_view_get_column_spacing

extern __typeof (exo_icon_view_set_column_spacing) IA__exo_icon_view_set_column_spacing __attribute((visibility("hidden")));
#define exo_icon_view_set_column_spacing IA__exo_icon_view_set_column_spacing

extern __typeof (exo_icon_view_get_margin) IA__exo_icon_view_get_margin __attribute((visibility("hidden")));
#define exo_icon_view_get_margin IA__exo_icon_view_get_margin

extern __typeof (exo_icon_view_set_margin) IA__exo_icon_view_set_margin __attribute((visibility("hidden")));
#define exo_icon_view_set_margin IA__exo_icon_view_set_margin

extern __typeof (exo_icon_view_get_selection_mode) IA__exo_icon_view_get_selection_mode __attribute((visibility("hidden")));
#define exo_icon_view_get_selection_mode IA__exo_icon_view_get_selection_mode

extern __typeof (exo_icon_view_set_selection_mode) IA__exo_icon_view_set_selection_mode __attribute((visibility("hidden")));
#define exo_icon_view_set_selection_mode IA__exo_icon_view_set_selection_mode

extern __typeof (exo_icon_view_get_single_click) IA__exo_icon_view_get_single_click __attribute((visibility("hidden")));
#define exo_icon_view_get_single_click IA__exo_icon_view_get_single_click

extern __typeof (exo_icon_view_set_single_click) IA__exo_icon_view_set_single_click __attribute((visibility("hidden")));
#define exo_icon_view_set_single_click IA__exo_icon_view_set_single_click

extern __typeof (exo_icon_view_get_single_click_timeout) IA__exo_icon_view_get_single_click_timeout __attribute((visibility("hidden")));
#define exo_icon_view_get_single_click_timeout IA__exo_icon_view_get_single_click_timeout

extern __typeof (exo_icon_view_set_single_click_timeout) IA__exo_icon_view_set_single_click_timeout __attribute((visibility("hidden")));
#define exo_icon_view_set_single_click_timeout IA__exo_icon_view_set_single_click_timeout

extern __typeof (exo_icon_view_get_layout_mode) IA__exo_icon_view_get_layout_mode __attribute((visibility("hidden")));
#define exo_icon_view_get_layout_mode IA__exo_icon_view_get_layout_mode

extern __typeof (exo_icon_view_set_layout_mode) IA__exo_icon_view_set_layout_mode __attribute((visibility("hidden")));
#define exo_icon_view_set_layout_mode IA__exo_icon_view_set_layout_mode

extern __typeof (exo_icon_view_widget_to_icon_coords) IA__exo_icon_view_widget_to_icon_coords __attribute((visibility("hidden")));
#define exo_icon_view_widget_to_icon_coords IA__exo_icon_view_widget_to_icon_coords

extern __typeof (exo_icon_view_icon_to_widget_coords) IA__exo_icon_view_icon_to_widget_coords __attribute((visibility("hidden")));
#define exo_icon_view_icon_to_widget_coords IA__exo_icon_view_icon_to_widget_coords

extern __typeof (exo_icon_view_get_path_at_pos) IA__exo_icon_view_get_path_at_pos __attribute((visibility("hidden")));
#define exo_icon_view_get_path_at_pos IA__exo_icon_view_get_path_at_pos

extern __typeof (exo_icon_view_get_item_at_pos) IA__exo_icon_view_get_item_at_pos __attribute((visibility("hidden")));
#define exo_icon_view_get_item_at_pos IA__exo_icon_view_get_item_at_pos

extern __typeof (exo_icon_view_get_visible_range) IA__exo_icon_view_get_visible_range __attribute((visibility("hidden")));
#define exo_icon_view_get_visible_range IA__exo_icon_view_get_visible_range

extern __typeof (exo_icon_view_selected_foreach) IA__exo_icon_view_selected_foreach __attribute((visibility("hidden")));
#define exo_icon_view_selected_foreach IA__exo_icon_view_selected_foreach

extern __typeof (exo_icon_view_select_path) IA__exo_icon_view_select_path __attribute((visibility("hidden")));
#define exo_icon_view_select_path IA__exo_icon_view_select_path

extern __typeof (exo_icon_view_unselect_path) IA__exo_icon_view_unselect_path __attribute((visibility("hidden")));
#define exo_icon_view_unselect_path IA__exo_icon_view_unselect_path

extern __typeof (exo_icon_view_path_is_selected) IA__exo_icon_view_path_is_selected __attribute((visibility("hidden")));
#define exo_icon_view_path_is_selected IA__exo_icon_view_path_is_selected

extern __typeof (exo_icon_view_get_item_column) IA__exo_icon_view_get_item_column __attribute((visibility("hidden")));
#define exo_icon_view_get_item_column IA__exo_icon_view_get_item_column

extern __typeof (exo_icon_view_get_item_row) IA__exo_icon_view_get_item_row __attribute((visibility("hidden")));
#define exo_icon_view_get_item_row IA__exo_icon_view_get_item_row

extern __typeof (exo_icon_view_get_selected_items) IA__exo_icon_view_get_selected_items __attribute((visibility("hidden")));
#define exo_icon_view_get_selected_items IA__exo_icon_view_get_selected_items

extern __typeof (exo_icon_view_select_all) IA__exo_icon_view_select_all __attribute((visibility("hidden")));
#define exo_icon_view_select_all IA__exo_icon_view_select_all

extern __typeof (exo_icon_view_unselect_all) IA__exo_icon_view_unselect_all __attribute((visibility("hidden")));
#define exo_icon_view_unselect_all IA__exo_icon_view_unselect_all

extern __typeof (exo_icon_view_selection_invert) IA__exo_icon_view_selection_invert __attribute((visibility("hidden")));
#define exo_icon_view_selection_invert IA__exo_icon_view_selection_invert

extern __typeof (exo_icon_view_item_activated) IA__exo_icon_view_item_activated __attribute((visibility("hidden")));
#define exo_icon_view_item_activated IA__exo_icon_view_item_activated

extern __typeof (exo_icon_view_get_cursor) IA__exo_icon_view_get_cursor __attribute((visibility("hidden")));
#define exo_icon_view_get_cursor IA__exo_icon_view_get_cursor

extern __typeof (exo_icon_view_set_cursor) IA__exo_icon_view_set_cursor __attribute((visibility("hidden")));
#define exo_icon_view_set_cursor IA__exo_icon_view_set_cursor

extern __typeof (exo_icon_view_scroll_to_path) IA__exo_icon_view_scroll_to_path __attribute((visibility("hidden")));
#define exo_icon_view_scroll_to_path IA__exo_icon_view_scroll_to_path

extern __typeof (exo_icon_view_enable_model_drag_source) IA__exo_icon_view_enable_model_drag_source __attribute((visibility("hidden")));
#define exo_icon_view_enable_model_drag_source IA__exo_icon_view_enable_model_drag_source

extern __typeof (exo_icon_view_enable_model_drag_dest) IA__exo_icon_view_enable_model_drag_dest __attribute((visibility("hidden")));
#define exo_icon_view_enable_model_drag_dest IA__exo_icon_view_enable_model_drag_dest

extern __typeof (exo_icon_view_unset_model_drag_source) IA__exo_icon_view_unset_model_drag_source __attribute((visibility("hidden")));
#define exo_icon_view_unset_model_drag_source IA__exo_icon_view_unset_model_drag_source

extern __typeof (exo_icon_view_unset_model_drag_dest) IA__exo_icon_view_unset_model_drag_dest __attribute((visibility("hidden")));
#define exo_icon_view_unset_model_drag_dest IA__exo_icon_view_unset_model_drag_dest

extern __typeof (exo_icon_view_set_reorderable) IA__exo_icon_view_set_reorderable __attribute((visibility("hidden")));
#define exo_icon_view_set_reorderable IA__exo_icon_view_set_reorderable

extern __typeof (exo_icon_view_get_reorderable) IA__exo_icon_view_get_reorderable __attribute((visibility("hidden")));
#define exo_icon_view_get_reorderable IA__exo_icon_view_get_reorderable

extern __typeof (exo_icon_view_set_drag_dest_item) IA__exo_icon_view_set_drag_dest_item __attribute((visibility("hidden")));
#define exo_icon_view_set_drag_dest_item IA__exo_icon_view_set_drag_dest_item

extern __typeof (exo_icon_view_get_drag_dest_item) IA__exo_icon_view_get_drag_dest_item __attribute((visibility("hidden")));
#define exo_icon_view_get_drag_dest_item IA__exo_icon_view_get_drag_dest_item

extern __typeof (exo_icon_view_get_dest_item_at_pos) IA__exo_icon_view_get_dest_item_at_pos __attribute((visibility("hidden")));
#define exo_icon_view_get_dest_item_at_pos IA__exo_icon_view_get_dest_item_at_pos

extern __typeof (exo_icon_view_create_drag_icon) IA__exo_icon_view_create_drag_icon __attribute((visibility("hidden")));
#define exo_icon_view_create_drag_icon IA__exo_icon_view_create_drag_icon

extern __typeof (exo_icon_view_get_enable_search) IA__exo_icon_view_get_enable_search __attribute((visibility("hidden")));
#define exo_icon_view_get_enable_search IA__exo_icon_view_get_enable_search

extern __typeof (exo_icon_view_set_enable_search) IA__exo_icon_view_set_enable_search __attribute((visibility("hidden")));
#define exo_icon_view_set_enable_search IA__exo_icon_view_set_enable_search

extern __typeof (exo_icon_view_get_search_column) IA__exo_icon_view_get_search_column __attribute((visibility("hidden")));
#define exo_icon_view_get_search_column IA__exo_icon_view_get_search_column

extern __typeof (exo_icon_view_set_search_column) IA__exo_icon_view_set_search_column __attribute((visibility("hidden")));
#define exo_icon_view_set_search_column IA__exo_icon_view_set_search_column

extern __typeof (exo_icon_view_get_search_equal_func) IA__exo_icon_view_get_search_equal_func __attribute((visibility("hidden")));
#define exo_icon_view_get_search_equal_func IA__exo_icon_view_get_search_equal_func

extern __typeof (exo_icon_view_set_search_equal_func) IA__exo_icon_view_set_search_equal_func __attribute((visibility("hidden")));
#define exo_icon_view_set_search_equal_func IA__exo_icon_view_set_search_equal_func

extern __typeof (exo_icon_view_get_search_position_func) IA__exo_icon_view_get_search_position_func __attribute((visibility("hidden")));
#define exo_icon_view_get_search_position_func IA__exo_icon_view_get_search_position_func

extern __typeof (exo_icon_view_set_search_position_func) IA__exo_icon_view_set_search_position_func __attribute((visibility("hidden")));
#define exo_icon_view_set_search_position_func IA__exo_icon_view_set_search_position_func

#endif
#endif
#ifdef __EXO_JOB_H__
#if 1
extern __typeof (exo_job_cancel) IA__exo_job_cancel __attribute((visibility("hidden")));
#define exo_job_cancel IA__exo_job_cancel

extern __typeof (exo_job_emit) IA__exo_job_emit __attribute((visibility("hidden")));
#define exo_job_emit IA__exo_job_emit

extern __typeof (exo_job_get_cancellable) IA__exo_job_get_cancellable __attribute((visibility("hidden")));
#define exo_job_get_cancellable IA__exo_job_get_cancellable

extern __typeof (exo_job_get_type) IA__exo_job_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define exo_job_get_type IA__exo_job_get_type

extern __typeof (exo_job_info_message) IA__exo_job_info_message __attribute((visibility("hidden")));
#define exo_job_info_message IA__exo_job_info_message

extern __typeof (exo_job_is_cancelled) IA__exo_job_is_cancelled __attribute((visibility("hidden")));
#define exo_job_is_cancelled IA__exo_job_is_cancelled

extern __typeof (exo_job_launch) IA__exo_job_launch __attribute((visibility("hidden")));
#define exo_job_launch IA__exo_job_launch

extern __typeof (exo_job_percent) IA__exo_job_percent __attribute((visibility("hidden")));
#define exo_job_percent IA__exo_job_percent

extern __typeof (exo_job_send_to_mainloop) IA__exo_job_send_to_mainloop __attribute((visibility("hidden")));
#define exo_job_send_to_mainloop IA__exo_job_send_to_mainloop

extern __typeof (exo_job_set_error_if_cancelled) IA__exo_job_set_error_if_cancelled __attribute((visibility("hidden")));
#define exo_job_set_error_if_cancelled IA__exo_job_set_error_if_cancelled

#endif
#endif
#ifdef __EXO_UTILS_H__
#if 1
extern __typeof (exo_noop) IA__exo_noop __attribute((visibility("hidden")));
#define exo_noop IA__exo_noop

extern __typeof (exo_noop_one) IA__exo_noop_one __attribute((visibility("hidden"))) G_GNUC_PURE;
#define exo_noop_one IA__exo_noop_one

extern __typeof (exo_noop_zero) IA__exo_noop_zero __attribute((visibility("hidden"))) G_GNUC_PURE;
#define exo_noop_zero IA__exo_noop_zero

extern __typeof (exo_noop_null) IA__exo_noop_null __attribute((visibility("hidden"))) G_GNUC_PURE;
#define exo_noop_null IA__exo_noop_null

extern __typeof (exo_noop_true) IA__exo_noop_true __attribute((visibility("hidden"))) G_GNUC_PURE;
#define exo_noop_true IA__exo_noop_true

extern __typeof (exo_noop_false) IA__exo_noop_false __attribute((visibility("hidden"))) G_GNUC_PURE;
#define exo_noop_false IA__exo_noop_false

#endif
#endif
#ifdef __EXO_SIMPLE_JOB_H__
#if 1
extern __typeof (exo_simple_job_get_type) IA__exo_simple_job_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define exo_simple_job_get_type IA__exo_simple_job_get_type

extern __typeof (exo_simple_job_launch) IA__exo_simple_job_launch __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define exo_simple_job_launch IA__exo_simple_job_launch

#endif
#endif
#ifdef __EXO_STRING_H__
#if 1
extern __typeof (exo_str_elide_underscores) IA__exo_str_elide_underscores __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define exo_str_elide_underscores IA__exo_str_elide_underscores

extern __typeof (exo_str_is_equal) IA__exo_str_is_equal __attribute((visibility("hidden")));
#define exo_str_is_equal IA__exo_str_is_equal

extern __typeof (exo_str_is_flag) IA__exo_str_is_flag __attribute((visibility("hidden")));
#define exo_str_is_flag IA__exo_str_is_flag

extern __typeof (exo_str_replace) IA__exo_str_replace __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define exo_str_replace IA__exo_str_replace

extern __typeof (exo_strdup_strftime) IA__exo_strdup_strftime __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define exo_strdup_strftime IA__exo_strdup_strftime

extern __typeof (exo_strndupv) IA__exo_strndupv __attribute((visibility("hidden"))) G_GNUC_MALLOC G_GNUC_WARN_UNUSED_RESULT;
#define exo_strndupv IA__exo_strndupv

extern __typeof (exo_str_looks_like_an_uri) IA__exo_str_looks_like_an_uri __attribute((visibility("hidden")));
#define exo_str_looks_like_an_uri IA__exo_str_looks_like_an_uri

#endif
#endif
#ifdef __EXO_TREE_VIEW_H__
#if 1
extern __typeof (exo_tree_view_get_type) IA__exo_tree_view_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define exo_tree_view_get_type IA__exo_tree_view_get_type

extern __typeof (exo_tree_view_new) IA__exo_tree_view_new __attribute((visibility("hidden"))) G_GNUC_MALLOC;
#define exo_tree_view_new IA__exo_tree_view_new

extern __typeof (exo_tree_view_get_single_click) IA__exo_tree_view_get_single_click __attribute((visibility("hidden")));
#define exo_tree_view_get_single_click IA__exo_tree_view_get_single_click

extern __typeof (exo_tree_view_set_single_click) IA__exo_tree_view_set_single_click __attribute((visibility("hidden")));
#define exo_tree_view_set_single_click IA__exo_tree_view_set_single_click

extern __typeof (exo_tree_view_get_single_click_timeout) IA__exo_tree_view_get_single_click_timeout __attribute((visibility("hidden")));
#define exo_tree_view_get_single_click_timeout IA__exo_tree_view_get_single_click_timeout

extern __typeof (exo_tree_view_set_single_click_timeout) IA__exo_tree_view_set_single_click_timeout __attribute((visibility("hidden")));
#define exo_tree_view_set_single_click_timeout IA__exo_tree_view_set_single_click_timeout

#endif
#endif

G_GNUC_END_IGNORE_DEPRECATIONS

#endif /* HAVE_GNUC_VISIBILITY */
