
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __EXO_ENUM_TYPES_H__
#define __EXO_ENUM_TYPES_H__
#include <libxfce4util/libxfce4util.h>
G_BEGIN_DECLS
/* enumerations from "exo-icon-view.h" */
GType exo_icon_view_drop_position_get_type (void) G_GNUC_CONST;
#define EXO_TYPE_ICON_VIEW_DROP_POSITION (exo_icon_view_drop_position_get_type())
GType exo_icon_view_layout_mode_get_type (void) G_GNUC_CONST;
#define EXO_TYPE_ICON_VIEW_LAYOUT_MODE (exo_icon_view_layout_mode_get_type())
G_END_DECLS

#endif /* !__EXO_ENUM_TYPES_H__ */

/* Generated data ends here */

