/* Generated by make-exo-alias.pl. Do not edit this file. */

#ifdef HAVE_GNUC_VISIBILITY

#include <glib.h>

G_GNUC_BEGIN_IGNORE_DEPRECATIONS

#if 1
#ifdef __EXO_BINDING_C__
#undef exo_binding_new 
extern __typeof (exo_binding_new) exo_binding_new __attribute((alias("IA__exo_binding_new"), visibility("default")));

#undef exo_binding_new_full 
extern __typeof (exo_binding_new_full) exo_binding_new_full __attribute((alias("IA__exo_binding_new_full"), visibility("default")));

#undef exo_binding_new_with_negation 
extern __typeof (exo_binding_new_with_negation) exo_binding_new_with_negation __attribute((alias("IA__exo_binding_new_with_negation"), visibility("default")));

#undef exo_binding_unbind 
extern __typeof (exo_binding_unbind) exo_binding_unbind __attribute((alias("IA__exo_binding_unbind"), visibility("default")));

#undef exo_mutual_binding_new 
extern __typeof (exo_mutual_binding_new) exo_mutual_binding_new __attribute((alias("IA__exo_mutual_binding_new"), visibility("default")));

#undef exo_mutual_binding_new_full 
extern __typeof (exo_mutual_binding_new_full) exo_mutual_binding_new_full __attribute((alias("IA__exo_mutual_binding_new_full"), visibility("default")));

#undef exo_mutual_binding_new_with_negation 
extern __typeof (exo_mutual_binding_new_with_negation) exo_mutual_binding_new_with_negation __attribute((alias("IA__exo_mutual_binding_new_with_negation"), visibility("default")));

#undef exo_mutual_binding_unbind 
extern __typeof (exo_mutual_binding_unbind) exo_mutual_binding_unbind __attribute((alias("IA__exo_mutual_binding_unbind"), visibility("default")));

#endif
#endif
#if 1
#ifdef __EXO_CELL_RENDERER_ICON_C__
#undef exo_cell_renderer_icon_get_type 
extern __typeof (exo_cell_renderer_icon_get_type) exo_cell_renderer_icon_get_type __attribute((alias("IA__exo_cell_renderer_icon_get_type"), visibility("default")));

#undef exo_cell_renderer_icon_new 
extern __typeof (exo_cell_renderer_icon_new) exo_cell_renderer_icon_new __attribute((alias("IA__exo_cell_renderer_icon_new"), visibility("default")));

#endif
#endif
#if 1
#ifdef __EXO_CONFIG_C__
#undef exo_check_version 
extern __typeof (exo_check_version) exo_check_version __attribute((alias("IA__exo_check_version"), visibility("default")));

#endif
#endif
#if 1
#ifdef __EXO_ENUM_TYPES_C__
#undef exo_icon_view_drop_position_get_type 
extern __typeof (exo_icon_view_drop_position_get_type) exo_icon_view_drop_position_get_type __attribute((alias("IA__exo_icon_view_drop_position_get_type"), visibility("default")));

#undef exo_icon_view_layout_mode_get_type 
extern __typeof (exo_icon_view_layout_mode_get_type) exo_icon_view_layout_mode_get_type __attribute((alias("IA__exo_icon_view_layout_mode_get_type"), visibility("default")));

#endif
#endif
#if 1
#ifdef __EXO_EXECUTE_C__
#undef exo_execute_preferred_application 
extern __typeof (exo_execute_preferred_application) exo_execute_preferred_application __attribute((alias("IA__exo_execute_preferred_application"), visibility("default")));

#undef exo_execute_preferred_application_on_screen 
extern __typeof (exo_execute_preferred_application_on_screen) exo_execute_preferred_application_on_screen __attribute((alias("IA__exo_execute_preferred_application_on_screen"), visibility("default")));

#undef exo_execute_terminal_shell 
extern __typeof (exo_execute_terminal_shell) exo_execute_terminal_shell __attribute((alias("IA__exo_execute_terminal_shell"), visibility("default")));

#undef exo_execute_terminal_shell_on_screen 
extern __typeof (exo_execute_terminal_shell_on_screen) exo_execute_terminal_shell_on_screen __attribute((alias("IA__exo_execute_terminal_shell_on_screen"), visibility("default")));

#endif
#endif
#if 1
#ifdef __EXO_GDK_PIXBUF_EXTENSIONS_C__
#undef exo_gdk_pixbuf_colorize 
extern __typeof (exo_gdk_pixbuf_colorize) exo_gdk_pixbuf_colorize __attribute((alias("IA__exo_gdk_pixbuf_colorize"), visibility("default")));

#undef exo_gdk_pixbuf_frame 
extern __typeof (exo_gdk_pixbuf_frame) exo_gdk_pixbuf_frame __attribute((alias("IA__exo_gdk_pixbuf_frame"), visibility("default")));

#undef exo_gdk_pixbuf_lucent 
extern __typeof (exo_gdk_pixbuf_lucent) exo_gdk_pixbuf_lucent __attribute((alias("IA__exo_gdk_pixbuf_lucent"), visibility("default")));

#undef exo_gdk_pixbuf_spotlight 
extern __typeof (exo_gdk_pixbuf_spotlight) exo_gdk_pixbuf_spotlight __attribute((alias("IA__exo_gdk_pixbuf_spotlight"), visibility("default")));

#undef exo_gdk_pixbuf_scale_down 
extern __typeof (exo_gdk_pixbuf_scale_down) exo_gdk_pixbuf_scale_down __attribute((alias("IA__exo_gdk_pixbuf_scale_down"), visibility("default")));

#undef exo_gdk_pixbuf_scale_ratio 
extern __typeof (exo_gdk_pixbuf_scale_ratio) exo_gdk_pixbuf_scale_ratio __attribute((alias("IA__exo_gdk_pixbuf_scale_ratio"), visibility("default")));

#undef exo_gdk_pixbuf_new_from_file_at_max_size 
extern __typeof (exo_gdk_pixbuf_new_from_file_at_max_size) exo_gdk_pixbuf_new_from_file_at_max_size __attribute((alias("IA__exo_gdk_pixbuf_new_from_file_at_max_size"), visibility("default")));

#endif
#endif
#if 1
#ifdef __EXO_GOBJECT_EXTENSIONS_C__
#undef exo_g_value_transform_negate 
extern __typeof (exo_g_value_transform_negate) exo_g_value_transform_negate __attribute((alias("IA__exo_g_value_transform_negate"), visibility("default")));

#endif
#endif
#if 1
#ifdef __EXO_GTK_EXTENSIONS_C__
#undef exo_gtk_object_destroy_later 
extern __typeof (exo_gtk_object_destroy_later) exo_gtk_object_destroy_later __attribute((alias("IA__exo_gtk_object_destroy_later"), visibility("default")));

#undef exo_gtk_file_chooser_add_thumbnail_preview 
extern __typeof (exo_gtk_file_chooser_add_thumbnail_preview) exo_gtk_file_chooser_add_thumbnail_preview __attribute((alias("IA__exo_gtk_file_chooser_add_thumbnail_preview"), visibility("default")));

#undef exo_gtk_url_about_dialog_hook 
extern __typeof (exo_gtk_url_about_dialog_hook) exo_gtk_url_about_dialog_hook __attribute((alias("IA__exo_gtk_url_about_dialog_hook"), visibility("default")));

#undef exo_gtk_dialog_get_action_area 
extern __typeof (exo_gtk_dialog_get_action_area) exo_gtk_dialog_get_action_area __attribute((alias("IA__exo_gtk_dialog_get_action_area"), visibility("default")));

#undef exo_gtk_dialog_add_secondary_button 
extern __typeof (exo_gtk_dialog_add_secondary_button) exo_gtk_dialog_add_secondary_button __attribute((alias("IA__exo_gtk_dialog_add_secondary_button"), visibility("default")));

#endif
#endif
#if 1
#ifdef __EXO_ICON_CHOOSER_DIALOG_C__
#undef exo_icon_chooser_dialog_get_type 
extern __typeof (exo_icon_chooser_dialog_get_type) exo_icon_chooser_dialog_get_type __attribute((alias("IA__exo_icon_chooser_dialog_get_type"), visibility("default")));

#undef exo_icon_chooser_dialog_new 
extern __typeof (exo_icon_chooser_dialog_new) exo_icon_chooser_dialog_new __attribute((alias("IA__exo_icon_chooser_dialog_new"), visibility("default")));

#undef exo_icon_chooser_dialog_get_icon 
extern __typeof (exo_icon_chooser_dialog_get_icon) exo_icon_chooser_dialog_get_icon __attribute((alias("IA__exo_icon_chooser_dialog_get_icon"), visibility("default")));

#undef exo_icon_chooser_dialog_set_icon 
extern __typeof (exo_icon_chooser_dialog_set_icon) exo_icon_chooser_dialog_set_icon __attribute((alias("IA__exo_icon_chooser_dialog_set_icon"), visibility("default")));

#endif
#endif
#if 1
#ifdef __EXO_ICON_VIEW_C__
#undef exo_icon_view_get_type 
extern __typeof (exo_icon_view_get_type) exo_icon_view_get_type __attribute((alias("IA__exo_icon_view_get_type"), visibility("default")));

#undef exo_icon_view_new 
extern __typeof (exo_icon_view_new) exo_icon_view_new __attribute((alias("IA__exo_icon_view_new"), visibility("default")));

#undef exo_icon_view_new_with_model 
extern __typeof (exo_icon_view_new_with_model) exo_icon_view_new_with_model __attribute((alias("IA__exo_icon_view_new_with_model"), visibility("default")));

#undef exo_icon_view_get_model 
extern __typeof (exo_icon_view_get_model) exo_icon_view_get_model __attribute((alias("IA__exo_icon_view_get_model"), visibility("default")));

#undef exo_icon_view_set_model 
extern __typeof (exo_icon_view_set_model) exo_icon_view_set_model __attribute((alias("IA__exo_icon_view_set_model"), visibility("default")));

#undef exo_icon_view_get_orientation 
extern __typeof (exo_icon_view_get_orientation) exo_icon_view_get_orientation __attribute((alias("IA__exo_icon_view_get_orientation"), visibility("default")));

#undef exo_icon_view_set_orientation 
extern __typeof (exo_icon_view_set_orientation) exo_icon_view_set_orientation __attribute((alias("IA__exo_icon_view_set_orientation"), visibility("default")));

#undef exo_icon_view_get_columns 
extern __typeof (exo_icon_view_get_columns) exo_icon_view_get_columns __attribute((alias("IA__exo_icon_view_get_columns"), visibility("default")));

#undef exo_icon_view_set_columns 
extern __typeof (exo_icon_view_set_columns) exo_icon_view_set_columns __attribute((alias("IA__exo_icon_view_set_columns"), visibility("default")));

#undef exo_icon_view_get_item_width 
extern __typeof (exo_icon_view_get_item_width) exo_icon_view_get_item_width __attribute((alias("IA__exo_icon_view_get_item_width"), visibility("default")));

#undef exo_icon_view_set_item_width 
extern __typeof (exo_icon_view_set_item_width) exo_icon_view_set_item_width __attribute((alias("IA__exo_icon_view_set_item_width"), visibility("default")));

#undef exo_icon_view_get_spacing 
extern __typeof (exo_icon_view_get_spacing) exo_icon_view_get_spacing __attribute((alias("IA__exo_icon_view_get_spacing"), visibility("default")));

#undef exo_icon_view_set_spacing 
extern __typeof (exo_icon_view_set_spacing) exo_icon_view_set_spacing __attribute((alias("IA__exo_icon_view_set_spacing"), visibility("default")));

#undef exo_icon_view_get_row_spacing 
extern __typeof (exo_icon_view_get_row_spacing) exo_icon_view_get_row_spacing __attribute((alias("IA__exo_icon_view_get_row_spacing"), visibility("default")));

#undef exo_icon_view_set_row_spacing 
extern __typeof (exo_icon_view_set_row_spacing) exo_icon_view_set_row_spacing __attribute((alias("IA__exo_icon_view_set_row_spacing"), visibility("default")));

#undef exo_icon_view_get_column_spacing 
extern __typeof (exo_icon_view_get_column_spacing) exo_icon_view_get_column_spacing __attribute((alias("IA__exo_icon_view_get_column_spacing"), visibility("default")));

#undef exo_icon_view_set_column_spacing 
extern __typeof (exo_icon_view_set_column_spacing) exo_icon_view_set_column_spacing __attribute((alias("IA__exo_icon_view_set_column_spacing"), visibility("default")));

#undef exo_icon_view_get_margin 
extern __typeof (exo_icon_view_get_margin) exo_icon_view_get_margin __attribute((alias("IA__exo_icon_view_get_margin"), visibility("default")));

#undef exo_icon_view_set_margin 
extern __typeof (exo_icon_view_set_margin) exo_icon_view_set_margin __attribute((alias("IA__exo_icon_view_set_margin"), visibility("default")));

#undef exo_icon_view_get_selection_mode 
extern __typeof (exo_icon_view_get_selection_mode) exo_icon_view_get_selection_mode __attribute((alias("IA__exo_icon_view_get_selection_mode"), visibility("default")));

#undef exo_icon_view_set_selection_mode 
extern __typeof (exo_icon_view_set_selection_mode) exo_icon_view_set_selection_mode __attribute((alias("IA__exo_icon_view_set_selection_mode"), visibility("default")));

#undef exo_icon_view_get_single_click 
extern __typeof (exo_icon_view_get_single_click) exo_icon_view_get_single_click __attribute((alias("IA__exo_icon_view_get_single_click"), visibility("default")));

#undef exo_icon_view_set_single_click 
extern __typeof (exo_icon_view_set_single_click) exo_icon_view_set_single_click __attribute((alias("IA__exo_icon_view_set_single_click"), visibility("default")));

#undef exo_icon_view_get_single_click_timeout 
extern __typeof (exo_icon_view_get_single_click_timeout) exo_icon_view_get_single_click_timeout __attribute((alias("IA__exo_icon_view_get_single_click_timeout"), visibility("default")));

#undef exo_icon_view_set_single_click_timeout 
extern __typeof (exo_icon_view_set_single_click_timeout) exo_icon_view_set_single_click_timeout __attribute((alias("IA__exo_icon_view_set_single_click_timeout"), visibility("default")));

#undef exo_icon_view_get_layout_mode 
extern __typeof (exo_icon_view_get_layout_mode) exo_icon_view_get_layout_mode __attribute((alias("IA__exo_icon_view_get_layout_mode"), visibility("default")));

#undef exo_icon_view_set_layout_mode 
extern __typeof (exo_icon_view_set_layout_mode) exo_icon_view_set_layout_mode __attribute((alias("IA__exo_icon_view_set_layout_mode"), visibility("default")));

#undef exo_icon_view_widget_to_icon_coords 
extern __typeof (exo_icon_view_widget_to_icon_coords) exo_icon_view_widget_to_icon_coords __attribute((alias("IA__exo_icon_view_widget_to_icon_coords"), visibility("default")));

#undef exo_icon_view_icon_to_widget_coords 
extern __typeof (exo_icon_view_icon_to_widget_coords) exo_icon_view_icon_to_widget_coords __attribute((alias("IA__exo_icon_view_icon_to_widget_coords"), visibility("default")));

#undef exo_icon_view_get_path_at_pos 
extern __typeof (exo_icon_view_get_path_at_pos) exo_icon_view_get_path_at_pos __attribute((alias("IA__exo_icon_view_get_path_at_pos"), visibility("default")));

#undef exo_icon_view_get_item_at_pos 
extern __typeof (exo_icon_view_get_item_at_pos) exo_icon_view_get_item_at_pos __attribute((alias("IA__exo_icon_view_get_item_at_pos"), visibility("default")));

#undef exo_icon_view_get_visible_range 
extern __typeof (exo_icon_view_get_visible_range) exo_icon_view_get_visible_range __attribute((alias("IA__exo_icon_view_get_visible_range"), visibility("default")));

#undef exo_icon_view_selected_foreach 
extern __typeof (exo_icon_view_selected_foreach) exo_icon_view_selected_foreach __attribute((alias("IA__exo_icon_view_selected_foreach"), visibility("default")));

#undef exo_icon_view_select_path 
extern __typeof (exo_icon_view_select_path) exo_icon_view_select_path __attribute((alias("IA__exo_icon_view_select_path"), visibility("default")));

#undef exo_icon_view_unselect_path 
extern __typeof (exo_icon_view_unselect_path) exo_icon_view_unselect_path __attribute((alias("IA__exo_icon_view_unselect_path"), visibility("default")));

#undef exo_icon_view_path_is_selected 
extern __typeof (exo_icon_view_path_is_selected) exo_icon_view_path_is_selected __attribute((alias("IA__exo_icon_view_path_is_selected"), visibility("default")));

#undef exo_icon_view_get_item_column 
extern __typeof (exo_icon_view_get_item_column) exo_icon_view_get_item_column __attribute((alias("IA__exo_icon_view_get_item_column"), visibility("default")));

#undef exo_icon_view_get_item_row 
extern __typeof (exo_icon_view_get_item_row) exo_icon_view_get_item_row __attribute((alias("IA__exo_icon_view_get_item_row"), visibility("default")));

#undef exo_icon_view_get_selected_items 
extern __typeof (exo_icon_view_get_selected_items) exo_icon_view_get_selected_items __attribute((alias("IA__exo_icon_view_get_selected_items"), visibility("default")));

#undef exo_icon_view_select_all 
extern __typeof (exo_icon_view_select_all) exo_icon_view_select_all __attribute((alias("IA__exo_icon_view_select_all"), visibility("default")));

#undef exo_icon_view_unselect_all 
extern __typeof (exo_icon_view_unselect_all) exo_icon_view_unselect_all __attribute((alias("IA__exo_icon_view_unselect_all"), visibility("default")));

#undef exo_icon_view_selection_invert 
extern __typeof (exo_icon_view_selection_invert) exo_icon_view_selection_invert __attribute((alias("IA__exo_icon_view_selection_invert"), visibility("default")));

#undef exo_icon_view_item_activated 
extern __typeof (exo_icon_view_item_activated) exo_icon_view_item_activated __attribute((alias("IA__exo_icon_view_item_activated"), visibility("default")));

#undef exo_icon_view_get_cursor 
extern __typeof (exo_icon_view_get_cursor) exo_icon_view_get_cursor __attribute((alias("IA__exo_icon_view_get_cursor"), visibility("default")));

#undef exo_icon_view_set_cursor 
extern __typeof (exo_icon_view_set_cursor) exo_icon_view_set_cursor __attribute((alias("IA__exo_icon_view_set_cursor"), visibility("default")));

#undef exo_icon_view_scroll_to_path 
extern __typeof (exo_icon_view_scroll_to_path) exo_icon_view_scroll_to_path __attribute((alias("IA__exo_icon_view_scroll_to_path"), visibility("default")));

#undef exo_icon_view_enable_model_drag_source 
extern __typeof (exo_icon_view_enable_model_drag_source) exo_icon_view_enable_model_drag_source __attribute((alias("IA__exo_icon_view_enable_model_drag_source"), visibility("default")));

#undef exo_icon_view_enable_model_drag_dest 
extern __typeof (exo_icon_view_enable_model_drag_dest) exo_icon_view_enable_model_drag_dest __attribute((alias("IA__exo_icon_view_enable_model_drag_dest"), visibility("default")));

#undef exo_icon_view_unset_model_drag_source 
extern __typeof (exo_icon_view_unset_model_drag_source) exo_icon_view_unset_model_drag_source __attribute((alias("IA__exo_icon_view_unset_model_drag_source"), visibility("default")));

#undef exo_icon_view_unset_model_drag_dest 
extern __typeof (exo_icon_view_unset_model_drag_dest) exo_icon_view_unset_model_drag_dest __attribute((alias("IA__exo_icon_view_unset_model_drag_dest"), visibility("default")));

#undef exo_icon_view_set_reorderable 
extern __typeof (exo_icon_view_set_reorderable) exo_icon_view_set_reorderable __attribute((alias("IA__exo_icon_view_set_reorderable"), visibility("default")));

#undef exo_icon_view_get_reorderable 
extern __typeof (exo_icon_view_get_reorderable) exo_icon_view_get_reorderable __attribute((alias("IA__exo_icon_view_get_reorderable"), visibility("default")));

#undef exo_icon_view_set_drag_dest_item 
extern __typeof (exo_icon_view_set_drag_dest_item) exo_icon_view_set_drag_dest_item __attribute((alias("IA__exo_icon_view_set_drag_dest_item"), visibility("default")));

#undef exo_icon_view_get_drag_dest_item 
extern __typeof (exo_icon_view_get_drag_dest_item) exo_icon_view_get_drag_dest_item __attribute((alias("IA__exo_icon_view_get_drag_dest_item"), visibility("default")));

#undef exo_icon_view_get_dest_item_at_pos 
extern __typeof (exo_icon_view_get_dest_item_at_pos) exo_icon_view_get_dest_item_at_pos __attribute((alias("IA__exo_icon_view_get_dest_item_at_pos"), visibility("default")));

#undef exo_icon_view_create_drag_icon 
extern __typeof (exo_icon_view_create_drag_icon) exo_icon_view_create_drag_icon __attribute((alias("IA__exo_icon_view_create_drag_icon"), visibility("default")));

#undef exo_icon_view_get_enable_search 
extern __typeof (exo_icon_view_get_enable_search) exo_icon_view_get_enable_search __attribute((alias("IA__exo_icon_view_get_enable_search"), visibility("default")));

#undef exo_icon_view_set_enable_search 
extern __typeof (exo_icon_view_set_enable_search) exo_icon_view_set_enable_search __attribute((alias("IA__exo_icon_view_set_enable_search"), visibility("default")));

#undef exo_icon_view_get_search_column 
extern __typeof (exo_icon_view_get_search_column) exo_icon_view_get_search_column __attribute((alias("IA__exo_icon_view_get_search_column"), visibility("default")));

#undef exo_icon_view_set_search_column 
extern __typeof (exo_icon_view_set_search_column) exo_icon_view_set_search_column __attribute((alias("IA__exo_icon_view_set_search_column"), visibility("default")));

#undef exo_icon_view_get_search_equal_func 
extern __typeof (exo_icon_view_get_search_equal_func) exo_icon_view_get_search_equal_func __attribute((alias("IA__exo_icon_view_get_search_equal_func"), visibility("default")));

#undef exo_icon_view_set_search_equal_func 
extern __typeof (exo_icon_view_set_search_equal_func) exo_icon_view_set_search_equal_func __attribute((alias("IA__exo_icon_view_set_search_equal_func"), visibility("default")));

#undef exo_icon_view_get_search_position_func 
extern __typeof (exo_icon_view_get_search_position_func) exo_icon_view_get_search_position_func __attribute((alias("IA__exo_icon_view_get_search_position_func"), visibility("default")));

#undef exo_icon_view_set_search_position_func 
extern __typeof (exo_icon_view_set_search_position_func) exo_icon_view_set_search_position_func __attribute((alias("IA__exo_icon_view_set_search_position_func"), visibility("default")));

#endif
#endif
#if 1
#ifdef __EXO_JOB_C__
#undef exo_job_cancel 
extern __typeof (exo_job_cancel) exo_job_cancel __attribute((alias("IA__exo_job_cancel"), visibility("default")));

#undef exo_job_emit 
extern __typeof (exo_job_emit) exo_job_emit __attribute((alias("IA__exo_job_emit"), visibility("default")));

#undef exo_job_get_cancellable 
extern __typeof (exo_job_get_cancellable) exo_job_get_cancellable __attribute((alias("IA__exo_job_get_cancellable"), visibility("default")));

#undef exo_job_get_type 
extern __typeof (exo_job_get_type) exo_job_get_type __attribute((alias("IA__exo_job_get_type"), visibility("default")));

#undef exo_job_info_message 
extern __typeof (exo_job_info_message) exo_job_info_message __attribute((alias("IA__exo_job_info_message"), visibility("default")));

#undef exo_job_is_cancelled 
extern __typeof (exo_job_is_cancelled) exo_job_is_cancelled __attribute((alias("IA__exo_job_is_cancelled"), visibility("default")));

#undef exo_job_launch 
extern __typeof (exo_job_launch) exo_job_launch __attribute((alias("IA__exo_job_launch"), visibility("default")));

#undef exo_job_percent 
extern __typeof (exo_job_percent) exo_job_percent __attribute((alias("IA__exo_job_percent"), visibility("default")));

#undef exo_job_send_to_mainloop 
extern __typeof (exo_job_send_to_mainloop) exo_job_send_to_mainloop __attribute((alias("IA__exo_job_send_to_mainloop"), visibility("default")));

#undef exo_job_set_error_if_cancelled 
extern __typeof (exo_job_set_error_if_cancelled) exo_job_set_error_if_cancelled __attribute((alias("IA__exo_job_set_error_if_cancelled"), visibility("default")));

#endif
#endif
#if 1
#ifdef __EXO_UTILS_C__
#undef exo_noop 
extern __typeof (exo_noop) exo_noop __attribute((alias("IA__exo_noop"), visibility("default")));

#undef exo_noop_one 
extern __typeof (exo_noop_one) exo_noop_one __attribute((alias("IA__exo_noop_one"), visibility("default")));

#undef exo_noop_zero 
extern __typeof (exo_noop_zero) exo_noop_zero __attribute((alias("IA__exo_noop_zero"), visibility("default")));

#undef exo_noop_null 
extern __typeof (exo_noop_null) exo_noop_null __attribute((alias("IA__exo_noop_null"), visibility("default")));

#undef exo_noop_true 
extern __typeof (exo_noop_true) exo_noop_true __attribute((alias("IA__exo_noop_true"), visibility("default")));

#undef exo_noop_false 
extern __typeof (exo_noop_false) exo_noop_false __attribute((alias("IA__exo_noop_false"), visibility("default")));

#endif
#endif
#if 1
#ifdef __EXO_SIMPLE_JOB_C__
#undef exo_simple_job_get_type 
extern __typeof (exo_simple_job_get_type) exo_simple_job_get_type __attribute((alias("IA__exo_simple_job_get_type"), visibility("default")));

#undef exo_simple_job_launch 
extern __typeof (exo_simple_job_launch) exo_simple_job_launch __attribute((alias("IA__exo_simple_job_launch"), visibility("default")));

#endif
#endif
#if 1
#ifdef __EXO_STRING_C__
#undef exo_str_elide_underscores 
extern __typeof (exo_str_elide_underscores) exo_str_elide_underscores __attribute((alias("IA__exo_str_elide_underscores"), visibility("default")));

#undef exo_str_is_equal 
extern __typeof (exo_str_is_equal) exo_str_is_equal __attribute((alias("IA__exo_str_is_equal"), visibility("default")));

#undef exo_str_is_flag 
extern __typeof (exo_str_is_flag) exo_str_is_flag __attribute((alias("IA__exo_str_is_flag"), visibility("default")));

#undef exo_str_replace 
extern __typeof (exo_str_replace) exo_str_replace __attribute((alias("IA__exo_str_replace"), visibility("default")));

#undef exo_strdup_strftime 
extern __typeof (exo_strdup_strftime) exo_strdup_strftime __attribute((alias("IA__exo_strdup_strftime"), visibility("default")));

#undef exo_strndupv 
extern __typeof (exo_strndupv) exo_strndupv __attribute((alias("IA__exo_strndupv"), visibility("default")));

#undef exo_str_looks_like_an_uri 
extern __typeof (exo_str_looks_like_an_uri) exo_str_looks_like_an_uri __attribute((alias("IA__exo_str_looks_like_an_uri"), visibility("default")));

#endif
#endif
#if 1
#ifdef __EXO_TREE_VIEW_C__
#undef exo_tree_view_get_type 
extern __typeof (exo_tree_view_get_type) exo_tree_view_get_type __attribute((alias("IA__exo_tree_view_get_type"), visibility("default")));

#undef exo_tree_view_new 
extern __typeof (exo_tree_view_new) exo_tree_view_new __attribute((alias("IA__exo_tree_view_new"), visibility("default")));

#undef exo_tree_view_get_single_click 
extern __typeof (exo_tree_view_get_single_click) exo_tree_view_get_single_click __attribute((alias("IA__exo_tree_view_get_single_click"), visibility("default")));

#undef exo_tree_view_set_single_click 
extern __typeof (exo_tree_view_set_single_click) exo_tree_view_set_single_click __attribute((alias("IA__exo_tree_view_set_single_click"), visibility("default")));

#undef exo_tree_view_get_single_click_timeout 
extern __typeof (exo_tree_view_get_single_click_timeout) exo_tree_view_get_single_click_timeout __attribute((alias("IA__exo_tree_view_get_single_click_timeout"), visibility("default")));

#undef exo_tree_view_set_single_click_timeout 
extern __typeof (exo_tree_view_set_single_click_timeout) exo_tree_view_set_single_click_timeout __attribute((alias("IA__exo_tree_view_set_single_click_timeout"), visibility("default")));

#endif
#endif

G_GNUC_END_IGNORE_DEPRECATIONS

#endif /* HAVE_GNUC_VISIBILITY */
