#TODO missing script for Go, see https://github.com/kahing/goofys/#installation
[source]
git = "https://github.com/kahing/goofys"
rev = "45b8d78375af1b24604439d2e60c567654bcdf88"
[build]
template = "custom"
