#TODO missing script for "make", see https://github.com/zerotier/ZeroTierOne#build-and-platform-notes
[source]
git = "https://github.com/zerotier/ZeroTierOne"
rev = "327eb9013b39809835a912c9117a0b9669f4661f"
[build]
template = "custom"
dependencies = [
    "openssl1",
]
