#TODO compiled but not tested
#TODO missing script to properly move the binary
[source]
git = "https://github.com/swc-project/swc"
[build]
template = "custom"
script = """
cookbook_cargo_packages swc_cli_impl
"""
