#TODO make the dependencies work
#TODO missing script for the waf build system, see https://ardour.org/building_linux.html
[source]
tar = "https://community.ardour.org/download?architecture=x86_64&type=source"
[build]
template = "custom"
dependencies = [
    "atk",
    "aubio",
    "boost",
    "fftw",
    "freetype2",
    "gdk-pixbuf",
    "glib",
    "gnome2-common",
    "gobject-introspection",
    "gtk-engines",
    "gtk2",
    "gtkmm",
    "harfbuzz",
    "itstool",
    "libarchive",
    "libiconv",
    "libogg",
    "libsamplerate",
    "libsndfile",
    "libusb",
    "libwebsockets",
    "libxslt",
    "lrdf",
    "nss-pem",
    "pango",
    "pcre",
    "libraptor2",
    "rdflib",
    "redland",
    "serd",
    "sratom",
    "taglib",
    "termcap",
    "util-linux",
    "vamp-plugin-sdk",
    "zlib",
    "atkmm",
    "cairo",
    "cppunit",
    "expat",
    "libflac",
    "fontconfig",
    "fribidi",
    "gettext",
    "glibmm",
    "gnome-doc-utils",
    "gtk-doc",
    "intltool",
    "libjpeg",
    "libffi",
    "liblo",
    "libpng",
    "libsigc++",
    "libtool",
    "libvorbis",
    "libxml2",
    "lilv",
    "lv2",
    "nss-nspr",
    "opus",
    "pangomm",
    "pixman",
    "librasqal",
    "readline",
    "rubberband",
    "sord",
    "suil",
    "libtiff",
    "xz",
]
