#TODO probably wrong script, see https://github.com/oxen-io/lokinet/blob/dev/docs/install.md#building
[source]
tar = "https://github.com/oxen-io/lokinet/releases/download/v0.9.11/lokinet-v0.9.11.tar.xz"
[build]
template = "custom"
dependencies = [
    "libcap",
    "libuv",
    "libsodium",
    "curl",
    "libevent",
    "libnettle",
    "openssl1",
    "unbound",
    "nlohmann-json",
]
script = """
COOKBOOK_CONFIGURE="cmake"
COOKBOOK_CONFIGURE_FLAGS=(
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_CROSSCOMPILING=True
    -DCMAKE_EXE_LINKER_FLAGS="-static"
    -DCMAKE_INSTALL_PREFIX="/"
    -DCMAKE_PREFIX_PATH="${COOKBOOK_SYSROOT}"
    -DCMAKE_SYSTEM_NAME=Generic
    -DCMAKE_SYSTEM_PROCESSOR="$(echo "${TARGET}" | cut -d - -f1)"
    -DCMAKE_VERBOSE_MAKEFILE=On
    -DBUILD_SHARED_LIBS=OFF
"${COOKBOOK_SOURCE}"
)
cookbook_configure
"""
