#TODO move to proper category
[source]
git = "https://github.com/justchokingaround/lobster"
[build]
template = "custom"
script = """
mkdir -pv "${COOKBOOK_STAGE}"/usr/bin
cp "${COOKBOOK_SOURCE}"/lobster.sh "${COOKBOOK_STAGE}"/usr/bin/lobster
chmod a+x "${COOKBOOK_STAGE}"/usr/bin/lobster
"""
