#TODO missing script for Meson, see https://github.com/Diego-Ivan/Flowtime#building-from-source
[source]
git = "https://github.com/Diego-Ivan/Flowtime"
rev = "2cb1160f7f61ec0a6add292deca38a3150336f03"
[build]
template = "custom"
dependencies = [
    "gtk4",
    "libxml2",
    "libadwaita",
]
