#TODO missing script for "make", see https://github.com/wolfpld/tracy/releases/latest/download/tracy.pdf
[source]
git = "https://github.com/wolfpld/tracy"
rev = "37aff70dfa50cf6307b3fee6074d627dc2929143"
[build]
template = "custom"
dependencies = [
    "glfw",
    "freetype2",
    "dbus",
    "capstone",
]
