/* automatically generated from actions-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (actions_dialog_ui)
#endif
#ifdef __GNUC__
static const char actions_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char actions_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><requires lib=\"libxfce4ui-2\" version=\"4.12\"/"
  "><object class=\"GtkImage\" id=\"image1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"icon_name\">window-close-symbolic</property></object><object class="
  "\"GtkImage\" id=\"image2\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"icon_name\""
  ">help-browser</property></object><object class=\"GtkListStore\" id=\"it"
  "ems-store\"><columns><column type=\"gboolean\"/><column type=\"gchararr"
  "ay\"/><column type=\"gchararray\"/><column type=\"guint\"/></columns></"
  "object><object class=\"GtkListStore\" id=\"mode-store\"><columns><colum"
  "n type=\"gchararray\"/></columns><data><row><col id=\"0\" translatable="
  "\"yes\">Action Buttons</col></row><row><col id=\"0\" translatable=\"yes"
  "\">Session Menu</col></row></data></object><object class=\"GtkListStore"
  "\" id=\"title-store\"><columns><column type=\"gchararray\"/></columns><"
  "data><row><col id=\"0\" translatable=\"yes\">Full Name</col></row><row>"
  "<col id=\"0\" translatable=\"yes\">Username</col></row><row><col id=\"0"
  "\" translatable=\"yes\">User ID</col></row><row><col id=\"0\" translata"
  "ble=\"yes\">Custom</col></row></data></object><object class=\"XfceTitle"
  "dDialog\" id=\"dialog\"><property name=\"can_focus\">False</property><p"
  "roperty name=\"title\" translatable=\"yes\">Action Buttons</property><p"
  "roperty name=\"default_width\">300</property><property name=\"default_h"
  "eight\">450</property><property name=\"icon_name\">org.xfce.panel.actio"
  "ns</property><property name=\"type_hint\">normal</property><child inter"
  "nal-child=\"vbox\"><object class=\"GtkBox\" id=\"dialog-vbox1\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"orientation\">vertical</property><property na"
  "me=\"spacing\">2</property><child internal-child=\"action_area\"><objec"
  "t class=\"GtkButtonBox\" id=\"dialog-action_area1\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"layout_style\">end</property><child><object class=\"GtkBu"
  "tton\" id=\"close-button\"><property name=\"label\" translatable=\"yes\""
  ">_Close</property><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">True</property><property name=\"receives_default\">Tr"
  "ue</property><property name=\"image\">image1</property><property name=\""
  "use_underline\">True</property></object><packing><property name=\"expan"
  "d\">False</property><property name=\"fill\">False</property><property n"
  "ame=\"position\">0</property></packing></child><child><object class=\"G"
  "tkButton\" id=\"help-button\"><property name=\"label\" translatable=\"y"
  "es\">_Help</property><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"receives_default\""
  ">True</property><property name=\"image\">image2</property><property nam"
  "e=\"use_underline\">True</property></object><packing><property name=\"e"
  "xpand\">False</property><property name=\"fill\">False</property><proper"
  "ty name=\"position\">1</property><property name=\"secondary\">True</pro"
  "perty></packing></child></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"pa"
  "ck_type\">end</property><property name=\"position\">0</property></packi"
  "ng></child><child><object class=\"GtkBox\" id=\"vbox1\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"border_width\">6</property><property name=\"orientati"
  "on\">vertical</property><property name=\"spacing\">6</property><child><"
  "object class=\"GtkFrame\" id=\"frame1\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"label_xalign\">0</property><property name=\"shadow_type\">none</prope"
  "rty><child><object class=\"GtkGrid\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"m"
  "argin_left\">18</property><property name=\"row_spacing\">6</property><p"
  "roperty name=\"column_spacing\">12</property><child><object class=\"Gtk"
  "ComboBox\" id=\"combo-mode\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"hexpand\""
  ">True</property><property name=\"model\">mode-store</property><child><o"
  "bject class=\"GtkCellRendererText\" id=\"cellrenderertext2\"/><attribut"
  "es><attribute name=\"text\">0</attribute></attributes></child></object>"
  "<packing><property name=\"left_attach\">1</property><property name=\"to"
  "p_attach\">0</property></packing></child><child><object class=\"GtkLabe"
  "l\" id=\"label3\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"label\" translatable"
  "=\"yes\">Appeara_nce:</property><property name=\"use_underline\">True</"
  "property><property name=\"xalign\">0</property></object><packing><prope"
  "rty name=\"left_attach\">0</property><property name=\"top_attach\">0</p"
  "roperty></packing></child><child><object class=\"GtkRevealer\" id=\"rev"
  "ealer-title\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"reveal_child\">True</pro"
  "perty><child><object class=\"GtkGrid\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "hexpand\">True</property><property name=\"row_spacing\">6</property><pr"
  "operty name=\"column_spacing\">12</property><child><object class=\"GtkL"
  "abel\" id=\"label-title\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"label\" tran"
  "slatable=\"yes\">Title:</property><property name=\"use_underline\">True"
  "</property><property name=\"xalign\">0</property></object><packing><pro"
  "perty name=\"left_attach\">0</property><property name=\"top_attach\">0<"
  "/property></packing></child><child><object class=\"GtkLabel\" id=\"labe"
  "l-cust-title\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\">Custo_m title:</property><property name=\"use_underline\">True</p"
  "roperty><property name=\"xalign\">0</property></object><packing><proper"
  "ty name=\"left_attach\">0</property><property name=\"top_attach\">1</pr"
  "operty></packing></child><child><object class=\"GtkComboBox\" id=\"comb"
  "o-title\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"hexpand\">True</property><pr"
  "operty name=\"model\">title-store</property><child><object class=\"GtkC"
  "ellRendererText\" id=\"cellrenderertext3\"/><attributes><attribute name"
  "=\"text\">0</attribute></attributes></child></object><packing><property"
  " name=\"left_attach\">1</property><property name=\"top_attach\">0</prop"
  "erty></packing></child><child><object class=\"GtkEntry\" id=\"entry-cus"
  "t-title\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"hexpand\">True</property><pro"
  "perty name=\"invisible_char\">\342\200\242</property></object><packing>"
  "<property name=\"left_attach\">1</property><property name=\"top_attach\""
  ">1</property></packing></child></object></child></object><packing><prop"
  "erty name=\"left_attach\">0</property><property name=\"top_attach\">1</"
  "property><property name=\"width\">2</property></packing></child></objec"
  "t></child><child type=\"label\"><object class=\"GtkLabel\" id=\"label1\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\">General<"
  "/property><attributes><attribute name=\"weight\" value=\"bold\"/></attr"
  "ibutes></object></child></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkFrame\""
  " id=\"frame2\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"label_xalign\">0</prope"
  "rty><property name=\"shadow_type\">none</property><child><object class="
  "\"GtkBox\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"margin_left\">12</property>"
  "<property name=\"vexpand\">True</property><property name=\"orientation\""
  ">vertical</property><property name=\"spacing\">6</property><child><obje"
  "ct class=\"GtkScrolledWindow\" id=\"scrolledwindow1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"border_width\">6</property><property name=\"shadow_type\""
  ">etched-in</property><child><object class=\"GtkTreeView\" id=\"actions-"
  "treeview\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">True</property><property name=\"hexpand\">True</property><pr"
  "operty name=\"vexpand\">True</property><property name=\"model\">items-s"
  "tore</property><property name=\"headers_clickable\">False</property><pr"
  "operty name=\"reorderable\">True</property><property name=\"search_colu"
  "mn\">0</property><child internal-child=\"selection\"><object class=\"Gt"
  "kTreeSelection\"/></child><child><object class=\"GtkTreeViewColumn\" id"
  "=\"treeviewcolumn1\"><property name=\"title\" translatable=\"yes\">Visi"
  "ble</property><child><object class=\"GtkCellRendererToggle\" id=\"visib"
  "le-toggle\"/><attributes><attribute name=\"active\">0</attribute></attr"
  "ibutes></child></object></child><child><object class=\"GtkTreeViewColum"
  "n\" id=\"treeviewcolumn2\"><property name=\"title\" translatable=\"yes\""
  ">Action</property><child><object class=\"GtkCellRendererText\" id=\"tex"
  "t-renderer\"/><attributes><attribute name=\"markup\">1</attribute></att"
  "ributes></child></object></child></object></child></object><packing><pr"
  "operty name=\"expand\">False</property><property name=\"fill\">True</pr"
  "operty><property name=\"position\">0</property></packing></child><child"
  "><object class=\"GtkCheckButton\" id=\"confirmation-dialog\"><property "
  "name=\"label\" translatable=\"yes\">_Show confirmation dialog</property"
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">False</property><pr"
  "operty name=\"tooltip_text\" translatable=\"yes\">Show a confirmation d"
  "ialog with a 30 second timeout for some of the actions.</property><prop"
  "erty name=\"use_underline\">True</property><property name=\"draw_indica"
  "tor\">True</property></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">1</property></packing></child></object></child><child type=\"labe"
  "l\"><object class=\"GtkLabel\" id=\"label2\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">_Actions</property><property name=\""
  "use_underline\">True</property><property name=\"mnemonic_widget\">actio"
  "ns-treeview</property><attributes><attribute name=\"weight\" value=\"bo"
  "ld\"/></attributes></object></child></object><packing><property name=\""
  "expand\">True</property><property name=\"fill\">True</property><propert"
  "y name=\"position\">1</property></packing></child></object><packing><pr"
  "operty name=\"expand\">True</property><property name=\"fill\">True</pro"
  "perty><property name=\"position\">1</property></packing></child></objec"
  "t></child><action-widgets><action-widget response=\"0\">close-button</a"
  "ction-widget><action-widget response=\"0\">help-button</action-widget><"
  "/action-widgets></object></interface>"
};

static const unsigned actions_dialog_ui_length = 10915u;

