#TODO Not compiled or tested
[source]
git = "https://github.com/slint-ui/cargo-ui"
rev = "230652da8e9d91f109d5e4be3a5831452243ebc0"
[build]
template = "custom"
dependencies = [
    "fontconfig",
    "libxkbcommon",
]
script = """
cookbook_cargo --no-default-features slint-backend-gl-all
"""
