#TODO missing script for "ant", see https://github.com/dacapobench/dacapobench#building
[source]
git = "https://github.com/dacapobench/dacapobench"
rev = "fd292e92f8c40495a6ca05ff3b8a77c6c4265606"
[build]
template = "custom"
