#TODO can't detect libiconv
# in case of problems, read https://www.php.net/manual/en/install.unix.php
[source]
tar = "https://www.php.net/distributions/php-8.3.0.tar.xz"
[build]
template = "configure"
dependencies = [
    "libxml2",
    "sqlite3",
    "libiconv",
]
