/* automatically generated from panel-preferences-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (panel_preferences_dialog_ui)
#endif
#ifdef __GNUC__
static const char panel_preferences_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char panel_preferences_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><requires lib=\"libxfce4ui-2\" version=\"4.12\"/"
  "><object class=\"GtkListStore\" id=\"autohide-behavior-store\"><columns"
  "><column type=\"gchararray\"/></columns><data><row><col id=\"0\" transl"
  "atable=\"yes\">Never</col></row><row><col id=\"0\" translatable=\"yes\""
  ">Intelligently</col></row><row><col id=\"0\" translatable=\"yes\">Alway"
  "s</col></row></data></object><object class=\"GtkSizeGroup\" id=\"bg-siz"
  "egroup\"/><object class=\"GtkSizeGroup\" id=\"display-sizegroup\"/><obj"
  "ect class=\"GtkAdjustment\" id=\"enter-opacity\"><property name=\"upper"
  "\">100</property><property name=\"value\">100</property><property name="
  "\"step_increment\">1</property><property name=\"page_increment\">10</pr"
  "operty></object><object class=\"GtkAdjustment\" id=\"icon-size\"><prope"
  "rty name=\"upper\">100</property><property name=\"step_increment\">1</p"
  "roperty><property name=\"page_increment\">10</property></object><object"
  " class=\"GtkImage\" id=\"image10\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"ico"
  "n_name\">package-x-generic</property></object><object class=\"GtkImage\""
  " id=\"image11\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"icon_name\">window-clo"
  "se-symbolic</property></object><object class=\"GtkImage\" id=\"image12\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"icon_name\">help-browser</property></"
  "object><object class=\"GtkImage\" id=\"image5\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"icon_name\">list-add-symbolic</property></object><object clas"
  "s=\"GtkImage\" id=\"image6\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"icon_name"
  "\">list-remove-symbolic</property></object><object class=\"GtkAdjustmen"
  "t\" id=\"leave-opacity\"><property name=\"upper\">100</property><proper"
  "ty name=\"value\">100</property><property name=\"step_increment\">1</pr"
  "operty><property name=\"page_increment\">10</property></object><object "
  "class=\"GtkAdjustment\" id=\"length\"><property name=\"lower\">1</prope"
  "rty><property name=\"upper\">1</property><property name=\"value\">1</pr"
  "operty><property name=\"step_increment\">1</property><property name=\"p"
  "age_increment\">100</property></object><object class=\"GtkListStore\" i"
  "d=\"mode-store\"><columns><column type=\"gchararray\"/></columns><data>"
  "<row><col id=\"0\" translatable=\"yes\">Horizontal</col></row><row><col"
  " id=\"0\" translatable=\"yes\">Vertical</col></row><row><col id=\"0\" t"
  "ranslatable=\"yes\">Deskbar</col></row></data></object><object class=\""
  "GtkAdjustment\" id=\"nrows\"><property name=\"lower\">1</property><prop"
  "erty name=\"upper\">6</property><property name=\"value\">1</property><p"
  "roperty name=\"step_increment\">1</property><property name=\"page_incre"
  "ment\">1</property></object><object class=\"GtkListStore\" id=\"output-"
  "store\"><columns><column type=\"gchararray\"/><column type=\"gchararray"
  "\"/></columns></object><object class=\"GtkListStore\" id=\"panel-store\""
  "><columns><column type=\"gint\"/><column type=\"gchararray\"/></columns"
  "></object><object class=\"GtkAdjustment\" id=\"size\"><property name=\""
  "lower\">16</property><property name=\"upper\">128</property><property n"
  "ame=\"value\">16</property><property name=\"step_increment\">1</propert"
  "y><property name=\"page_increment\">10</property></object><object class"
  "=\"GtkListStore\" id=\"styles-store\"><columns><column type=\"gchararra"
  "y\"/></columns><data><row><col id=\"0\" translatable=\"yes\">None (use "
  "system style)</col></row><row><col id=\"0\" translatable=\"yes\">Solid "
  "color</col></row><row><col id=\"0\" translatable=\"yes\">Background ima"
  "ge</col></row></data></object><object class=\"XfceTitledDialog\" id=\"d"
  "ialog\"><property name=\"can_focus\">False</property><property name=\"t"
  "itle\" translatable=\"yes\">Panel Preferences</property><property name="
  "\"window_position\">center-on-parent</property><property name=\"icon_na"
  "me\">org.xfce.panel</property><property name=\"type_hint\">normal</prop"
  "erty><child internal-child=\"vbox\"><object class=\"GtkBox\" id=\"dialo"
  "g-vbox1\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"orientation\">vertical</prop"
  "erty><property name=\"spacing\">2</property><child internal-child=\"act"
  "ion_area\"><object class=\"GtkButtonBox\" id=\"dialog-action_area1\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"layout_style\">end</property><child><obj"
  "ect class=\"GtkButton\" id=\"button-close\"><property name=\"label\" tr"
  "anslatable=\"yes\">_Close</property><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">True</property><property name=\"rec"
  "eives_default\">True</property><property name=\"image\">image11</proper"
  "ty><property name=\"use_underline\">True</property></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">False</"
  "property><property name=\"position\">0</property></packing></child><chi"
  "ld><object class=\"GtkButton\" id=\"button-help\"><property name=\"labe"
  "l\" translatable=\"yes\">_Help</property><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">True</property><property name="
  "\"receives_default\">True</property><property name=\"image\">image12</p"
  "roperty><property name=\"use_underline\">True</property></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Fa"
  "lse</property><property name=\"position\">1</property><property name=\""
  "secondary\">True</property></packing></child></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">False</proper"
  "ty><property name=\"pack_type\">end</property><property name=\"position"
  "\">0</property></packing></child><child><object class=\"GtkBox\" id=\"p"
  "lug-child\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"border_width\">6</property"
  "><property name=\"orientation\">vertical</property><property name=\"spa"
  "cing\">12</property><child><object class=\"GtkGrid\" id=\"panel-profile"
  "s\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"row_spacing\">6</property><propert"
  "y name=\"column_spacing\">12</property><child><object class=\"GtkBox\" "
  "id=\"hbox7\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"spacing\">6</property><chi"
  "ld><object class=\"GtkLabel\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"label\" "
  "translatable=\"yes\">Profiles:</property></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">True</property><p"
  "roperty name=\"position\">0</property></packing></child></object><packi"
  "ng><property name=\"left_attach\">0</property><property name=\"top_atta"
  "ch\">0</property></packing></child><child><object class=\"GtkSeparator\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"hexpand\">True</property></object><pa"
  "cking><property name=\"left_attach\">0</property><property name=\"top_a"
  "ttach\">1</property><property name=\"width\">2</property></packing></ch"
  "ild><child><object class=\"GtkButton\" id=\"panel-switch\"><property na"
  "me=\"label\" translatable=\"yes\">_Backup and restore</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"receives_default\">True</property><property na"
  "me=\"tooltip_text\" translatable=\"yes\">Switch between panel presets</"
  "property><property name=\"image\">image10</property><property name=\"us"
  "e_underline\">True</property></object><packing><property name=\"left_at"
  "tach\">1</property><property name=\"top_attach\">0</property></packing>"
  "</child></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">0</prop"
  "erty></packing></child><child><object class=\"GtkBox\" id=\"hbox3\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"spacing\">6</property><child><object clas"
  "s=\"GtkComboBox\" id=\"panel-combobox\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"model\">panel-store</property><child><object class=\"GtkCellRendererT"
  "ext\" id=\"cellrenderertext2\"/><attributes><attribute name=\"text\">1<"
  "/attribute></attributes></child></object><packing><property name=\"expa"
  "nd\">True</property><property name=\"fill\">True</property><property na"
  "me=\"position\">0</property></packing></child><child><object class=\"Gt"
  "kButton\" id=\"panel-add\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"receives_def"
  "ault\">True</property><property name=\"tooltip_text\" translatable=\"ye"
  "s\">Add a new panel</property><child><object class=\"GtkImage\" id=\"im"
  "age1\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"margin_left\">3</property><prop"
  "erty name=\"margin_right\">3</property><property name=\"margin_top\">3<"
  "/property><property name=\"margin_bottom\">3</property><property name=\""
  "icon_name\">list-add</property></object></child></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">1</property></packing></child><child><"
  "object class=\"GtkButton\" id=\"panel-remove\"><property name=\"visible"
  "\">True</property><property name=\"sensitive\">False</property><propert"
  "y name=\"can_focus\">True</property><property name=\"receives_default\""
  ">True</property><property name=\"tooltip_text\" translatable=\"yes\">Re"
  "move the currently selected panel</property><child><object class=\"GtkI"
  "mage\" id=\"image2\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"margin_left\">3</"
  "property><property name=\"margin_right\">3</property><property name=\"m"
  "argin_top\">3</property><property name=\"margin_bottom\">3</property><p"
  "roperty name=\"icon_name\">list-remove</property></object></child></obj"
  "ect><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">2</property></packing"
  "></child></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">1</pro"
  "perty></packing></child><child><object class=\"GtkNotebook\" id=\"noteb"
  "ook\"><property name=\"visible\">True</property><property name=\"sensit"
  "ive\">False</property><property name=\"can_focus\">True</property><chil"
  "d><object class=\"GtkBox\" id=\"vbox2\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"border_width\">12</property><property name=\"orientation\">vertical</"
  "property><property name=\"spacing\">6</property><child><object class=\""
  "GtkGrid\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"margin_bottom\">18</property"
  "><property name=\"row_spacing\">6</property><property name=\"column_spa"
  "cing\">12</property><child><object class=\"GtkLabel\" id=\"label2\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"hexpand\">True</property><property name=\""
  "label\" translatable=\"yes\">&lt;b&gt;General&lt;/b&gt;</property><prop"
  "erty name=\"use_markup\">True</property><property name=\"xalign\">0</pr"
  "operty></object><packing><property name=\"left_attach\">0</property><pr"
  "operty name=\"top_attach\">0</property><property name=\"width\">2</prop"
  "erty></packing></child><child><object class=\"GtkLabel\" id=\"label1\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"margin_left\">12</property><property n"
  "ame=\"label\" translatable=\"yes\">M_ode:</property><property name=\"us"
  "e_underline\">True</property><property name=\"xalign\">0</property></ob"
  "ject><packing><property name=\"left_attach\">0</property><property name"
  "=\"top_attach\">1</property></packing></child><child><object class=\"Gt"
  "kComboBox\" id=\"mode\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"hexpand\">True"
  "</property><property name=\"model\">mode-store</property><child><object"
  " class=\"GtkCellRendererText\" id=\"cellrenderertext1\"/><attributes><a"
  "ttribute name=\"text\">0</attribute></attributes></child></object><pack"
  "ing><property name=\"left_attach\">1</property><property name=\"top_att"
  "ach\">1</property></packing></child><child><object class=\"GtkCheckButt"
  "on\" id=\"span-monitors\"><property name=\"label\" translatable=\"yes\""
  ">Span mo_nitors</property><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">True</property><property name=\"receives_defa"
  "ult\">False</property><property name=\"tooltip_text\" translatable=\"ye"
  "s\">Select this option to extend the panel over multiple monitors.</pro"
  "perty><property name=\"margin_left\">12</property><property name=\"use_"
  "underline\">True</property><property name=\"draw_indicator\">True</prop"
  "erty></object><packing><property name=\"left_attach\">0</property><prop"
  "erty name=\"top_attach\">3</property><property name=\"width\">2</proper"
  "ty></packing></child><child><object class=\"GtkCheckButton\" id=\"posit"
  "ion-locked\"><property name=\"label\" translatable=\"yes\">_Lock panel<"
  "/property><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">False</pro"
  "perty><property name=\"tooltip_text\" translatable=\"yes\">Select this "
  "option to hide the handles of the panel and lock its position.</propert"
  "y><property name=\"margin_left\">12</property><property name=\"use_unde"
  "rline\">True</property><property name=\"draw_indicator\">True</property"
  "></object><packing><property name=\"left_attach\">0</property><property"
  " name=\"top_attach\">4</property><property name=\"width\">2</property><"
  "/packing></child><child><object class=\"GtkCheckButton\" id=\"disable-s"
  "truts\"><property name=\"label\" translatable=\"yes\">Keep panel _above"
  " windows</property><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"receives_default\">F"
  "alse</property><property name=\"tooltip_text\" translatable=\"yes\">Sel"
  "ect this option if you want maximized windows to cover the area behind "
  "the panel. This only works when the panel is attached to a screen edge."
  "</property><property name=\"margin_left\">12</property><property name=\""
  "use_underline\">True</property><property name=\"draw_indicator\">True</"
  "property></object><packing><property name=\"left_attach\">0</property><"
  "property name=\"top_attach\">6</property><property name=\"width\">2</pr"
  "operty></packing></child><child><object class=\"GtkBox\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"spacing\">12</property><child><object class=\"GtkLab"
  "el\" id=\"autohide_label\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"margin_left"
  "\">12</property><property name=\"label\" translatable=\"yes\">Au_tomati"
  "cally hide the panel:</property><property name=\"use_underline\">True</"
  "property><property name=\"xalign\">0</property></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">0</property></packing></child><child><o"
  "bject class=\"GtkComboBox\" id=\"autohide-behavior\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"model\">autohide-behavior-store</property><child><object"
  " class=\"GtkCellRendererText\" id=\"cellrenderertext5\"/><attributes><a"
  "ttribute name=\"text\">0</attribute></attributes></child></object><pack"
  "ing><property name=\"expand\">True</property><property name=\"fill\">Tr"
  "ue</property><property name=\"pack_type\">end</property><property name="
  "\"position\">1</property></packing></child></object><packing><property "
  "name=\"left_attach\">0</property><property name=\"top_attach\">5</prope"
  "rty><property name=\"width\">2</property></packing></child><child><obje"
  "ct class=\"GtkLabel\" id=\"output-label\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"margin_left\">12</property><property name=\"label\" translatable=\""
  "yes\">O_utput:</property><property name=\"use_underline\">True</propert"
  "y><property name=\"xalign\">0</property></object><packing><property nam"
  "e=\"left_attach\">0</property><property name=\"top_attach\">2</property"
  "></packing></child><child><object class=\"GtkComboBox\" id=\"output-nam"
  "e\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"model\">output-store</property><ch"
  "ild><object class=\"GtkCellRendererText\" id=\"cellrenderertext3\"/><at"
  "tributes><attribute name=\"text\">1</attribute></attributes></child></o"
  "bject><packing><property name=\"left_attach\">1</property><property nam"
  "e=\"top_attach\">2</property></packing></child></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">0</property></packing></child><child><o"
  "bject class=\"GtkGrid\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"row_spacing\">"
  "6</property><property name=\"column_spacing\">12</property><child><obje"
  "ct class=\"GtkLabel\" id=\"label5\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"la"
  "bel\" translatable=\"yes\" comments=\"I18N: name of the section (frame)"
  " in the panel preferences where the user can define the length and size"
  " of the panel\">&lt;b&gt;Measurements&lt;/b&gt;</property><property nam"
  "e=\"use_markup\">True</property><property name=\"xalign\">0</property><"
  "/object><packing><property name=\"left_attach\">0</property><property n"
  "ame=\"top_attach\">0</property><property name=\"width\">2</property></p"
  "acking></child><child><object class=\"GtkLabel\" id=\"label3\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"margin_left\">12</property><property name=\"la"
  "bel\" translatable=\"yes\">Row _size (pixels):</property><property name"
  "=\"use_underline\">True</property><property name=\"xalign\">0</property"
  "></object><packing><property name=\"left_attach\">0</property><property"
  " name=\"top_attach\">1</property></packing></child><child><object class"
  "=\"GtkLabel\" id=\"label18\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"margin_le"
  "ft\">12</property><property name=\"label\" translatable=\"yes\">Num_ber"
  " of rows:</property><property name=\"use_underline\">True</property><pr"
  "operty name=\"xalign\">0</property></object><packing><property name=\"l"
  "eft_attach\">0</property><property name=\"top_attach\">2</property></pa"
  "cking></child><child><object class=\"GtkLabel\" id=\"label4\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"margin_left\">12</property><property name=\"lab"
  "el\" translatable=\"yes\">L_ength (pixels):</property><property name=\""
  "use_underline\">True</property><property name=\"xalign\">0</property></"
  "object><packing><property name=\"left_attach\">0</property><property na"
  "me=\"top_attach\">3</property></packing></child><child><object class=\""
  "GtkScale\" id=\"length-scale\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">True</property><property name=\"hexpand\""
  ">True</property><property name=\"adjustment\">length</property><propert"
  "y name=\"digits\">0</property><property name=\"value_pos\">right</prope"
  "rty></object><packing><property name=\"left_attach\">1</property><prope"
  "rty name=\"top_attach\">3</property></packing></child><child><object cl"
  "ass=\"GtkCheckButton\" id=\"length-adjust\"><property name=\"label\" tr"
  "anslatable=\"yes\">A_utomatically increase the length</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"receives_default\">False</property><property n"
  "ame=\"tooltip_text\" translatable=\"yes\">Select this option to automat"
  "ically increase the length of the panel if the plugins request more spa"
  "ce.</property><property name=\"margin_left\">12</property><property nam"
  "e=\"use_underline\">True</property><property name=\"draw_indicator\">Tr"
  "ue</property></object><packing><property name=\"left_attach\">0</proper"
  "ty><property name=\"top_attach\">4</property><property name=\"width\">2"
  "</property></packing></child><child><object class=\"GtkSpinButton\" id="
  "\"size-scale\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"halign\">end</property><"
  "property name=\"valign\">center</property><property name=\"adjustment\""
  ">size</property></object><packing><property name=\"left_attach\">1</pro"
  "perty><property name=\"top_attach\">1</property></packing></child><chil"
  "d><object class=\"GtkSpinButton\" id=\"nrows-scale\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"halign\">end</property><property name=\"valign\">center</"
  "property><property name=\"adjustment\">nrows</property></object><packin"
  "g><property name=\"left_attach\">1</property><property name=\"top_attac"
  "h\">2</property></packing></child></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">True</property><property"
  " name=\"position\">2</property></packing></child></object></child><chil"
  "d type=\"tab\"><object class=\"GtkLabel\" id=\"label6\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"label\" translatable=\"yes\">D_isplay</property><prop"
  "erty name=\"use_underline\">True</property></object><packing><property "
  "name=\"tab_fill\">False</property></packing></child><child><object clas"
  "s=\"GtkBox\" id=\"vbox7\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"border_width"
  "\">12</property><property name=\"orientation\">vertical</property><prop"
  "erty name=\"spacing\">6</property><child><object class=\"GtkGrid\" id=\""
  "general-grid\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"margin_bottom\">18</pro"
  "perty><property name=\"row_spacing\">6</property><property name=\"colum"
  "n_spacing\">12</property><child><object class=\"GtkLabel\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"label\" translatable=\"yes\">&lt;b&gt;General&lt;/"
  "b&gt;</property><property name=\"use_markup\">True</property><property "
  "name=\"xalign\">0</property></object><packing><property name=\"left_att"
  "ach\">0</property><property name=\"top_attach\">0</property></packing><"
  "/child><child><object class=\"GtkLabel\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"margin_left\">12</property><property name=\"hexpand\">True</property"
  "><property name=\"label\" translatable=\"yes\">Dark mode</property><pro"
  "perty name=\"xalign\">0</property></object><packing><property name=\"le"
  "ft_attach\">0</property><property name=\"top_attach\">1</property></pac"
  "king></child><child><object class=\"GtkSwitch\" id=\"dark-mode\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"halign\">end</property><property name=\"valig"
  "n\">center</property></object><packing><property name=\"left_attach\">1"
  "</property><property name=\"top_attach\">1</property></packing></child>"
  "<child><placeholder/></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"position\">0</property></packing></child><child><object class=\"GtkGr"
  "id\" id=\"background-grid\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"margin_bot"
  "tom\">18</property><property name=\"row_spacing\">6</property><property"
  " name=\"column_spacing\">12</property><child><object class=\"GtkLabel\""
  " id=\"label8\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"hexpand\">True</propert"
  "y><property name=\"label\" translatable=\"yes\">&lt;b&gt;Background&lt;"
  "/b&gt;</property><property name=\"use_markup\">True</property><property"
  " name=\"xalign\">0</property></object><packing><property name=\"left_at"
  "tach\">0</property><property name=\"top_attach\">0</property><property "
  "name=\"width\">2</property></packing></child><child><object class=\"Gtk"
  "Label\" id=\"label7\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"margin_left\">12"
  "</property><property name=\"label\" translatable=\"yes\">_Style:</prope"
  "rty><property name=\"use_underline\">True</property><property name=\"xa"
  "lign\">0</property></object><packing><property name=\"left_attach\">0</"
  "property><property name=\"top_attach\">1</property></packing></child><c"
  "hild><object class=\"GtkComboBox\" id=\"background-style\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"hexpand\">True</property><property name=\"model\">"
  "styles-store</property><child><object class=\"GtkCellRendererText\" id="
  "\"cellrenderertext4\"/><attributes><attribute name=\"text\">0</attribut"
  "e></attributes></child></object><packing><property name=\"left_attach\""
  ">1</property><property name=\"top_attach\">1</property></packing></chil"
  "d><child><object class=\"GtkLabel\" id=\"background-rgba-label\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"margin_left\">12</property><property name=\""
  "label\" translatable=\"yes\">C_olor:</property><property name=\"use_und"
  "erline\">True</property><property name=\"xalign\">0</property></object>"
  "<packing><property name=\"left_attach\">0</property><property name=\"to"
  "p_attach\">2</property></packing></child><child><object class=\"GtkColo"
  "rButton\" id=\"background-rgba\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"recei"
  "ves_default\">True</property><property name=\"halign\">end</property><p"
  "roperty name=\"title\" translatable=\"yes\">Pick a Panel Color</propert"
  "y><property name=\"rgba\">rgb(217,64,217)</property></object><packing><"
  "property name=\"left_attach\">1</property><property name=\"top_attach\""
  ">2</property></packing></child><child><object class=\"GtkLabel\" id=\"b"
  "ackground-image-label\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"margin_left\">"
  "12</property><property name=\"label\" translatable=\"yes\">_File:</prop"
  "erty><property name=\"use_underline\">True</property><property name=\"x"
  "align\">0</property></object><packing><property name=\"left_attach\">0<"
  "/property><property name=\"top_attach\">3</property></packing></child><"
  "child><object class=\"GtkFileChooserButton\" id=\"background-image\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"title\" translatable=\"yes\">Select A Ba"
  "ckground Image</property></object><packing><property name=\"left_attach"
  "\">1</property><property name=\"top_attach\">3</property></packing></ch"
  "ild></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">1</property"
  "></packing></child><child><object class=\"GtkGrid\" id=\"icons-grid\"><"
  "property name=\"name\">icons-grid</property><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"margin_bottom\">18</property><property name=\"row_spacing\">6</pr"
  "operty><property name=\"column_spacing\">12</property><child><object cl"
  "ass=\"GtkLabel\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"label\" translatable="
  "\"yes\">&lt;b&gt;Icons&lt;/b&gt;</property><property name=\"use_markup\""
  ">True</property><property name=\"xalign\">0</property></object><packing"
  "><property name=\"left_attach\">0</property><property name=\"top_attach"
  "\">0</property></packing></child><child><object class=\"GtkLabel\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"margin_left\">12</property><property name="
  "\"label\" translatable=\"yes\">Adjust size au_tomatically</property><pr"
  "operty name=\"use_underline\">True</property><property name=\"xalign\">"
  "0</property></object><packing><property name=\"left_attach\">0</propert"
  "y><property name=\"top_attach\">1</property></packing></child><child><o"
  "bject class=\"GtkSwitch\" id=\"icon-size-switch\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"halign\">end</property><property name=\"valign\">center</pro"
  "perty></object><packing><property name=\"left_attach\">1</property><pro"
  "perty name=\"top_attach\">1</property></packing></child><child><object "
  "class=\"GtkRevealer\" id=\"icon-size-revealer\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"reveal_child\">True</property><child><object class=\"GtkBox\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"hexpand\">True</property><property na"
  "me=\"spacing\">6</property><child><object class=\"GtkLabel\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"margin_left\">12</property><property name=\"labe"
  "l\" translatable=\"yes\">Fixed icon _size (pixels):</property><property"
  " name=\"use_underline\">True</property><property name=\"xalign\">0</pro"
  "perty></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">True</property><property name=\"position\">0</proper"
  "ty></packing></child><child><object class=\"GtkSpinButton\" id=\"icon-s"
  "ize-spinbutton\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">True</property><property name=\"adjustment\">icon-size"
  "</property></object><packing><property name=\"expand\">False</property>"
  "<property name=\"fill\">True</property><property name=\"pack_type\">end"
  "</property><property name=\"position\">1</property></packing></child></"
  "object></child></object><packing><property name=\"left_attach\">0</prop"
  "erty><property name=\"top_attach\">2</property><property name=\"width\""
  ">2</property></packing></child><child><placeholder/></child></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">2</property></packing></chi"
  "ld><child><object class=\"GtkLabel\" id=\"label11\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"label\" translatable=\"yes\">&lt;b&gt;Opacity&lt;/b&gt;</"
  "property><property name=\"use_markup\">True</property><property name=\""
  "xalign\">0</property></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">3</property></packing></child><child><object class=\"GtkRevealer\""
  " id=\"composited-info\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"reveal_child\""
  ">True</property><child><object class=\"GtkInfoBar\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><ch"
  "ild internal-child=\"action_area\"><object class=\"GtkButtonBox\"><prop"
  "erty name=\"can_focus\">False</property><property name=\"spacing\">6</p"
  "roperty><property name=\"layout_style\">end</property><child><object cl"
  "ass=\"GtkButton\" id=\"xfwm4-settings\"><property name=\"label\" transl"
  "atable=\"yes\">Configure...</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"r"
  "eceives_default\">True</property></object><packing><property name=\"exp"
  "and\">True</property><property name=\"fill\">True</property><property n"
  "ame=\"position\">0</property></packing></child></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">False</prop"
  "erty><property name=\"position\">0</property></packing></child><child i"
  "nternal-child=\"content_area\"><object class=\"GtkBox\"><property name="
  "\"can_focus\">False</property><property name=\"spacing\">6</property><c"
  "hild><object class=\"GtkImage\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"icon_n"
  "ame\">dialog-information-symbolic</property></object><packing><property"
  " name=\"expand\">False</property><property name=\"fill\">True</property"
  "><property name=\"position\">0</property></packing></child><child><obje"
  "ct class=\"GtkLabel\" id=\"label17\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"l"
  "abel\" translatable=\"yes\">&lt;b&gt;Compositing is currently disabled&"
  "lt;/b&gt;\nEnable compositing in the window manager for opacity setting"
  "s in the panel.</property><property name=\"use_markup\">True</property>"
  "<property name=\"wrap\">True</property><property name=\"max-width-chars"
  "\">0</property></object><packing><property name=\"expand\">True</proper"
  "ty><property name=\"fill\">True</property><property name=\"position\">1"
  "</property></packing></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">False</property><property name"
  "=\"position\">0</property></packing></child></object></child></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">True</property><property name=\"position\">4</property></packing></c"
  "hild><child><object class=\"GtkGrid\" id=\"composited\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"margin_left\">12</property><property name=\"row_spaci"
  "ng\">6</property><property name=\"column_spacing\">12</property><child>"
  "<object class=\"GtkLabel\" id=\"label9\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"label\" translatable=\"yes\" comments=\"I18N: label for the enter tr"
  "ansparency slider\">_Enter:</property><property name=\"use_underline\">"
  "True</property><property name=\"xalign\">0</property></object><packing>"
  "<property name=\"left_attach\">0</property><property name=\"top_attach\""
  ">0</property></packing></child><child><object class=\"GtkScale\" id=\"e"
  "nter-opacity-scale\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"hexpand\">True</pr"
  "operty><property name=\"adjustment\">enter-opacity</property><property "
  "name=\"digits\">0</property><property name=\"value_pos\">right</propert"
  "y></object><packing><property name=\"left_attach\">1</property><propert"
  "y name=\"top_attach\">0</property></packing></child><child><object clas"
  "s=\"GtkLabel\" id=\"label10\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"label\" "
  "translatable=\"yes\" comments=\"I18N: label for the leave transparency "
  "slider\">_Leave:</property><property name=\"use_underline\">True</prope"
  "rty><property name=\"xalign\">0</property></object><packing><property n"
  "ame=\"left_attach\">0</property><property name=\"top_attach\">1</proper"
  "ty></packing></child><child><object class=\"GtkScale\" id=\"leave-opaci"
  "ty-scale\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">True</property><property name=\"tooltip_text\" translatable="
  "\"yes\">Transparency when the pointer is not hovering over the panel, w"
  "ith 0 being fully transparent and 100 fully opaque.</property><property"
  " name=\"hexpand\">True</property><property name=\"adjustment\">leave-op"
  "acity</property><property name=\"digits\">0</property><property name=\""
  "value_pos\">right</property></object><packing><property name=\"left_att"
  "ach\">1</property><property name=\"top_attach\">1</property></packing><"
  "/child></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">True</property><property name=\"position\">5</prope"
  "rty></packing></child></object><packing><property name=\"position\">1</"
  "property></packing></child><child type=\"tab\"><object class=\"GtkLabel"
  "\" id=\"label12\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"label\" translatable"
  "=\"yes\">Appeara_nce</property><property name=\"use_underline\">True</p"
  "roperty></object><packing><property name=\"position\">1</property><prop"
  "erty name=\"tab_fill\">False</property></packing></child><child><object"
  " class=\"GtkBox\" id=\"hbox4\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"border_"
  "width\">12</property><property name=\"spacing\">6</property><child><obj"
  "ect class=\"GtkBox\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"orientation\">ver"
  "tical</property><child><object class=\"GtkScrolledWindow\" id=\"scrolle"
  "dwindow3\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">True</property><property name=\"shadow_type\">etched-in</pro"
  "perty><child><object class=\"GtkTreeView\" id=\"item-treeview\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"vexpand\">True</property><property name=\"head"
  "ers_visible\">False</property><property name=\"rules_hint\">True</prope"
  "rty><property name=\"enable_search\">False</property><child internal-ch"
  "ild=\"selection\"><object class=\"GtkTreeSelection\"/></child></object>"
  "</child></object><packing><property name=\"expand\">True</property><pro"
  "perty name=\"fill\">True</property><property name=\"position\">0</prope"
  "rty></packing></child><child><object class=\"GtkBox\" id=\"vbox6\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><child><object class=\"GtkButton\" id=\"item-add\"><propert"
  "y name=\"label\" translatable=\"yes\">_Add</property><property name=\"v"
  "isible\">True</property><property name=\"sensitive\">False</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"receives_def"
  "ault\">True</property><property name=\"tooltip_text\" translatable=\"ye"
  "s\">Add new item to this panel</property><property name=\"image\">image"
  "5</property><property name=\"use_underline\">True</property></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">2</property></packing></chi"
  "ld><child><object class=\"GtkButton\" id=\"item-remove\"><property name"
  "=\"label\" translatable=\"yes\">_Remove</property><property name=\"visi"
  "ble\">True</property><property name=\"sensitive\">False</property><prop"
  "erty name=\"can_focus\">True</property><property name=\"receives_defaul"
  "t\">True</property><property name=\"tooltip_text\" translatable=\"yes\""
  ">Remove currently selected item</property><property name=\"image\">imag"
  "e6</property><property name=\"use_underline\">True</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">True</property><property name=\"position\">3</property></packing></c"
  "hild><child><object class=\"GtkButton\" id=\"item-properties\"><propert"
  "y name=\"visible\">True</property><property name=\"sensitive\">False</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"re"
  "ceives_default\">True</property><property name=\"tooltip_text\" transla"
  "table=\"yes\">Edit the currently selected item</property><child><object"
  " class=\"GtkImage\" id=\"image7\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"icon"
  "_name\">document-properties-symbolic</property></object></child></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"f"
  "ill\">True</property><property name=\"position\">4</property></packing>"
  "</child><child><object class=\"GtkButton\" id=\"item-about\"><property "
  "name=\"visible\">True</property><property name=\"sensitive\">False</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"rece"
  "ives_default\">True</property><property name=\"tooltip_text\" translata"
  "ble=\"yes\">Show about information of the currently selected item</prop"
  "erty><child><object class=\"GtkImage\" id=\"image8\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"icon_name\">help-about-symbolic</property></object></chi"
  "ld></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">5</property>"
  "</packing></child><style><class name=\"inline-toolbar\"/></style></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">2</property></packing"
  "></child></object><packing><property name=\"expand\">True</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">0</prop"
  "erty></packing></child><child><object class=\"GtkBox\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"orientation\">vertical</property><child><object class=\""
  "GtkButton\" id=\"item-up\"><property name=\"visible\">True</property><p"
  "roperty name=\"sensitive\">False</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">True</property><pro"
  "perty name=\"tooltip_text\" translatable=\"yes\">Move currently selecte"
  "d item up by one row</property><child><object class=\"GtkImage\" id=\"i"
  "mage3\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"icon_name\">go-up-symbolic</pr"
  "operty></object></child></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkButton"
  "\" id=\"item-down\"><property name=\"visible\">True</property><property"
  " name=\"sensitive\">False</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">True</property><property n"
  "ame=\"tooltip_text\" translatable=\"yes\">Move currently selected item "
  "down by one row</property><child><object class=\"GtkImage\" id=\"image4"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"icon_name\">go-down-symbolic</prope"
  "rty></object></child></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">1</property></packing></child><style><class name=\"linked\"/></st"
  "yle></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">2</property"
  "></packing></child></object><packing><property name=\"position\">2</pro"
  "perty></packing></child><child type=\"tab\"><object class=\"GtkLabel\" "
  "id=\"label14\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\">Ite_ms</property><property name=\"use_underline\">True</property>"
  "</object><packing><property name=\"position\">2</property><property nam"
  "e=\"tab_fill\">False</property></packing></child></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">True</pro"
  "perty><property name=\"position\">2</property></packing></child></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"f"
  "ill\">True</property><property name=\"position\">1</property></packing>"
  "</child></object></child><action-widgets><action-widget response=\"0\">"
  "button-close</action-widget><action-widget response=\"1\">button-help</"
  "action-widget></action-widgets></object></interface>"
};

static const unsigned panel_preferences_dialog_ui_length = 41777u;

