#TODO build instructions - https://github.com/openjdk/jdk17u/blob/master/doc/building.md
#TODO not compiled or tested
[source]
git = "https://github.com/openjdk/jdk17u"
rev = "b78a848cc7ae5787d9ec9ea0ce843cd63b06efec"
[build]
template = "custom"
dependencies = [
    "fontconfig",
]
script = """
COOKBOOK_CONFIGURE_FLAGS+=(
    --enable-headless-only=yes
)
cookbook_configure
"""
