#TODO probably wrong template, see https://gitlab.gnome.org/GNOME/glibmm#building
[source]
tar = "https://download.gnome.org/sources/glibmm/2.78/glibmm-2.78.0.tar.xz"
[build]
template = "configure"
dependencies = [
    "glib",
]
