#TODO port to redox
#TODO build instructions - https://github.com/H-M-H/Weylus#building
[source]
git = "https://github.com/H-M-H/Weylus"
[build]
template = "custom"
dependencies = [
    "pango",
    "gstreamer",
    "dbus",
    "libx11",
    "libxext",
    "libxft",
    "libxinerama",
    "libxcursor",
    "libxi",
    "libxv",
    "libxfixes",
    "libxtst",
    "libxrender",
    "libxrandr",
    "libxcomposite",
]
script = """
cookbook_cargo_packages weylus
"""
