#TODO probably wrong script, see https://github.com/snes9xgit/snes9x/wiki/Compiling
[source]
git = "https://github.com/snes9xgit/snes9x"
rev = "8b82d487937d9ea39f7229d280c6f6686c415fe7"
[build]
template = "custom"
dependencies = [
    "sdl2",
    "gtk3mm",
    "libpng",
    "zlib",
    "libx11",
    "libepoxy",
]
script = """
COOKBOOK_CONFIGURE="cmake"
COOKBOOK_CONFIGURE_FLAGS=(
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_CROSSCOMPILING=True
    -DCMAKE_EXE_LINKER_FLAGS="-static"
    -DCMAKE_INSTALL_PREFIX="/"
    -DCMAKE_PREFIX_PATH="${COOKBOOK_SYSROOT}"
    -DCMAKE_SYSTEM_NAME=Generic
    -DCMAKE_SYSTEM_PROCESSOR="$(echo "${TARGET}" | cut -d - -f1)"
    -DCMAKE_VERBOSE_MAKEFILE=On
"${COOKBOOK_SOURCE}"
)
cookbook_configure
"""
