#TODO termios crate error
[source]
git = "https://github.com/casey/intermodal"
[build]
template = "custom"
script = """
cookbook_cargo
mv "${COOKBOOK_STAGE}/usr/bin/imdl" "${COOKBOOK_STAGE}/usr/bin/intermodal"
"""
