#TODO program source code error
[source]
git = "https://github.com/orf/gping"
rev = "7547db0d2d8c22cf15066d51fcd41dc57cb5b046"
[build]
template = "custom"
script = """
cookbook_cargo_packages gping
"""
