#TODO Not compiled or tested
[source]
git = "https://github.com/karlstav/cava"
rev = "81211e9e16302312ee4322a99840c110bce0e13d"
[build]
template = "custom"
dependencies = [
    "ncurses",
    "fftw",
]
script = """
export CPPFLAGS="-I${COOKBOOK_SYSROOT}/include/ncurses"
cookbook_configure
"""
