/* Generated by make-libxfce4ui-alias.pl. Do not edit this file. */

#ifdef HAVE_GNUC_VISIBILITY

#include <glib.h>

/* silence '-Wdeprecated-declarations' warnings from our own deprecations */
G_GNUC_BEGIN_IGNORE_DEPRECATIONS

#if 1
#ifdef __LIBXFCE4UI_CONFIG_C__
#undef libxfce4ui_check_version
extern __typeof (libxfce4ui_check_version) libxfce4ui_check_version __attribute((alias("IA__libxfce4ui_check_version"), visibility("default")));

#endif
#endif
#if 1
#ifdef __LIBXFCE4UI_ENUM_TYPES_C__
#undef xfce_sm_client_error_enum_get_type
extern __typeof (xfce_sm_client_error_enum_get_type) xfce_sm_client_error_enum_get_type __attribute((alias("IA__xfce_sm_client_error_enum_get_type"), visibility("default")));

#undef xfce_sm_client_restart_style_get_type
extern __typeof (xfce_sm_client_restart_style_get_type) xfce_sm_client_restart_style_get_type __attribute((alias("IA__xfce_sm_client_restart_style_get_type"), visibility("default")));

#undef xfce_sm_client_shutdown_hint_get_type
extern __typeof (xfce_sm_client_shutdown_hint_get_type) xfce_sm_client_shutdown_hint_get_type __attribute((alias("IA__xfce_sm_client_shutdown_hint_get_type"), visibility("default")));

#endif
#endif
#if 1
#ifdef __XFCE_DIALOGS_C__
#undef xfce_dialog_show_help
extern __typeof (xfce_dialog_show_help) xfce_dialog_show_help __attribute((alias("IA__xfce_dialog_show_help"), visibility("default")));

#undef xfce_dialog_show_help_with_version
extern __typeof (xfce_dialog_show_help_with_version) xfce_dialog_show_help_with_version __attribute((alias("IA__xfce_dialog_show_help_with_version"), visibility("default")));

#undef xfce_dialog_show_info
extern __typeof (xfce_dialog_show_info) xfce_dialog_show_info __attribute((alias("IA__xfce_dialog_show_info"), visibility("default")));

#undef xfce_dialog_show_warning
extern __typeof (xfce_dialog_show_warning) xfce_dialog_show_warning __attribute((alias("IA__xfce_dialog_show_warning"), visibility("default")));

#undef xfce_dialog_show_error
extern __typeof (xfce_dialog_show_error) xfce_dialog_show_error __attribute((alias("IA__xfce_dialog_show_error"), visibility("default")));

#undef xfce_dialog_confirm
extern __typeof (xfce_dialog_confirm) xfce_dialog_confirm __attribute((alias("IA__xfce_dialog_confirm"), visibility("default")));

#undef xfce_dialog_confirm_close_tabs
extern __typeof (xfce_dialog_confirm_close_tabs) xfce_dialog_confirm_close_tabs __attribute((alias("IA__xfce_dialog_confirm_close_tabs"), visibility("default")));

#undef xfce_message_dialog_new
extern __typeof (xfce_message_dialog_new) xfce_message_dialog_new __attribute((alias("IA__xfce_message_dialog_new"), visibility("default")));

#undef xfce_message_dialog_new_valist
extern __typeof (xfce_message_dialog_new_valist) xfce_message_dialog_new_valist __attribute((alias("IA__xfce_message_dialog_new_valist"), visibility("default")));

#undef xfce_message_dialog
extern __typeof (xfce_message_dialog) xfce_message_dialog __attribute((alias("IA__xfce_message_dialog"), visibility("default")));

#endif
#endif
#if 1
#ifdef __XFCE_GDK_EXTENSIONS_C__
#undef xfce_gdk_screen_get_active
extern __typeof (xfce_gdk_screen_get_active) xfce_gdk_screen_get_active __attribute((alias("IA__xfce_gdk_screen_get_active"), visibility("default")));

#undef xfce_gdk_screen_get_geometry
extern __typeof (xfce_gdk_screen_get_geometry) xfce_gdk_screen_get_geometry __attribute((alias("IA__xfce_gdk_screen_get_geometry"), visibility("default")));

#undef xfce_gdk_device_grab
extern __typeof (xfce_gdk_device_grab) xfce_gdk_device_grab __attribute((alias("IA__xfce_gdk_device_grab"), visibility("default")));

#endif
#endif
#if 1
#ifdef __XFCE_GTK_EXTENSIONS_C__
#undef xfce_gtk_menu_item_new
extern __typeof (xfce_gtk_menu_item_new) xfce_gtk_menu_item_new __attribute((alias("IA__xfce_gtk_menu_item_new"), visibility("default")));

#undef xfce_gtk_image_menu_item_new
extern __typeof (xfce_gtk_image_menu_item_new) xfce_gtk_image_menu_item_new __attribute((alias("IA__xfce_gtk_image_menu_item_new"), visibility("default")));

#undef xfce_gtk_image_menu_item_new_from_icon_name
extern __typeof (xfce_gtk_image_menu_item_new_from_icon_name) xfce_gtk_image_menu_item_new_from_icon_name __attribute((alias("IA__xfce_gtk_image_menu_item_new_from_icon_name"), visibility("default")));

#undef xfce_gtk_check_menu_item_new
extern __typeof (xfce_gtk_check_menu_item_new) xfce_gtk_check_menu_item_new __attribute((alias("IA__xfce_gtk_check_menu_item_new"), visibility("default")));

#undef xfce_gtk_radio_menu_item_new
extern __typeof (xfce_gtk_radio_menu_item_new) xfce_gtk_radio_menu_item_new __attribute((alias("IA__xfce_gtk_radio_menu_item_new"), visibility("default")));

#undef xfce_gtk_menu_item_new_from_action_entry
extern __typeof (xfce_gtk_menu_item_new_from_action_entry) xfce_gtk_menu_item_new_from_action_entry __attribute((alias("IA__xfce_gtk_menu_item_new_from_action_entry"), visibility("default")));

#undef xfce_gtk_toggle_menu_item_new_from_action_entry
extern __typeof (xfce_gtk_toggle_menu_item_new_from_action_entry) xfce_gtk_toggle_menu_item_new_from_action_entry __attribute((alias("IA__xfce_gtk_toggle_menu_item_new_from_action_entry"), visibility("default")));

#undef xfce_gtk_tool_button_new_from_action_entry
extern __typeof (xfce_gtk_tool_button_new_from_action_entry) xfce_gtk_tool_button_new_from_action_entry __attribute((alias("IA__xfce_gtk_tool_button_new_from_action_entry"), visibility("default")));

#undef xfce_gtk_toggle_tool_button_new_from_action_entry
extern __typeof (xfce_gtk_toggle_tool_button_new_from_action_entry) xfce_gtk_toggle_tool_button_new_from_action_entry __attribute((alias("IA__xfce_gtk_toggle_tool_button_new_from_action_entry"), visibility("default")));

#undef xfce_gtk_accel_map_add_entries
extern __typeof (xfce_gtk_accel_map_add_entries) xfce_gtk_accel_map_add_entries __attribute((alias("IA__xfce_gtk_accel_map_add_entries"), visibility("default")));

#undef xfce_gtk_accel_group_connect_action_entries
extern __typeof (xfce_gtk_accel_group_connect_action_entries) xfce_gtk_accel_group_connect_action_entries __attribute((alias("IA__xfce_gtk_accel_group_connect_action_entries"), visibility("default")));

#undef xfce_gtk_accel_group_disconnect_action_entries
extern __typeof (xfce_gtk_accel_group_disconnect_action_entries) xfce_gtk_accel_group_disconnect_action_entries __attribute((alias("IA__xfce_gtk_accel_group_disconnect_action_entries"), visibility("default")));

#undef xfce_gtk_get_action_entry_by_id
extern __typeof (xfce_gtk_get_action_entry_by_id) xfce_gtk_get_action_entry_by_id __attribute((alias("IA__xfce_gtk_get_action_entry_by_id"), visibility("default")));

#undef xfce_gtk_translate_action_entries
extern __typeof (xfce_gtk_translate_action_entries) xfce_gtk_translate_action_entries __attribute((alias("IA__xfce_gtk_translate_action_entries"), visibility("default")));

#undef xfce_gtk_handle_tab_accels
extern __typeof (xfce_gtk_handle_tab_accels) xfce_gtk_handle_tab_accels __attribute((alias("IA__xfce_gtk_handle_tab_accels"), visibility("default")));

#undef xfce_gtk_execute_tab_accel
extern __typeof (xfce_gtk_execute_tab_accel) xfce_gtk_execute_tab_accel __attribute((alias("IA__xfce_gtk_execute_tab_accel"), visibility("default")));

#undef xfce_gtk_menu_append_seperator
extern __typeof (xfce_gtk_menu_append_seperator) xfce_gtk_menu_append_seperator __attribute((alias("IA__xfce_gtk_menu_append_seperator"), visibility("default")));

#undef xfce_gtk_menu_append_separator
extern __typeof (xfce_gtk_menu_append_separator) xfce_gtk_menu_append_separator __attribute((alias("IA__xfce_gtk_menu_append_separator"), visibility("default")));

#undef xfce_gtk_button_new_mixed
extern __typeof (xfce_gtk_button_new_mixed) xfce_gtk_button_new_mixed __attribute((alias("IA__xfce_gtk_button_new_mixed"), visibility("default")));

#undef xfce_gtk_frame_box_new
extern __typeof (xfce_gtk_frame_box_new) xfce_gtk_frame_box_new __attribute((alias("IA__xfce_gtk_frame_box_new"), visibility("default")));

#undef xfce_gtk_frame_box_new_with_content
extern __typeof (xfce_gtk_frame_box_new_with_content) xfce_gtk_frame_box_new_with_content __attribute((alias("IA__xfce_gtk_frame_box_new_with_content"), visibility("default")));

#undef xfce_gtk_window_center_on_active_screen
extern __typeof (xfce_gtk_window_center_on_active_screen) xfce_gtk_window_center_on_active_screen __attribute((alias("IA__xfce_gtk_window_center_on_active_screen"), visibility("default")));

#undef xfce_gtk_menu_popup_until_mapped
extern __typeof (xfce_gtk_menu_popup_until_mapped) xfce_gtk_menu_popup_until_mapped __attribute((alias("IA__xfce_gtk_menu_popup_until_mapped"), visibility("default")));

#undef xfce_widget_reparent
extern __typeof (xfce_widget_reparent) xfce_widget_reparent __attribute((alias("IA__xfce_widget_reparent"), visibility("default")));

#undef xfce_icon_name_from_desktop_id
extern __typeof (xfce_icon_name_from_desktop_id) xfce_icon_name_from_desktop_id __attribute((alias("IA__xfce_icon_name_from_desktop_id"), visibility("default")));

#undef xfce_gicon_from_name
extern __typeof (xfce_gicon_from_name) xfce_gicon_from_name __attribute((alias("IA__xfce_gicon_from_name"), visibility("default")));

#undef xfce_gtk_menu_item_set_accel_label
extern __typeof (xfce_gtk_menu_item_set_accel_label) xfce_gtk_menu_item_set_accel_label __attribute((alias("IA__xfce_gtk_menu_item_set_accel_label"), visibility("default")));

#undef xfce_has_gtk_frame_extents
extern __typeof (xfce_has_gtk_frame_extents) xfce_has_gtk_frame_extents __attribute((alias("IA__xfce_has_gtk_frame_extents"), visibility("default")));

#undef xfce_gtk_label_set_a11y_relation
extern __typeof (xfce_gtk_label_set_a11y_relation) xfce_gtk_label_set_a11y_relation __attribute((alias("IA__xfce_gtk_label_set_a11y_relation"), visibility("default")));

#endif
#endif
#if 1
#ifdef __XFCE_SPAWN_C__
#undef xfce_spawn_on_screen_with_child_watch
extern __typeof (xfce_spawn_on_screen_with_child_watch) xfce_spawn_on_screen_with_child_watch __attribute((alias("IA__xfce_spawn_on_screen_with_child_watch"), visibility("default")));

#undef xfce_spawn_on_screen
extern __typeof (xfce_spawn_on_screen) xfce_spawn_on_screen __attribute((alias("IA__xfce_spawn_on_screen"), visibility("default")));

#undef xfce_spawn
extern __typeof (xfce_spawn) xfce_spawn __attribute((alias("IA__xfce_spawn"), visibility("default")));

#undef xfce_spawn_command_line_on_screen
extern __typeof (xfce_spawn_command_line_on_screen) xfce_spawn_command_line_on_screen __attribute((alias("IA__xfce_spawn_command_line_on_screen"), visibility("default")));

#undef xfce_spawn_command_line
extern __typeof (xfce_spawn_command_line) xfce_spawn_command_line __attribute((alias("IA__xfce_spawn_command_line"), visibility("default")));

#endif
#endif
#if 1
#ifdef __XFCE_FILENAME_INPUT_C__
#undef xfce_filename_input_get_type
extern __typeof (xfce_filename_input_get_type) xfce_filename_input_get_type __attribute((alias("IA__xfce_filename_input_get_type"), visibility("default")));

#undef xfce_filename_input_get_text
extern __typeof (xfce_filename_input_get_text) xfce_filename_input_get_text __attribute((alias("IA__xfce_filename_input_get_text"), visibility("default")));

#undef xfce_filename_input_check
extern __typeof (xfce_filename_input_check) xfce_filename_input_check __attribute((alias("IA__xfce_filename_input_check"), visibility("default")));

#undef xfce_filename_input_get_entry
extern __typeof (xfce_filename_input_get_entry) xfce_filename_input_get_entry __attribute((alias("IA__xfce_filename_input_get_entry"), visibility("default")));

#undef xfce_filename_input_sensitise_widget
extern __typeof (xfce_filename_input_sensitise_widget) xfce_filename_input_sensitise_widget __attribute((alias("IA__xfce_filename_input_sensitise_widget"), visibility("default")));

#undef xfce_filename_input_desensitise_widget
extern __typeof (xfce_filename_input_desensitise_widget) xfce_filename_input_desensitise_widget __attribute((alias("IA__xfce_filename_input_desensitise_widget"), visibility("default")));

#endif
#endif
#if 1
#ifdef __XFCE_SM_CLIENT_C__
#undef xfce_sm_client_get_type
extern __typeof (xfce_sm_client_get_type) xfce_sm_client_get_type __attribute((alias("IA__xfce_sm_client_get_type"), visibility("default")));

#undef xfce_sm_client_get_option_group
extern __typeof (xfce_sm_client_get_option_group) xfce_sm_client_get_option_group __attribute((alias("IA__xfce_sm_client_get_option_group"), visibility("default")));

#undef xfce_sm_client_get
extern __typeof (xfce_sm_client_get) xfce_sm_client_get __attribute((alias("IA__xfce_sm_client_get"), visibility("default")));

#undef xfce_sm_client_get_with_argv
extern __typeof (xfce_sm_client_get_with_argv) xfce_sm_client_get_with_argv __attribute((alias("IA__xfce_sm_client_get_with_argv"), visibility("default")));

#undef xfce_sm_client_get_full
extern __typeof (xfce_sm_client_get_full) xfce_sm_client_get_full __attribute((alias("IA__xfce_sm_client_get_full"), visibility("default")));

#undef xfce_sm_client_connect
extern __typeof (xfce_sm_client_connect) xfce_sm_client_connect __attribute((alias("IA__xfce_sm_client_connect"), visibility("default")));

#undef xfce_sm_client_disconnect
extern __typeof (xfce_sm_client_disconnect) xfce_sm_client_disconnect __attribute((alias("IA__xfce_sm_client_disconnect"), visibility("default")));

#undef xfce_sm_client_error_quark
extern __typeof (xfce_sm_client_error_quark) xfce_sm_client_error_quark __attribute((alias("IA__xfce_sm_client_error_quark"), visibility("default")));

#undef xfce_sm_client_is_connected
extern __typeof (xfce_sm_client_is_connected) xfce_sm_client_is_connected __attribute((alias("IA__xfce_sm_client_is_connected"), visibility("default")));

#undef xfce_sm_client_is_resumed
extern __typeof (xfce_sm_client_is_resumed) xfce_sm_client_is_resumed __attribute((alias("IA__xfce_sm_client_is_resumed"), visibility("default")));

#undef xfce_sm_client_set_desktop_file
extern __typeof (xfce_sm_client_set_desktop_file) xfce_sm_client_set_desktop_file __attribute((alias("IA__xfce_sm_client_set_desktop_file"), visibility("default")));

#undef xfce_sm_client_request_shutdown
extern __typeof (xfce_sm_client_request_shutdown) xfce_sm_client_request_shutdown __attribute((alias("IA__xfce_sm_client_request_shutdown"), visibility("default")));

#undef xfce_sm_client_get_client_id
extern __typeof (xfce_sm_client_get_client_id) xfce_sm_client_get_client_id __attribute((alias("IA__xfce_sm_client_get_client_id"), visibility("default")));

#undef xfce_sm_client_get_state_file
extern __typeof (xfce_sm_client_get_state_file) xfce_sm_client_get_state_file __attribute((alias("IA__xfce_sm_client_get_state_file"), visibility("default")));

#undef xfce_sm_client_set_restart_style
extern __typeof (xfce_sm_client_set_restart_style) xfce_sm_client_set_restart_style __attribute((alias("IA__xfce_sm_client_set_restart_style"), visibility("default")));

#undef xfce_sm_client_get_restart_style
extern __typeof (xfce_sm_client_get_restart_style) xfce_sm_client_get_restart_style __attribute((alias("IA__xfce_sm_client_get_restart_style"), visibility("default")));

#undef xfce_sm_client_set_priority
extern __typeof (xfce_sm_client_set_priority) xfce_sm_client_set_priority __attribute((alias("IA__xfce_sm_client_set_priority"), visibility("default")));

#undef xfce_sm_client_get_priority
extern __typeof (xfce_sm_client_get_priority) xfce_sm_client_get_priority __attribute((alias("IA__xfce_sm_client_get_priority"), visibility("default")));

#undef xfce_sm_client_set_restart_command
extern __typeof (xfce_sm_client_set_restart_command) xfce_sm_client_set_restart_command __attribute((alias("IA__xfce_sm_client_set_restart_command"), visibility("default")));

#undef xfce_sm_client_get_restart_command
extern __typeof (xfce_sm_client_get_restart_command) xfce_sm_client_get_restart_command __attribute((alias("IA__xfce_sm_client_get_restart_command"), visibility("default")));

#undef xfce_sm_client_set_current_directory
extern __typeof (xfce_sm_client_set_current_directory) xfce_sm_client_set_current_directory __attribute((alias("IA__xfce_sm_client_set_current_directory"), visibility("default")));

#undef xfce_sm_client_get_current_directory
extern __typeof (xfce_sm_client_get_current_directory) xfce_sm_client_get_current_directory __attribute((alias("IA__xfce_sm_client_get_current_directory"), visibility("default")));

#endif
#endif
#if 1
#ifdef __XFCE_TITLED_DIALOG_C__
#undef xfce_titled_dialog_get_type
extern __typeof (xfce_titled_dialog_get_type) xfce_titled_dialog_get_type __attribute((alias("IA__xfce_titled_dialog_get_type"), visibility("default")));

#undef xfce_titled_dialog_new
extern __typeof (xfce_titled_dialog_new) xfce_titled_dialog_new __attribute((alias("IA__xfce_titled_dialog_new"), visibility("default")));

#undef xfce_titled_dialog_new_with_buttons
extern __typeof (xfce_titled_dialog_new_with_buttons) xfce_titled_dialog_new_with_buttons __attribute((alias("IA__xfce_titled_dialog_new_with_buttons"), visibility("default")));

#undef xfce_titled_dialog_new_with_mixed_buttons
extern __typeof (xfce_titled_dialog_new_with_mixed_buttons) xfce_titled_dialog_new_with_mixed_buttons __attribute((alias("IA__xfce_titled_dialog_new_with_mixed_buttons"), visibility("default")));

#undef xfce_titled_dialog_get_subtitle
extern __typeof (xfce_titled_dialog_get_subtitle) xfce_titled_dialog_get_subtitle __attribute((alias("IA__xfce_titled_dialog_get_subtitle"), visibility("default")));

#undef xfce_titled_dialog_set_subtitle
extern __typeof (xfce_titled_dialog_set_subtitle) xfce_titled_dialog_set_subtitle __attribute((alias("IA__xfce_titled_dialog_set_subtitle"), visibility("default")));

#undef xfce_titled_dialog_create_action_area
extern __typeof (xfce_titled_dialog_create_action_area) xfce_titled_dialog_create_action_area __attribute((alias("IA__xfce_titled_dialog_create_action_area"), visibility("default")));

#undef xfce_titled_dialog_add_button
extern __typeof (xfce_titled_dialog_add_button) xfce_titled_dialog_add_button __attribute((alias("IA__xfce_titled_dialog_add_button"), visibility("default")));

#undef xfce_titled_dialog_add_action_widget
extern __typeof (xfce_titled_dialog_add_action_widget) xfce_titled_dialog_add_action_widget __attribute((alias("IA__xfce_titled_dialog_add_action_widget"), visibility("default")));

#undef xfce_titled_dialog_set_default_response
extern __typeof (xfce_titled_dialog_set_default_response) xfce_titled_dialog_set_default_response __attribute((alias("IA__xfce_titled_dialog_set_default_response"), visibility("default")));

#endif
#endif

G_GNUC_END_IGNORE_DEPRECATIONS

#endif /* HAVE_GNUC_VISIBILITY */
