#TODO probably wrong script, see https://github.com/dolphin-emu/dolphin/wiki/Building-for-Linux
#TODO probably missing dependencies
[source]
git = "https://github.com/dolphin-emu/dolphin"
[build]
template = "custom"
dependencies = [
    "ffmpeg6",
    "libevdev",
    "libusb",
    "pango",
    "cairo",
    "qt6-base",
    "qt6-svg",
    "mesa",
    "curl",
    "libvulkan",
    "openal",
]
script = """
COOKBOOK_CONFIGURE="cmake"
COOKBOOK_CONFIGURE_FLAGS=(
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_CROSSCOMPILING=True
    -DCMAKE_EXE_LINKER_FLAGS="-static"
    -DCMAKE_INSTALL_PREFIX="/"
    -DCMAKE_PREFIX_PATH="${COOKBOOK_SYSROOT}"
    -DCMAKE_SYSTEM_NAME=Generic
    -DCMAKE_SYSTEM_PROCESSOR="$(echo "${TARGET}" | cut -d - -f1)"
    -DCMAKE_VERBOSE_MAKEFILE=On
"${COOKBOOK_SOURCE}"
)
cookbook_configure
"""
