[package]
name = "virtio-netd"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
static_assertions = "1.1.0"
futures = { version = "0.3.28", features = ["executor"] }

virtio-core = { path = "../../virtio-core" }
pcid = { path = "../../pcid" }
common = { path = "../../common" }
driver-network = { path = "../driver-network" }

redox-daemon = "0.1"
redox_syscall = "0.5"
libredox = "0.1.3"
