#TODO ncurses crate error
[source]
git = "https://github.com/hrkfdn/ncspot"
rev = "92e0852b3796601f406ebfdd697635ea63566a31"
[build]
template = "custom"
dependencies = [
    "openssl1",
    "ncurses",
]
script = """
export CPPFLAGS="-I${COOKBOOK_SYSROOT}/include/ncurses"
cookbook_cargo --features rodio_backend,pancurses_backend
"""
