#TODO port to Orbital
[source]
git = "https://github.com/AmmarAbouZor/tui-journal"
rev = "40943d8b4081d61cd549398ff68c6f219444167b"
[build]
template = "cargo"
dependencies = [
    "openssl1",
    "sqlite3",
]
