#TODO Not compiled or tested
[source]
tar = "https://github.com/Qalculate/qalculate-gtk/releases/download/v4.9.0/qalculate-gtk-4.9.0.tar.gz"
[build]
template = "configure"
dependencies = [
    "gtk3",
    "libqalculate",
]
