/* automatically generated from applicationsmenu-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (applicationsmenu_dialog_ui)
#endif
#ifdef __GNUC__
static const char applicationsmenu_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char applicationsmenu_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><requires lib=\"libxfce4ui-2\" version=\"4.12\"/"
  "><object class=\"GtkImage\" id=\"image1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"icon_name\">alacarte</property></object><object class=\"GtkImage\" "
  "id=\"image2\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"icon_name\">help-browser"
  "</property></object><object class=\"GtkImage\" id=\"image3\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"icon_name\">window-close-symbolic</property></ob"
  "ject><object class=\"XfceTitledDialog\" id=\"dialog\"><property name=\""
  "can_focus\">False</property><property name=\"title\" translatable=\"yes"
  "\">Applications Menu</property><property name=\"icon_name\">org.xfce.pa"
  "nel.applicationsmenu</property><property name=\"type_hint\">normal</pro"
  "perty><child internal-child=\"vbox\"><object class=\"GtkBox\" id=\"dial"
  "og-vbox2\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"orientation\">vertical</pro"
  "perty><property name=\"spacing\">2</property><child internal-child=\"ac"
  "tion_area\"><object class=\"GtkButtonBox\" id=\"dialog-action_area2\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"layout_style\">end</property><child><ob"
  "ject class=\"GtkButton\" id=\"help-button\"><property name=\"label\" tr"
  "anslatable=\"yes\">_Help</property><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"rece"
  "ives_default\">True</property><property name=\"image\">image2</property"
  "><property name=\"use_underline\">True</property></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">False</pr"
  "operty><property name=\"position\">0</property><property name=\"seconda"
  "ry\">True</property></packing></child><child><object class=\"GtkButton\""
  " id=\"close-button\"><property name=\"label\" translatable=\"yes\">_Clo"
  "se</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">True</pr"
  "operty><property name=\"image\">image3</property><property name=\"use_u"
  "nderline\">True</property></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">False</property><property name=\""
  "position\">1</property></packing></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"pack_type\">end</property><property name=\"position\">0"
  "</property></packing></child><child><object class=\"GtkBox\" id=\"vbox1"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"border_width\">6</property><propert"
  "y name=\"orientation\">vertical</property><property name=\"spacing\">6<"
  "/property><child><object class=\"GtkFrame\" id=\"frame3\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"label_xalign\">0</property><property name=\"shadow_"
  "type\">none</property><child><object class=\"GtkGrid\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"margin_left\">18</property><property name=\"row_spacing"
  "\">6</property><property name=\"column_spacing\">12</property><child><o"
  "bject class=\"GtkLabel\" id=\"label4\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "label\" translatable=\"yes\">_Icon:</property><property name=\"use_unde"
  "rline\">True</property><property name=\"xalign\">0</property></object><"
  "packing><property name=\"left_attach\">0</property><property name=\"top"
  "_attach\">6</property></packing></child><child><object class=\"GtkEntry"
  "\" id=\"button-title\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"invisible_char\""
  ">\342\200\242</property></object><packing><property name=\"left_attach\""
  ">1</property><property name=\"top_attach\">5</property></packing></chil"
  "d><child><object class=\"GtkLabel\" id=\"label2\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"label\" translatable=\"yes\">Button _title:</property><prop"
  "erty name=\"use_underline\">True</property><property name=\"xalign\">0<"
  "/property></object><packing><property name=\"left_attach\">0</property>"
  "<property name=\"top_attach\">5</property></packing></child><child><obj"
  "ect class=\"GtkCheckButton\" id=\"small\"><property name=\"label\" tran"
  "slatable=\"yes\">Show button on one _line</property><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"receives_default\">False</property><property name=\"use_un"
  "derline\">True</property><property name=\"draw_indicator\">True</proper"
  "ty></object><packing><property name=\"left_attach\">0</property><proper"
  "ty name=\"top_attach\">4</property><property name=\"width\">2</property"
  "></packing></child><child><object class=\"GtkCheckButton\" id=\"show-bu"
  "tton-title\"><property name=\"label\" translatable=\"yes\">_Show button"
  " title</property><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">True</property><property name=\"receives_default\">Fal"
  "se</property><property name=\"use_underline\">True</property><property "
  "name=\"draw_indicator\">True</property></object><packing><property name"
  "=\"left_attach\">0</property><property name=\"top_attach\">3</property>"
  "<property name=\"width\">2</property></packing></child><child><object c"
  "lass=\"GtkCheckButton\" id=\"show-tooltips\"><property name=\"label\" t"
  "ranslatable=\"yes\">Show application d_escription in tooltip</property>"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "True</property><property name=\"receives_default\">False</property><pro"
  "perty name=\"use_underline\">True</property><property name=\"image_posi"
  "tion\">right</property><property name=\"draw_indicator\">True</property"
  "></object><packing><property name=\"left_attach\">0</property><property"
  " name=\"top_attach\">2</property><property name=\"width\">2</property><"
  "/packing></child><child><object class=\"GtkCheckButton\" id=\"show-menu"
  "-icons\"><property name=\"label\" translatable=\"yes\">Show ic_ons in m"
  "enu</property><property name=\"visible\">True</property><property name="
  "\"can_focus\">True</property><property name=\"receives_default\">False<"
  "/property><property name=\"use_underline\">True</property><property nam"
  "e=\"draw_indicator\">True</property></object><packing><property name=\""
  "left_attach\">0</property><property name=\"top_attach\">1</property><pr"
  "operty name=\"width\">2</property></packing></child><child><object clas"
  "s=\"GtkCheckButton\" id=\"show-generic-names\"><property name=\"label\""
  " translatable=\"yes\">Show generic application n_ames</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"receives_default\">False</property><property n"
  "ame=\"tooltip_text\" translatable=\"yes\">Select this option to show th"
  "e generic application name in the menu, for example \"File Manager\" in"
  "stead of \"Thunar\"</property><property name=\"use_underline\">True</pr"
  "operty><property name=\"draw_indicator\">True</property></object><packi"
  "ng><property name=\"left_attach\">0</property><property name=\"top_atta"
  "ch\">0</property><property name=\"width\">2</property></packing></child"
  "><child><object class=\"GtkButton\" id=\"icon-button\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">True</property><property name=\"halig"
  "n\">start</property><child><placeholder/></child></object><packing><pro"
  "perty name=\"left_attach\">1</property><property name=\"top_attach\">6<"
  "/property></packing></child></object></child><child type=\"label\"><obj"
  "ect class=\"GtkLabel\" id=\"label1\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"l"
  "abel\" translatable=\"yes\">Appearance</property><attributes><attribute"
  " name=\"weight\" value=\"bold\"/></attributes></object></child></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">0</property></packing><"
  "/child><child><object class=\"GtkFrame\" id=\"frame1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label_xalign\">0</property><property name=\"shadow_type"
  "\">none</property><child><object class=\"GtkAlignment\" id=\"alignment1"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"left_padding\">12</property><child>"
  "<object class=\"GtkBox\" id=\"vbox2\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "border_width\">6</property><property name=\"orientation\">vertical</pro"
  "perty><property name=\"spacing\">6</property><child><object class=\"Gtk"
  "Box\" id=\"hbox1\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"spacing\">12</prope"
  "rty><child><object class=\"GtkRadioButton\" id=\"use-default-menu\"><pr"
  "operty name=\"label\" translatable=\"yes\">Use the _default menu</prope"
  "rty><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">True</property><property name=\"receives_default\">False</property>"
  "<property name=\"use_underline\">True</property><property name=\"draw_i"
  "ndicator\">True</property></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">True</property><property name=\""
  "position\">0</property></packing></child><child><object class=\"GtkButt"
  "on\" id=\"edit-menu-button\"><property name=\"label\" translatable=\"ye"
  "s\">Ed_it Menu</property><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">True</property><property name=\"receives_defau"
  "lt\">True</property><property name=\"image\">image1</property><property"
  " name=\"use_underline\">True</property></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">True</property><pro"
  "perty name=\"position\">1</property></packing></child></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">True"
  "</property><property name=\"position\">0</property></packing></child><c"
  "hild><object class=\"GtkRadioButton\" id=\"use-custom-menu\"><property "
  "name=\"label\" translatable=\"yes\">Use c_ustom menu file:</property><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Tr"
  "ue</property><property name=\"receives_default\">False</property><prope"
  "rty name=\"use_underline\">True</property><property name=\"active\">Tru"
  "e</property><property name=\"draw_indicator\">True</property><property "
  "name=\"group\">use-default-menu</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">True</property><"
  "property name=\"position\">1</property></packing></child><child><object"
  " class=\"GtkAlignment\" id=\"alignment5\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"left_padding\">22</property><child><object class=\"GtkHBox\" id=\"c"
  "ustom-box\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"spacing\">12</property><ch"
  "ild><object class=\"GtkLabel\" id=\"label5\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">Menu _file:</property><property nam"
  "e=\"use_underline\">True</property></object><packing><property name=\"e"
  "xpand\">False</property><property name=\"fill\">True</property><propert"
  "y name=\"position\">0</property></packing></child><child><object class="
  "\"GtkFileChooserButton\" id=\"custom-file\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"title\" translatable=\"yes\">Select A Menu File</property></objec"
  "t><packing><property name=\"expand\">True</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">1</property></packing><"
  "/child></object></child></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">2</property></packing></child></object></child></object></chil"
  "d><child type=\"label\"><object class=\"GtkLabel\" id=\"label3\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"label\" translatable=\"yes\">Menu File</prop"
  "erty><attributes><attribute name=\"weight\" value=\"bold\"/></attribute"
  "s></object></child></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"fill\">True</property><property name=\"positio"
  "n\">1</property></packing></child></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">True</property><property"
  " name=\"position\">1</property></packing></child></object></child><acti"
  "on-widgets><action-widget response=\"0\">help-button</action-widget><ac"
  "tion-widget response=\"0\">close-button</action-widget></action-widgets"
  "></object><object class=\"GtkSizeGroup\" id=\"sizegroup1\"/></interface"
  ">"
};

static const unsigned applicationsmenu_dialog_ui_length = 12645u;

