#TODO compiled but not tested (after cargo update)
#TODO missing script to properly move th binary
[source]
git = "https://github.com/the-lean-crate/criner"
[build]
template = "custom"
dependencies = [
    "openssl1",
]
script = """
cookbook_cargo_packages criner
"""
