/* automatically generated from xfce4-session-settings.ui */
#ifdef __SUNPRO_C
#pragma align 4 (xfce4_session_settings_ui)
#endif
#ifdef __GNUC__
static const char xfce4_session_settings_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfce4_session_settings_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.12\"/><requires lib=\"libxfce4ui-2\" version=\"4.12\"/"
  "><object class=\"GtkImage\" id=\"image1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"icon_name\">edit-clear-symbolic</property></object><object class=\""
  "GtkImage\" id=\"image2\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"icon_name\">d"
  "ocument-save-symbolic</property></object><object class=\"GtkImage\" id="
  "\"image3\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"icon_name\">list-remove-sym"
  "bolic</property></object><object class=\"GtkImage\" id=\"image4\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"icon_name\">list-remove-symbolic</property>"
  "</object><object class=\"GtkImage\" id=\"image5\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"icon_name\">window-close-symbolic</property></object><objec"
  "t class=\"GtkImage\" id=\"image7\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"ico"
  "n_name\">help-browser</property></object><object class=\"GtkImage\" id="
  "\"image8\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"icon_name\">window-close-sy"
  "mbolic</property></object><object class=\"GtkPopover\" id=\"session-inf"
  "o\"><property name=\"can_focus\">False</property><child><object class=\""
  "GtkLabel\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"margin_left\">12</property>"
  "<property name=\"margin_right\">12</property><property name=\"margin_to"
  "p\">12</property><property name=\"margin_bottom\">12</property><propert"
  "y name=\"label\" translatable=\"yes\">These applications are a part of "
  "the currently-running session,\nand can be saved now or when you log ou"
  "t.\nChanges below will only take effect when the session is saved.</pro"
  "perty><property name=\"use_markup\">True</property><property name=\"xal"
  "ign\">0</property></object></child></object><object class=\"XfceTitledD"
  "ialog\" id=\"xfce4_session_settings_dialog\"><property name=\"can_focus"
  "\">False</property><property name=\"title\" translatable=\"yes\">Sessio"
  "n and Startup</property><property name=\"window_position\">center-on-pa"
  "rent</property><property name=\"default_width\">600</property><property"
  " name=\"default_height\">500</property><property name=\"icon_name\">org"
  ".xfce.session</property><property name=\"type_hint\">dialog</property><"
  "child internal-child=\"vbox\"><object class=\"GtkBox\" id=\"dialog-vbox"
  "1\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"orientation\">vertical</property><"
  "property name=\"spacing\">2</property><child internal-child=\"action_ar"
  "ea\"><object class=\"GtkButtonBox\" id=\"dialog-action_area1\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><child><object class=\"GtkButton\" id=\"button1\"><property nam"
  "e=\"label\" translatable=\"yes\">_Help</property><property name=\"use_a"
  "ction_appearance\">False</property><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"rece"
  "ives_default\">True</property><property name=\"image\">image7</property"
  "><property name=\"use_underline\">True</property></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">False</pr"
  "operty><property name=\"position\">0</property></packing></child><child"
  "><object class=\"GtkButton\" id=\"button2\"><property name=\"label\" tr"
  "anslatable=\"yes\">_Close</property><property name=\"use_action_appeara"
  "nce\">False</property><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"receives_default\""
  ">True</property><property name=\"image\">image5</property><property nam"
  "e=\"use_underline\">True</property></object><packing><property name=\"e"
  "xpand\">False</property><property name=\"fill\">False</property><proper"
  "ty name=\"position\">1</property></packing></child></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">True</p"
  "roperty><property name=\"pack_type\">end</property><property name=\"pos"
  "ition\">1</property></packing></child><child><object class=\"GtkNoteboo"
  "k\" id=\"plug-child\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"border_width\">6<"
  "/property><child><object class=\"GtkBox\" id=\"vbox1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"valign\">start</property><property name=\"border_width\""
  ">12</property><property name=\"orientation\">vertical</property><proper"
  "ty name=\"spacing\">18</property><child><object class=\"GtkFrame\" id=\""
  "frame1\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label_xalign\">0</property><p"
  "roperty name=\"shadow_type\">none</property><child><object class=\"GtkA"
  "lignment\" id=\"alignment2\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"top_paddi"
  "ng\">6</property><property name=\"left_padding\">12</property><child><o"
  "bject class=\"GtkCheckButton\" id=\"chk_display_chooser\"><property nam"
  "e=\"label\" translatable=\"yes\">_Display chooser on login</property><p"
  "roperty name=\"use_action_appearance\">False</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">False</property><property name=\"tool"
  "tip_text\" translatable=\"yes\">Display the session chooser every time "
  "Xfce starts</property><property name=\"use_underline\">True</property><"
  "property name=\"xalign\">0.5</property><property name=\"draw_indicator\""
  ">True</property></object></child></object></child><child type=\"label\""
  "><object class=\"GtkLabel\" id=\"label6\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"label\" translatable=\"yes\">&lt;b&gt;Session Chooser&lt;/b&gt;</pr"
  "operty><property name=\"use_markup\">True</property></object></child></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">True</property><property name=\"position\">0</property></pac"
  "king></child><child><object class=\"GtkFrame\" id=\"frame2\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"label_xalign\">0</property><property name=\"shad"
  "ow_type\">none</property><child><object class=\"GtkAlignment\" id=\"ali"
  "gnment3\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"top_padding\">6</property><p"
  "roperty name=\"left_padding\">12</property><child><object class=\"GtkBo"
  "x\" id=\"vbox2\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"orientation\">vertica"
  "l</property><property name=\"spacing\">6</property><child><object class"
  "=\"GtkCheckButton\" id=\"chk_session_autosave\"><property name=\"label\""
  " translatable=\"yes\">Automatically save session on logo_ut</property><"
  "property name=\"use_action_appearance\">False</property><property name="
  "\"visible\">True</property><property name=\"can_focus\">True</property>"
  "<property name=\"receives_default\">False</property><property name=\"to"
  "oltip_text\" translatable=\"yes\">Always save the session when logging "
  "out</property><property name=\"use_underline\">True</property><property"
  " name=\"xalign\">0.5</property><property name=\"draw_indicator\">True</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">0</pro"
  "perty></packing></child><child><object class=\"GtkCheckButton\" id=\"ch"
  "k_logout_prompt\"><property name=\"label\" translatable=\"yes\">Pro_mpt"
  " on logout</property><property name=\"use_action_appearance\">False</pr"
  "operty><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">True</property><property name=\"receives_default\">False</proper"
  "ty><property name=\"tooltip_text\" translatable=\"yes\">Prompt for conf"
  "irmation when logging out</property><property name=\"use_underline\">Tr"
  "ue</property><property name=\"xalign\">0.5</property><property name=\"a"
  "ctive\">True</property><property name=\"draw_indicator\">True</property"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">True</property><property name=\"position\">1</property></"
  "packing></child></object></child></object></child><child type=\"label\""
  "><object class=\"GtkLabel\" id=\"label7\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"label\" translatable=\"yes\">&lt;b&gt;Logout Settings&lt;/b&gt;</pr"
  "operty><property name=\"use_markup\">True</property></object></child></"
  "object><packing><property name=\"expand\">True</property><property name"
  "=\"fill\">True</property><property name=\"position\">1</property></pack"
  "ing></child><child><object class=\"GtkFrame\" id=\"frame5\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"label_xalign\">0</property><property name=\"shado"
  "w_type\">none</property><child><object class=\"GtkAlignment\" id=\"alig"
  "nment1\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"top_padding\">6</property><pr"
  "operty name=\"left_padding\">12</property><child><object class=\"GtkBox"
  "\" id=\"vbox6\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"orientation\">vertical"
  "</property><property name=\"spacing\">6</property><child><object class="
  "\"GtkCheckButton\" id=\"chk_lock_screen\"><property name=\"label\" tran"
  "slatable=\"yes\">Lock screen be_fore sleep</property><property name=\"u"
  "se_action_appearance\">False</property><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">False</property><property name=\"tooltip_text\" tran"
  "slatable=\"yes\">Run xflock4 before suspending or hibernating the syste"
  "m</property><property name=\"use_underline\">True</property><property n"
  "ame=\"xalign\">0</property><property name=\"draw_indicator\">True</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">True</property><property name=\"position\">0</propert"
  "y></packing></child></object></child></object></child><child type=\"lab"
  "el\"><object class=\"GtkLabel\" id=\"label25\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"label\" translatable=\"yes\">&lt;b&gt;Shutdown&lt;/b&gt;</prop"
  "erty><property name=\"use_markup\">True</property></object></child></ob"
  "ject><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">2</property></packing"
  "></child></object></child><child type=\"tab\"><object class=\"GtkLabel\""
  " id=\"label1\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\">_General</property><property name=\"use_underline\">True</propert"
  "y></object><packing><property name=\"tab_fill\">False</property></packi"
  "ng></child><child><object class=\"GtkBox\" id=\"vbox8\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"border_width\">12</property><property name=\"orientat"
  "ion\">vertical</property><child><object class=\"GtkInfoBar\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><child internal-child=\"action_area\"><object class=\"GtkButtonBo"
  "x\"><property name=\"can_focus\">False</property><property name=\"spaci"
  "ng\">6</property><property name=\"layout_style\">end</property><child><"
  "object class=\"GtkButton\" id=\"btn_save_session\"><property name=\"lab"
  "el\" translatable=\"yes\">Save Sess_ion</property><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"receives_default\">True</property><property name=\"valign\">"
  "center</property><property name=\"image\">image2</property><property na"
  "me=\"use_underline\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">True</property><proper"
  "ty name=\"pack_type\">end</property><property name=\"position\">0</prop"
  "erty></packing></child><child><object class=\"GtkMenuButton\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"receives_default\">True</property><property name"
  "=\"popover\">session-info</property><child><object class=\"GtkImage\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"icon_name\">dialog-information-symbolic"
  "</property></object></child><style><class name=\"circular\"/></style></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">True</property><property name=\"pack_type\">end</property><p"
  "roperty name=\"position\">1</property><property name=\"non_homogeneous\""
  ">True</property></packing></child></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">False</property><propert"
  "y name=\"position\">0</property></packing></child><child internal-child"
  "=\"content_area\"><object class=\"GtkBox\"><property name=\"can_focus\""
  ">False</property><child><object class=\"GtkLabel\" id=\"label_active_se"
  "ssion\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"label\" translatable=\"yes\">C"
  "urrently active session: &lt;b&gt;Default&lt;/b&gt;</property><property"
  " name=\"use_markup\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">True</property><proper"
  "ty name=\"position\">0</property></packing></child></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">False</"
  "property><property name=\"position\">0</property></packing></child><chi"
  "ld><placeholder/></child></object><packing><property name=\"expand\">Fa"
  "lse</property><property name=\"fill\">True</property><property name=\"p"
  "osition\">1</property></packing></child><child><object class=\"GtkScrol"
  "ledWindow\" id=\"scrolledwindow4\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"shad"
  "ow_type\">etched-in</property><child><object class=\"GtkTreeView\" id=\""
  "treeview_clients\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><child internal-child=\"selection\"><"
  "object class=\"GtkTreeSelection\" id=\"treeview-selection2\"/></child><"
  "/object></child></object><packing><property name=\"expand\">True</prope"
  "rty><property name=\"fill\">True</property><property name=\"position\">"
  "2</property></packing></child><child><object class=\"GtkBox\" id=\"hbox"
  "7\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"spacing\">6</property><child><obje"
  "ct class=\"GtkBox\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><child><placeholder/></child><child"
  "><object class=\"GtkButton\" id=\"btn_quit_client\"><property name=\"la"
  "bel\" translatable=\"yes\">_Quit Program</property><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">True</property><prop"
  "erty name=\"receives_default\">True</property><property name=\"image\">"
  "image3</property><property name=\"use_underline\">True</property></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">1</property></packing"
  "></child><style><class name=\"inline-toolbar\"/></style></object><packi"
  "ng><property name=\"expand\">True</property><property name=\"fill\">Tru"
  "e</property><property name=\"pack_type\">end</property><property name=\""
  "position\">3</property></packing></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">True</property><p"
  "roperty name=\"position\">3</property></packing></child></object><packi"
  "ng><property name=\"position\">1</property></packing></child><child typ"
  "e=\"tab\"><object class=\"GtkLabel\" id=\"label3\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"label\" translatable=\"yes\">Current Sessio_n</property><p"
  "roperty name=\"use_underline\">True</property></object><packing><proper"
  "ty name=\"position\">1</property><property name=\"tab_fill\">False</pro"
  "perty></packing></child><child><object class=\"GtkBox\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"border_width\">12</property><property name=\"orientat"
  "ion\">vertical</property><child><object class=\"GtkBox\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"orientation\">vertical</property><child><object clas"
  "s=\"GtkScrolledWindow\" id=\"saved-sessions\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"shadow_type\">in</property><child><object class=\"GtkTreeView\" i"
  "d=\"saved-sessions-list\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">True</property><child internal-child=\"select"
  "ion\"><object class=\"GtkTreeSelection\"/></child></object></child></ob"
  "ject><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkBox\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><child><object"
  " class=\"GtkBox\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"orientation\">vertic"
  "al</property><child><object class=\"GtkButton\" id=\"btn_delete_session"
  "\"><property name=\"label\" translatable=\"yes\">_Remove</property><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">True"
  "</property><property name=\"receives_default\">True</property><property"
  " name=\"tooltip_text\" translatable=\"yes\">Delete the selected session"
  "</property><property name=\"image\">image4</property><property name=\"u"
  "se_underline\">True</property></object><packing><property name=\"expand"
  "\">False</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">0</property></packing></child></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">0</property></packing></child><child><obj"
  "ect class=\"GtkBox\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"orientation\">ver"
  "tical</property><child><object class=\"GtkButton\" id=\"btn_clear_sessi"
  "ons\"><property name=\"label\" translatable=\"yes\">Clear Save_d Sessio"
  "ns</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">True</pr"
  "operty><property name=\"halign\">end</property><property name=\"valign\""
  ">center</property><property name=\"image\">image1</property><property n"
  "ame=\"use_underline\">True</property><property name=\"always_show_image"
  "\">True</property></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">0</property></packing></child></object><packing><property name=\"exp"
  "and\">False</property><property name=\"fill\">False</property><property"
  " name=\"pack_type\">end</property><property name=\"position\">1</proper"
  "ty></packing></child><style><class name=\"inline-toolbar\"/></style></o"
  "bject><packing><property name=\"expand\">False</property><property name"
  "=\"fill\">True</property><property name=\"position\">1</property></pack"
  "ing></child></object><packing><property name=\"expand\">True</property>"
  "<property name=\"fill\">True</property><property name=\"position\">0</p"
  "roperty></packing></child></object><packing><property name=\"position\""
  ">3</property></packing></child><child type=\"tab\"><object class=\"GtkL"
  "abel\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"label\" translatable=\"yes\">Sa"
  "ved _Sessions</property><property name=\"use_underline\">True</property"
  "></object><packing><property name=\"position\">1</property><property na"
  "me=\"tab_fill\">False</property></packing></child><child><object class="
  "\"GtkBox\" id=\"vbox3\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"border_width\""
  ">12</property><property name=\"orientation\">vertical</property><proper"
  "ty name=\"spacing\">18</property><child><object class=\"GtkFrame\" id=\""
  "frame3\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label_xalign\">0</property><p"
  "roperty name=\"shadow_type\">none</property><child><object class=\"GtkA"
  "lignment\" id=\"alignment4\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"top_paddi"
  "ng\">6</property><property name=\"left_padding\">12</property><child><o"
  "bject class=\"GtkBox\" id=\"vbox4\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"or"
  "ientation\">vertical</property><property name=\"spacing\">6</property><"
  "child><object class=\"GtkCheckButton\" id=\"chk_compat_gnome\"><propert"
  "y name=\"label\" translatable=\"yes\">Launch GN_OME services on startup"
  "</property><property name=\"use_action_appearance\">False</property><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Tru"
  "e</property><property name=\"receives_default\">False</property><proper"
  "ty name=\"tooltip_text\" translatable=\"yes\">Start GNOME services, suc"
  "h as gnome-keyring</property><property name=\"use_underline\">True</pro"
  "perty><property name=\"xalign\">0.5</property><property name=\"draw_ind"
  "icator\">True</property></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkCheckB"
  "utton\" id=\"chk_compat_kde\"><property name=\"label\" translatable=\"y"
  "es\">Launch _KDE services on startup</property><property name=\"use_act"
  "ion_appearance\">False</property><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">True</property><property name=\"receiv"
  "es_default\">False</property><property name=\"tooltip_text\" translatab"
  "le=\"yes\">Start KDE services, such as kdeinit</property><property name"
  "=\"use_underline\">True</property><property name=\"xalign\">0.5</proper"
  "ty><property name=\"draw_indicator\">True</property></object><packing><"
  "property name=\"expand\">False</property><property name=\"fill\">True</"
  "property><property name=\"position\">1</property></packing></child></ob"
  "ject></child></object></child><child type=\"label\"><object class=\"Gtk"
  "Label\" id=\"label8\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"label\" translat"
  "able=\"yes\">&lt;b&gt;Compatibility&lt;/b&gt;</property><property name="
  "\"use_markup\">True</property></object></child></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">0</property></packing></child><child><o"
  "bject class=\"GtkFrame\" id=\"frame4\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "label_xalign\">0</property><property name=\"shadow_type\">none</propert"
  "y><child><object class=\"GtkAlignment\" id=\"alignment5\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"top_padding\">6</property><property name=\"left_pad"
  "ding\">12</property><child><object class=\"GtkCheckButton\" id=\"chk_en"
  "able_tcp\"><property name=\"label\" translatable=\"yes\">Manage _remote"
  " applications</property><property name=\"use_action_appearance\">False<"
  "/property><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">False</pro"
  "perty><property name=\"tooltip_text\" translatable=\"yes\">Manage remot"
  "e applications over the network (this may be a security risk)</property"
  "><property name=\"use_underline\">True</property><property name=\"xalig"
  "n\">0.5</property><property name=\"draw_indicator\">True</property></ob"
  "ject></child></object></child><child type=\"label\"><object class=\"Gtk"
  "Label\" id=\"label9\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"label\" translat"
  "able=\"yes\">&lt;b&gt;Security&lt;/b&gt;</property><property name=\"use"
  "_markup\">True</property></object></child></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">True</property><"
  "property name=\"position\">1</property></packing></child></object><pack"
  "ing><property name=\"position\">3</property></packing></child><child ty"
  "pe=\"tab\"><object class=\"GtkLabel\" id=\"label4\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"label\" translatable=\"yes\">Ad_vanced</property><propert"
  "y name=\"use_underline\">True</property></object><packing><property nam"
  "e=\"position\">3</property><property name=\"tab_fill\">False</property>"
  "</packing></child><child><placeholder/></child><child type=\"tab\"><pla"
  "ceholder/></child></object><packing><property name=\"expand\">True</pro"
  "perty><property name=\"fill\">True</property><property name=\"position\""
  ">0</property></packing></child></object></child><action-widgets><action"
  "-widget response=\"-11\">button1</action-widget><action-widget response"
  "=\"-7\">button2</action-widget></action-widgets></object><object class="
  "\"GtkDialog\" id=\"dialog_saving\"><property name=\"can_focus\">False</"
  "property><property name=\"border_width\">5</property><property name=\"t"
  "itle\" translatable=\"yes\">Saving Session</property><property name=\"r"
  "esizable\">False</property><property name=\"window_position\">center-on"
  "-parent</property><property name=\"destroy_with_parent\">True</property"
  "><property name=\"icon_name\">xfce4-session</property><property name=\""
  "type_hint\">dialog</property><property name=\"skip_taskbar_hint\">True<"
  "/property><property name=\"skip_pager_hint\">True</property><property n"
  "ame=\"transient_for\">xfce4_session_settings_dialog</property><child><p"
  "laceholder/></child><child internal-child=\"vbox\"><object class=\"GtkB"
  "ox\" id=\"dialog-vbox2\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"orientation\""
  ">vertical</property><property name=\"spacing\">2</property><child inter"
  "nal-child=\"action_area\"><object class=\"GtkButtonBox\" id=\"dialog-ac"
  "tion_area2\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"layout_style\">end</proper"
  "ty><child><object class=\"GtkButton\" id=\"button3\"><property name=\"l"
  "abel\">_Close</property><property name=\"use_action_appearance\">False<"
  "/property><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">True</prop"
  "erty><property name=\"image\">image8</property><property name=\"use_und"
  "erline\">True</property></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">False</property><property name=\"p"
  "osition\">0</property></packing></child></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">True</property><pr"
  "operty name=\"pack_type\">end</property><property name=\"position\">0</"
  "property></packing></child><child><object class=\"GtkBox\" id=\"vbox5\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"border_width\">6</property><property "
  "name=\"orientation\">vertical</property><property name=\"spacing\">6</p"
  "roperty><child><object class=\"GtkBox\" id=\"hbox8\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"spacing\">12</property><child><object class=\"GtkImage\""
  " id=\"image6\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"icon_name\">dialog-info"
  "rmation</property><property name=\"icon_size\">6</property></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">0</property></packing></chi"
  "ld><child><object class=\"GtkLabel\" id=\"label10\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"label\" translatable=\"yes\">Your session is being saved."
  "  If you do not wish to wait, you may close this window.</property><pro"
  "perty name=\"wrap\">True</property><property name=\"xalign\">0</propert"
  "y></object><packing><property name=\"expand\">True</property><property "
  "name=\"fill\">True</property><property name=\"position\">1</property></"
  "packing></child></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">True</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkProgressBar\" "
  "id=\"progress_save_session\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">1</property></packing></child></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld></object></child><action-widgets><action-widget response=\"0\">butto"
  "n3</action-widget></action-widgets></object></interface>"
};

static const unsigned xfce4_session_settings_ui_length = 28520u;

