#TODO Add Redox OS on the Bash script
[source]
git = "https://github.com/dylanaraps/neofetch"
rev = "60d07dee6b76769d8c487a40639fb7b5a1a7bc85"
[build]
template = "custom"
script = """
mkdir -pv "${COOKBOOK_STAGE}"/usr/bin
cp "${COOKBOOK_SOURCE}"/neofetch "${COOKBOOK_STAGE}"/usr/bin/neofetch
chmod a+x "${COOKBOOK_STAGE}"/usr/bin/neofetch
"""
