#TODO libssh2-sys crate error
[source]
git = "https://github.com/angeldollface/mandy"
rev = "a64f20d0386af628af2662ed2a1e72faf9efe355"
[build]
template = "custom"
dependencies = [
    "openssl1",
]
script = """
cookbook_cargo_packages mandy-bin
"""
