#TODO missing script for building, see https://github.com/capstone-engine/capstone/blob/next/COMPILE.TXT
[source]
git = "https://github.com/capstone-engine/capstone"
rev = "097c04d9413c59a58b00d4d1c8d5dc0ac158ffaa"
[build]
template = "custom"
