#TODO missing script for "make", see https://github.com/ccrma/miniAudicle#linux
[source]
git = "https://github.com/ccrma/miniAudicle"
rev = "3ef25e881cec9ee823d9cf93346c2d6feb089007"
[build]
template = "custom"
dependencies = [
    "pulseaudio",
    "libsndfile",
    "qt6-base",
]
