#TODO missing script for CMake, see https://qmcpack.readthedocs.io/en/develop/installation.html#building-with-cmake
#TODO probably missing dependencies
[source]
git = "https://github.com/QMCPACK/qmcpack"
rev = "9d0d968139fc33f71dbf9159f526dd7b47f10a3b"
[build]
template = "custom"
dependencies = [
    "openmpi",
    "openblas",
    "hdf5",
    "libxml2",
    "boost",
    "fftw",
]
