#TODO missing script for Maven, see https://github.com/apache/iotdb#build-iotdb-from-source
[source]
git = "https://github.com/apache/iotdb"
rev = "5d0bfb0c25082b61cb8830aa04ec34a13edccd31"
[build]
template = "custom"
