#TODO build instructions - https://github.com/openjdk/jdk21u/blob/master/doc/building.md
#TODO not compiled or tested
[source]
git = "https://github.com/openjdk/jdk21u"
rev = "060c4f7589e7f13febd402f4dac3320f4c032b08"
[build]
template = "custom"
dependencies = [
    "fontconfig",
]
script = """
COOKBOOK_CONFIGURE_FLAGS+=(
    --enable-headless-only=yes
)
cookbook_configure
"""
