#TODO missing script for CMake, see https://github.com/srsran/srsRAN_Project#build-instructions
#TODO missing dependencies
[source]
git = "https://github.com/srsran/srsRAN_Project"
rev = "374200deefd8e1b96fab7328525fd593a808a641"
[build]
template = "custom"
dependencies = [
    "fftw",
    "mbedtls",
]
