#TODO probably wrong script, see https://wiki.scribus.net/canvas/Official:Compile_with_CMake
[source]
tar = "https://sourceforge.net/projects/scribus/files/scribus/1.4.8/scribus-1.4.8.tar.xz/download"
[build]
template = "custom"
dependencies = [
    "qt4",
    "cairo",
    "freetype2",
    "libxml2",
    "liblcms",
    "libtiff",
    "libjpeg",
    "fontconfig",
]
script = """
COOKBOOK_CONFIGURE="cmake"
COOKBOOK_CONFIGURE_FLAGS=(
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_CROSSCOMPILING=True
    -DCMAKE_EXE_LINKER_FLAGS="-static"
    -DCMAKE_INSTALL_PREFIX="/"
    -DCMAKE_PREFIX_PATH="${COOKBOOK_SYSROOT}"
    -DCMAKE_SYSTEM_NAME=Generic
    -DCMAKE_SYSTEM_PROCESSOR="$(echo "${TARGET}" | cut -d - -f1)"
    -DCMAKE_VERBOSE_MAKEFILE=On
"${COOKBOOK_SOURCE}"
)
cookbook_configure
"""
