#TODO missing script for CMake, see https://github.com/ARM-software/astc-encoder/blob/main/Docs/Building.md#macos-and-linux-using-make
[source]
git = "https://github.com/ARM-software/astc-encoder"
rev = "aeece2f609db959d1c5e43e4f00bd177ea130575"
[build]
template = "custom"
