#TODO missing script for Meson, lacking installation instructions
[source]
git = "https://github.com/taunoe/tauno-monitor"
rev = "fecab98710bf6918141f34709f4ee1a055413056"
[build]
template = "custom"
