#TODO missing script for CMake, see https://taskwarrior.org/download/#quick-setup
[source]
tar = "https://github.com/GothenburgBitFactory/taskserver/releases/download/v1.1.0/taskd-1.1.0.tar.gz"
[build]
template = "custom"
