#TODO missing script for "make", see https://disservin.github.io/stockfish-docs/pages/Compiling-from-source.html
[source]
git = "https://github.com/official-stockfish/Stockfish"
rev = "68e1e9b3811e16cad014b590d7443b9063b3eb52"
[build]
template = "custom"
