# Configuration for using acid

include = ["base.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 256

# Package settings
[packages]
acid = {}
coreutils = {}
ion = {}

[[files]]
path = "/usr/lib/init.d/10_acid"
data = """
export RUST_BACKTRACE full
acid
acid create_test
acid switch
acid tls
acid thread
shutdown
"""
