# Default desktop configuration

include = ["server.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 512

# Package settings
[packages]
audiod = {}
installer-gui = {}
netsurf = {}
orbdata = {}
orbital = "recipe"
orbterm = "recipe"
orbutils = "recipe"
helloworld = {}

[[files]]
path = "/usr/lib/init.d/20_orbital"
data = """
audiod
orbital orblogin launcher
"""

# Override console config to not switch to VT 2
[[files]]
path = "/usr/lib/init.d/30_console"
data = """
getty 2
getty debug: -J
"""
