# Default desktop configuration

include = ["server-minimal.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 128

# Package settings
[packages]
drivers = {}
orbdata = {}
orbital = "recipe"
orbterm = {}
orbutils-background = "recipe"
orbutils-launcher = "recipe"
orbutils-orblogin = "recipe"

[[files]]
path = "/usr/lib/init.d/00_drivers"
data = """
pcid /etc/pcid.d/
"""

[[files]]
path = "/usr/lib/init.d/20_orbital"
data = """
orbital orblogin launcher
"""
