#TODO compiled but not tested
[source]
git = "https://github.com/str4d/rage"
rev = "e6180f1a2004008873b8e8d40110995ecec416c4"
[build]
template = "custom"
script = """
cookbook_cargo_packages rage
"""
