#TODO missing script for "make", see https://github.com/upx/upx/blob/devel/README.SRC
[source]
tar = "https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-src.tar.xz"
[build]
template = "custom"
