#TODO move to proper category
[source]
git = "https://github.com/justchokingaround/jerry"
[build]
template = "custom"
script = """
mkdir -pv "${COOKBOOK_STAGE}"/usr/bin
cp "${COOKBOOK_SOURCE}"/jerry.sh "${COOKBOOK_STAGE}"/usr/bin/jerry
chmod a+x "${COOKBOOK_STAGE}"/usr/bin/jerry
"""
