#TODO probably wrong script, see https://github.com/CelestiaProject/Celestia/blob/master/INSTALL.md#celestia-install-instructions-for-unix
#TODO finish the recipes of some dependencies
#TODO the SDL2 frontend is limited, Qt6 or Qt5 is preferred
[source]
tar = "https://github.com/CelestiaProject/Celestia/releases/download/1.6.4/celestia-1.6.4.tar.xz"
[build]
template = "custom"
dependencies = [
    "mesa",
    "mesa-glu",
    "sdl2",
    "libepoxy",
    "libeigen",
    "libfmt",
    "freetype2",
    "libpng",
    "libjpeg",
    "luajit",
]
script = """
COOKBOOK_CONFIGURE="cmake"
COOKBOOK_CONFIGURE_FLAGS=(
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_CROSSCOMPILING=True
    -DCMAKE_EXE_LINKER_FLAGS="-static"
    -DCMAKE_INSTALL_PREFIX="/"
    -DCMAKE_PREFIX_PATH="${COOKBOOK_SYSROOT}"
    -DCMAKE_SYSTEM_NAME=Generic
    -DCMAKE_SYSTEM_PROCESSOR="$(echo "${TARGET}" | cut -d - -f1)"
    -DCMAKE_VERBOSE_MAKEFILE=On
    -DENABLE_INTERFACE=ON
    -DENABLE_SDL=On
"${COOKBOOK_SOURCE}"
)
cookbook_configure
"""
