#TODO move to proper category
[source]
git = "https://github.com/hackerb9/lsix"
[build]
template = "custom"
script = """
mkdir -pv "${COOKBOOK_STAGE}"/usr/bin
cp "${COOKBOOK_SOURCE}"/lsix "${COOKBOOK_STAGE}"/usr/bin/lsix
chmod a+x "${COOKBOOK_STAGE}"/usr/bin/lsix
"""
