#TODO missing script for building, see https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/Docs/Build-Guide.md#linux-operating-systems-64-bit
[source]
git = "https://gitlab.com/AOMediaCodec/SVT-AV1"
rev = "59645eea34e2815b627b8293aa3af254eddd0d69"
[build]
template = "custom"
