#TODO missing script for the SCons, see https://github.com/guillaumechereau/goxel#linuxbsd
[source]
git = "https://github.com/guillaumechereau/goxel"
rev = "4cdf7bc49cbfd87e60692f49483ea60271729845"
[build]
template = "custom"
dependencies = [
    "gtk3",
    "glfw3",
]
