#TODO missing script for CMake, see https://github.com/endless-sky/endless-sky/blob/master/docs/readme-cmake.md#building-the-game
[source]
git = "https://github.com/endless-sky/endless-sky"
rev = "95e72950e1554392666fa41bb18c978868aa6611"
[build]
template = "custom"
dependencies = [
    "sdl2",
    "libpng",
    "libjpeg",
    "mesa",
    "glew",
    "openal",
    "libmad",
    "libuuid",
]
