[source]
git = "https://gitlab.redox-os.org/redox-os/orbutils.git"

[build]
template = "custom"
script = """
ORIGINAL_SOURCE="${COOKBOOK_SOURCE}"

mkdir -pv "${COOKBOOK_STAGE}/ui"
cp -rv "${COOKBOOK_SOURCE}/apps" "${COOKBOOK_STAGE}/ui/apps"

COOKBOOK_SOURCE="${ORIGINAL_SOURCE}/orbutils"
"${COOKBOOK_CARGO}" install \
        --path "${COOKBOOK_SOURCE}" \
        --root "${COOKBOOK_STAGE}/usr" \
        --locked \
        --no-track \
        ${install_flags}

COOKBOOK_SOURCE="${ORIGINAL_SOURCE}/calculator"
"${COOKBOOK_CARGO}" install \
        --path "${COOKBOOK_SOURCE}" \
        --root "${COOKBOOK_STAGE}/usr" \
        --locked \
        --no-track \
        ${install_flags}
"""
