/* automatically generated from sn-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (sn_dialog_ui)
#endif
#ifdef __GNUC__
static const char sn_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char sn_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.18\"/><requires lib=\"libxfce4ui-2\" version=\"4.12\"/"
  "><object class=\"GtkImage\" id=\"image1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"icon_name\">edit-clear-symbolic</property></object><object class=\""
  "GtkImage\" id=\"image4\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"icon_name\">w"
  "indow-close-symbolic</property></object><object class=\"GtkListStore\" "
  "id=\"items-store\"><columns><column type=\"GdkPixbuf\"/><column type=\""
  "gchararray\"/><column type=\"gboolean\"/><column type=\"gchararray\"/><"
  "/columns></object><object class=\"GtkListStore\" id=\"legacy-items-stor"
  "e\"><columns><column type=\"GdkPixbuf\"/><column type=\"gchararray\"/><"
  "column type=\"gboolean\"/><column type=\"gchararray\"/></columns></obje"
  "ct><object class=\"GtkAdjustment\" id=\"size-adjustment\"><property nam"
  "e=\"upper\">64</property><property name=\"value\">22</property><propert"
  "y name=\"step_increment\">1</property><property name=\"page_increment\""
  ">2</property></object><object class=\"XfceTitledDialog\" id=\"dialog\">"
  "<property name=\"can_focus\">False</property><property name=\"title\" t"
  "ranslatable=\"yes\">Status Tray Items</property><property name=\"defaul"
  "t_width\">425</property><property name=\"default_height\">575</property"
  "><property name=\"icon_name\">org.xfce.panel.statustray</property><prop"
  "erty name=\"type_hint\">normal</property><child internal-child=\"vbox\""
  "><object class=\"GtkBox\" id=\"dialog-vbox2\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"orientation\">vertical</property><property name=\"spacing\">2</p"
  "roperty><child internal-child=\"action_area\"><object class=\"GtkButton"
  "Box\" id=\"dialog-action_area2\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><child><object class=\""
  "GtkButton\" id=\"close-button\"><property name=\"label\">_Close</proper"
  "ty><property name=\"visible\">True</property><property name=\"can_focus"
  "\">True</property><property name=\"receives_default\">True</property><p"
  "roperty name=\"image\">image4</property><property name=\"use_underline\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkButton\" id=\""
  "items-clear\"><property name=\"label\" translatable=\"yes\">C_lear Know"
  "n Items</property><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">True</property><property name=\"receives_default\">Tr"
  "ue</property><property name=\"tooltip_text\" translatable=\"yes\">Reset"
  "s the list of items and their visibility settings</property><property n"
  "ame=\"image\">image1</property><property name=\"use_underline\">True</p"
  "roperty></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">False</property><property name=\"position\">1</pro"
  "perty><property name=\"secondary\">True</property><property name=\"non_"
  "homogeneous\">True</property></packing></child></object><packing><prope"
  "rty name=\"expand\">True</property><property name=\"fill\">True</proper"
  "ty><property name=\"pack_type\">end</property><property name=\"position"
  "\">0</property></packing></child><child><object class=\"GtkBox\" id=\"v"
  "box1\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"border_width\">12</property><pr"
  "operty name=\"orientation\">vertical</property><property name=\"spacing"
  "\">18</property><child><object class=\"GtkFrame\" id=\"frame2\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"label_xalign\">0</property><property name=\"s"
  "hadow_type\">none</property><child><object class=\"GtkAlignment\" id=\""
  "alignment2\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"top_padding\">6</property>"
  "<property name=\"left_padding\">12</property><child><object class=\"Gtk"
  "Grid\" id=\"icon_grid\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><child><object class=\"GtkRevea"
  "ler\" id=\"revealer-icon-size\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"margin"
  "_top\">6</property><property name=\"reveal_child\">True</property><chil"
  "d><object class=\"GtkBox\" id=\"hbox1\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"spacing\">12</property><child><object class=\"GtkLabel\" id=\"label2\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"hexpand\">True</property><property na"
  "me=\"label\" translatable=\"yes\">_Fixed icon size (pixels):</property>"
  "<property name=\"use_underline\">True</property><property name=\"mnemon"
  "ic_widget\">spinbutton-icon-size</property><property name=\"xalign\">0<"
  "/property></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">True</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkSpinButton\" id=\"sp"
  "inbutton-icon-size\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"halign\">end</prop"
  "erty><property name=\"valign\">center</property><property name=\"adjust"
  "ment\">size-adjustment</property><property name=\"numeric\">True</prope"
  "rty></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">1</property"
  "></packing></child></object></child></object><packing><property name=\""
  "left_attach\">0</property><property name=\"top_attach\">1</property><pr"
  "operty name=\"width\">2</property></packing></child><child><object clas"
  "s=\"GtkLabel\" id=\"auto_size_label\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "halign\">start</property><property name=\"hexpand\">True</property><pro"
  "perty name=\"label\" translatable=\"yes\">Adjust size _automatically</p"
  "roperty><property name=\"use_underline\">True</property></object><packi"
  "ng><property name=\"left_attach\">0</property><property name=\"top_atta"
  "ch\">0</property></packing></child><child><object class=\"GtkSwitch\" i"
  "d=\"switch-auto-size\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"halign\">end</pr"
  "operty><property name=\"valign\">center</property></object><packing><pr"
  "operty name=\"left_attach\">1</property><property name=\"top_attach\">0"
  "</property></packing></child></object></child></object></child><child t"
  "ype=\"label\"><object class=\"GtkLabel\" id=\"label1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">Icons</property><attribute"
  "s><attribute name=\"weight\" value=\"bold\"/></attributes></object></ch"
  "ild></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">0</property"
  "></packing></child><child><object class=\"GtkFrame\" id=\"frame1\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"label_xalign\">0</property><property name="
  "\"shadow_type\">none</property><child><object class=\"GtkAlignment\" id"
  "=\"alignment1\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"top_padding\">6</prope"
  "rty><property name=\"left_padding\">12</property><child><object class=\""
  "GtkBox\" id=\"vbox4\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"orientation\">ve"
  "rtical</property><property name=\"spacing\">6</property><child><object "
  "class=\"GtkCheckButton\" id=\"checkbutton-single-row\"><property name=\""
  "label\" translatable=\"yes\">Arrange _items in a single row</property><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"receives_default\">False</property><prop"
  "erty name=\"tooltip_text\" translatable=\"yes\">If enabled, ensure that"
  " the items are laid out in a single row</property><property name=\"use_"
  "underline\">True</property><property name=\"draw_indicator\">True</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">True</property><property name=\"position\">0</propert"
  "y></packing></child><child><object class=\"GtkCheckButton\" id=\"checkb"
  "utton-hide-new-items\"><property name=\"label\" translatable=\"yes\">_H"
  "ide items by default</property><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">True</property><property name=\"receives"
  "_default\">False</property><property name=\"tooltip_text\" translatable"
  "=\"yes\">When enabled, all new items will be marked as \"Hidden\"</prop"
  "erty><property name=\"use_underline\">True</property><property name=\"d"
  "raw_indicator\">True</property></object><packing><property name=\"expan"
  "d\">False</property><property name=\"fill\">True</property><property na"
  "me=\"position\">2</property></packing></child><child><object class=\"Gt"
  "kCheckButton\" id=\"checkbutton-square-icons\"><property name=\"label\""
  " translatable=\"yes\">_Square items</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"tooltip_text\""
  " translatable=\"yes\">Item buttons will take a square when it\'s possib"
  "le</property><property name=\"use_underline\">True</property><property "
  "name=\"draw_indicator\">True</property></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">True</property><pro"
  "perty name=\"position\">2</property></packing></child></object></child>"
  "</object></child><child type=\"label\"><object class=\"GtkLabel\" id=\""
  "label4\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label\" translatable=\"yes\">"
  "Behavior</property><attributes><attribute name=\"weight\" value=\"bold\""
  "/></attributes></object></child></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">True</property><property n"
  "ame=\"position\">2</property></packing></child><child><object class=\"G"
  "tkStackSwitcher\" id=\"items_stack_switcher\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"halign\">center</property><property name=\"stack\">items_stack</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">3</pro"
  "perty></packing></child><child><object class=\"GtkStack\" id=\"items_st"
  "ack\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><property name=\"transition_type\">slide-left-rig"
  "ht</property><child><object class=\"GtkBox\" id=\"sn_box\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"orientation\">vertical</property><property name=\""
  "spacing\">18</property><child><object class=\"GtkFrame\" id=\"sn_known_"
  "items\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"label_xalign\">0</property><pr"
  "operty name=\"shadow_type\">none</property><child><object class=\"GtkAl"
  "ignment\" id=\"sn_alignment\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"top_padd"
  "ing\">6</property><child><object class=\"GtkBox\" id=\"hbox2\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"vexpand\">True</property><property name=\"spac"
  "ing\">6</property><child><object class=\"GtkScrolledWindow\" id=\"scrol"
  "ledwindow1\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"hscrollbar_policy\">never</"
  "property><property name=\"shadow_type\">in</property><child><object cla"
  "ss=\"GtkTreeView\" id=\"items-treeview\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">True</property><property name="
  "\"model\">items-store</property><property name=\"headers_clickable\">Fa"
  "lse</property><property name=\"rules_hint\">True</property><property na"
  "me=\"enable_search\">False</property><child internal-child=\"selection\""
  "><object class=\"GtkTreeSelection\"/></child><child><object class=\"Gtk"
  "TreeViewColumn\" id=\"treeviewcolumn-icon\"><property name=\"min_width\""
  ">24</property><child><object class=\"GtkCellRendererPixbuf\" id=\"cellr"
  "endererpixbuf1\"/><attributes><attribute name=\"pixbuf\">0</attribute><"
  "/attributes></child></object></child><child><object class=\"GtkTreeView"
  "Column\" id=\"treeviewcolumn-name\"><property name=\"title\" translatab"
  "le=\"yes\">Item</property><property name=\"expand\">True</property><chi"
  "ld><object class=\"GtkCellRendererText\" id=\"cellrenderertext1\"/><att"
  "ributes><attribute name=\"text\">1</attribute></attributes></child></ob"
  "ject></child><child><object class=\"GtkTreeViewColumn\" id=\"treeviewco"
  "lumn-hidden\"><property name=\"title\" translatable=\"yes\">Hidden</pro"
  "perty><child><object class=\"GtkCellRendererToggle\" id=\"hidden-toggle"
  "\"/><attributes><attribute name=\"active\">2</attribute></attributes></"
  "child></object></child></object></child></object><packing><property nam"
  "e=\"expand\">True</property><property name=\"fill\">True</property><pro"
  "perty name=\"position\">0</property></packing></child><child><object cl"
  "ass=\"GtkBox\" id=\"vbox5\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"orientatio"
  "n\">vertical</property><child><object class=\"GtkButton\" id=\"item-up\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">True</property><pro"
  "perty name=\"tooltip_text\" translatable=\"yes\">Move the selected item"
  " one row up</property><child><object class=\"GtkImage\" id=\"image2\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"icon_name\">go-up-symbolic</property></"
  "object></child></object><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">True</property><property name=\"position\">"
  "0</property></packing></child><child><object class=\"GtkButton\" id=\"i"
  "tem-down\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">True</property><property name=\"receives_default\">True</pro"
  "perty><property name=\"tooltip_text\" translatable=\"yes\">Move the sel"
  "ected item one row down</property><child><object class=\"GtkImage\" id="
  "\"image3\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"icon_name\">go-down-symboli"
  "c</property></object></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"position\">1</property></packing></child><style><class name=\"linked\""
  "/></style></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">True</property><property name=\"position\">1</pr"
  "operty></packing></child></object></child></object></child><child type="
  "\"label\"><object class=\"GtkLabel\" id=\"sn_known_items_label\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"label\" translatable=\"yes\">Known Items</pr"
  "operty><attributes><attribute name=\"weight\" value=\"bold\"/></attribu"
  "tes></object></child></object><packing><property name=\"expand\">True</"
  "property><property name=\"fill\">True</property><property name=\"positi"
  "on\">0</property></packing></child><child><object class=\"GtkFrame\" id"
  "=\"frame3\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label_xalign\">0</property"
  "><property name=\"shadow_type\">none</property><child><object class=\"G"
  "tkAlignment\" id=\"alignment3\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"top_pa"
  "dding\">6</property><property name=\"left_padding\">12</property><child"
  "><object class=\"GtkBox\" id=\"vbox3\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "orientation\">vertical</property><property name=\"spacing\">6</property"
  "><child><object class=\"GtkCheckButton\" id=\"checkbutton-menu-is-prima"
  "ry\"><property name=\"label\" translatable=\"yes\">_Menu is primary act"
  "ion</property><property name=\"visible\">True</property><property name="
  "\"can_focus\">True</property><property name=\"receives_default\">False<"
  "/property><property name=\"tooltip_text\" translatable=\"yes\">Left cli"
  "ck will always display the menu for item</property><property name=\"use"
  "_underline\">True</property><property name=\"draw_indicator\">True</pro"
  "perty></object><packing><property name=\"expand\">True</property><prope"
  "rty name=\"fill\">True</property><property name=\"position\">0</propert"
  "y></packing></child><child><object class=\"GtkCheckButton\" id=\"checkb"
  "utton-symbolic-icons\"><property name=\"label\" translatable=\"yes\">_R"
  "equest symbolic icons</property><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"receive"
  "s_default\">False</property><property name=\"tooltip_text\" translatabl"
  "e=\"yes\">Load symbolic icons if available</property><property name=\"u"
  "se_underline\">True</property><property name=\"draw_indicator\">True</p"
  "roperty></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">1</prop"
  "erty></packing></child></object></child></object></child><child type=\""
  "label\"><object class=\"GtkLabel\" id=\"label3\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"label\" translatable=\"yes\">Features</property><attributes>"
  "<attribute name=\"weight\" value=\"bold\"/></attributes></object></chil"
  "d></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">True</property><property name=\"position\">1</property><"
  "/packing></child></object><packing><property name=\"name\">Status Notif"
  "iers</property><property name=\"title\" translatable=\"yes\">Status Not"
  "ifiers</property></packing></child><child><object class=\"GtkFrame\" id"
  "=\"systray_frame\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"label_xalign\">0</p"
  "roperty><property name=\"shadow_type\">none</property><child><object cl"
  "ass=\"GtkAlignment\" id=\"systray_frame_alignment\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"top_padding\">6</property><child><object class=\"GtkBox\""
  " id=\"hbox3\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"spacing\">6</property><c"
  "hild><object class=\"GtkScrolledWindow\" id=\"scrolledwindow2\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"hscrollbar_policy\">never</property><property "
  "name=\"shadow_type\">in</property><child><object class=\"GtkTreeView\" "
  "id=\"legacy-items-treeview\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">True</property><property name=\"model\">le"
  "gacy-items-store</property><property name=\"headers_clickable\">False</"
  "property><property name=\"rules_hint\">True</property><property name=\""
  "enable_search\">False</property><property name=\"search_column\">1</pro"
  "perty><child internal-child=\"selection\"><object class=\"GtkTreeSelect"
  "ion\"/></child><child><object class=\"GtkTreeViewColumn\" id=\"treeview"
  "column-legacy-icon\"><property name=\"min_width\">24</property><child><"
  "object class=\"GtkCellRendererPixbuf\" id=\"cellrendererpixbuf2\"/><att"
  "ributes><attribute name=\"pixbuf\">0</attribute></attributes></child></"
  "object></child><child><object class=\"GtkTreeViewColumn\" id=\"treeview"
  "column-legacy-name\"><property name=\"title\" translatable=\"yes\">Item"
  "</property><property name=\"expand\">True</property><child><object clas"
  "s=\"GtkCellRendererText\" id=\"cellrenderertext2\"/><attributes><attrib"
  "ute name=\"text\">1</attribute></attributes></child></object></child><c"
  "hild><object class=\"GtkTreeViewColumn\" id=\"treeviewcolumn-legacy-hid"
  "den\"><property name=\"title\" translatable=\"yes\">Hidden</property><c"
  "hild><object class=\"GtkCellRendererToggle\" id=\"legacy-hidden-toggle\""
  "/><attributes><attribute name=\"active\">2</attribute></attributes></ch"
  "ild></object></child></object></child></object><packing><property name="
  "\"expand\">True</property><property name=\"fill\">True</property><prope"
  "rty name=\"position\">0</property></packing></child><child><object clas"
  "s=\"GtkBox\" id=\"vbox6\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"orientation\""
  ">vertical</property><child><object class=\"GtkButton\" id=\"legacy-item"
  "-up\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">True</property><property name=\"receives_default\">True</property"
  "><property name=\"tooltip_text\" translatable=\"yes\">Move the selected"
  " item one row up</property><child><object class=\"GtkImage\" id=\"image"
  "5\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"icon_name\">go-up-symbolic</proper"
  "ty></object></child></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">True</property><property name=\"positi"
  "on\">0</property></packing></child><child><object class=\"GtkButton\" i"
  "d=\"legacy-item-down\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"receives_default"
  "\">True</property><property name=\"tooltip_text\" translatable=\"yes\">"
  "Move the selected item one row down</property><child><object class=\"Gt"
  "kImage\" id=\"image6\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"icon_name\">go-"
  "down-symbolic</property></object></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">True</property><p"
  "roperty name=\"position\">1</property></packing></child><style><class n"
  "ame=\"linked\"/></style></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">1</property></packing></child></object></child></object></chil"
  "d><child type=\"label\"><object class=\"GtkLabel\" id=\"systray_frame_l"
  "abel\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"label\" translatable=\"yes\">Kn"
  "own Items</property><attributes><attribute name=\"weight\" value=\"bold"
  "\"/></attributes></object></child></object><packing><property name=\"na"
  "me\">Systray Icons</property><property name=\"title\" translatable=\"ye"
  "s\">Systray Icons</property><property name=\"position\">1</property></p"
  "acking></child></object><packing><property name=\"expand\">True</proper"
  "ty><property name=\"fill\">True</property><property name=\"position\">4"
  "</property></packing></child></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child></object></child><action-widge"
  "ts><action-widget response=\"0\">close-button</action-widget></action-w"
  "idgets></object></interface>"
};

static const unsigned sn_dialog_ui_length = 22369u;

