#TODO missing script for building, see https://github.com/c-koi/gmic-qt#build-instructions
#TODO probably missing dependencies
[source]
git = "https://github.com/c-koi/gmic-qt"
rev = "b616829854c0e482d63b9fe8eca48e73d7cd3bd8"
[build]
template = "custom"
