#TODO not compiled or tested
[source]
tar = "https://mosh.org/mosh-1.4.0.tar.gz"
[build]
template = "custom"
dependencies = [
    "openssl1",
    "ncurses",
    "zlib",
]
script = """
export CPPFLAGS="-I${COOKBOOK_SYSROOT}/include/ncurses"
cookbook_configure
"""
