#TODO not compiled or tested
[source]
tar = "https://invisible-island.net/archives/lynx/tarballs/lynx2.8.9rel.1.tar.gz"
[build]
template = "custom"
dependencies = [
    "ncurses",
]
script = """
export CPPFLAGS="-I${COOKBOOK_SYSROOT}/include/ncurses"
cookbook_configure
"""
