#TODO missing script for "make", see https://pierrebeucher.github.io/novops/install.html#from-source
[source]
git = "https://github.com/PierreBeucher/novops"
rev = "e0891144108a889f18448b39aebe9d5a5ac2689d"
[build]
template = "custom"
