#TODO missing script for building, see https://github.com/Tencent/TNN/blob/master/doc/en/user/compile_en.md#iv-compilex86-linux
[source]
git = "https://github.com/Tencent/TNN"
rev = "491dfc8653e200b5e8a428069638e191662a0882"
[build]
template = "custom"
