#TODO missing script for CMake, see https://github.com/appleseedhq/appleseed/wiki/Building-appleseed-on-Linux
[source]
git = "https://github.com/appleseedhq/appleseed"
rev = "015adb503af58cb80103e0c3ddeefc20d99d204f"
[build]
template = "custom"
dependencies = [
    "zlib",
    "qt5-base",
    "libnsl",
]
