#TODO make dependencies work
[source]
git = "https://github.com/NixOS/nix"
rev = "50f8f1c8bc019a4c0fd098b9ac674b94cfc6af0d"
[build]
template = "custom"
dependencies = [
    "libbrotili",
    "openssl1",
    "curl",
    "sqlite3",
    "libeditline",
    "boost",
    "libsodium",
    "libcpuid",
]
script = """
autoreconf -vfi
COOKBOOK_CONFIGURE_FLAGS+=(
    --disable-tests
)
cookbook_configure
"""
