/* automatically generated from tasklist-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (tasklist_dialog_ui)
#endif
#ifdef __GNUC__
static const char tasklist_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char tasklist_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><requires lib=\"libxfce4ui-2\" version=\"4.12\"/"
  "><object class=\"GtkImage\" id=\"image1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"icon_name\">help-browser</property></object><object class=\"GtkImag"
  "e\" id=\"image2\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"icon_name\">window-c"
  "lose-symbolic</property></object><object class=\"GtkListStore\" id=\"mi"
  "ddle-click-model\"><columns><column type=\"gchararray\"/></columns><dat"
  "a><row><col id=\"0\" translatable=\"yes\">Nothing</col></row><row><col "
  "id=\"0\" translatable=\"yes\">Close Window</col></row><row><col id=\"0\""
  " translatable=\"yes\">Minimize Window</col></row><row><col id=\"0\" tra"
  "nslatable=\"yes\">New Instance</col></row></data></object><object class"
  "=\"GtkListStore\" id=\"sort-order-model\"><columns><column type=\"gchar"
  "array\"/></columns><data><row><col id=\"0\" translatable=\"yes\">Timest"
  "amp</col></row><row><col id=\"0\" translatable=\"yes\">Group title and "
  "timestamp</col></row><row><col id=\"0\" translatable=\"yes\">Window tit"
  "le</col></row><row><col id=\"0\" translatable=\"yes\">Group title and w"
  "indow title</col></row><row><col id=\"0\" translatable=\"yes\">None, al"
  "low drag-and-drop</col></row></data></object><object class=\"XfceTitled"
  "Dialog\" id=\"dialog\"><property name=\"can_focus\">False</property><pr"
  "operty name=\"title\" translatable=\"yes\">Window Buttons</property><pr"
  "operty name=\"icon_name\">org.xfce.panel.tasklist</property><property n"
  "ame=\"type_hint\">normal</property><child internal-child=\"vbox\"><obje"
  "ct class=\"GtkBox\" id=\"dialog-vbox2\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"orientation\">vertical</property><property name=\"spacing\">2</proper"
  "ty><child internal-child=\"action_area\"><object class=\"GtkButtonBox\""
  " id=\"dialog-action_area2\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"layout_sty"
  "le\">end</property><child><object class=\"GtkButton\" id=\"close-button"
  "\"><property name=\"label\" translatable=\"yes\">_Close</property><prop"
  "erty name=\"use_action_appearance\">False</property><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"receives_default\">True</property><property name=\"image\""
  ">image2</property><property name=\"use_underline\">True</property></obj"
  "ect><packing><property name=\"expand\">False</property><property name=\""
  "fill\">False</property><property name=\"position\">0</property></packin"
  "g></child><child><object class=\"GtkButton\" id=\"help-button\"><proper"
  "ty name=\"label\" translatable=\"yes\">_Help</property><property name=\""
  "use_action_appearance\">False</property><property name=\"visible\">True"
  "</property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">True</property><property name=\"image\">image1</prop"
  "erty><property name=\"use_underline\">True</property></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">False"
  "</property><property name=\"position\">1</property><property name=\"sec"
  "ondary\">True</property></packing></child></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">True</property><"
  "property name=\"pack_type\">end</property><property name=\"position\">0"
  "</property></packing></child><child><object class=\"GtkBox\" id=\"vbox1"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"border_width\">6</property><propert"
  "y name=\"orientation\">vertical</property><property name=\"spacing\">6<"
  "/property><child><object class=\"GtkFrame\" id=\"frame3\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"label_xalign\">0</property><property name=\"shadow_"
  "type\">none</property><child><object class=\"GtkAlignment\" id=\"alignm"
  "ent3\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"left_padding\">12</property><ch"
  "ild><object class=\"GtkBox\" id=\"vbox3\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"border_width\">6</property><property name=\"orientation\">vertical<"
  "/property><property name=\"spacing\">6</property><child><object class=\""
  "GtkCheckButton\" id=\"show-labels\"><property name=\"label\" translatab"
  "le=\"yes\">Show button _labels</property><property name=\"use_action_ap"
  "pearance\">False</property><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"receives_def"
  "ault\">False</property><property name=\"use_underline\">True</property>"
  "<property name=\"draw_indicator\">True</property></object><packing><pro"
  "perty name=\"expand\">True</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">0</property></packing></child><child><"
  "object class=\"GtkCheckButton\" id=\"flat-buttons\"><property name=\"la"
  "bel\" translatable=\"yes\">Show _flat buttons</property><property name="
  "\"use_action_appearance\">False</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><property name"
  "=\"receives_default\">False</property><property name=\"use_underline\">"
  "True</property><property name=\"draw_indicator\">True</property></objec"
  "t><packing><property name=\"expand\">True</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">1</property></packing><"
  "/child><child><object class=\"GtkCheckButton\" id=\"show-handle\"><prop"
  "erty name=\"label\" translatable=\"yes\">Show _handle</property><proper"
  "ty name=\"use_action_appearance\">False</property><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"receives_default\">False</property><property name=\"use_unde"
  "rline\">True</property><property name=\"draw_indicator\">True</property"
  "></object><packing><property name=\"expand\">True</property><property n"
  "ame=\"fill\">True</property><property name=\"position\">2</property></p"
  "acking></child><child><object class=\"GtkCheckButton\" id=\"show-toolti"
  "ps\"><property name=\"label\" translatable=\"yes\">Show _tooltips</prop"
  "erty><property name=\"use-action-appearance\">False</property><property"
  " name=\"visible\">True</property><property name=\"can-focus\">True</pro"
  "perty><property name=\"receives-default\">False</property><property nam"
  "e=\"use-underline\">True</property><property name=\"draw-indicator\">Tr"
  "ue</property></object><packing><property name=\"expand\">True</property"
  "><property name=\"fill\">True</property><property name=\"position\">3</"
  "property></packing></child><child><object class=\"GtkBox\" id=\"hbox2\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"spacing\">12</property><child><object"
  " class=\"GtkLabel\" id=\"label5\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"labe"
  "l\" translatable=\"yes\">Sorting _order:</property><property name=\"use"
  "_underline\">True</property><property name=\"mnemonic_widget\">sort-ord"
  "er</property></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">True</property><property name=\"position\">0<"
  "/property></packing></child><child><object class=\"GtkComboBox\" id=\"s"
  "ort-order\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"model\">sort-order-model</"
  "property><child><object class=\"GtkCellRendererText\" id=\"cellrenderer"
  "text1\"/><attributes><attribute name=\"text\">0</attribute></attributes"
  "></child></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">1</pro"
  "perty></packing></child></object><packing><property name=\"expand\">Tru"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">4</property></packing></child></object></child></object></child"
  "><child type=\"label\"><object class=\"GtkLabel\" id=\"label1\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"label\" translatable=\"yes\">Appearance</prop"
  "erty><attributes><attribute name=\"weight\" value=\"bold\"/></attribute"
  "s></object></child></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"fill\">True</property><property name=\"positio"
  "n\">0</property></packing></child><child><object class=\"GtkFrame\" id="
  "\"frame1\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"label_xalign\">0</property>"
  "<property name=\"shadow_type\">none</property><child><object class=\"Gt"
  "kAlignment\" id=\"alignment1\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"left_pa"
  "dding\">12</property><child><object class=\"GtkBox\" id=\"vbox2\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"border_width\">6</property><property name=\""
  "orientation\">vertical</property><property name=\"spacing\">6</property"
  "><child><object class=\"GtkBox\" id=\"hbox3\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"spacing\">12</property><child><object class=\"GtkLabel\" id=\"la"
  "bel6\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"label\" translatable=\"yes\">Mi"
  "_ddle click action:</property><property name=\"use_underline\">True</pr"
  "operty><property name=\"mnemonic_widget\">middle-click</property><prope"
  "rty name=\"xalign\">0</property></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">True</property><property n"
  "ame=\"position\">0</property></packing></child><child><object class=\"G"
  "tkComboBox\" id=\"middle-click\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"model"
  "\">middle-click-model</property><child><object class=\"GtkCellRendererT"
  "ext\" id=\"cellrenderertext3\"/><attributes><attribute name=\"text\">0<"
  "/attribute></attributes></child></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">True</property><property n"
  "ame=\"position\">1</property></packing></child></object><packing><prope"
  "rty name=\"expand\">True</property><property name=\"fill\">True</proper"
  "ty><property name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkCheckButton\" id=\"grouping\"><property name=\"label\" "
  "translatable=\"yes\">_Group windows by application</property><property "
  "name=\"use_action_appearance\">False</property><property name=\"visible"
  "\">True</property><property name=\"can_focus\">True</property><property"
  " name=\"receives_default\">False</property><property name=\"use_underli"
  "ne\">True</property><property name=\"draw_indicator\">True</property></"
  "object><packing><property name=\"expand\">True</property><property name"
  "=\"fill\">True</property><property name=\"position\">1</property></pack"
  "ing></child><child><object class=\"GtkCheckButton\" id=\"switch-workspa"
  "ce-on-unminimize\"><property name=\"label\" translatable=\"yes\">Restor"
  "e minimized windows to current _workspace</property><property name=\"us"
  "e_action_appearance\">False</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"r"
  "eceives_default\">False</property><property name=\"use_underline\">True"
  "</property><property name=\"draw_indicator\">True</property></object><p"
  "acking><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">2</property></packing></chi"
  "ld><child><object class=\"GtkCheckButton\" id=\"show-wireframes\"><prop"
  "erty name=\"label\" translatable=\"yes\">D_raw window frame when hoveri"
  "ng a button</property><property name=\"use_action_appearance\">False</p"
  "roperty><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"receives_default\">False</prope"
  "rty><property name=\"use_underline\">True</property><property name=\"dr"
  "aw_indicator\">True</property></object><packing><property name=\"expand"
  "\">True</property><property name=\"fill\">True</property><property name"
  "=\"position\">3</property></packing></child><child><object class=\"GtkC"
  "heckButton\" id=\"window-scrolling\"><property name=\"label\" translata"
  "ble=\"yes\">_Switch windows using the mouse wheel</property><property n"
  "ame=\"use_action_appearance\">False</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"use_underline"
  "\">True</property><property name=\"draw_indicator\">True</property></ob"
  "ject><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">4</property></packing"
  "></child></object></child></object></child><child type=\"label\"><objec"
  "t class=\"GtkLabel\" id=\"label3\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"lab"
  "el\" translatable=\"yes\">Behaviour</property><attributes><attribute na"
  "me=\"weight\" value=\"bold\"/></attributes></object></child></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld><child><object class=\"GtkFrame\" id=\"frame2\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"label_xalign\">0</property><property name=\"shadow_type\">"
  "none</property><child><object class=\"GtkAlignment\" id=\"alignment2\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"left_padding\">12</property><child><ob"
  "ject class=\"GtkBox\" id=\"vbox4\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"bor"
  "der_width\">6</property><property name=\"orientation\">vertical</proper"
  "ty><property name=\"spacing\">6</property><child><object class=\"GtkChe"
  "ckButton\" id=\"include-all-workspaces\"><property name=\"label\" trans"
  "latable=\"yes\">Show windows from _all workspaces</property><property n"
  "ame=\"use_action_appearance\">False</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"use_underline"
  "\">True</property><property name=\"draw_indicator\">True</property></ob"
  "ject><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkCheckButton\" id=\"include-all-monit"
  "ors\"><property name=\"label\" translatable=\"yes\">Show windows from a"
  "ll mo_nitors</property><property name=\"use_action_appearance\">False</"
  "property><property name=\"visible\">True</property><property name=\"can"
  "_focus\">True</property><property name=\"receives_default\">False</prop"
  "erty><property name=\"use_underline\">True</property><property name=\"d"
  "raw_indicator\">True</property></object><packing><property name=\"expan"
  "d\">True</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">1</property></packing></child><child><object class=\"Gtk"
  "CheckButton\" id=\"show-only-minimized\"><property name=\"label\" trans"
  "latable=\"yes\">Show only _minimized windows</property><property name=\""
  "use_action_appearance\">False</property><property name=\"visible\">True"
  "</property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">False</property><property name=\"use_underline\">Tru"
  "e</property><property name=\"draw_indicator\">True</property></object><"
  "packing><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld></object></child></object></child><child type=\"label\"><object clas"
  "s=\"GtkLabel\" id=\"label2\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"label\" t"
  "ranslatable=\"yes\">Filtering</property><attributes><attribute name=\"w"
  "eight\" value=\"bold\"/></attributes></object></child></object><packing"
  "><property name=\"expand\">True</property><property name=\"fill\">True<"
  "/property><property name=\"position\">2</property></packing></child></o"
  "bject><packing><property name=\"expand\">False</property><property name"
  "=\"fill\">True</property><property name=\"position\">1</property></pack"
  "ing></child></object></child><action-widgets><action-widget response=\""
  "0\">close-button</action-widget><action-widget response=\"0\">help-butt"
  "on</action-widget></action-widgets></object></interface>"
};

static const unsigned tasklist_dialog_ui_length = 16033u;

