#TODO probably wrong script, see https://github.com/neovim/neovim/wiki/Installing-Neovim#install-from-source
[source]
git = "https://github.com/neovim/neovim"
rev = "d772f697a281ce9c58bf933997b87c7f27428a60"
[build]
template = "custom"
dependencies = [
    "luajit",
    "gettext",
    "less",
    "libuv",
    "libvterm",
    "libtickit",
]
script = """
    COOKBOOK_CONFIGURE="cmake"
    COOKBOOK_CONFIGURE_FLAGS=(
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_CROSSCOMPILING=True
    -DCMAKE_EXE_LINKER_FLAGS="-static"
    -DCMAKE_INSTALL_PREFIX="/"
    -DCMAKE_PREFIX_PATH="${COOKBOOK_SYSROOT}"
    -DCMAKE_SYSTEM_NAME=Generic
    -DCMAKE_SYSTEM_PROCESSOR="$(echo "${TARGET}" | cut -d - -f1)"
    -DCMAKE_VERBOSE_MAKEFILE=On
"${COOKBOOK_SOURCE}"
)
cookbook_configure
"""
