#TODO missing script for "make", see https://github.com/charmplusplus/projections#compiling-projections
[source]
git = "https://github.com/charmplusplus/projections"
rev = "831b63af68f325c64dac307d9d2b5b07d9a21caa"
[build]
template = "custom"
