#TODO missing script for Cake, see https://github.com/NickvisionApps/Parabolic/blob/main/CONTRIBUTING.md#developing-on-linux
#TODO missing dependencies - https://github.com/NickvisionApps/Parabolic/blob/main/CONTRIBUTING.md#developing-on-linux
[source]
git = "https://github.com/NickvisionApps/Parabolic"
rev = "0aeaf7ab241f7405278352e448372c720ddb85f0"
[build]
template = "custom"
dependencies = [
    "ffmpeg6",
    "yt-dlp",
    "gtk4",
    "libadwaita",
    "aria2",
]
