/* automatically generated from keyboard-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (keyboard_dialog_ui)
#endif
#ifdef __GNUC__
static const char keyboard_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char keyboard_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><requires lib=\"libxfce4ui-2\" version=\"4.13\"/"
  "><object class=\"GtkImage\" id=\"image1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"icon_name\">document-revert-symbolic</property></object><object cla"
  "ss=\"GtkImage\" id=\"image10\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"icon_na"
  "me\">document-edit-symbolic</property></object><object class=\"GtkImage"
  "\" id=\"image11\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"icon_name\">list-rem"
  "ove-symbolic</property></object><object class=\"GtkImage\" id=\"image2\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"icon_name\">window-close-symbolic</pr"
  "operty></object><object class=\"GtkImage\" id=\"image5\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"icon_name\">help-browser</property></object><object "
  "class=\"GtkImage\" id=\"image6\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"icon_"
  "name\">list-add-symbolic</property></object><object class=\"GtkImage\" "
  "id=\"image7\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"icon_name\">list-remove-"
  "symbolic</property></object><object class=\"GtkImage\" id=\"image8\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"icon_name\">document-edit-symbolic</prop"
  "erty></object><object class=\"GtkImage\" id=\"image9\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"icon_name\">list-add-symbolic</property></object><objec"
  "t class=\"XfceTitledDialog\" id=\"keyboard-layout-selection-dialog\"><p"
  "roperty name=\"can_focus\">False</property><property name=\"title\" tra"
  "nslatable=\"yes\">Keyboard layout selection</property><property name=\""
  "window_position\">center-on-parent</property><property name=\"default_h"
  "eight\">300</property><property name=\"icon_name\">org.xfce.settings.ke"
  "yboard</property><property name=\"type_hint\">dialog</property><child i"
  "nternal-child=\"vbox\"><object class=\"GtkBox\" id=\"dialog-vbox2\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"orientation\">vertical</property><propert"
  "y name=\"spacing\">2</property><child internal-child=\"action_area\"><o"
  "bject class=\"GtkButtonBox\" id=\"dialog-action_area2\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"layout_style\">end</property><child><object class=\"G"
  "tkButton\" id=\"layout_selection_cancel_button\"><property name=\"label"
  "\" translatable=\"yes\">_Cancel</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><property name"
  "=\"receives_default\">True</property><property name=\"use_underline\">T"
  "rue</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">False</property><property name=\"position\">"
  "0</property></packing></child><child><object class=\"GtkButton\" id=\"l"
  "ayout_selection_ok_button\"><property name=\"label\" translatable=\"yes"
  "\">_OK</property><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">True</property><property name=\"receives_default\">Tru"
  "e</property><property name=\"use_underline\">True</property></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">1</property></packing></ch"
  "ild></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">True</property><property name=\"pack_type\">end</prope"
  "rty><property name=\"position\">0</property></packing></child><child><o"
  "bject class=\"GtkScrolledWindow\" id=\"scrolledwindow3\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">True</property"
  "><property name=\"border_width\">6</property><property name=\"shadow_ty"
  "pe\">in</property><child><object class=\"GtkTreeView\" id=\"layout_sele"
  "ction_view\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"headers_visible\">False</pr"
  "operty><property name=\"search_column\">0</property><child internal-chi"
  "ld=\"selection\"><object class=\"GtkTreeSelection\" id=\"treeview-selec"
  "tion1\"/></child></object></child></object><packing><property name=\"ex"
  "pand\">True</property><property name=\"fill\">True</property><property "
  "name=\"position\">1</property></packing></child></object></child><actio"
  "n-widgets><action-widget response=\"-6\">layout_selection_cancel_button"
  "</action-widget><action-widget response=\"-5\">layout_selection_ok_butt"
  "on</action-widget></action-widgets></object><object class=\"GtkAdjustme"
  "nt\" id=\"net_cursor_blink_time\"><property name=\"lower\">100</propert"
  "y><property name=\"upper\">2000</property><property name=\"value\">1000"
  "</property><property name=\"step_increment\">1</property><property name"
  "=\"page_increment\">10</property></object><object class=\"GtkSizeGroup\""
  " id=\"sizegroup1\"/><object class=\"GtkAdjustment\" id=\"xkb_key_repeat"
  "_delay\"><property name=\"lower\">10</property><property name=\"upper\""
  ">1000</property><property name=\"value\">500</property><property name=\""
  "step_increment\">1</property><property name=\"page_increment\">10</prop"
  "erty></object><object class=\"GtkAdjustment\" id=\"xkb_key_repeat_rate\""
  "><property name=\"lower\">1</property><property name=\"upper\">250</pro"
  "perty><property name=\"value\">20</property><property name=\"step_incre"
  "ment\">1</property><property name=\"page_increment\">10</property></obj"
  "ect><object class=\"XfceTitledDialog\" id=\"keyboard-settings-dialog\">"
  "<property name=\"can_focus\">False</property><property name=\"title\" t"
  "ranslatable=\"yes\">Keyboard</property><property name=\"window_position"
  "\">center-on-parent</property><property name=\"default_width\">400</pro"
  "perty><property name=\"default_height\">600</property><property name=\""
  "icon_name\">org.xfce.settings.keyboard</property><property name=\"type_"
  "hint\">dialog</property><child internal-child=\"vbox\"><object class=\""
  "GtkBox\" id=\"dialog-vbox1\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"orientati"
  "on\">vertical</property><property name=\"spacing\">2</property><child i"
  "nternal-child=\"action_area\"><object class=\"GtkButtonBox\" id=\"dialo"
  "g-action_area1\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"layout_style\">end</p"
  "roperty><child><object class=\"GtkButton\" id=\"button2\"><property nam"
  "e=\"label\" translatable=\"yes\">_Close</property><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"receives_default\">True</property><property name=\"image\">i"
  "mage2</property><property name=\"use_underline\">True</property></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"f"
  "ill\">False</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkButton\" id=\"button1\"><property na"
  "me=\"label\" translatable=\"yes\">_Help</property><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"receives_default\">True</property><property name=\"image\">i"
  "mage5</property><property name=\"use_underline\">True</property></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"f"
  "ill\">False</property><property name=\"position\">0</property><property"
  " name=\"secondary\">True</property></packing></child></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">True<"
  "/property><property name=\"pack_type\">end</property><property name=\"p"
  "osition\">0</property></packing></child><child><object class=\"GtkNoteb"
  "ook\" id=\"plug-child\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">True</property><property name=\"border_width\">"
  "6</property><child><object class=\"GtkScrolledWindow\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><c"
  "hild><object class=\"GtkViewport\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><child><object class"
  "=\"GtkBox\" id=\"vbox3\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"border_width\""
  ">12</property><property name=\"orientation\">vertical</property><proper"
  "ty name=\"spacing\">18</property><child><object class=\"GtkFrame\" id=\""
  "frame1\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label_xalign\">0</property><p"
  "roperty name=\"shadow_type\">none</property><child><object class=\"GtkA"
  "lignment\" id=\"alignment5\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"top_paddi"
  "ng\">6</property><property name=\"left_padding\">12</property><child><o"
  "bject class=\"GtkCheckButton\" id=\"restore_numlock\"><property name=\""
  "label\" translatable=\"yes\">Restore num l_ock state on startup</proper"
  "ty><property name=\"visible\">True</property><property name=\"can_focus"
  "\">True</property><property name=\"receives_default\">False</property><"
  "property name=\"halign\">start</property><property name=\"use_underline"
  "\">True</property><property name=\"draw_indicator\">True</property></ob"
  "ject></child></object></child><child type=\"label\"><object class=\"Gtk"
  "Label\" id=\"label9\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"label\" translat"
  "able=\"yes\">General</property><property name=\"use_markup\">True</prop"
  "erty><attributes><attribute name=\"weight\" value=\"bold\"/></attribute"
  "s></object></child></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"fill\">True</property><property name=\"positio"
  "n\">0</property></packing></child><child><object class=\"GtkFrame\" id="
  "\"frame2\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"label_xalign\">0</property>"
  "<property name=\"shadow_type\">none</property><child><object class=\"Gt"
  "kAlignment\" id=\"alignment2\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"top_pad"
  "ding\">6</property><property name=\"left_padding\">12</property><child>"
  "<object class=\"GtkBox\" id=\"vbox1\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "orientation\">vertical</property><property name=\"spacing\">6</property"
  "><child><object class=\"GtkCheckButton\" id=\"xkb_key_repeat_check\"><p"
  "roperty name=\"label\" translatable=\"yes\">_Enable key repeat</propert"
  "y><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">False</property><pr"
  "operty name=\"tooltip_text\" translatable=\"yes\">When selected, pressi"
  "ng and holding down a key emits the same character over and over again<"
  "/property><property name=\"halign\">start</property><property name=\"us"
  "e_underline\">True</property><property name=\"active\">True</property><"
  "property name=\"draw_indicator\">True</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">False</pro"
  "perty><property name=\"position\">0</property></packing></child><child>"
  "<object class=\"GtkAlignment\" id=\"xkb_key_repeat_box\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"left_padding\">12</property><child><object class=\"G"
  "tkBox\" id=\"vbox6\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"orientation\">ver"
  "tical</property><property name=\"spacing\">6</property><child><object c"
  "lass=\"GtkLabel\" id=\"label7\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"halign"
  "\">start</property><property name=\"label\" translatable=\"yes\">_Repea"
  "t delay:</property><property name=\"use_underline\">True</property><pro"
  "perty name=\"mnemonic_widget\">xkb_key_repeat_delay_scale</property></o"
  "bject><packing><property name=\"expand\">False</property><property name"
  "=\"fill\">False</property><property name=\"position\">0</property></pac"
  "king></child><child><object class=\"GtkScale\" id=\"xkb_key_repeat_dela"
  "y_scale\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"tooltip_text\" translatable=\""
  "yes\">The time, in milliseconds, before a pressed key begins repeating<"
  "/property><property name=\"adjustment\">xkb_key_repeat_delay</property>"
  "<property name=\"digits\">0</property><property name=\"value_pos\">righ"
  "t</property></object><packing><property name=\"expand\">True</property>"
  "<property name=\"fill\">True</property><property name=\"position\">1</p"
  "roperty></packing></child><child><object class=\"GtkLabel\" id=\"label1"
  "0\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"halign\">start</property><property"
  " name=\"label\" translatable=\"yes\">Repe_at speed:</property><property"
  " name=\"use_underline\">True</property><property name=\"mnemonic_widget"
  "\">xkb_key_repeat_rate_scale</property></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">False</property><pr"
  "operty name=\"position\">2</property></packing></child><child><object c"
  "lass=\"GtkScale\" id=\"xkb_key_repeat_rate_scale\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">True</property><prop"
  "erty name=\"tooltip_text\" translatable=\"yes\">The rate at which keyst"
  "rokes are generated while a key is pressed</property><property name=\"a"
  "djustment\">xkb_key_repeat_rate</property><property name=\"digits\">0</"
  "property><property name=\"value_pos\">right</property></object><packing"
  "><property name=\"expand\">True</property><property name=\"fill\">True<"
  "/property><property name=\"position\">3</property></packing></child></o"
  "bject></child></object><packing><property name=\"expand\">True</propert"
  "y><property name=\"fill\">True</property><property name=\"position\">1<"
  "/property></packing></child></object></child></object></child><child ty"
  "pe=\"label\"><object class=\"GtkLabel\" id=\"label5\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">Typing Settings</property>"
  "<attributes><attribute name=\"weight\" value=\"bold\"/></attributes></o"
  "bject></child></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">False</property><property name=\"position\">"
  "1</property></packing></child><child><object class=\"GtkFrame\" id=\"fr"
  "ame3\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"label_xalign\">0</property><pro"
  "perty name=\"shadow_type\">none</property><child><object class=\"GtkAli"
  "gnment\" id=\"alignment3\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"top_padding"
  "\">6</property><property name=\"left_padding\">12</property><child><obj"
  "ect class=\"GtkBox\" id=\"vbox4\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"orie"
  "ntation\">vertical</property><property name=\"spacing\">6</property><ch"
  "ild><object class=\"GtkCheckButton\" id=\"net_cursor_blink_check\"><pro"
  "perty name=\"label\" translatable=\"yes\">Show _blinking</property><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">True"
  "</property><property name=\"receives_default\">False</property><propert"
  "y name=\"tooltip_text\" translatable=\"yes\">Specify whether or not the"
  " text cursor blinks</property><property name=\"halign\">start</property"
  "><property name=\"use_underline\">True</property><property name=\"draw_"
  "indicator\">True</property></object><packing><property name=\"expand\">"
  "False</property><property name=\"fill\">False</property><property name="
  "\"position\">0</property></packing></child><child><object class=\"GtkAl"
  "ignment\" id=\"net_cursor_blink_box\"><property name=\"visible\">True</"
  "property><property name=\"sensitive\">False</property><property name=\""
  "can_focus\">False</property><property name=\"left_padding\">12</propert"
  "y><child><object class=\"GtkBox\" id=\"vbox7\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"orientation\">vertical</property><property name=\"spacing\">6<"
  "/property><child><object class=\"GtkLabel\" id=\"label13\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"halign\">start</property><property name=\"label\" "
  "translatable=\"yes\">Blink _delay:</property><property name=\"use_under"
  "line\">True</property><property name=\"mnemonic_widget\">net_cursor_bli"
  "nk_time_scale</property></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">False</property><property name=\"p"
  "osition\">0</property></packing></child><child><object class=\"GtkScale"
  "\" id=\"net_cursor_blink_time_scale\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"t"
  "ooltip_text\" translatable=\"yes\">The delay, in milliseconds, between "
  "successive blinks of the cursor</property><property name=\"adjustment\""
  ">net_cursor_blink_time</property><property name=\"digits\">0</property>"
  "<property name=\"value_pos\">right</property></object><packing><propert"
  "y name=\"expand\">True</property><property name=\"fill\">True</property"
  "><property name=\"position\">1</property></packing></child></object></c"
  "hild></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">True</property><property name=\"position\">1</propert"
  "y></packing></child></object></child></object></child><child type=\"lab"
  "el\"><object class=\"GtkLabel\" id=\"label6\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">Cursor</property><attributes><attri"
  "bute name=\"weight\" value=\"bold\"/></attributes></object></child></ob"
  "ject><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">2</property></packing"
  "></child><child><object class=\"GtkBox\" id=\"hbox1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"spacing\">12</property><child><object class=\"GtkLabel\""
  " id=\"label12\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\">_Test area:</property><property name=\"use_underline\">True</prop"
  "erty><property name=\"mnemonic_widget\">entry1</property></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">0</property></packing></child"
  "><child><object class=\"GtkEntry\" id=\"entry1\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">True</property><proper"
  "ty name=\"invisible_char\">\342\200\242</property><property name=\"prim"
  "ary_icon_activatable\">False</property><property name=\"secondary_icon_"
  "activatable\">False</property></object><packing><property name=\"expand"
  "\">True</property><property name=\"fill\">True</property><property name"
  "=\"position\">1</property></packing></child></object><packing><property"
  " name=\"expand\">False</property><property name=\"fill\">True</property"
  "><property name=\"position\">3</property></packing></child></object></c"
  "hild></object></child></object></child><child type=\"tab\"><object clas"
  "s=\"GtkLabel\" id=\"label2\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"label\" t"
  "ranslatable=\"yes\">Beha_vior</property><property name=\"use_underline\""
  ">True</property></object><packing><property name=\"tab_fill\">False</pr"
  "operty></packing></child><child><object class=\"GtkBox\" id=\"vbox5\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"border_width\">12</property><property n"
  "ame=\"orientation\">vertical</property><child><object class=\"GtkLabel\""
  " id=\"label14\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"margin_bottom\">6</pro"
  "perty><property name=\"label\" translatable=\"yes\">Define shortcuts fo"
  "r la_unching applications:</property><property name=\"use_underline\">T"
  "rue</property><property name=\"mnemonic_widget\">kbd_shortcuts_view</pr"
  "operty><property name=\"xalign\">0</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">False</proper"
  "ty><property name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkScrolledWindow\" id=\"scrolledwindow2\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">True</property>"
  "<property name=\"shadow_type\">etched-in</property><child><object class"
  "=\"GtkTreeView\" id=\"kbd_shortcuts_view\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">True</property><property nam"
  "e=\"search_column\">0</property><child internal-child=\"selection\"><ob"
  "ject class=\"GtkTreeSelection\" id=\"treeview-selection2\"/></child></o"
  "bject></child></object><packing><property name=\"expand\">True</propert"
  "y><property name=\"fill\">True</property><property name=\"position\">1<"
  "/property></packing></child><child><object class=\"GtkBox\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><child><object class=\"GtkBox\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><child><object cla"
  "ss=\"GtkButton\" id=\"add_shortcut_button\"><property name=\"label\" tr"
  "anslatable=\"yes\">_Add</property><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">True</property><property name=\"image\">image6</property>"
  "<property name=\"use_underline\">True</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">False</pro"
  "perty><property name=\"position\">0</property></packing></child><child>"
  "<object class=\"GtkButton\" id=\"edit_shortcut_button\"><property name="
  "\"label\" translatable=\"yes\">_Edit</property><property name=\"visible"
  "\">True</property><property name=\"can_focus\">True</property><property"
  " name=\"receives_default\">True</property><property name=\"image\">imag"
  "e8</property><property name=\"use_underline\">True</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">False</property><property name=\"position\">1</property></packing></"
  "child><child><object class=\"GtkButton\" id=\"delete_shortcut_button\">"
  "<property name=\"label\" translatable=\"yes\">_Remove</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"receives_default\">True</property><property na"
  "me=\"image\">image7</property><property name=\"use_underline\">True</pr"
  "operty></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">True</property><property name=\"position\">2</prope"
  "rty></packing></child></object><packing><property name=\"expand\">False"
  "</property><property name=\"fill\">False</property><property name=\"pos"
  "ition\">0</property></packing></child><child><object class=\"GtkBox\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><child><object class=\"GtkButton\" id=\"reset_shortcuts_"
  "button\"><property name=\"label\" translatable=\"yes\">Reset to _Defaul"
  "ts</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">True</pr"
  "operty><property name=\"image\">image1</property><property name=\"use_u"
  "nderline\">True</property></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">True</property><property name=\""
  "position\">0</property></packing></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">True</property><p"
  "roperty name=\"pack_type\">end</property><property name=\"position\">1<"
  "/property></packing></child><style><class name=\"inline-toolbar\"/></st"
  "yle></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">2</property"
  "></packing></child></object><packing><property name=\"position\">1</pro"
  "perty></packing></child><child type=\"tab\"><object class=\"GtkLabel\" "
  "id=\"label3\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"label\" translatable=\"y"
  "es\">A_pplication Shortcuts</property><property name=\"use_underline\">"
  "True</property></object><packing><property name=\"position\">1</propert"
  "y><property name=\"tab_fill\">False</property></packing></child><child>"
  "<object class=\"GtkScrolledWindow\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">True</property><child><object class"
  "=\"GtkViewport\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><child><object class=\"GtkBox\" id=\"x"
  "kb_tab_layout_vbox\"><property name=\"can_focus\">False</property><prop"
  "erty name=\"border_width\">12</property><property name=\"orientation\">"
  "vertical</property><property name=\"spacing\">18</property><child><obje"
  "ct class=\"GtkBox\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><child><object class=\"GtkLabel\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"label\" translatable=\"yes\">&lt;b&gt;U"
  "se system defaults&lt;/b&gt;</property><property name=\"use_markup\">Tr"
  "ue</property><property name=\"xalign\">0</property></object><packing><p"
  "roperty name=\"expand\">True</property><property name=\"fill\">True</pr"
  "operty><property name=\"position\">0</property></packing></child><child"
  "><object class=\"GtkSwitch\" id=\"xkb_use_system_default_switch\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"halign\">end</property><property name=\"vali"
  "gn\">center</property><property name=\"active\">True</property></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">1</property></packing><"
  "/child></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">True</property><property name=\"position\">0</prope"
  "rty></packing></child><child><object class=\"GtkFrame\" id=\"xkb_model_"
  "frame\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"label_xalign\">0</property><pr"
  "operty name=\"shadow_type\">none</property><child><object class=\"GtkAl"
  "ignment\" id=\"alignment1\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"top_paddin"
  "g\">6</property><property name=\"left_padding\">12</property><child><ob"
  "ject class=\"GtkComboBox\" id=\"xkb_model_combo\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property></obj"
  "ect></child></object></child><child type=\"label\"><object class=\"GtkL"
  "abel\" id=\"label11\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"label\" translat"
  "able=\"yes\">_Keyboard model</property><property name=\"use_underline\""
  ">True</property><attributes><attribute name=\"weight\" value=\"bold\"/>"
  "</attributes></object></child></object><packing><property name=\"expand"
  "\">False</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">1</property></packing></child><child><object class=\"Gtk"
  "Box\" id=\"hbox4\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"spacing\">6</proper"
  "ty><property name=\"homogeneous\">True</property><child><object class=\""
  "GtkFrame\" id=\"xkb_grpkey_frame\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"lab"
  "el_xalign\">0</property><property name=\"shadow_type\">none</property><"
  "child><object class=\"GtkAlignment\" id=\"alignment6\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"top_padding\">6</property><property name=\"left_padding"
  "\">12</property><child><object class=\"GtkComboBox\" id=\"xkb_grpkey_co"
  "mbo\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property></object></child></object></child><child type=\"l"
  "abel\"><object class=\"GtkLabel\" id=\"label1\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"label\" translatable=\"yes\">Change la_yout option</property>"
  "<property name=\"use_underline\">True</property><attributes><attribute "
  "name=\"weight\" value=\"bold\"/></attributes></object></child></object>"
  "<packing><property name=\"expand\">False</property><property name=\"fil"
  "l\">True</property><property name=\"position\">0</property></packing></"
  "child><child><object class=\"GtkFrame\" id=\"xkb_composekey_frame\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"label_xalign\">0</property><property name"
  "=\"shadow_type\">none</property><child><object class=\"GtkAlignment\" i"
  "d=\"alignment7\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"top_padding\">6</prop"
  "erty><property name=\"left_padding\">12</property><child><object class="
  "\"GtkComboBox\" id=\"xkb_composekey_combo\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property></object></"
  "child></object></child><child type=\"label\"><object class=\"GtkLabel\""
  " id=\"label15\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\">Co_mpose key</property><property name=\"use_underline\">True</pro"
  "perty><attributes><attribute name=\"weight\" value=\"bold\"/></attribut"
  "es></object></child></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">True</property><property name=\"positi"
  "on\">1</property></packing></child></object><packing><property name=\"e"
  "xpand\">False</property><property name=\"fill\">True</property><propert"
  "y name=\"position\">2</property></packing></child><child><object class="
  "\"GtkFrame\" id=\"xkb_layout_frame\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"l"
  "abel_xalign\">0</property><property name=\"shadow_type\">none</property"
  "><child><object class=\"GtkAlignment\" id=\"alignment4\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"top_padding\">6</property><child><object class=\"Gtk"
  "Box\" id=\"vbox8\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"spacing\">6</proper"
  "ty><child><object class=\"GtkBox\" id=\"hbox3\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"orientation\">vertical</property><child><object class=\"GtkSc"
  "rolledWindow\" id=\"scrolledwindow1\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"s"
  "hadow_type\">etched-in</property><child><object class=\"GtkTreeView\" i"
  "d=\"xkb_layout_view\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"search_column\">0"
  "</property><child internal-child=\"selection\"><object class=\"GtkTreeS"
  "election\" id=\"treeview-selection3\"/></child></object></child></objec"
  "t><packing><property name=\"expand\">True</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">0</property></packing><"
  "/child><child><object class=\"GtkButtonBox\" id=\"hbuttonbox2\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"layout_style\">start</property><child><object"
  " class=\"GtkButton\" id=\"xkb_layout_add_button\"><property name=\"labe"
  "l\" translatable=\"yes\">_Add</property><property name=\"visible\">True"
  "</property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">True</property><property name=\"image\">image9</prop"
  "erty><property name=\"use_underline\">True</property></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">False"
  "</property><property name=\"position\">0</property><property name=\"non"
  "_homogeneous\">True</property></packing></child><child><object class=\""
  "GtkButton\" id=\"xkb_layout_edit_button\"><property name=\"label\" tran"
  "slatable=\"yes\">_Edit</property><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">True</property><property name=\"receiv"
  "es_default\">True</property><property name=\"image\">image10</property>"
  "<property name=\"use_underline\">True</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">False</pro"
  "perty><property name=\"position\">1</property><property name=\"non_homo"
  "geneous\">True</property></packing></child><child><object class=\"GtkBu"
  "tton\" id=\"xkb_layout_delete_button\"><property name=\"label\" transla"
  "table=\"yes\">_Remove</property><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"receive"
  "s_default\">True</property><property name=\"image\">image11</property><"
  "property name=\"use_underline\">True</property></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">False</prop"
  "erty><property name=\"position\">2</property><property name=\"non_homog"
  "eneous\">True</property></packing></child><style><class name=\"inline-t"
  "oolbar\"/></style></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">1</property></packing></child></object><packing><property name=\"exp"
  "and\">True</property><property name=\"fill\">True</property><property n"
  "ame=\"position\">0</property></packing></child><child><object class=\"G"
  "tkBox\" id=\"vbuttonbox1\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"orientation"
  "\">vertical</property><child><object class=\"GtkButton\" id=\"xkb_layou"
  "t_up_button\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">True</property><property name=\"receives_default\">True</"
  "property><property name=\"tooltip_text\" translatable=\"yes\">Move curr"
  "ently selected item up by one row</property><child><object class=\"GtkI"
  "mage\" id=\"image4\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"icon_name\">go-up"
  "-symbolic</property></object></child></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">0</property></packing></child><child><object clas"
  "s=\"GtkButton\" id=\"xkb_layout_down_button\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">True</property><property name=\"tooltip_text\""
  " translatable=\"yes\">Move currently selected item down by one row</pro"
  "perty><child><object class=\"GtkImage\" id=\"image3\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"icon_name\">go-down-symbolic</property></object></child"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">False</property><property name=\"position\">1</property><"
  "/packing></child><style><class name=\"linked\"/></style></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Fa"
  "lse</property><property name=\"position\">2</property></packing></child"
  "></object></child></object></child><child type=\"label\"><object class="
  "\"GtkLabel\" id=\"label8\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"label\" tra"
  "nslatable=\"yes\">Key_board layout</property><property name=\"use_under"
  "line\">True</property><attributes><attribute name=\"weight\" value=\"bo"
  "ld\"/></attributes></object></child></object><packing><property name=\""
  "expand\">True</property><property name=\"fill\">True</property><propert"
  "y name=\"position\">3</property></packing></child></object></child></ob"
  "ject></child></object><packing><property name=\"position\">2</property>"
  "</packing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"l"
  "abel4\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"label\" translatable=\"yes\">_"
  "Layout</property><property name=\"use_underline\">True</property></obje"
  "ct><packing><property name=\"position\">2</property><property name=\"ta"
  "b_fill\">False</property></packing></child></object><packing><property "
  "name=\"expand\">True</property><property name=\"fill\">True</property><"
  "property name=\"position\">1</property></packing></child></object></chi"
  "ld><action-widgets><action-widget response=\"0\">button2</action-widget"
  "><action-widget response=\"-11\">button1</action-widget></action-widget"
  "s></object></interface>"
};

static const unsigned keyboard_dialog_ui_length = 35623u;

