#TODO probably wrong script, see https://github.com/PCSX2/pcsx2/wiki/10-Building-on-Linux
#TODO probably need patches on submodules
#TODO determine dependencies - https://aur.archlinux.org/packages/pcsx2-git
[source]
git = "https://github.com/PCSX2/pcsx2.git"
[build]
template = "custom"
dependencies = [
    "sdl2",
    "xz",
    "libpng",
    "qt6-base",
    "qt6-svg",
    "qt6-wayland",
    "mesa",
    "libaio",
    "harfbuzz",
    "libpcap",
    "pipewire",
    "libsamplerate",
    "soundtouch",
    "zlib",
    "libxml2",
    "ffmpeg6",
    "libwayland",
]
script = """
    COOKBOOK_CONFIGURE="cmake"
    COOKBOOK_CONFIGURE_FLAGS=(
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_CROSSCOMPILING=True
    -DCMAKE_EXE_LINKER_FLAGS="-static"
    -DCMAKE_INSTALL_PREFIX="/"
    -DCMAKE_PREFIX_PATH="${COOKBOOK_SYSROOT}"
    -DCMAKE_SYSTEM_NAME=Generic
    -DCMAKE_SYSTEM_PROCESSOR="$(echo "${TARGET}" | cut -d - -f1)"
    -DCMAKE_VERBOSE_MAKEFILE=On
"${COOKBOOK_SOURCE}"
)
cookbook_configure
"""
