#TODO missing script for "make", see https://github.com/mupen64plus/mupen64plus-input-sdl/blob/master/INSTALL#L11
[source]
git = "https://github.com/mupen64plus/mupen64plus-input-sdl"
[build]
template = "custom"
