#TODO Port Smithay
#TODO probably wrong script for configuration, see https://github.com/YaLTeR/niri#installation
[source]
git = "https://github.com/YaLTeR/niri"
[build]
template = "custom"
dependencies = [
    "libwayland",
]
script = """
mkdir -pv "${COOKBOOK_STAGE}"/usr/bin
mkdir -pv "${COOKBOOK_STAGE}"/usr/share/wayland-sessions
mkdir -pv "${COOKBOOK_STAGE}"/usr/share/xdg-desktop-portal
cp -rv "${COOKBOOK_SOURCE}"/resources/niri-session "${COOKBOOK_STAGE}"/usr/bin
cp -rv "${COOKBOOK_SOURCE}"/resources/niri.desktop "${COOKBOOK_STAGE}"/usr/share/wayland-sessions
cp -rv "${COOKBOOK_SOURCE}"/resources/niri-portals.conf "${COOKBOOK_STAGE}"/usr/share/xdg-desktop-portal
cookbook_cargo
"""
