#TODO make the "less" dependency work
[source]
git = "https://github.com/dandavison/delta"
rev = "03f1569a9aff964e9291371d9928d0584327eae2"
[build]
template = "custom"
dependencies = [
    "less",
]
script = """
cookbook_cargo_packages git-delta
"""
