#TODO Make OpenCV 4 work
[source]
git = "https://github.com/maxcurzi/tplay"
rev = "f32d5d3df7e3c6a873d1b113ef3b707b016b3a69"
[build]
template = "cargo"
dependencies = [
    "ffmpeg6",
    "llvm",
    "openssl1",
    "opencv4",
]
