#TODO openssl-sys crate error
[source]
git = "https://github.com/iomentum/cargo-scaffold"
[build]
template = "custom"
dependencies = [
    "openssl1",
]
script = """
export OPENSSL_DIR="${COOKBOOK_SYSROOT}"
export OPENSSL_STATIC="true"
cookbook_cargo
"""
