#TODO missing script for Meson, lacking build instructions
[source]
tar = "https://download.gnome.org/sources/pitivi/2023/pitivi-2023.03.tar.xz"
[build]
template = "custom"
dependencies = [
    "gtk3",
    "gstreamer",
    "libpeas",
]
