#TODO openssl-sys crate compilation error
[source]
git = "https://github.com/mihaigalos/aim"
[build]
dependencies = [
    "openssl1",
]
template = "custom"
script = """
export OPENSSL_DIR="${COOKBOOK_SYSROOT}"
export OPENSSL_STATIC="true"
cookbook_cargo
"""
