#TODO probably wrong script, see https://github.com/LMMS/lmms/wiki/Compiling#build-environment
[source]
tar = "https://github.com/LMMS/lmms/releases/download/v1.2.2/lmms_1.2.2.tar.xz"
[build]
template = "custom"
dependencies = [
    "qt5-base",
    "libsamplerate",
    "libvorbis",
    "libogg",
    "sdl2",
    "fftw",
    "libstk",
    "fltk",
]
script = """
    COOKBOOK_CONFIGURE="cmake"
    COOKBOOK_CONFIGURE_FLAGS=(
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_CROSSCOMPILING=True
    -DCMAKE_EXE_LINKER_FLAGS="-static"
    -DCMAKE_INSTALL_PREFIX="/"
    -DCMAKE_PREFIX_PATH="${COOKBOOK_SYSROOT}"
    -DCMAKE_SYSTEM_NAME=Generic
    -DCMAKE_SYSTEM_PROCESSOR="$(echo "${TARGET}" | cut -d - -f1)"
    -DCMAKE_VERBOSE_MAKEFILE=On
"${COOKBOOK_SOURCE}"
)
cookbook_configure
"""
