#TODO missing script for "make", see https://github.com/mupen64plus/mupen64plus-video-glide64/blob/master/src/INSTALL
[source]
git = "https://github.com/mupen64plus/mupen64plus-video-glide64"
[build]
template = "custom"
