[package]
name = "jest"
description="Hand (gest)ure recongition in Rust. To be used by Orbital."
authors = ["Boris Nezlobin"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
