#TODO openssl-sys crate error
[source]
git = "https://github.com/extrawurst/gitui"
rev = "87686118768e89b5e86611b4057c05d0d7abb2bc"
[build]
template = "custom"
dependencies = [
    "openssl1",
]
script = """
export OPENSSL_DIR="${COOKBOOK_SYSROOT}"
export OPENSSL_STATIC="true"
cookbook_cargo
"""
