[source]
git = "https://gitlab.redox-os.org/redox-os/zerod.git"

[build]
template = "custom"
script = """
cookbook_cargo --bin zerod

# TODO: symlinks aren't supported by redox-initfs
#ln -sv zerod "${COOKBOOK_STAGE}/usr/bin/nulld"

cp "${COOKBOOK_STAGE}/usr/bin/zerod" "${COOKBOOK_STAGE}/usr/bin/nulld"
"""
