#TODO openssl-sys crate error
[source]
git = "https://github.com/MarcoIeni/release-plz"
rev = "68baf26d77a887c3ad90e4ad75ce77d9788f2442"
[build]
dependencies = [
    "openssl1",
]
template = "custom"
script = """
export OPENSSL_DIR="${COOKBOOK_SYSROOT}"
export OPENSSL_STATIC="true"
cookbook_cargo_packages release-plz
"""
