#TODO probably wrong script, see https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC#linux
#TODO probably missing dependencies, see https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux#install-the-required-dependencies
[source]
tar = "https://github.com/keepassxreboot/keepassxc/releases/download/2.7.6/keepassxc-2.7.6-src.tar.xz"
[build]
template = "custom"
dependencies = [
    "qt5-base",
    "qt5-svg",
    "qt5-x11extras",
    "zlib",
    "libbotan",
    "libargon2",
    "libxi",
    "libxtst",
    "readline",
]
script = """
COOKBOOK_CONFIGURE="cmake"
COOKBOOK_CONFIGURE_FLAGS=(
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_CROSSCOMPILING=True
    -DCMAKE_EXE_LINKER_FLAGS="-static"
    -DCMAKE_INSTALL_PREFIX="/"
    -DCMAKE_PREFIX_PATH="${COOKBOOK_SYSROOT}"
    -DCMAKE_SYSTEM_NAME=Generic
    -DCMAKE_SYSTEM_PROCESSOR="$(echo "${TARGET}" | cut -d - -f1)"
    -DCMAKE_VERBOSE_MAKEFILE=On
    -DWITH_XC_AUTOTYPE=OFF
    -DWITH_XC_UPDATECHECK=OFF
    -DKEEPASSXC_BUILD_TYPE=Release
    -DWITH_APP_BUNDLE=OFF
"${COOKBOOK_SOURCE}"
)
cookbook_configure
"""
