#TODO missing script for "make", see https://github.com/mupen64plus/mupen64plus-core#2-building-from-source
[source]
git = "https://github.com/mupen64plus/mupen64plus-core"
[build]
template = "custom"
dependencies = [
    "sdl2",
    "libpng",
    "freetype2",
    "zlib",
]
