#TODO Not compiled/tested yet
[source]
git = "https://github.com/fabiangreffrath/crispy-doom"
rev = "593f5b97023ed39b7640073160c06895bbfc3d26"
[build]
template = "configure"
dependencies = [
    "sdl2",
    "sdl2-mixer",
    "sdl2-net",
]
