#TODO missing script for "make", see https://trac.smokin-guns.org/wiki/SmokinGuns/Building/linux
#TODO bundled with the ioquake3 engine?
#TODO determine dependencies
[source]
git = "https://github.com/smokin-guns/SmokinGuns"
[build]
template = "custom"
