#TODO missing script for CMake, see https://github.com/TheTumultuousUnicornOfDarkness/CPU-X/wiki/manual-build#build-and-install-cpu-x
[source]
git = "https://github.com/TheTumultuousUnicornOfDarkness/CPU-X"
rev = "b957c031a2eab2c6c88275c4616a6a5e8c8e7670"
[build]
template = "custom"
dependencies = [
    "gtk3mm",
    "ncurses",
    "glfw",
    "libvulkan",
    "libstatgrab",
    "libcpuid",
    "pciutils",
]
script = """
export CPPFLAGS="-I${COOKBOOK_SYSROOT}/include/ncurses"
"""
