#TODO missing script for building, see https://ant.apache.org/manual/install.html#buildingant
[source]
tar = "https://downloads.apache.org/ant/source/apache-ant-1.10.14-src.tar.xz"
[build]
template = "custom"
