/* automatically generated from windowmenu-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (windowmenu_dialog_ui)
#endif
#ifdef __GNUC__
static const char windowmenu_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char windowmenu_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><requires lib=\"libxfce4ui-2\" version=\"4.12\"/"
  "><object class=\"GtkImage\" id=\"image1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"icon_name\">help-browser</property></object><object class=\"GtkImag"
  "e\" id=\"image2\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"icon_name\">window-c"
  "lose-symbolic</property></object><object class=\"GtkListStore\" id=\"st"
  "yle-model\"><columns><column type=\"gchararray\"/></columns><data><row>"
  "<col id=\"0\" translatable=\"yes\">Icon</col></row><row><col id=\"0\" t"
  "ranslatable=\"yes\">Arrow</col></row></data></object><object class=\"Xf"
  "ceTitledDialog\" id=\"dialog\"><property name=\"can_focus\">False</prop"
  "erty><property name=\"title\" translatable=\"yes\">Window Menu</propert"
  "y><property name=\"icon_name\">org.xfce.panel.windowmenu</property><pro"
  "perty name=\"type_hint\">normal</property><child internal-child=\"vbox\""
  "><object class=\"GtkBox\" id=\"dialog-vbox2\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"orientation\">vertical</property><property name=\"spacing\">2</p"
  "roperty><child internal-child=\"action_area\"><object class=\"GtkButton"
  "Box\" id=\"dialog-action_area2\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"layou"
  "t_style\">end</property><child><object class=\"GtkButton\" id=\"close-b"
  "utton\"><property name=\"label\" translatable=\"yes\">_Close</property>"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "True</property><property name=\"receives_default\">True</property><prop"
  "erty name=\"image\">image2</property><property name=\"use_underline\">T"
  "rue</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">False</property><property name=\"position\">"
  "0</property></packing></child><child><object class=\"GtkButton\" id=\"h"
  "elp-button\"><property name=\"label\" translatable=\"yes\">_Help</prope"
  "rty><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">True</property><property name=\"receives_default\">True</property><"
  "property name=\"image\">image1</property><property name=\"use_underline"
  "\">True</property></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">False</property><property name=\"positio"
  "n\">1</property><property name=\"secondary\">True</property></packing><"
  "/child></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">False</property><property name=\"pack_type\">end</p"
  "roperty><property name=\"position\">0</property></packing></child><chil"
  "d><object class=\"GtkBox\" id=\"vbox1\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"border_width\">6</property><property name=\"orientation\">vertical</p"
  "roperty><property name=\"spacing\">6</property><child><object class=\"G"
  "tkFrame\" id=\"frame3\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"label_xalign\""
  ">0</property><property name=\"shadow_type\">none</property><child><obje"
  "ct class=\"GtkAlignment\" id=\"alignment3\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"left_padding\">12</property><child><object class=\"GtkBox\" id=\""
  "vbox3\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"border_width\">6</property><pr"
  "operty name=\"orientation\">vertical</property><property name=\"spacing"
  "\">6</property><child><object class=\"GtkBox\" id=\"hbox1\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"spacing\">12</property><child><object class=\"Gtk"
  "Label\" id=\"label5\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"label\" translat"
  "able=\"yes\">Button layout:</property><property name=\"xalign\">0</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">True</property><property name=\"position\">0</propert"
  "y></packing></child><child><object class=\"GtkComboBox\" id=\"style\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"model\">style-model</property><child><o"
  "bject class=\"GtkCellRendererText\" id=\"cellrenderertext1\"/><attribut"
  "es><attribute name=\"text\">0</attribute></attributes></child></object>"
  "<packing><property name=\"expand\">True</property><property name=\"fill"
  "\">True</property><property name=\"position\">1</property></packing></c"
  "hild></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">True</property><property name=\"position\">0</propert"
  "y></packing></child><child><object class=\"GtkCheckButton\" id=\"worksp"
  "ace-actions\"><property name=\"label\" translatable=\"yes\">Show worksp"
  "ace a_ctions</property><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"receives_default"
  "\">False</property><property name=\"use_underline\">True</property><pro"
  "perty name=\"draw_indicator\">True</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">1</property></packing></child><child><obj"
  "ect class=\"GtkCheckButton\" id=\"workspace-names\"><property name=\"la"
  "bel\" translatable=\"yes\">Show workspace _names</property><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">True</proper"
  "ty><property name=\"receives_default\">False</property><property name=\""
  "use_underline\">True</property><property name=\"draw_indicator\">True</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">2</pro"
  "perty></packing></child><child><object class=\"GtkCheckButton\" id=\"ur"
  "gentcy-notification\"><property name=\"label\" translatable=\"yes\">Ena"
  "ble _urgency notification</property><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">True</property><property name=\"rec"
  "eives_default\">False</property><property name=\"use_underline\">True</"
  "property><property name=\"draw_indicator\">True</property></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "True</property><property name=\"position\">3</property></packing></chil"
  "d></object></child></object></child><child type=\"label\"><object class"
  "=\"GtkLabel\" id=\"label1\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"label\" tr"
  "anslatable=\"yes\">Appearance</property><attributes><attribute name=\"w"
  "eight\" value=\"bold\"/></attributes></object></child></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">True"
  "</property><property name=\"position\">0</property></packing></child><c"
  "hild><object class=\"GtkFrame\" id=\"frame1\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label_xalign\">0</property><property name=\"shadow_type\">none</"
  "property><child><object class=\"GtkAlignment\" id=\"alignment1\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"left_padding\">12</property><child><object c"
  "lass=\"GtkBox\" id=\"vbox2\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"border_wi"
  "dth\">6</property><property name=\"orientation\">vertical</property><pr"
  "operty name=\"spacing\">6</property><child><object class=\"GtkCheckButt"
  "on\" id=\"all-workspaces\"><property name=\"label\" translatable=\"yes\""
  ">Show windows from _all workspaces</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"use_underline"
  "\">True</property><property name=\"draw_indicator\">True</property></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">True</property><property name=\"position\">0</property></packi"
  "ng></child></object></child></object></child><child type=\"label\"><obj"
  "ect class=\"GtkLabel\" id=\"label3\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"l"
  "abel\" translatable=\"yes\">Filtering</property><attributes><attribute "
  "name=\"weight\" value=\"bold\"/></attributes></object></child></object>"
  "<packing><property name=\"expand\">False</property><property name=\"fil"
  "l\">True</property><property name=\"position\">1</property></packing></"
  "child></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">True</property><property name=\"position\">1</proper"
  "ty></packing></child></object></child><action-widgets><action-widget re"
  "sponse=\"0\">close-button</action-widget><action-widget response=\"0\">"
  "help-button</action-widget></action-widgets></object></interface>"
};

static const unsigned windowmenu_dialog_ui_length = 8645u;

