[package]
name = "usbscsid"
version = "0.1.0"
authors = ["4lDO2 <4lDO2@protonmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.11" # Only for debugging
libredox = "0.1.3"
plain = "0.2"
redox-daemon = "0.1"
redox_syscall = "0.5"
thiserror = "1"
xhcid = { path = "../../xhcid" }
